In [1]:
import json
import numpy as np
import pandas as pd
import pickle5 as pickle
import copy

In [2]:
#pip show pickle5

In [3]:
rdf_all = pd.read_csv('./modcloth/df_electronics.csv', sep=",")
rdf_all['user_id'] = rdf_all['user_id'].astype('category').cat.codes
rdf_all.head()

,item_id,user_id,rating,timestamp,model_attr,category,brand,year,user_attr,split
0,0,0,5.0,1999-06-13,Female,Portable Audio & Video,NaN,1999,NaN,0
1,0,1,5.0,1999-06-14,Female,Portable Audio & Video,NaN,1999,NaN,0
2,0,2,3.0,1999-06-17,Female,Portable Audio & Video,NaN,1999,NaN,0
3,0,3,1.0,1999-07-01,Female,Portable Audio & Video,NaN,1999,NaN,0
4,0,4,2.0,1999-07-06,Female,Portable Audio & Video,NaN,1999,NaN,0

In [4]:
valeurs_uniques = rdf_all['model_attr'].unique()

print(valeurs_uniques)

['Female' 'Female&Male' 'Male']

In [5]:
rdf_all = rdf_all.dropna(subset=['user_attr'])
rdf_all.reset_index(drop=True, inplace=True)
rdf_all.head()

,item_id,user_id,rating,timestamp,model_attr,category,brand,year,user_attr,split
0,0,28,2.0,1999-12-01,Female,Portable Audio & Video,NaN,1999,Female,0
1,3,81,5.0,2000-03-31,Female,Camera & Photo,NaN,2005,Male,0
2,7,131,4.0,2000-06-15,Female,Home Audio,Philips,2001,Male,0
3,3,139,3.0,2000-06-29,Female,Camera & Photo,NaN,2005,Female,0
4,8,178,1.0,2000-10-19,Female,Accessories & Supplies,NaN,2000,Male,0

In [6]:
rdf = rdf_all[["user_id","item_id", "rating"]]

rdf.head()

   user_id  item_id  rating
0       28        0     2.0
1       81        3     5.0
2      131        7     4.0
3      139        3     3.0
4      178        8     1.0

In [7]:
user_df = rdf_all[["user_id", "user_attr"]]

user_df.shape

(174124, 2)

In [8]:
user_df.head()

   user_id user_attr
0       28    Female
1       81      Male
2      131      Male
3      139    Female
4      178      Male

In [9]:
user_type_dict = dict()
for u in range(len(user_df)):
    type_str = user_df.at[u, "user_attr"]
    
    #type_list = type_str.split('|')
    type_list = type_str
    user_type_dict[user_df.at[u, 'user_id']] = [type_list]

In [10]:
print(user_type_dict)

{28: ['Female'], 81: ['Male'], 131: ['Male'], 139: ['Female'], 178: ['Male'], 231: ['Male'], 233: ['Female'], 257: ['Female'], 269: ['Male'], 274: ['Male'], 309: ['Male'], 340: ['Male'], 369: ['Female'], 385: ['Male'], 404: ['Male'], 418: ['Female'], 432: ['Female'], 505: ['Male'], 516: ['Male'], 545: ['Male'], 551: ['Male'], 571: ['Female'], 603: ['Male'], 627: ['Female'], 671: ['Male'], 683: ['Female'], 688: ['Female'], 707: ['Male'], 725: ['Female'], 760: ['Male'], 767: ['Male'], 782: ['Female'], 829: ['Male'], 840: ['Female'], 841: ['Female'], 844: ['Female'], 858: ['Male'], 868: ['Female'], 939: ['Male'], 945: ['Male'], 950: ['Male'], 952: ['Female'], 985: ['Female'], 991: ['Male'], 1011: ['Male'], 1078: ['Male'], 1079: ['Male'], 1081: ['Male'], 1115: ['Female'], 1136: ['Female'], 1140: ['Male'], 1147: ['Female'], 1156: ['Male'], 1168: ['Female'], 1188: ['Female'], 1197: ['Male'], 1205: ['Male'], 1222: ['Male'], 1225: ['Male'], 1236: ['Female'], 1289: ['Male'], 1293: ['Male'], 1297: ['Male'], 1304: ['Male'], 1313: ['Male'], 1329: ['Male'], 1377: ['Male'], 1383: ['Male'], 1386: ['Female'], 1401: ['Female'], 1443: ['Male'], 1459: ['Female'], 1463: ['Female'], 1464: ['Male'], 1489: ['Male'], 1508: ['Male'], 1559: ['Male'], 1610: ['Male'], 1651: ['Male'], 1670: ['Female'], 1678: ['Female'], 1680: ['Male'], 1688: ['Female'], 1689: ['Male'], 1690: ['Male'], 1717: ['Female'], 1723: ['Male'], 1732: ['Male'], 1755: ['Male'], 1763: ['Female'], 1764: ['Male'], 1852: ['Female'], 1858: ['Male'], 1863: ['Male'], 1904: ['Male'], 1907: ['Male'], 1926: ['Male'], 1940: ['Male'], 2024: ['Male'], 2025: ['Female'], 2098: ['Male'], 2132: ['Male'], 2143: ['Male'], 2162: ['Male'], 2180: ['Male'], 2206: ['Male'], 2218: ['Female'], 2221: ['Female'], 2293: ['Female'], 2300: ['Male'], 2302: ['Male'], 2313: ['Male'], 2325: ['Male'], 2327: ['Male'], 2354: ['Male'], 2358: ['Male'], 2381: ['Male'], 2386: ['Male'], 2394: ['Female'], 2418: ['Female'], 2432: ['Male'], 2434: ['Female'], 2476: ['Male'], 2502: ['Female'], 2503: ['Male'], 2506: ['Female'], 2507: ['Female'], 2522: ['Male'], 2563: ['Male'], 2572: ['Male'], 2580: ['Male'], 2604: ['Male'], 2620: ['Male'], 2634: ['Female'], 2640: ['Male'], 2650: ['Male'], 2669: ['Male'], 2674: ['Male'], 2697: ['Male'], 2721: ['Male'], 2726: ['Female'], 2752: ['Male'], 2770: ['Male'], 2787: ['Male'], 2799: ['Female'], 2802: ['Male'], 2809: ['Male'], 2814: ['Female'], 2817: ['Male'], 2820: ['Male'], 2830: ['Female'], 2857: ['Male'], 2862: ['Female'], 2866: ['Male'], 2904: ['Female'], 2915: ['Male'], 2928: ['Female'], 2956: ['Female'], 2973: ['Male'], 2989: ['Male'], 2992: ['Male'], 3013: ['Male'], 3021: ['Male'], 3040: ['Male'], 3048: ['Female'], 3049: ['Female'], 3053: ['Male'], 3058: ['Female'], 3061: ['Male'], 3073: ['Female'], 3079: ['Male'], 3092: ['Female'], 3101: ['Female'], 3114: ['Male'], 3127: ['Female'], 3128: ['Male'], 3130: ['Male'], 3162: ['Female'], 3184: ['Male'], 3209: ['Male'], 3217: ['Male'], 3227: ['Female'], 3280: ['Male'], 3300: ['Male'], 3316: ['Male'], 3343: ['Male'], 3352: ['Female'], 3362: ['Male'], 3371: ['Male'], 3377: ['Female'], 3404: ['Male'], 3415: ['Female'], 3420: ['Male'], 3426: ['Male'], 3435: ['Male'], 3443: ['Male'], 3465: ['Male'], 3481: ['Male'], 3482: ['Male'], 3501: ['Male'], 3504: ['Female'], 3511: ['Male'], 3544: ['Male'], 3576: ['Female'], 3581: ['Female'], 3590: ['Male'], 3611: ['Female'], 3613: ['Male'], 3615: ['Female'], 3624: ['Female'], 3633: ['Male'], 3659: ['Female'], 3663: ['Male'], 3687: ['Male'], 3715: ['Female'], 3723: ['Male'], 3726: ['Female'], 3728: ['Male'], 3734: ['Female'], 3772: ['Female'], 3789: ['Male'], 3815: ['Female'], 3839: ['Male'], 3845: ['Female'], 3869: ['Male'], 3903: ['Male'], 3932: ['Male'], 3933: ['Female'], 3939: ['Male'], 3947: ['Male'], 3953: ['Female'], 3969: ['Female'], 3976: ['Female'], 3997: ['Male'], 4007: ['Male'], 4022: ['Male'], 4025: ['Male'], 4037: ['Female'], 4040: ['Female'], 4054: ['Male'], 4081: ['Male'], 4094: ['Female'], 4104: ['Female'], 4132: ['Male'], 4204: ['Female'], 4212: ['Male'], 4218: ['Female'], 4273: ['Male'], 4278: ['Male'], 4282: ['Female'], 4284: ['Female'], 4354: ['Male'], 4378: ['Male'], 4384: ['Female'], 4398: ['Male'], 4399: ['Female'], 4403: ['Male'], 4422: ['Female'], 4426: ['Female'], 4432: ['Male'], 4449: ['Female'], 4451: ['Male'], 4464: ['Male'], 4471: ['Male'], 4473: ['Female'], 4474: ['Male'], 4483: ['Male'], 4493: ['Male'], 4494: ['Male'], 4588: ['Male'], 4650: ['Male'], 4663: ['Male'], 4664: ['Male'], 4673: ['Female'], 4681: ['Male'], 4715: ['Male'], 4759: ['Male'], 4767: ['Male'], 4770: ['Male'], 4778: ['Male'], 4787: ['Male'], 4789: ['Female'], 4808: ['Female'], 4838: ['Female'], 4841: ['Female'], 4845: ['Male'], 4853: ['Female'], 4880: ['Male'], 4891: ['Female'], 4900: ['Female'], 4932: ['Female'], 4933: ['Male'], 4934: ['Female'], 4961: ['Male'], 4971: ['Male'], 4991: ['Female'], 4992: ['Female'], 4993: ['Female'], 4997: ['Female'], 5002: ['Male'], 5005: ['Female'], 5029: ['Male'], 5037: ['Male'], 5069: ['Male'], 5090: ['Female'], 5107: ['Female'], 5137: ['Male'], 5143: ['Male'], 5156: ['Male'], 5165: ['Male'], 5172: ['Male'], 5182: ['Male'], 5183: ['Female'], 5187: ['Male'], 5225: ['Male'], 5250: ['Male'], 5256: ['Female'], 5260: ['Male'], 5286: ['Female'], 5287: ['Female'], 5301: ['Male'], 5309: ['Male'], 5319: ['Male'], 5334: ['Male'], 5353: ['Male'], 5354: ['Female'], 5389: ['Female'], 5400: ['Male'], 5414: ['Female'], 5415: ['Female'], 5421: ['Male'], 5434: ['Male'], 5437: ['Male'], 5447: ['Male'], 5451: ['Male'], 5503: ['Female'], 5504: ['Female'], 5506: ['Male'], 5511: ['Male'], 5512: ['Male'], 5516: ['Female'], 5528: ['Female'], 5547: ['Male'], 5564: ['Male'], 5567: ['Male'], 5596: ['Male'], 5628: ['Female'], 5635: ['Male'], 5657: ['Female'], 5677: ['Female'], 5681: ['Male'], 5687: ['Female'], 5696: ['Male'], 5717: ['Female'], 5724: ['Male'], 5750: ['Male'], 5754: ['Male'], 5792: ['Female'], 5798: ['Male'], 5841: ['Female'], 5857: ['Male'], 5871: ['Male'], 5908: ['Male'], 5929: ['Male'], 5945: ['Female'], 5956: ['Female'], 5958: ['Male'], 5976: ['Male'], 5998: ['Female'], 6005: ['Male'], 6043: ['Female'], 6051: ['Male'], 6060: ['Male'], 6068: ['Female'], 6069: ['Male'], 6071: ['Male'], 6078: ['Female'], 6110: ['Male'], 6135: ['Male'], 6140: ['Female'], 6151: ['Male'], 6156: ['Female'], 6157: ['Male'], 6171: ['Female'], 6188: ['Male'], 6196: ['Male'], 6218: ['Female'], 6225: ['Male'], 6240: ['Male'], 6273: ['Male'], 6275: ['Female'], 6306: ['Female'], 6313: ['Male'], 6323: ['Male'], 6325: ['Female'], 6331: ['Male'], 6360: ['Female'], 6382: ['Male'], 6402: ['Male'], 6426: ['Male'], 6442: ['Male'], 6448: ['Female'], 6449: ['Female'], 6453: ['Female'], 6454: ['Male'], 6474: ['Male'], 6481: ['Male'], 6493: ['Male'], 6495: ['Male'], 6500: ['Male'], 6522: ['Female'], 6558: ['Male'], 6571: ['Male'], 6584: ['Female'], 6587: ['Male'], 6624: ['Female'], 6632: ['Male'], 6674: ['Male'], 6695: ['Female'], 6715: ['Female'], 6725: ['Male'], 6735: ['Male'], 6743: ['Female'], 6752: ['Male'], 6759: ['Male'], 6774: ['Male'], 6776: ['Male'], 6780: ['Male'], 6793: ['Female'], 6805: ['Male'], 6838: ['Female'], 6840: ['Female'], 6846: ['Male'], 6849: ['Male'], 6862: ['Male'], 6874: ['Male'], 6894: ['Male'], 6910: ['Male'], 6919: ['Male'], 6928: ['Male'], 6935: ['Male'], 6938: ['Female'], 6962: ['Male'], 6975: ['Male'], 7000: ['Female'], 7003: ['Male'], 7036: ['Male'], 7038: ['Female'], 7071: ['Male'], 7076: ['Female'], 7089: ['Female'], 7095: ['Male'], 7118: ['Male'], 7135: ['Female'], 7154: ['Female'], 7217: ['Female'], 7229: ['Male'], 7230: ['Female'], 7242: ['Male'], 7259: ['Male'], 7263: ['Male'], 7274: ['Female'], 7283: ['Female'], 7300: ['Male'], 7321: ['Female'], 7337: ['Male'], 7342: ['Male'], 7363: ['Female'], 7383: ['Female'], 7384: ['Female'], 7405: ['Female'], 7407: ['Male'], 7408: ['Female'], 7427: ['Female'], 7429: ['Male'], 7433: ['Male'], 7441: ['Male'], 7452: ['Female'], 7453: ['Male'], 7469: ['Male'], 7470: ['Female'], 7473: ['Male'], 7484: ['Male'], 7487: ['Male'], 7528: ['Male'], 7549: ['Female'], 7554: ['Male'], 7597: ['Female'], 7605: ['Male'], 7636: ['Female'], 7644: ['Female'], 7645: ['Male'], 7669: ['Female'], 7677: ['Female'], 7684: ['Female'], 7694: ['Male'], 7695: ['Male'], 7730: ['Female'], 7736: ['Female'], 7753: ['Male'], 7792: ['Male'], 7820: ['Female'], 7838: ['Male'], 7859: ['Male'], 7870: ['Male'], 7872: ['Female'], 7878: ['Female'], 7881: ['Male'], 7898: ['Male'], 7994: ['Male'], 7998: ['Female'], 8040: ['Male'], 8051: ['Female'], 8057: ['Female'], 8089: ['Female'], 8091: ['Male'], 8105: ['Female'], 8126: ['Male'], 8136: ['Male'], 8168: ['Female'], 8213: ['Female'], 8231: ['Male'], 8256: ['Female'], 8295: ['Male'], 8384: ['Female'], 8387: ['Male'], 8389: ['Male'], 8416: ['Female'], 8440: ['Female'], 8449: ['Female'], 8456: ['Male'], 8458: ['Male'], 8461: ['Male'], 8469: ['Female'], 8472: ['Male'], 8486: ['Male'], 8490: ['Male'], 8515: ['Female'], 8539: ['Male'], 8542: ['Male'], 8547: ['Male'], 8565: ['Male'], 8574: ['Male'], 8581: ['Male'], 8587: ['Male'], 8622: ['Female'], 8639: ['Male'], 8655: ['Female'], 8668: ['Male'], 8677: ['Female'], 8716: ['Female'], 8719: ['Female'], 8722: ['Female'], 8753: ['Female'], 8765: ['Male'], 8768: ['Female'], 8775: ['Female'], 8801: ['Female'], 8825: ['Male'], 8830: ['Female'], 8842: ['Male'], 8850: ['Female'], 8852: ['Female'], 8866: ['Male'], 8869: ['Male'], 8877: ['Male'], 8891: ['Male'], 8896: ['Male'], 8900: ['Female'], 8901: ['Female'], 8904: ['Female'], 8912: ['Male'], 8915: ['Female'], 8921: ['Female'], 8927: ['Male'], 8935: ['Female'], 8953: ['Male'], 8989: ['Female'], 8994: ['Male'], 9075: ['Male'], 9092: ['Male'], 9095: ['Female'], 9110: ['Female'], 9114: ['Male'], 9124: ['Male'], 9144: ['Male'], 9161: ['Female'], 9163: ['Female'], 9186: ['Male'], 9203: ['Male'], 9207: ['Male'], 9208: ['Male'], 9210: ['Male'], 9214: ['Female'], 9218: ['Male'], 9224: ['Male'], 9243: ['Male'], 9258: ['Male'], 9262: ['Male'], 9272: ['Male'], 9281: ['Female'], 9300: ['Female'], 9350: ['Male'], 9376: ['Male'], 9394: ['Male'], 9397: ['Female'], 9400: ['Male'], 9422: ['Female'], 9443: ['Female'], 9447: ['Male'], 9481: ['Female'], 9490: ['Female'], 9507: ['Female'], 9537: ['Male'], 9554: ['Male'], 9556: ['Male'], 9565: ['Male'], 9568: ['Male'], 9590: ['Female'], 9600: ['Male'], 9619: ['Male'], 9631: ['Male'], 9689: ['Male'], 9695: ['Female'], 9702: ['Male'], 9714: ['Male'], 9721: ['Male'], 9730: ['Male'], 9739: ['Male'], 9744: ['Male'], 9756: ['Male'], 9775: ['Male'], 9802: ['Female'], 9835: ['Male'], 9846: ['Male'], 9868: ['Male'], 9879: ['Male'], 9906: ['Female'], 9914: ['Male'], 9936: ['Male'], 9941: ['Male'], 9953: ['Male'], 9966: ['Male'], 9967: ['Male'], 9978: ['Male'], 9988: ['Female'], 10003: ['Male'], 10028: ['Female'], 10063: ['Female'], 10071: ['Male'], 10085: ['Male'], 10090: ['Male'], 10104: ['Female'], 10106: ['Female'], 10117: ['Female'], 10164: ['Male'], 10198: ['Male'], 10199: ['Male'], 10200: ['Male'], 10203: ['Male'], 10213: ['Male'], 10218: ['Male'], 10237: ['Female'], 10239: ['Male'], 10254: ['Male'], 10260: ['Male'], 10272: ['Female'], 10275: ['Female'], 10286: ['Female'], 10310: ['Male'], 10331: ['Male'], 10373: ['Male'], 10379: ['Female'], 10418: ['Male'], 10431: ['Male'], 10455: ['Male'], 10456: ['Male'], 10460: ['Male'], 10469: ['Female'], 10500: ['Female'], 10519: ['Male'], 10520: ['Female'], 10527: ['Male'], 10538: ['Male'], 10590: ['Male'], 10599: ['Male'], 10611: ['Male'], 10631: ['Male'], 10639: ['Female'], 10660: ['Male'], 10670: ['Male'], 10675: ['Female'], 10708: ['Female'], 10727: ['Male'], 10746: ['Male'], 10752: ['Male'], 10764: ['Female'], 10767: ['Female'], 10773: ['Male'], 10776: ['Female'], 10794: ['Female'], 10804: ['Male'], 10810: ['Male'], 10815: ['Male'], 10820: ['Female'], 10829: ['Female'], 10834: ['Male'], 10839: ['Female'], 10851: ['Male'], 10862: ['Male'], 10866: ['Male'], 10874: ['Male'], 10882: ['Male'], 10883: ['Female'], 10893: ['Female'], 10934: ['Male'], 10956: ['Male'], 10971: ['Female'], 11014: ['Male'], 11028: ['Male'], 11031: ['Female'], 11039: ['Female'], 11058: ['Female'], 11063: ['Male'], 11098: ['Female'], 11108: ['Male'], 11109: ['Female'], 11111: ['Male'], 11119: ['Male'], 11151: ['Female'], 11159: ['Male'], 11172: ['Male'], 11182: ['Female'], 11203: ['Female'], 11226: ['Male'], 11234: ['Male'], 11247: ['Male'], 11267: ['Female'], 11271: ['Male'], 11276: ['Female'], 11301: ['Male'], 11308: ['Female'], 11320: ['Male'], 11323: ['Male'], 11343: ['Male'], 11365: ['Male'], 11391: ['Male'], 11394: ['Male'], 11415: ['Male'], 11457: ['Female'], 11458: ['Male'], 11470: ['Male'], 11499: ['Male'], 11500: ['Male'], 11517: ['Female'], 11529: ['Male'], 11538: ['Male'], 11581: ['Male'], 11643: ['Male'], 11647: ['Male'], 11664: ['Male'], 11674: ['Male'], 11679: ['Male'], 11693: ['Male'], 11694: ['Female'], 11698: ['Male'], 11716: ['Female'], 11723: ['Female'], 11730: ['Female'], 11745: ['Female'], 11766: ['Male'], 11780: ['Male'], 11789: ['Female'], 11798: ['Male'], 11799: ['Male'], 11801: ['Male'], 11825: ['Female'], 11837: ['Female'], 11840: ['Male'], 11841: ['Male'], 11845: ['Female'], 11857: ['Male'], 11863: ['Male'], 11892: ['Male'], 11897: ['Female'], 11910: ['Male'], 11920: ['Male'], 11922: ['Male'], 11939: ['Male'], 11955: ['Male'], 11964: ['Male'], 11993: ['Female'], 12000: ['Male'], 12004: ['Male'], 12018: ['Female'], 12041: ['Female'], 12045: ['Male'], 12048: ['Male'], 12088: ['Female'], 12099: ['Male'], 12101: ['Male'], 12104: ['Female'], 12126: ['Male'], 12133: ['Female'], 12147: ['Male'], 12155: ['Female'], 12156: ['Male'], 12164: ['Female'], 12166: ['Female'], 12172: ['Male'], 12220: ['Male'], 12227: ['Male'], 12234: ['Male'], 12243: ['Female'], 12262: ['Male'], 12269: ['Male'], 12290: ['Male'], 12317: ['Male'], 12326: ['Female'], 12337: ['Female'], 12352: ['Female'], 12354: ['Male'], 12392: ['Male'], 12393: ['Female'], 12396: ['Female'], 12402: ['Male'], 12406: ['Male'], 12413: ['Female'], 12419: ['Female'], 12455: ['Male'], 12457: ['Female'], 12470: ['Male'], 12501: ['Male'], 12508: ['Male'], 12528: ['Male'], 12529: ['Male'], 12530: ['Female'], 12540: ['Female'], 12551: ['Female'], 12553: ['Male'], 12567: ['Male'], 12579: ['Male'], 12598: ['Male'], 12607: ['Female'], 12608: ['Female'], 12618: ['Female'], 12627: ['Male'], 12630: ['Male'], 12632: ['Female'], 12634: ['Male'], 12636: ['Male'], 12651: ['Male'], 12690: ['Male'], 12700: ['Male'], 12728: ['Male'], 12777: ['Male'], 12792: ['Female'], 12796: ['Female'], 12806: ['Male'], 12808: ['Female'], 12815: ['Male'], 12825: ['Male'], 12844: ['Male'], 12861: ['Male'], 12872: ['Female'], 12883: ['Male'], 12894: ['Male'], 12915: ['Female'], 12932: ['Male'], 12949: ['Female'], 12955: ['Female'], 12960: ['Male'], 12966: ['Female'], 12974: ['Female'], 12978: ['Female'], 12987: ['Male'], 12988: ['Female'], 12992: ['Male'], 13000: ['Male'], 13001: ['Male'], 13014: ['Male'], 13061: ['Male'], 13077: ['Male'], 13078: ['Male'], 13079: ['Female'], 13084: ['Female'], 13098: ['Male'], 13100: ['Male'], 13107: ['Male'], 13114: ['Female'], 13129: ['Male'], 13132: ['Male'], 13187: ['Female'], 13190: ['Male'], 13193: ['Male'], 13200: ['Female'], 13247: ['Male'], 13259: ['Male'], 13275: ['Male'], 13292: ['Male'], 13294: ['Male'], 13296: ['Male'], 13300: ['Male'], 13306: ['Female'], 13332: ['Female'], 13336: ['Male'], 13357: ['Female'], 13360: ['Male'], 13366: ['Female'], 13370: ['Male'], 13393: ['Male'], 13395: ['Female'], 13424: ['Female'], 13428: ['Female'], 13473: ['Male'], 13478: ['Male'], 13492: ['Female'], 13498: ['Female'], 13501: ['Female'], 13506: ['Male'], 13513: ['Male'], 13528: ['Male'], 13533: ['Male'], 13534: ['Male'], 13540: ['Male'], 13543: ['Female'], 13565: ['Female'], 13597: ['Female'], 13603: ['Male'], 13604: ['Male'], 13607: ['Female'], 13613: ['Male'], 13621: ['Male'], 13622: ['Female'], 13662: ['Male'], 13669: ['Male'], 13672: ['Male'], 13676: ['Female'], 13721: ['Male'], 13745: ['Male'], 13746: ['Male'], 13749: ['Female'], 13761: ['Male'], 13766: ['Female'], 13767: ['Male'], 13771: ['Male'], 13790: ['Female'], 13813: ['Male'], 13814: ['Male'], 13817: ['Female'], 13818: ['Female'], 13903: ['Male'], 13908: ['Female'], 13925: ['Male'], 13929: ['Male'], 13937: ['Male'], 13945: ['Female'], 13954: ['Female'], 13985: ['Male'], 13998: ['Male'], 14022: ['Female'], 14030: ['Male'], 14070: ['Female'], 14071: ['Male'], 14075: ['Female'], 14080: ['Male'], 14082: ['Male'], 14117: ['Male'], 14129: ['Male'], 14134: ['Male'], 14148: ['Male'], 14159: ['Female'], 14162: ['Male'], 14173: ['Female'], 14174: ['Female'], 14191: ['Female'], 14195: ['Male'], 14197: ['Female'], 14226: ['Female'], 14233: ['Male'], 14239: ['Female'], 14247: ['Female'], 14252: ['Female'], 14257: ['Male'], 14261: ['Male'], 14265: ['Male'], 14272: ['Female'], 14281: ['Male'], 14282: ['Male'], 14285: ['Male'], 14289: ['Male'], 14302: ['Female'], 14306: ['Female'], 14314: ['Female'], 14322: ['Male'], 14373: ['Female'], 14391: ['Male'], 14392: ['Male'], 14410: ['Female'], 14422: ['Male'], 14466: ['Male'], 14469: ['Male'], 14476: ['Female'], 14478: ['Male'], 14500: ['Male'], 14508: ['Female'], 14511: ['Female'], 14531: ['Female'], 14532: ['Male'], 14544: ['Female'], 14548: ['Male'], 14572: ['Male'], 14575: ['Female'], 14602: ['Female'], 14628: ['Female'], 14634: ['Female'], 14665: ['Female'], 14666: ['Male'], 14669: ['Female'], 14689: ['Female'], 14717: ['Male'], 14742: ['Female'], 14753: ['Female'], 14808: ['Male'], 14825: ['Female'], 14838: ['Female'], 14880: ['Male'], 14883: ['Female'], 14886: ['Female'], 14892: ['Female'], 14907: ['Female'], 14919: ['Male'], 14945: ['Female'], 14952: ['Female'], 14969: ['Male'], 14984: ['Male'], 14988: ['Male'], 14994: ['Female'], 15027: ['Female'], 15031: ['Female'], 15059: ['Male'], 15064: ['Female'], 15069: ['Female'], 15073: ['Female'], 15094: ['Male'], 15107: ['Female'], 15134: ['Male'], 15138: ['Female'], 15159: ['Male'], 15170: ['Male'], 15188: ['Male'], 15200: ['Male'], 15210: ['Male'], 15223: ['Male'], 15224: ['Female'], 15225: ['Female'], 15233: ['Male'], 15236: ['Male'], 15246: ['Female'], 15264: ['Male'], 15266: ['Female'], 15271: ['Male'], 15287: ['Male'], 15338: ['Male'], 15352: ['Female'], 15360: ['Male'], 15368: ['Male'], 15372: ['Male'], 15397: ['Female'], 15400: ['Male'], 15403: ['Male'], 15405: ['Female'], 15410: ['Female'], 15426: ['Female'], 15441: ['Male'], 15490: ['Male'], 15496: ['Female'], 15530: ['Male'], 15575: ['Female'], 15581: ['Female'], 15586: ['Female'], 15625: ['Male'], 15641: ['Male'], 15644: ['Female'], 15674: ['Male'], 15686: ['Female'], 15702: ['Male'], 15711: ['Female'], 15717: ['Male'], 15725: ['Female'], 15726: ['Male'], 15730: ['Female'], 15738: ['Male'], 15746: ['Male'], 15772: ['Female'], 15786: ['Male'], 15797: ['Female'], 15810: ['Female'], 15815: ['Female'], 15817: ['Male'], 15837: ['Female'], 15844: ['Female'], 15868: ['Male'], 15883: ['Male'], 15907: ['Male'], 15910: ['Male'], 15928: ['Female'], 15955: ['Female'], 15963: ['Male'], 15968: ['Female'], 15970: ['Male'], 15972: ['Female'], 15988: ['Male'], 15990: ['Male'], 16017: ['Male'], 16023: ['Female'], 16054: ['Male'], 16076: ['Male'], 16090: ['Female'], 16114: ['Male'], 16133: ['Female'], 16140: ['Male'], 16149: ['Male'], 16187: ['Male'], 16200: ['Female'], 16202: ['Male'], 16213: ['Female'], 16227: ['Male'], 16248: ['Female'], 16250: ['Male'], 16262: ['Female'], 16279: ['Male'], 16286: ['Female'], 16298: ['Male'], 16299: ['Male'], 16302: ['Female'], 16311: ['Female'], 16340: ['Female'], 16370: ['Male'], 16387: ['Female'], 16394: ['Male'], 16396: ['Female'], 16399: ['Female'], 16407: ['Male'], 16411: ['Male'], 16442: ['Female'], 16449: ['Male'], 16451: ['Female'], 16469: ['Female'], 16476: ['Male'], 16499: ['Male'], 16528: ['Male'], 16530: ['Male'], 16532: ['Female'], 16534: ['Male'], 16550: ['Female'], 16605: ['Male'], 16644: ['Male'], 16657: ['Male'], 16677: ['Male'], 16708: ['Female'], 16724: ['Male'], 16755: ['Male'], 16768: ['Femal

In [11]:
item_set = set(rdf['item_id'].unique())
user_set = set(rdf['user_id'].unique())
print('item num = ' + str(len(item_set)))
print('user num = ' + str(len(user_set)))

item num = 8188
user num = 132393

In [12]:
# count the number for each user type and sort
import operator
type_count = dict()
for l in user_type_dict:
    for g in user_type_dict[l]:
        if not g in type_count:
            type_count[g] = 1
        else:
            type_count[g] += 1

type_count_sorted = sorted(type_count.items(), key=operator.itemgetter(1), reverse=True)
type_count_sorted

[('Female', 71043), ('Male', 61350)]

In [13]:
key_type = ['Female', 'Male']

# get the key_type->user_list dict
key_type_user = dict()
for k in key_type:
    key_type_user[k] = list()
for user in user_type_dict:
    for t in user_type_dict[user]:
        if t in key_type:
            key_type_user[t].append(user)

In [14]:
# collect all the users with key types
key_user_set = set()
for types in key_type_user:
    key_user_set |= set(key_type_user[types])

nonkey_user_set = user_set - key_user_set

In [15]:
# remove the non-key type users in rdf
remove_list = []
for user in nonkey_user_set:
    remove_list += rdf.index[rdf['user_id'] == user].values.tolist()

In [16]:
print(len(remove_list))

0

In [17]:
rdf.drop(remove_list, inplace=True)

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:3997: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [18]:
rdf.reset_index(drop=True, inplace=True)
rating_df = copy.copy(rdf)

In [19]:
len(rdf['user_id'].unique())

132393

In [20]:
rdf = copy.copy(rating_df)

In [21]:
# iteratively remove items and users with less than 2 reviews
rdf.reset_index(drop=True, inplace=True)

rdf['user_freq'] = rdf.groupby('user_id')['user_id'].transform('count')
rdf.drop(rdf.index[rdf['user_freq'] <= 2], inplace=True)
rdf.reset_index(drop=True, inplace=True)
rdf['item_freq'] = rdf.groupby('item_id')['item_id'].transform('count')
rdf.drop(rdf.index[rdf['item_freq'] <= 2], inplace=True)
rdf.reset_index(drop=True, inplace=True)
rdf['user_freq'] = rdf.groupby('user_id')['user_id'].transform('count')
rdf.reset_index(drop=True, inplace=True)
rdf['user_id'].value_counts()

30661     34
7605      30
179602    29
16528     29
22606     28
          ..
355003     1
117441     1
389800     1
104481     1
230146     1
Name: user_id, Length: 7882, dtype: int64

In [22]:
item_list = rdf['item_id'].unique()
user_list = rdf['user_id'].unique()
print('item num = ' + str(len(item_list)))
print('user num = ' + str(len(user_list)))

item num = 2289
user num = 7882

In [23]:
# get the user and item str id->int id dict
i = 0
user_id_dict = dict()
for u in user_list:
    if not u in user_id_dict:
        user_id_dict[u] = i
        i += 1
j = 0
item_id_dict = dict()
for i in item_list:
    if not i in item_id_dict:
        item_id_dict[i] = j
        j += 1

In [24]:
print('sparsity: ' + str(len(rdf) * 1.0 / (len(user_list) * len(item_list))))

sparsity: 0.0014978468451600825

In [25]:
# get the df of train, vali, and test set
rdf.reset_index(inplace=True, drop=True)
train_df = rdf.copy()
vali_df = rdf.copy()
test_df = rdf.copy()

train_ratio = 0.8
vali_ratio = 0.0
test_ratio = 0.2
num_all = len(rdf)
vali_idx = []
test_idx = []

test_vali_idx = []
i = 0
num_user = len(user_list)
for u in user_list:
    u_idx = train_df.index[train_df['user_id'] == u]
    idx_len = len(u_idx)
    test_len = int(idx_len * (test_ratio + vali_ratio))
    if test_len == 0:
        test_len = 1
    tmp = np.random.choice(u_idx, size=test_len, replace=False)
    test_vali_idx += tmp.tolist()
    i += 1
    if i % 5000 == 0:
        print(str(i) + '/' + str(num_user))

# tmp = (np.random.choice(range(num_all), size=(test_len+vali_len), replace=False)).tolist()
test_len = int(len(test_vali_idx) * test_ratio / (test_ratio + vali_ratio))
vali_len = int(len(test_vali_idx) - test_len)
test_idx = (np.random.choice(test_vali_idx, size=test_len, replace=False)).tolist()
vali_idx = (np.random.choice(test_vali_idx, size=vali_len, replace=False)).tolist()

test_set = set(test_idx)
vali_set = set(vali_idx)
train_set = set(range(num_all)) - test_set - vali_set
train_idx = list(train_set)
train_df.drop((test_idx + vali_idx), axis=0, inplace=True)
test_df.drop((train_idx + vali_idx), axis=0, inplace=True)
vali_df.drop((train_idx + test_idx), axis=0, inplace=True)

5000/7882

In [26]:
len(train_df['user_id'].unique())

7645

In [27]:
common_users =test_df['user_id'].isin(train_df['user_id'])# ne conserver que les utilisateurs donc l'id est présent dans le train set
test_df = test_df[common_users]
#print(common_users)
common_uid =rdf['user_id'].isin(train_df['user_id'])
rdf = rdf[common_uid]
test_df.reset_index(drop=True, inplace=True)
rdf.reset_index(drop=True, inplace=True)
print(train_df)

       user_id  item_id  rating  user_freq  item_freq
0          683        3     1.0          3          3
2         1156       81     5.0          8         14
4         1188       81     5.0          6         14
5         1188       80     4.0          6          8
7         1156       83     5.0          8          8
...        ...      ...     ...        ...        ...
27016   312530     8341     2.0          2         15
27017    19236     7089     4.0          4         37
27018    56662     9041     5.0          3          3
27019   932318     7089     5.0          3         37
27021   495678     7533     4.0          4          4

[18968 rows x 5 columns]

In [28]:
item_list = rdf['item_id'].unique()
user_list = rdf['user_id'].unique()
print('item num = ' + str(len(item_list)))
print('user num = ' + str(len(user_list)))

item num = 2289
user num = 7645

In [29]:
i = 0
user_id_dict = dict()
for u in user_list:
    if not u in user_id_dict:
        user_id_dict[u] = i
        i += 1
j = 0
item_id_dict = dict()
for i in item_list:
    if not i in item_id_dict:
        item_id_dict[i] = j
        j += 1

In [31]:
# get the matrix of train, vali and test set

train_df.reset_index(drop=True, inplace=True)
test_df.reset_index(drop=True, inplace=True)
vali_df.reset_index(drop=True, inplace=True)
rdf.reset_index(drop=True, inplace=True)
train = np.zeros((len(user_list), len(item_list)))
test = np.zeros((len(user_list), len(item_list)))
vali = np.zeros((len(user_list), len(item_list)))
for r in range(len(train_df)):
    train[user_id_dict[train_df.at[r, 'user_id']], item_id_dict[train_df.at[r, 'item_id']]] = 1.0
for r in range(len(test_df)):
    test[user_id_dict[test_df.at[r, 'user_id']], item_id_dict[test_df.at[r, 'item_id']]] = 1.0
for r in range(len(vali_df)):
    vali[user_id_dict[vali_df.at[r, 'user_id']], item_id_dict[vali_df.at[r, 'item_id']]] = 1.0

In [32]:
print(len(train_df))

18968

In [33]:
# get the user int id-> str id list, and the same for item 
user_list = user_id_dict.keys()
user_idd_list = list()
for u in range(len(user_list)):
    user_idd_list.append('')
for user in user_id_dict:
    user_idd_list[user_id_dict[user]] = user

item_list = item_id_dict.keys()
item_idd_list = list()
for i in range(len(item_list)):
    item_idd_list.append('')
for item in item_id_dict:
    item_idd_list[item_id_dict[item]] = item
    
# get the user int id->types list
user_idd_type_list = list()
for u in range(len(user_idd_list)):
    user_idd_type_list.append(user_type_dict[user_idd_list[u]])

In [34]:
train_df.head()

   user_id  item_id  rating  user_freq  item_freq
0      683        3     1.0          3          3
1     1156       81     5.0          8         14
2     1188       81     5.0          6         14
3     1188       80     4.0          6          8
4     1156       83     5.0          8          8

In [35]:
train_df.drop('user_freq', axis=1, inplace=True)
train_df.drop('item_freq', axis=1, inplace=True)
vali_df.drop('user_freq', axis=1, inplace=True)
vali_df.drop('item_freq', axis=1, inplace=True)
test_df.drop('user_freq', axis=1, inplace=True)
test_df.drop('item_freq', axis=1, inplace=True)
rdf.drop('user_freq', axis=1, inplace=True)
rdf.drop('item_freq', axis=1, inplace=True)

In [36]:
len(test_df['user_id'].unique())

7645

In [37]:
# get df for rdf, train, vali, test with int id for user and item
import copy
rating_df = copy.copy(rdf)
for i in range(len(rdf)):
    rating_df.at[i, 'user_id'] = user_id_dict[rating_df.at[i, 'user_id']]
    rating_df.at[i, 'item_id'] = item_id_dict[rating_df.at[i, 'item_id']]

training_df = copy.copy(train_df)
for i in range(len(training_df)):
    training_df.at[i, 'user_id'] = user_id_dict[training_df.at[i, 'user_id']]
    training_df.at[i, 'item_id'] = item_id_dict[training_df.at[i, 'item_id']]

valiing_df = copy.copy(vali_df)
for i in range(len(valiing_df)):
    valiing_df.at[i, 'user_id'] = user_id_dict[valiing_df.at[i, 'user_id']]
    valiing_df.at[i, 'item_id'] = item_id_dict[valiing_df.at[i, 'item_id']]

testing_df = copy.copy(test_df)
for i in range(len(testing_df)):
    testing_df.at[i, 'user_id'] = user_id_dict[testing_df.at[i, 'user_id']]
    testing_df.at[i, 'item_id'] = item_id_dict[testing_df.at[i, 'item_id']]

In [38]:
# generate the rating list for each key type, get the type->ratings dict
rdf.reset_index(drop=True, inplace=True)
key_type_rating = dict()
for k in key_type:
    key_type_rating[k] = 0.0
for r in range(len(rdf)):
    user = rdf.at[r, 'user_id']
    gl = user_type_dict[user]
    for k in key_type:
        if k in gl:
            key_type_rating[k] += 1.0

# get the user int id->type list
type_user_vector = dict()
for k in key_type:
    type_user_vector[k] = np.zeros((1, len(user_list)))
for u in range(len(user_idd_type_list)):
    type_list = user_idd_type_list[u]
    for t in type_list:
        if t in key_type:
            type_user_vector[t][0,u] = 1.0

In [39]:
len(user_idd_type_list)

7645

In [40]:
with open("user_type_dict_amazon.pkl", "wb") as f:
    pickle.dump(user_type_dict, f)
with open("type_user_vector_amazon.pkl", "wb") as f:
    pickle.dump(type_user_vector, f, pickle.HIGHEST_PROTOCOL)
with open("key_type_amazon.pkl", "wb") as f:
    pickle.dump(key_type, f, pickle.HIGHEST_PROTOCOL)
with open("user_id_dict_amazon.pkl", "wb") as f:
    pickle.dump(user_id_dict, f, pickle.HIGHEST_PROTOCOL)
with open("item_id_dict_amazon.pkl", "wb") as f:
    pickle.dump(item_id_dict, f, pickle.HIGHEST_PROTOCOL)
# with open("rdf.pkl", "wb") as f:
#     pickle.dump(rdf, f, pickle.HIGHEST_PROTOCOL)
with open("rating_df_amazon.pkl", "wb") as f:
    pickle.dump(rating_df, f, pickle.HIGHEST_PROTOCOL)
with open("training_df_amazon.pkl", "wb") as f:
    pickle.dump(training_df, f, pickle.HIGHEST_PROTOCOL)
with open("valiing_df_amazon.pkl", "wb") as f:
    pickle.dump(valiing_df, f, pickle.HIGHEST_PROTOCOL)
with open("testing_df_amazon.pkl", "wb") as f:
    pickle.dump(testing_df, f, pickle.HIGHEST_PROTOCOL)
with open("user_idd_type_list_amazon.pkl", "wb") as f:
    pickle.dump(user_idd_type_list, f, pickle.HIGHEST_PROTOCOL)
with open("item_idd_list_amazon.pkl", "wb") as f:
    pickle.dump(item_idd_list, f, pickle.HIGHEST_PROTOCOL)
with open("user_idd_list_amazon.pkl", "wb") as f:
    pickle.dump(user_idd_list, f, pickle.HIGHEST_PROTOCOL)
with open("key_type_rating_amazon.pkl", "wb") as f:
    pickle.dump(key_type_rating, f, pickle.HIGHEST_PROTOCOL)
    
with open("train_amazon.mat", "wb") as f:
    np.save(f, train)
with open("test_amazon.mat", "wb") as f:
    np.save(f, test)
with open("vali_amazon.mat", "wb") as f:
    np.save(f, vali)

In [41]:
# count the number for each user type and sort
import pickle5 as pickle
from operator import itemgetter
user_list = rdf['user_id'].unique()
#user_type_dict = pickle.load(open('./user_type_dict.pkl'))

with open('./user_type_dict_amazon.pkl', 'rb') as f:
    user_type_dict = pickle.load(f,encoding='latin1')

with open('./key_type_amazon.pkl', 'rb') as f:
    key_type = pickle.load(f,encoding='latin1')

#key_type = pickle.load(open('./key_type.pkl'))

type_count = dict()
for u in user_list:
    gl = user_type_dict[u]
    for g in gl:
        if g in key_type:
            if not g in type_count:
                type_count[g] = 1
            else:
                type_count[g] += 1

# with open("genre_count.pkl", "wb") as f:
#     pickle.dump(genre_count, f, pickle.HIGHEST_PROTOCOL)
                
type_count_sorted = sorted(type_count.items(), key=itemgetter(1), reverse=True)
type_count_sorted

[('Male', 5199), ('Female', 2446)]

In [42]:
with open("type_count_amazon.pkl", "wb") as f:
    pickle.dump(type_count_sorted, f)

In [43]:
import numpy as np

import copy as copy
train = np.load('./train_amazon.mat')

with open('./user_idd_type_list_amazon.pkl', 'rb') as f:
    user_idd_type_list = pickle.load(f,encoding='latin1')

user_idd_type_list = np.array(user_idd_type_list)


mask = 1.0 * (train > 0)
item_type_count = list()
for i in range(train.shape[1]):
    temp_type_count = copy.copy(type_count)
    mask_i = mask[:, i]
    gll = user_idd_type_list[mask_i == 1.0]
    for gl in gll:
        for g in gl:
            if g in key_type:
                temp_type_count[g] -= 1
    item_type_count.append(temp_type_count)
# with open("user_genre_count.pkl", "wb") as f:
#     pickle.dump(user_genre_count, f, pickle.HIGHEST_PROTOCOL)

In [44]:
with open("item_type_count_amazon.pkl", "wb") as f:
    pickle.dump(item_type_count, f)

In [45]:
len(item_type_count)

2289

In [46]:
type_count_sorted

[('Male', 5199), ('Female', 2446)]

In [47]:
with open('./key_type_rating_amazon.pkl', 'rb') as f:
    key_type_rating = pickle.load(f,encoding='latin1')


#key_type_rating = pickle.load(open('./key_genre_rating.pkl'))
type_avg_like = dict()
for k in key_type:
    type_avg_like[k] = key_type_rating[k] * 1.0 / type_count[k]

In [48]:
type_avg_like_sorted = sorted(type_avg_like.items(), key=itemgetter(1), reverse=True)
type_avg_like_sorted

[('Male', 3.529140219272937), ('Female', 3.4501226492232218)]