In [1]:
import tensorflow as tf
import time
import numpy as np
import os
import copy
import pickle
import argparse
import utilityarm as utility
import pandas as pd
from sklearn.metrics import *

In [2]:
import tensorflow.compat.v1 as tf

tf.disable_v2_behavior() 

class FairAdvBPR:

    def __init__(self, sess, dict_args, train_df, test_df, user_type, type_error_weight, key_type, user_type_list, item_type_count):
       
        self.dataname = dict_args['dataname']

        self.key_type = key_type
        self.user_type_list = user_type_list
        self.item_type_count = item_type_count
        self.layers = dict_args['layers']
        self.sess = sess
        
        self.num_cols = len(train_df['item_id'].unique())
        self.num_rows = len(train_df['user_id'].unique())

        self.hidden_neuron = dict_args['hidden_neuron']
        self.neg = dict_args['neg']
        self.batch_size = dict_args['batch_size']

        self.train_df = train_df
        self.vali_df = test_df
        self.num_train = len(self.train_df)
        self.num_vali = len(self.vali_df)

        self.train_epoch = dict_args['train_epoch']
        self.train_epoch_a = dict_args['train_epoch_a']

        self.lr_r = dict_args['lr_r'] # learning rate
        self.lr_a = dict_args['lr_a'] # learning rate
        self.alpha = dict_args['alpha'] # learning rate
        self.optimizer_method = dict_args['optimizer_method']
        self.display_step = dict_args['display_step']
        
        self.type_error_weight = type_error_weight
        self.num_type = dict_args['num_type']
        
        self.user_type = user_type
        self.type_count_list = []
        for k in range(self.num_type):
            self.type_count_list.append(np.sum(user_type[:,k]))

        
        self.reg = dict_args['reg'] # regularization term trade-off
        self.reg_s = dict_args['reg_s']

        print('**********fairAdvBPR**********')
        #print(self.args)
        self._prepare_model()

    def loadmodel(self, saver, checkpoint_dir):
        ckpt = tf.train.get_checkpoint_state(checkpoint_dir)
        if ckpt and ckpt.model_checkpoint_path:
            ckpt_name = os.path.basename(ckpt.model_checkpoint_path)
            saver.restore(self.sess, os.path.join(checkpoint_dir, ckpt_name))
            return True
        else:
            return False
        
    def run(self):
        init = tf.global_variables_initializer()
        self.sess.run(init)

        saver = tf.train.Saver([self.P, self.Q])
        self.loadmodel(saver, "./"+self.dataname+"/BPR_check_points")

        for epoch_itr in range(1, self.train_epoch + 1 + self.train_epoch_a):
            self.train_model(epoch_itr)
            if epoch_itr % self.display_step == 0:
                self.test_model(epoch_itr)
        return self.make_records()

    def _prepare_model(self):
        with tf.name_scope("input_data"):
            self.user_input = tf.placeholder(tf.int32, shape=[None, 1], name="user_input")
            self.item_input_pos = tf.placeholder(tf.int32, shape=[None, 1], name="item_input_pos")
            self.item_input_neg = tf.placeholder(tf.int32, shape=[None, 1], name="item_input_neg")

            self.input_user_type = tf.placeholder(dtype=tf.float32, shape=[None, self.num_type]
                                                   , name="input_user_type")
            self.input_user_error_weight = tf.placeholder(dtype=tf.float32, shape=[None, 1]
                                                          , name="input_user_error_weight")

        with tf.variable_scope("BPR", reuse=tf.AUTO_REUSE):
            self.P = tf.get_variable(name="P",
                                     initializer=tf.truncated_normal(shape=[self.num_rows, self.hidden_neuron], mean=0,
                                                                     stddev=0.03), dtype=tf.float32)
            self.Q = tf.get_variable(name="Q",
                                     initializer=tf.truncated_normal(shape=[self.num_cols+1, self.hidden_neuron], mean=0,
                                                                     stddev=0.03), dtype=tf.float32)
        para_r = tf.get_collection(tf.GraphKeys.GLOBAL_VARIABLES, scope="BPR")

        with tf.variable_scope("Adversarial", reuse=tf.AUTO_REUSE):
            num_layer = len(self.layers)
            adv_W = []
            adv_b = []
            for l in range(num_layer):
                if l == 0:
                    in_shape = 21
                else:
                    in_shape = self.layers[l - 1]
                adv_W.append(tf.get_variable(name="adv_W" + str(l),
                                             initializer=tf.truncated_normal(shape=[in_shape, self.layers[l]],
                                                                             mean=0, stddev=0.03), dtype=tf.float32))
                adv_b.append(tf.get_variable(name="adv_b" + str(l),
                                             initializer=tf.truncated_normal(shape=[1, self.layers[l]],
                                                                             mean=0, stddev=0.03), dtype=tf.float32))
            adv_W_out = tf.get_variable(name="adv_W_out",
                                        initializer=tf.truncated_normal(shape=[self.layers[-1], self.num_type],
                                                                        mean=0, stddev=0.03), dtype=tf.float32)

            adv_b_out = tf.get_variable(name="adv_b_out",
                                        initializer=tf.truncated_normal(shape=[1, self.num_type],
                                                                        mean=0, stddev=0.03), dtype=tf.float32)
        para_a = tf.get_collection(tf.GraphKeys.GLOBAL_VARIABLES, scope="Adversarial")

        p = tf.reduce_sum(tf.nn.embedding_lookup(self.P, self.user_input), 1)
        q_neg = tf.reduce_sum(tf.nn.embedding_lookup(self.Q, self.item_input_neg), 1)
        q_pos = tf.reduce_sum(tf.nn.embedding_lookup(self.Q, self.item_input_pos), 1)

        predict_pos = tf.reduce_sum(p * q_pos, 1)
        predict_neg = tf.reduce_sum(p * q_neg, 1)

        r_cost1 = tf.reduce_sum(tf.nn.softplus(-(predict_pos - predict_neg)))
        r_cost2 = self.reg * 0.5 * (self.l2_norm(self.P) + self.l2_norm(self.Q))  # regularization term
        pred = tf.matmul(self.P, tf.transpose(self.Q))
        self.s_mean = tf.reduce_mean(pred, axis=1)
        self.s_std = tf.keras.backend.std(pred, axis=1)
        self.s_cost = tf.reduce_sum(tf.square(self.s_mean) + tf.square(self.s_std) - 2 * tf.log(self.s_std) - 1)
        self.r_cost = r_cost1 + r_cost2 + self.reg_s * 0.5 * self.s_cost
        
        print('shape q pos',q_pos.shape)
        print('shape p',p.shape)
        print('shape predict pos ', predict_pos.shape)
        
        adv_last = tf.reshape(predict_pos, [tf.shape(self.input_user_type)[0], 1])
        print('shape adv_last ', adv_last.shape)
        adv_last = tf.concat([adv_last, q_pos], 1)
        
        for l in range(num_layer):
            adv = tf.nn.relu(tf.matmul(adv_last, adv_W[l]) + adv_b[l])
            adv_last = adv
        self.adv_output = tf.nn.sigmoid(tf.matmul(adv_last, adv_W_out) + adv_b_out)
        self.a_cost = tf.reduce_sum(tf.square(self.adv_output - self.input_user_type) * self.input_user_error_weight)

        self.all_cost = self.r_cost - self.alpha * self.a_cost  # the loss function

        with tf.variable_scope("Optimizer", reuse=tf.AUTO_REUSE):
            self.r_optimizer = tf.train.AdamOptimizer(learning_rate=self.lr_r).minimize(self.r_cost, var_list=para_r)
            self.a_optimizer = tf.train.AdamOptimizer(learning_rate=self.lr_a).minimize(self.a_cost, var_list=para_a)
            self.all_optimizer = tf.train.AdamOptimizer(learning_rate=self.lr_r).minimize(self.all_cost, var_list=para_r)


    def train_model(self, itr):
        NS_start_time = time.time() * 1000.0
        epoch_r_cost = 0.0
        epoch_s_cost = 0.0
        epoch_s_mean = 0.0
        epoch_s_std = 0.0
        epoch_a_cost = 0.0
        num_sample, user_list, item_pos_list, item_neg_list = utility.negative_sample(self.train_df, self.num_rows,
                                                                                      self.num_cols, self.neg)
        NS_end_time = time.time() * 1000.0

        start_time = time.time() * 1000.0
        num_batch = int(num_sample / float(self.batch_size)) + 1
        random_idx = np.random.permutation(num_sample)
        for i in range(num_batch):
            # get the indices of the current batch
            if i == num_batch - 1:
                batch_idx = random_idx[i * self.batch_size:]
            elif i < num_batch - 1:
                batch_idx = random_idx[(i * self.batch_size):((i + 1) * self.batch_size)]

            if itr > self.train_epoch:
                random_idx_a = np.random.permutation(num_sample)
                print("boucle adversarial debut-- num batch ",i)
                for j in range(num_batch):
                    if j == num_batch - 1:
                        batch_idx_a = random_idx_a[j * self.batch_size:]
                    elif j < num_batch - 1:
                        batch_idx_a = random_idx_a[(j * self.batch_size):((j + 1) * self.batch_size)]
                    user_idx_list = ((user_list[batch_idx_a, :]).reshape((len(batch_idx_a)))).tolist()
                    _, tmp_a_cost = self.sess.run(  # do the optimization by the minibatch
                        [self.a_optimizer, self.a_cost],
                        feed_dict={self.user_input: user_list[batch_idx_a, :],
                                   self.item_input_pos: item_pos_list[batch_idx_a, :],
                                   self.item_input_neg: item_neg_list[batch_idx_a, :],
                                   self.input_user_type: self.user_type[user_idx_list,:],
                                   self.input_user_error_weight: self.type_error_weight[user_idx_list,:]})
                    epoch_a_cost += tmp_a_cost

                user_idx_list = ((user_list[batch_idx, :]).reshape((len(batch_idx)))).tolist()
                _, tmp_r_cost, tmp_s_cost, tmp_s_mean, tmp_s_std = self.sess.run(  # do the optimization by the minibatch
                    [self.all_optimizer, self.all_cost, self.s_cost, self.s_mean, self.s_std],
                    feed_dict={self.user_input: user_list[batch_idx, :],
                               self.item_input_pos: item_pos_list[batch_idx, :],
                               self.item_input_neg: item_neg_list[batch_idx, :],
                               self.input_user_type: self.user_type[user_idx_list, :],
                               self.input_user_error_weight: self.type_error_weight[user_idx_list, :]})
                epoch_r_cost += tmp_r_cost
                epoch_s_mean += np.mean(tmp_s_mean)
                epoch_s_std += np.mean(tmp_s_std)
                epoch_s_cost += tmp_s_cost
                print("boucle adversarial fin")
            else:
                user_idx_list = ((user_list[batch_idx, :]).reshape((len(batch_idx)))).tolist()
                _, tmp_r_cost, tmp_s_cost, tmp_s_mean, tmp_s_std = self.sess.run(  # do the optimization by the minibatch
                    [self.r_optimizer, self.r_cost, self.s_cost, self.s_mean, self.s_std],
                    feed_dict={self.user_input: user_list[batch_idx, :],
                               self.item_input_pos: item_pos_list[batch_idx, :],
                               self.item_input_neg: item_neg_list[batch_idx, :],
                               self.input_user_type: self.user_type[user_idx_list, :],
                               self.input_user_error_weight: self.type_error_weight[user_idx_list, :]})
                epoch_r_cost += tmp_r_cost
                epoch_s_mean += np.mean(tmp_s_mean)
                epoch_s_std += np.mean(tmp_s_std)
                epoch_s_cost += tmp_s_cost
        epoch_a_cost /= num_batch
        if itr % self.display_step == 0:
            print ("Training //", "Epoch %d //" % itr, " Total r_cost = %.5f" % epoch_r_cost,
                   " Total s_cost = %.5f" % epoch_s_cost,
                   " Total s_mean = %.5f" % epoch_s_mean,
                   " Total s_std = %.5f" % epoch_s_std,
                   " Total a_cost = %.5f" % epoch_a_cost,
                   "Training time : %d ms" % (time.time() * 1000.0 - start_time),
                   "negative Sampling time : %d ms" % (NS_end_time - NS_start_time),
                   "negative samples : %d" % (num_sample))
       
    def test_model(self, itr):  # calculate the cost and rmse of testing set in each epoch
        if itr % self.display_step == 0:
            start_time = time.time() * 1000.0
            P, Q = self.sess.run([self.P, self.Q])
            Rec = np.matmul(P, Q.T)

            [precision, recall, f_score, NDCG] = utility.test_model_all(Rec, self.vali_df, self.train_df)
#             utility.ranking_analysis(Rec, self.vali_df, self.train_df, self.key_genre, self.item_genre_list,
#                                      self.user_genre_count)
            utility.test_model_per_user_type(Rec, self.vali_df, self.train_df, self.user_type_list, self.key_type)
            auc = utility.auc_per_user(Rec, self.vali_df, self.train_df)
            print("AUC global is: ", auc)
            
            filename = './IembfairAdvBPR_results/epoch'+ str(itr) +'_Rec_' + self.dataname + '_iembfairAdvBPR.npy'
            os.makedirs(os.path.dirname(filename), exist_ok=True)           
            with open(filename, "wb") as f:
                np.save(f, Rec)
            

    def make_records(self):  # record all the results' details into files
        P, Q = self.sess.run([self.P, self.Q])
        Rec = np.matmul(P, Q.T)

        [precision, recall, f_score, NDCG] = utility.test_model_all(Rec, self.vali_df, self.train_df)
        return precision, recall, f_score, NDCG, Rec

#     def test_model(self, itr):  # calculate the cost and rmse of testing set in each epoch
#         if itr % self.display_step == 0:
#             start_time = time.time() * 1000.0
#             P, Q = self.sess.run([self.P, self.Q])
#             Rec = np.matmul(P, Q.T)

#             [precision, recall, f_score, NDCG] = utility.test_model_all(Rec, self.vali_df, self.train_df)
# #             utility.ranking_analysis(Rec, self.vali_df, self.train_df, self.key_type, self.user_type_list,
# #                                      self.item_type_count)
#             utility.test_model_per_user_type(Rec, self.vali_df, self.train_df, self.user_type_list, self.key_type)
#             auc = utility.auc_per_user(Rec, self.vali_df, self.train_df)
#             print("AUC global is: ", auc)
#             print (
#                 "Testing //", "Epoch %d //" % itr,
#                 "Testing time : %d ms" % (time.time() * 1000.0 - start_time))
#             print("=" * 200)


    @staticmethod
    def l2_norm(tensor):
        return tf.reduce_sum(tf.square(tensor))

WARNING:tensorflow:From C:\Users\anoulape\AppData\Roaming\Python\Python39\site-packages\tensorflow\python\compat\v2_compat.py:107: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term

In [3]:

#optimizer_method = ['Adam', 'Adadelta', 'Adagrad', 'RMSProp', 'GradientDescent','Momentum'], default='Adam')


train_epoch = 1
train_epoch_a = 20 #default 20
display_step = 1
lr_r = 0.01
lr_a = 0.005
reg = 0.1
reg_s = 30
alpha = 1000
optimizer_method = 'Adam'
hidden_neuron = 20
n = 1
neg = 5
batch_size = 256
layers = [50, 50, 50, 50]
dataname = 'ml1m-6'

In [4]:
dict_args =  {"train_epoch": train_epoch,
              "train_epoch_a": train_epoch_a,
            "display_step":display_step,
            "lr_r":lr_r,
            "lr_a":lr_a,
            "reg":reg,
            "reg_s":reg_s,
            "alpha":alpha,
            "optimizer_method":optimizer_method,
            "hidden_neuron":hidden_neuron,
            "n":n,
            "neg":neg,
            "batch_size":batch_size,
            "layers":layers,
            "dataname":dataname}
dict_args

{'train_epoch': 1,
 'train_epoch_a': 1,
 'display_step': 1,
 'lr_r': 0.01,
 'lr_a': 0.005,
 'reg': 0.1,
 'reg_s': 30,
 'alpha': 1000,
 'optimizer_method': 'Adam',
 'hidden_neuron': 20,
 'n': 1,
 'neg': 5,
 'batch_size': 1024,
 'layers': [50, 50, 50, 50],
 'dataname': 'ml1m-6'}

In [5]:
with open('./training_df.pkl', 'rb') as f:
    train_df = pickle.load(f,encoding='latin1')

# with open('./' + dataname + '/valiing_df.pkl', 'rb') as f:
#     vali_df = pickle.load(f,encoding='latin1')  # for validation
    
with open('./testing_df.pkl', 'rb') as f:
    test_df = pickle.load(f,encoding='latin1')  # for validation
# vali_df = pickle.load(open('./' + dataname + '/testing_df.pkl'))  # for testing

with open('./key_type.pkl', 'rb') as f:
    key_type = pickle.load(f,encoding='latin1')
    
with open('./user_idd_type_list.pkl', 'rb') as f:
    user_idd_type_list = pickle.load(f,encoding='latin1')
    
with open('./type_user_vector.pkl', 'rb') as f:
    type_user_vector = pickle.load(f,encoding='latin1')

with open('./type_count.pkl', 'rb') as f:
    type_count = pickle.load(f,encoding='latin1')
    
with open('./item_type_count.pkl', 'rb') as f:
    item_type_count = pickle.load(f,encoding='latin1')

In [6]:
train_df.head(20)

    user_id  item_id  rating
0         0        0       5
1         0        2       3
2         0        3       4
3         0        4       5
4         0        5       3
5         0        7       5
6         0        9       4
7         0       10       5
8         0       11       4
9         0       12       4
10        0       14       5
11        0       15       4
12        0       16       3
13        0       18       5
14        0       19       4
15        0       20       3
16        0       21       3
17        0       22       5
18        0       23       5
19        0       24       3

In [7]:
train_df.shape

(802322, 3)

In [8]:
test_df.head(20)

    user_id  item_id  rating
0         0        1       3
1         0        6       5
2         0        8       4
3         0       13       4
4         0       17       4
5         0       28       4
6         0       39       5
7         0       42       4
8         0       43       4
9         0       50       4
10        1       58       4
11        1       59       5
12        1       70       4
13        1       71       3
14        1       72       2
15        1       73       3
16        1       78       5
17        1       85       5
18        1       88       4
19        1       89       4

In [9]:
test_df.shape

(197595, 3)

In [10]:
print(len(user_idd_type_list))

6040

In [11]:
user_idd_type_list

array([['F'],
       ['M'],
       ['M'],
       ...,
       ['F'],
       ['F'],
       ['M']], dtype='<U1')

In [12]:
print(type_user_vector['F'].shape)

(1, 6040)

In [13]:
type_user_vector

{'M': array([[0., 1., 1., ..., 0., 0., 1.]]),
 'F': array([[1., 0., 0., ..., 1., 1., 0.]])}

In [14]:
len(item_type_count)

3503

In [15]:
item_type_count

[{'F': 1353, 'M': 3293},
 {'F': 1578, 'M': 4041},
 {'F': 1464, 'M': 4053},
 {'F': 1362, 'M': 3596},
 {'F': 1335, 'M': 3335},
 {'F': 1192, 'M': 2962},
 {'F': 1598, 'M': 3863},
 {'F': 1434, 'M': 3530},
 {'F': 1521, 'M': 3935},
 {'F': 1301, 'M': 3378},
 {'F': 1400, 'M': 3779},
 {'F': 1630, 'M': 4253},
 {'F': 1609, 'M': 4115},
 {'F': 1407, 'M': 3442},
 {'F': 1482, 'M': 3847},
 {'F': 1381, 'M': 3271},
 {'F': 1605, 'M': 4086},
 {'F': 1549, 'M': 4014},
 {'F': 1540, 'M': 3955},
 {'F': 1393, 'M': 3443},
 {'F': 1450, 'M': 3677},
 {'F': 1626, 'M': 4064},
 {'F': 1197, 'M': 2764},
 {'F': 1218, 'M': 2965},
 {'F': 1606, 'M': 4152},
 {'F': 1586, 'M': 4158},
 {'F': 1222, 'M': 2972},
 {'F': 1313, 'M': 3467},
 {'F': 1680, 'M': 4303},
 {'F': 1567, 'M': 3943},
 {'F': 1563, 'M': 3950},
 {'F': 1570, 'M': 4119},
 {'F': 1595, 'M': 4080},
 {'F': 1356, 'M': 3576},
 {'F': 1581, 'M': 4063},
 {'F': 1589, 'M': 4135},
 {'F': 1675, 'M': 4260},
 {'F': 1537, 'M': 4044},
 {'F': 1186, 'M': 2893},
 {'F': 1443, 'M': 3564},
 {'F': 1233, 'M': 3146},
 {'F': 1410, 'M': 3550},
 {'F': 1530, 'M': 3986},
 {'F': 1495, 'M': 3684},
 {'F': 1178, 'M': 2442},
 {'F': 1414, 'M': 3804},
 {'F': 1536, 'M': 4035},
 {'F': 1469, 'M': 3845},
 {'F': 1234, 'M': 2679},
 {'F': 1566, 'M': 4195},
 {'F': 1358, 'M': 3418},
 {'F': 1186, 'M': 2855},
 {'F': 1507, 'M': 3845},
 {'F': 1548, 'M': 4042},
 {'F': 1636, 'M': 4106},
 {'F': 1595, 'M': 4169},
 {'F': 1619, 'M': 4074},
 {'F': 1550, 'M': 3572},
 {'F': 1447, 'M': 3344},
 {'F': 1492, 'M': 3696},
 {'F': 1338, 'M': 2908},
 {'F': 1616, 'M': 4106},
 {'F': 1469, 'M': 2973},
 {'F': 1654, 'M': 4018},
 {'F': 1163, 'M': 2571},
 {'F': 1661, 'M': 4028},
 {'F': 1672, 'M': 4097},
 {'F': 1435, 'M': 3277},
 {'F': 1400, 'M': 3102},
 {'F': 1538, 'M': 3893},
 {'F': 1686, 'M': 4185},
 {'F': 1658, 'M': 4105},
 {'F': 1642, 'M': 3856},
 {'F': 1629, 'M': 4013},
 {'F': 1559, 'M': 3765},
 {'F': 1488, 'M': 3799},
 {'F': 1644, 'M': 4055},
 {'F': 1635, 'M': 3952},
 {'F': 1454, 'M': 3245},
 {'F': 1592, 'M': 3846},
 {'F': 1659, 'M': 4219},
 {'F': 1624, 'M': 4149},
 {'F': 1455, 'M': 4017},
 {'F': 1584, 'M': 3803},
 {'F': 1337, 'M': 3240},
 {'F': 1469, 'M': 3586},
 {'F': 1527, 'M': 3486},
 {'F': 1571, 'M': 3934},
 {'F': 1459, 'M': 4020},
 {'F': 1441, 'M': 3739},
 {'F': 1556, 'M': 3646},
 {'F': 1540, 'M': 4002},
 {'F': 1280, 'M': 2811},
 {'F': 1619, 'M': 3777},
 {'F': 1619, 'M': 3795},
 {'F': 1605, 'M': 4033},
 {'F': 1480, 'M': 3433},
 {'F': 1340, 'M': 2575},
 {'F': 1622, 'M': 3787},
 {'F': 1671, 'M': 3976},
 {'F': 1686, 'M': 4229},
 {'F': 1609, 'M': 4011},
 {'F': 1683, 'M': 4295},
 {'F': 1623, 'M': 4198},
 {'F': 950, 'M': 2308},
 {'F': 1392, 'M': 3540},
 {'F': 1577, 'M': 4087},
 {'F': 1652, 'M': 3876},
 {'F': 1604, 'M': 4168},
 {'F': 1430, 'M': 3974},
 {'F': 1526, 'M': 3731},
 {'F': 1571, 'M': 3912},
 {'F': 1546, 'M': 3798},
 {'F': 1249, 'M': 2655},
 {'F': 1692, 'M': 4292},
 {'F': 1566, 'M': 4015},
 {'F': 1174, 'M': 3048},
 {'F': 1576, 'M': 3582},
 {'F': 1613, 'M': 4122},
 {'F': 1594, 'M': 3656},
 {'F': 1560, 'M': 3695},
 {'F': 1611, 'M': 4046},
 {'F': 1621, 'M': 3777},
 {'F': 1410, 'M': 3469},
 {'F': 1189, 'M': 2480},
 {'F': 1550, 'M': 3719},
 {'F': 1481, 'M': 3655},
 {'F': 1242, 'M': 2787},
 {'F': 1130, 'M': 2798},
 {'F': 1533, 'M': 3960},
 {'F': 1630, 'M': 3900},
 {'F': 1619, 'M': 3964},
 {'F': 1297, 'M': 2654},
 {'F': 1548, 'M': 3618},
 {'F': 1051, 'M': 3092},
 {'F': 1630, 'M': 4012},
 {'F': 1602, 'M': 3760},
 {'F': 1548, 'M': 3850},
 {'F': 1553, 'M': 3819},
 {'F': 1546, 'M': 3591},
 {'F': 1607, 'M': 4076},
 {'F': 1523, 'M': 3758},
 {'F': 1614, 'M': 4109},
 {'F': 1580, 'M': 3965},
 {'F': 1639, 'M': 3970},
 {'F': 1472, 'M': 3481},
 {'F': 1615, 'M': 3782},
 {'F': 1555, 'M': 3562},
 {'F': 1442, 'M': 3473},
 {'F': 1573, 'M': 3992},
 {'F': 1555, 'M': 3624},
 {'F': 1351, 'M': 3091},
 {'F': 1604, 'M': 4161},
 {'F': 1359, 'M': 3769},
 {'F': 1699, 'M': 4221},
 {'F': 1533, 'M': 3395},
 {'F': 1361, 'M': 3544},
 {'F': 1656, 'M': 4009},
 {'F': 1620, 'M': 4134},
 {'F': 1602, 'M': 4023},
 {'F': 1478, 'M': 3200},
 {'F': 1690, 'M': 4315},
 {'F': 1658, 'M': 4056},
 {'F': 1604, 'M': 3788},
 {'F': 1350, 'M': 3555},
 {'F': 1654, 'M': 4256},
 {'F': 1501, 'M': 3759},
 {'F': 1219, 'M': 3036},
 {'F': 1367, 'M': 3410},
 {'F': 1691, 'M': 4273},
 {'F': 1556, 'M': 3916},
 {'F': 1183, 'M': 3102},
 {'F': 1657, 'M': 4096},
 {'F': 1574, 'M': 4015},
 {'F': 1414, 'M': 3629},
 {'F': 1509, 'M': 3577},
 {'F': 1410, 'M': 3668},
 {'F': 1413, 'M': 3466},
 {'F': 1549, 'M': 4078},
 {'F': 1598, 'M': 3886},
 {'F': 1645, 'M': 4030},
 {'F': 1683, 'M': 4162},
 {'F': 1614, 'M': 3889},
 {'F': 1450, 'M': 3532},
 {'F': 1265, 'M': 2933},
 {'F': 1669, 'M': 4201},
 {'F': 1441, 'M': 3301},
 {'F': 1603, 'M': 3960},
 {'F': 1613, 'M': 3768},
 {'F': 1281, 'M': 2700},
 {'F': 1705, 'M': 4261},
 {'F': 1639, 'M': 4030},
 {'F': 1648, 'M': 3949},
 {'F': 1593, 'M': 4009},
 {'F': 1570, 'M': 3658},
 {'F': 1506, 'M': 3459},
 {'F': 1643, 'M': 3957},
 {'F': 1673, 'M': 4078},
 {'F': 1538, 'M': 3724},
 {'F': 1472, 'M': 3406},
 {'F': 1537, 'M': 3785},
 {'F': 1634, 'M': 4018},
 {'F': 1554, 'M': 3667},
 {'F': 1527, 'M': 3635},
 {'F': 1605, 'M': 3842},
 {'F': 1537, 'M': 3606},
 {'F': 1431, 'M': 3351},
 {'F': 1423, 'M': 3808},
 {'F': 1675, 'M': 3947},
 {'F': 1440, 'M': 2997},
 {'F': 1451, 'M': 3249},
 {'F': 1593, 'M': 3580},
 {'F': 1615, 'M': 3823},
 {'F': 1449, 'M': 3256},
 {'F': 1573, 'M': 3403},
 {'F': 1630, 'M': 3742},
 {'F': 1602, 'M': 3729},
 {'F': 1411, 'M': 2938},
 {'F': 1390, 'M': 3198},
 {'F': 1571, 'M': 4002},
 {'F': 1630, 'M': 4115},
 {'F': 1321, 'M': 3617},
 {'F': 1616, 'M': 3851},
 {'F': 1671, 'M': 4267},
 {'F': 1677, 'M': 4275},
 {'F': 1651, 'M': 4212},
 {'F': 1584, 'M': 3880},
 {'F': 1709, 'M': 4324},
 {'F': 1615, 'M': 4250},
 {'F': 1598, 'M': 3979},
 {'F': 1691, 'M': 4306},
 {'F': 1547, 'M': 3737},
 {'F': 1651, 'M': 4260},
 {'F': 1700, 'M': 4297},
 {'F': 1690, 'M': 4271},
 {'F': 1674, 'M': 4285},
 {'F': 1600, 'M': 3684},
 {'F': 1486, 'M': 3330},
 {'F': 1520, 'M': 4034},
 {'F': 1664, 'M': 4178},
 {'F': 1592, 'M': 3817},
 {'F': 1697, 'M': 4262},
 {'F': 1494, 'M': 3606},
 {'F': 1494, 'M': 3538},
 {'F': 1267, 'M': 3014},
 {'F': 1665, 'M': 4259},
 {'F': 1259, 'M': 2932},
 {'F': 1643, 'M': 4220},
 {'F': 1685, 'M': 4234},
 {'F': 1654, 'M': 4276},
 {'F': 1691, 'M': 4213},
 {'F': 1561, 'M': 3682},
 {'F': 1578, 'M': 4153},
 {'F': 1692, 'M': 4237},
 {'F': 1688, 'M': 4265},
 {'F': 1603, 'M': 3657},
 {'F': 1521, 'M': 3823},
 {'F': 1694, 'M': 4275},
 {'F': 1574, 'M': 3948},
 {'F': 1379, 'M': 3237},
 {'F': 1598, 'M': 4084},
 {'F': 1658, 'M': 4213},
 {'F': 1681, 'M': 4272},
 {'F': 1491, 'M': 3691},
 {'F': 1368, 'M': 3352},
 {'F': 1631, 'M': 4156},
 {'F': 1589, 'M': 4135},
 {'F': 1638, 'M': 4059},
 {'F': 1628, 'M': 3991},
 {'F': 1634, 'M': 4160},
 {'F': 1696, 'M': 4297},
 {'F': 1665, 'M': 4266},
 {'F': 1548, 'M': 3756},
 {'F': 1280, 'M': 3014},
 {'F': 1578, 'M': 3940},
 {'F': 1514, 'M': 3744},
 {'F': 1621, 'M': 4036},
 {'F': 1443, 'M': 3193},
 {'F': 1663, 'M': 4014},
 {'F': 1648, 'M': 4179},
 {'F': 1345, 'M': 3471},
 {'F': 1633, 'M': 4168},
 {'F': 1686, 'M': 4288},
 {'F': 1336, 'M': 3518},
 {'F': 1579, 'M': 4056},
 {'F': 1660, 'M': 4222},
 {'F': 1693, 'M': 4272},
 {'F': 1558, 'M': 3794},
 {'F': 1625, 'M': 3927},
 {'F': 1684, 'M': 4283},
 {'F': 1426, 'M': 3502},
 {'F': 1597, 'M': 3842},
 {'F': 1577, 'M': 3859},
 {'F': 1644, 'M': 4067},
 {'F': 1613, 'M': 3854},
 {'F': 1699, 'M': 4300},
 {'F': 1643, 'M': 3986},
 {'F': 1689, 'M': 4281},
 {'F': 1673, 'M': 4211},
 {'F': 1669, 'M': 4307},
 {'F': 1672, 'M': 4135},
 {'F': 1675, 'M': 4187},
 {'F': 1706, 'M': 4326},
 {'F': 1611, 'M': 4215},
 {'F': 1625, 'M': 4134},
 {'F': 1381, 'M': 3578},
 {'F': 1621, 'M': 4107},
 {'F': 1667, 'M': 4210},
 {'F': 1623, 'M': 4048},
 {'F': 1671, 'M': 4228},
 {'F': 1690, 'M': 4303},
 {'F': 1612, 'M': 3933},
 {'F': 1567, 'M': 3985},
 {'F': 1674, 'M': 4211},
 {'F': 1671, 'M': 4251},
 {'F': 1363, 'M': 3445},
 {'F': 1456, 'M': 3663},
 {'F': 1470, 'M': 3373},
 {'F': 1701, 'M': 4324},
 {'F': 1569, 'M': 3776},
 {'F': 1688, 'M': 4309},
 {'F': 1445, 'M': 3538},
 {'F': 1534, 'M': 3651},
 {'F': 1572, 'M': 4041},
 {'F': 1603, 'M': 3857},
 {'F': 1605, 'M': 3898},
 {'F': 1556, 'M': 3675},
 {'F': 1639, 'M': 3956},
 {'F': 1595, 'M': 3889},
 {'F': 1696, 'M': 4292},
 {'F': 1666, 'M': 4210},
 {'F': 1497, 'M': 3744},
 {'F': 1516, 'M': 3941},
 {'F': 1677, 'M': 4297},
 {'F': 1645, 'M': 4123},
 {'F': 1470, 'M': 3600},
 {'F': 1528, 'M': 3503},
 {'F': 1558, 'M': 4104},
 {'F': 1523, 'M': 3689},
 {'F': 1670, 'M': 4230},
 {'F': 1631, 'M': 4031},
 {'F': 1696, 'M': 4295},
 {'F': 1602, 'M': 4062},
 {'F': 1537, 'M': 3641},
 {'F': 1673, 'M': 4300},
 {'F': 1606, 'M': 4154},
 {'F': 1647, 'M': 4231},
 {'F': 1688, 'M': 4229},
 {'F': 1653, 'M': 4008},
 {'F': 1576, 'M': 3842},
 {'F': 1482, 'M': 3569},
 {'F': 1653, 'M': 4151},
 {'F': 1424, 'M': 3467},
 {'F': 1606, 'M': 4197},
 {'F': 1628, 'M': 4064},
 {'F': 1599, 'M': 4081},
 {'F': 1661, 'M': 4150},
 {'F': 1558, 'M': 4002},
 {'F': 1613, 'M': 4124},
 {'F': 1591, 'M': 3939},
 {'F': 1647, 'M': 4261},
 {'F': 1601, 'M': 4075},
 {'F': 1704, 'M': 4304},
 {'F': 1567, 'M': 3939},
 {'F': 1658, 'M': 4063},
 {'F': 1578, 'M': 4077},
 {'F': 1619, 'M': 3977},
 {'F': 1703, 'M': 4316},
 {'F': 1658, 'M': 4172},
 {'F': 1501, 'M': 4024},
 {'F': 1705, 'M': 4314},
 {'F': 1509, 'M': 3798},
 {'F': 1485, 'M': 3871},
 {'F': 1666, 'M': 4214},
 {'F': 1528, 'M': 3800},
 {'F': 1594, 'M': 3856},
 {'F': 1487, 'M': 3338},
 {'F': 1643, 'M': 4128},
 {'F': 1665, 'M': 4277},
 {'F': 1625, 'M': 4089},
 {'F': 1659, 'M': 4236},
 {'F': 1248, 'M': 3389},
 {'F': 1318, 'M': 3718},
 {'F': 1471, 'M': 3838},
 {'F': 1683, 'M': 4232},
 {'F': 1435, 'M': 3536},
 {'F': 1501, 'M': 3728},
 {'F': 1614, 'M': 3969},
 {'F': 1623, 'M': 4163},
 {'F': 1605, 'M': 4192},
 {'F': 1451, 'M': 3666},
 {'F': 1627, 'M': 4184},
 {'F': 1427, 'M': 3831},
 {'F': 1682, 'M': 4178},
 {'F': 1684, 'M': 4057},
 {'F': 1658, 'M': 4299},
 {'F': 1377, 'M': 3828},
 {'F': 1681, 'M': 4136},
 {'F': 1623, 'M': 4273},
 {'F': 1592, 'M': 4028},
 {'F': 1423, 'M': 3954},
 {'F': 1629, 'M': 4140},
 {'F': 1673, 'M': 4275},
 {'F': 1656, 'M': 4286},
 {'F': 1652, 'M': 4130},
 {'F': 1574, 'M': 4066},
 {'F': 1499, 'M': 3549},
 {'F': 1691, 'M': 4169},
 {'F': 1656, 'M': 4246},
 {'F': 1575, 'M': 4009},
 {'F': 1698, 'M': 4317},
 {'F': 1510, 'M': 4078},
 {'F': 1493, 'M': 4145},
 {'F': 1676, 'M': 4195},
 {'F': 1482, 'M': 3946},
 {'F': 1594, 'M': 4096},
 {'F': 1529, 'M': 3950},
 {'F': 1361, 'M': 4016},
 {'F': 1534, 'M': 4133},
 {'F': 1477, 'M': 4018},
 {'F': 1293, 'M': 3378},
 {'F': 1672, 'M': 4274},
 {'F': 1660, 'M': 4245},
 {'F': 1558, 'M': 4069},
 {'F': 1431, 'M': 3683},
 {'F': 1522, 'M': 4024},
 {'F': 1481, 'M': 3883},
 {'F': 1689, 'M': 4268},
 {'F': 1446, 'M': 3758},
 {'F': 1597, 'M': 4208},
 {'F': 1684, 'M': 4136},
 {'F': 1568, 'M': 3767},
 {'F': 1502, 'M': 3412},
 {'F': 1571, 'M': 3702},
 {'F': 1439, 'M': 3235},
 {'F': 1421, 'M': 3847},
 {'F': 1698, 'M': 4280},
 {'F': 1345, 'M': 3617},
 {'F': 1491, 'M': 3741},
 {'F': 1572, 'M': 3998},
 {'F': 1688, 'M': 4164},
 {'F': 1681, 'M': 4180},
 {'F': 1673, 'M': 4298},
 {'F': 1676, 'M': 4224},
 {'F': 1532, 'M': 3931},
 {'F': 1644, 'M': 4077},
 {'F': 1631, 'M': 4020},
 {'F': 1641, 'M': 4128},
 {'F': 1586, 'M': 4002},
 {'F': 1699, 'M': 4302},
 {'F': 1641, 'M': 4263},
 {'F': 1676, 'M': 4301},
 {'F': 1593, 'M': 4179},
 {'F': 1549, 'M': 4083},
 {'F': 1521, 'M': 3772},
 {'F': 1675, 'M': 4220},
 {'F': 1685, 'M': 4228},
 {'F': 1637, 'M': 4132},
 {'F': 1663, 'M': 4129},
 {'F': 1615, 'M': 4146},
 {'F': 1616, 'M': 4062},
 {'F': 1607, 'M': 3827},
 {'F': 1628, 'M': 4111},
 {'F': 1626, 'M': 4045},
 {'F': 1564, 'M': 4097},
 {'F': 1524, 'M': 3868},
 {'F': 1647, 'M': 4174},
 {'F': 1671, 'M': 4020},
 {'F': 1682, 'M': 4104},
 {'F': 1592, 'M': 4146},
 {'F': 1506, 'M': 3773},
 {'F': 1599, 'M': 4186},
 {'F': 1611, 'M': 4140},
 {'F': 1689, 'M': 4265},
 {'F': 1568, 'M': 3994},
 {'F': 1615, 'M': 4166},
 {'F': 1705, 'M': 4257},
 {'F': 1653, 'M': 4259},
 {'F': 1639, 'M': 4212},
 {'F': 1626, 'M': 4055},
 {'F': 1625, 'M': 4016},
 {'F': 1569, 'M': 4174},
 {'F': 1562, 'M': 3894},
 {'F': 1629, 'M': 4117},
 {'F': 1571, 'M': 4019},
 {'F': 1697, 'M': 4315},
 {'F': 1508, 'M': 3537},
 {'F': 1582, 'M': 4130},
 {'F': 1642, 'M': 4007},
 {'F': 1592, 'M': 3840},
 {'F': 1685, 'M': 4231},
 {'F': 1518, 'M': 3976},
 {'F': 1675, 'M': 4281},
 {'F': 1649, 'M': 4051},
 {'F': 1685, 'M': 4311},
 {'F': 1617, 'M': 3907},
 {'F': 1654, 'M': 4234},
 {'F': 1688, 'M': 4103},
 {'F': 1625, 'M': 4216},
 {'F': 1400, 'M': 3527},
 {'F': 1560, 'M': 4014},
 {'F': 1557, 'M': 3921},
 {'F': 1561, 'M': 4098},
 {'F': 1674, 'M': 4219},
 {'F': 1468, 'M': 3790},
 {'F': 1417, 'M': 3695},
 {'F': 1591, 'M': 3947},
 {'F': 1628, 'M': 4133},
 {'F': 1606, 'M': 3991},
 {'F': 1505, 'M': 3639},
 {'F': 1551, 'M': 4116},
 {'F': 1634, 'M': 4124},
 {'F': 1474, 'M': 3464},
 {'F': 1637, 'M': 4220},
 {'F': 1498, 'M': 3614},
 {'F': 1444, 'M': 3462},
 {'F': 1615, 'M': 3951},
 {'F': 1515, 'M': 3812},
 {'F': 1632, 'M': 4135},
 {'F': 1550, 'M': 3825},
 {'F': 1544, 'M': 3926},
 {'F': 1489, 'M': 3834},
 {'F': 1587, 'M': 3971},
 {'F': 1580, 'M': 3888},
 {'F': 1469, 'M': 3671},
 {'F': 1564, 'M': 3895},
 {'F': 1672, 'M': 4091},
 {'F': 1573, 'M': 3828},
 {'F': 1541, 'M': 3424},
 {'F': 1462, 'M': 3630},
 {'F': 1626, 'M': 4007},
 {'F': 1410, 'M': 3539},
 {'F': 1644, 'M': 4085},
 {'F': 1542, 'M': 3689},
 {'F': 1461, 'M': 3686},
 {'F': 1521, 'M': 3824},
 {'F': 1670, 'M': 4254},
 {'F': 1486, 'M': 3685},
 {'F': 1482, 'M': 3454},
 {'F': 1599, 'M': 4069},
 {'F': 1648, 'M': 4235},
 {'F': 1508, 'M': 3505},
 {'F': 1544, 'M': 3896},
 {'F': 1694, 'M': 4315},
 {'F': 1645, 'M': 4147},
 {'F': 1631, 'M': 4063},
 {'F': 1587, 'M': 3644},
 {'F': 1313, 'M': 3469},
 {'F': 1634, 'M': 4247},
 {'F': 1705, 'M': 4302},
 {'F': 1670, 'M': 4171},
 {'F': 1582, 'M': 4138},
 {'F': 1606, 'M': 4075},
 {'F': 1606, 'M': 4026},
 {'F': 1701, 'M': 4298},
 {'F': 1618, 'M': 3685},
 {'F': 1559, 'M': 3905},
 {'F': 1535, 'M': 4167},
 {'F': 1524, 'M': 3702},
 {'F': 1518, 'M': 3574},
 {'F': 1641, 'M': 4033},
 {'F': 1644, 'M': 4048},
 {'F': 1604, 'M': 3947},
 {'F': 1622, 'M': 4037},
 {'F': 1626, 'M': 3892},
 {'F': 1513, 'M': 3740},
 {'F': 1554, 'M': 3959},
 {'F': 1411, 'M': 3731},
 {'F': 1629, 'M': 3983},
 {'F': 1674, 'M': 4182},
 {'F': 1653, 'M': 4224},
 {'F': 1599, 'M': 4150},
 {'F': 1642, 'M': 4252},
 {'F': 1567, 'M': 3916},
 {'F': 1685, 'M': 4259},
 {'F': 1576, 'M': 3846},
 {'F': 1544, 'M': 4128},
 {'F': 1594, 'M': 4020},
 {'F': 1645, 'M': 4191},
 {'F': 1667, 'M': 4198},
 {'F': 1597, 'M': 4048},
 {'F': 1589, 'M': 4112},
 {'F': 1657, 'M': 4141},
 {'F': 1574, 'M': 4142},
 {'F': 1575, 'M': 3934},
 {'F': 1521, 'M': 3982},
 {'F': 1542, 'M': 3521},
 {'F': 1476, 'M': 3411},
 {'F': 1592, 'M': 4054},
 {'F': 1689, 'M': 4291},
 {'F': 1623, 'M': 3887},
 {'F': 1603, 'M': 3881},
 {'F': 1631, 'M': 4165},
 {'F': 1526, 'M': 4053},
 {'F': 1600, 'M': 3988},
 {'F': 1657, 'M': 4262},
 {'F': 1532, 'M': 3972},
 {'F': 1570, 'M': 3718},
 {'F': 1697, 'M': 4261},
 {'F': 1633, 'M': 4044},
 {'F': 1493, 'M': 3583},
 {'F': 1655, 'M': 4092},
 {'F': 1673, 'M': 4154},
 {'F': 1460, 'M': 3571},
 {'F': 1642, 'M': 4157},
 {'F': 1569, 'M': 3541},
 {'F': 1555, 'M': 3965},
 {'F': 1664, 'M': 4263},
 {'F': 1462, 'M': 3893},
 {'F': 1479, 'M': 3803},
 {'F': 1658, 'M': 4056},
 {'F': 1514, 'M': 3418},
 {'F': 1549, 'M': 4025},
 {'F': 1610, 'M': 4203},
 {'F': 1538, 'M': 3838},
 {'F': 1653, 'M': 3916},
 {'F': 1635, 'M': 4235},
 {'F': 1580, 'M': 3930},
 {'F': 1632, 'M': 4049},
 {'F': 1575, 'M': 3675},
 {'F': 1636, 'M': 4125},
 {'F': 1647, 'M': 4224},
 {'F': 1558, 'M': 3911},
 {'F': 1610, 'M': 3960},
 {'F': 1647, 'M': 4195},
 {'F': 1564, 'M': 3768},
 {'F': 1672, 'M': 4215},
 {'F': 1597, 'M': 4198},
 {'F': 1659, 'M': 4169},
 {'F': 1475, 'M': 3723},
 {'F': 1623, 'M': 3823},
 {'F': 1610, 'M': 3968},
 {'F': 1552, 'M': 4071},
 {'F': 1538, 'M': 3636},
 {'F': 1671, 'M': 4232},
 {'F': 1500, 'M': 3785},
 {'F': 1640, 'M': 4176},
 {'F': 1673, 'M': 4198},
 {'F': 1639, 'M': 4059},
 {'F': 1469, 'M': 4020},
 {'F': 1614, 'M': 4237},
 {'F': 1617, 'M': 3775},
 {'F': 1423, 'M': 3438},
 {'F': 1542, 'M': 3334},
 {'F': 1589, 'M': 3696},
 {'F': 1559, 'M': 4191},
 {'F': 1566, 'M': 3565},
 {'F': 1550, 'M': 3645},
 {'F': 1531, 'M': 4164},
 {'F': 1640, 'M': 4250},
 {'F': 1632, 'M': 4170},
 {'F': 1605, 'M': 3822},
 {'F': 1662, 'M': 4174},
 {'F': 1653, 'M': 4195},
 {'F': 1682, 'M': 4233},
 {'F': 1627, 'M': 3960},
 {'F': 1570, 'M': 3898},
 {'F': 1557, 'M': 3883},
 {'F': 1692, 'M': 4288},
 {'F': 1673, 'M': 4219},
 {'F': 1657, 'M': 4246},
 {'F': 1479, 'M': 3652},
 {'F': 1427, 'M': 3241},
 {'F': 1662, 'M': 3960},
 {'F': 1607, 'M': 3622},
 {'F': 1577, 'M': 4135},
 {'F': 1627, 'M': 3833},
 {'F': 1624, 'M': 4110},
 {'F': 1640, 'M': 4098},
 {'F': 1326, 'M': 2935},
 {'F': 1652, 'M': 4209},
 {'F': 1642, 'M': 4174},
 {'F': 1665, 'M': 4194},
 {'F': 1593, 'M': 4015},
 {'F': 1588, 'M': 4244},
 {'F': 1576, 'M': 3946},
 {'F': 1535, 'M': 3688},
 {'F': 1703, 'M': 4173},
 {'F': 1568, 'M': 3806},
 {'F': 1618, 'M': 4270},
 {'F': 1625, 'M': 4156},
 {'F': 1584, 'M': 4065},
 {'F': 1567, 'M': 4066},
 {'F': 1622, 'M': 3985},
 {'F': 1646, 'M': 4259},
 {'F': 1640, 'M': 4189},
 {'F': 1567, 'M': 4038},
 {'F': 1656, 'M': 4046},
 {'F': 1605, 'M': 4023},
 {'F': 1675, 'M': 4157},
 {'F': 1445, 'M': 3926},
 {'F': 1698, 'M': 4273},
 {'F': 1625, 'M': 4020},
 {'F': 1542, 'M': 3900},
 {'F': 1629, 'M': 4096},
 {'F': 1566, 'M': 3966},
 {'F': 1593, 'M': 4026},
 {'F': 1675, 'M': 4095},
 {'F': 1642, 'M': 4073},
 {'F': 1632, 'M': 4102},
 {'F': 1584, 'M': 4161},
 {'F': 1630, 'M': 3969},
 {'F': 1615, 'M': 3704},
 {'F': 1605, 'M': 4057},
 {'F': 1568, 'M': 4041},
 {'F': 1705, 'M': 4313},
 {'F': 1640, 'M': 4180},
 {'F': 1670, 'M': 4281},
 {'F': 1623, 'M': 4245},
 {'F': 1643, 'M': 4182},
 {'F': 1662, 'M': 4144},
 {'F': 1453, 'M': 3302},
 {'F': 1697, 'M': 4297},
 {'F': 1568, 'M': 3661},
 {'F': 1474, 'M': 3096},
 {'F': 1578, 'M': 3821},
 {'F': 1598, 'M': 3973},
 {'F': 1569, 'M': 3893},
 {'F': 1587, 'M': 3789},
 {'F': 1475, 'M': 3720},
 {'F': 1584, 'M': 3850},
 {'F': 1627, 'M': 4212},
 {'F': 1647, 'M': 4153},
 {'F': 1518, 'M': 4048},
 {'F': 1664, 'M': 4039},
 {'F': 1684, 'M': 4299},
 {'F': 1460, 'M': 3956},
 {'F': 1617, 'M': 4104},
 {'F': 1624, 'M': 3795},
 {'F': 1407, 'M': 3840},
 {'F': 1613, 'M': 3929},
 {'F': 1533, 'M': 4001},
 {'F': 1551, 'M': 3791},
 {'F': 1407, 'M': 3258},
 {'F': 1620, 'M': 4086},
 {'F': 1645, 'M': 4042},
 {'F': 1622, 'M': 4203},
 {'F': 1525, 'M': 3603},
 {'F': 1534, 'M': 3590},
 {'F': 1624, 'M': 4106},
 {'F': 1601, 'M': 3685},
 {'F': 1439, 'M': 3552},
 {'F': 1660, 'M': 4118},
 {'F': 1460, 'M': 3131},
 {'F': 1669, 'M': 4197},
 {'F': 1553, 'M': 3947},
 {'F': 1640, 'M': 4077},
 {'F': 1656, 'M': 4240},
 {'F': 1558, 'M': 3546},
 {'F': 1679, 'M': 4297},
 {'F': 1699, 'M': 4318},
 {'F': 1638, 'M': 4160},
 {'F': 1696, 'M': 4311},
 {'F': 1619, 'M': 3971},
 {'F': 1603, 'M': 3801},
 {'F': 1489, 'M': 3478},
 {'F': 1561, 'M': 3742},
 {'F': 1667, 'M': 4280},
 {'F': 1566, 'M': 3663},
 {'F': 1665, 'M': 4073},
 {'F': 1604, 'M': 4030},
 {'F': 1638, 'M': 4207},
 {'F': 1608, 'M': 3789},
 {'F': 1664, 'M': 4115},
 {'F': 1668, 'M': 4193},
 {'F': 1562, 'M': 3870},
 {'F': 1386, 'M': 3564},
 {'F': 1599, 'M': 3668},
 {'F': 1662, 'M': 4206},
 {'F': 1518, 'M': 3848},
 {'F': 1524, 'M': 3701},
 {'F': 1615, 'M': 3948},
 {'F': 1641, 'M': 4098},
 {'F': 1669, 'M': 4196},
 {'F': 1653, 'M': 4232},
 {'F': 1592, 'M': 3525},
 {'F': 1606, 'M': 3915},
 {'F': 1662, 'M': 4143},
 {'F': 1682, 'M': 4248},
 {'F': 1689, 'M': 4232},
 {'F': 1675, 'M': 4200},
 {'F': 1674, 'M': 4251},
 {'F': 1685, 'M': 4308},
 {'F': 1632, 'M': 3982},
 {'F': 1700, 'M': 4321},
 {'F': 1697, 'M': 4316},
 {'F': 1681, 'M': 4205},
 {'F': 1643, 'M': 4108},
 {'F': 1477, 'M': 3443},
 {'F': 1648, 'M': 4249},
 {'F': 1464, 'M': 3587},
 {'F': 1667, 'M': 4164},
 {'F': 1498, 'M': 3672},
 {'F': 1589, 'M': 3900},
 {'F': 1578, 'M': 3942},
 {'F': 1572, 'M': 3881},
 {'F': 1638, 'M': 4192},
 {'F': 1508, 'M': 3650},
 {'F': 1540, 'M': 3893},
 {'F': 1512, 'M': 3904},

In [16]:
print(type_count)

{'F': 1709, 'M': 4331}

In [17]:
num_item = len(train_df['item_id'].unique())
num_user = len(train_df['user_id'].unique())
num_type = len(key_type)
print('items number : ',num_item)
print('users number : ',num_user)
print('user types : ',key_type)

items number :  3503
users number :  6040
user types :  ['M', 'F']

In [18]:
dict_args["num_type"] = len(key_type)

In [19]:
user_type_list = [] #preprocessing to be sure that user types are really the right ones armielle 
for u in range(num_user):
    gl = user_idd_type_list[u]
    tmp = []
    for g in gl:
        if g in key_type:
            tmp.append(g)
    user_type_list.append(tmp)

print(len(user_type_list))

6040

In [20]:
# genreate user_type matrix
user_type = np.zeros((num_user, num_type))
for u in range(num_user):
    gl = user_type_list[u]
    for k in range(num_type):
        if key_type[k] in gl:
            user_type[u, k] = 1.0

In [21]:
len(user_type_list)

6040

In [22]:
print('*' * 50)
print('number of positive feedback: ' + str(len(train_df)))
print('estimated number of training samples: ' + str(neg * len(train_df)))
print('*' * 50)

**************************************************
number of positive feedback: 802322
estimated number of training samples: 4011610
**************************************************

In [23]:
type_count_mean_reciprocal = []
for k in key_type:
    type_count_mean_reciprocal.append(1.0 / type_count[k])
type_count_mean_reciprocal = (np.array(type_count_mean_reciprocal)).reshape((num_type, 1))
type_error_weight = np.dot(user_type, type_count_mean_reciprocal)

In [24]:
# generate user_type matrix
type_user_indicator = np.zeros((num_type, num_user))

for k in range(num_type):
    type_user_indicator[k,:] = type_user_vector[key_type[k]]

In [25]:
precision = np.zeros(4)
recall = np.zeros(4)
f1 = np.zeros(4)
ndcg = np.zeros(4)
RSP = np.zeros(4)
REO = np.zeros(4)

precision

array([0., 0., 0., 0.])

In [26]:
len(user_type_list)

6040

In [27]:
tf.compat.v1.disable_eager_execution()

for i in range(n):
    with tf.compat.v1.Session() as sess:
        fairadvbpr = FairAdvBPR(sess, dict_args, train_df, test_df, user_type, type_error_weight, key_type, user_type_list, item_type_count)
        [prec_one, rec_one, f_one, ndcg_one, Rec] = fairadvbpr.run()
        #[RSP_one, REO_one] = utility.ranking_analysis(Rec, vali_df, train_df, key_genre, item_genre_list, user_genre_count)
#         precision += prec_one
#         recall += rec_one
#         f1 += f_one
#         ndcg += ndcg_one
#         RSP += RSP_one
#         REO += REO_one

**********fairAdvBPR**********
shape q pos (?, 20)
shape p (?, 20)
shape predict pos  (?,)
shape adv_last  (?, 1)
INFO:tensorflow:Restoring parameters from ./ml1m-6/BPR_check_points\check_point.ckpt-1
Training // Epoch 1 //  Total r_cost = 5383379.62384  Total s_cost = 127782.06882  Total s_mean = -1.75820  Total s_std = 3906.86892  Total a_cost = 0.00000 Training time : 751472 ms negative Sampling time : 174120 ms negative samples : 4011610
precision_1	[0.2561258],	||	 precision_5	[0.2046689],	||	 precision_10	[0.1792550],	||	 precision_15	[0.1634768]
recall_1   	[0.0098782],	||	 recall_5   	[0.0370207],	||	 recall_10   	[0.0640690],	||	 recall_15   	[0.0860630]
f_measure_1	[0.0190227],	||	 f_measure_5	[0.0627002],	||	 f_measure_10	[0.0943983],	||	 f_measure_15	[0.1127620]
ndcg_1     	[0.2561258],	||	 ndcg_5     	[0.2146712],	||	 ndcg_10     	[0.1981298],	||	 ndcg_15     	[0.1902918]
Metrics for user type	 M
precision_1	[0.2897714],	||	 precision_5	[0.2295082],	||	 precision_10	[0.1990995],	||	 precision_15	[0.1806203]
recall_1	[0.0110282],	||	 recall_5	[0.0408246],	||	 recall_10	[0.0697984],	||	 recall_15	[0.0929004]
ndcg_1	[0.2897714],	||	 ndcg_5	[0.2412574],	||	 ndcg_10	[0.2209589],	||	 ndcg_15	[0.2110702]
AUC per user type	[0.8352815]
Metrics for user type	 F
precision_1	[0.1708602],	||	 precision_5	[0.1417203],	||	 precision_10	[0.1289643],	||	 precision_15	[0.1200312]
recall_1	[0.0069637],	||	 recall_5	[0.0273807],	||	 recall_10	[0.0495495],	||	 recall_15	[0.0687354]
ndcg_1	[0.1708602],	||	 ndcg_5	[0.1472958],	||	 ndcg_10	[0.1402754],	||	 ndcg_15	[0.1376345]
AUC per user type	[0.8025257]
AUC global is:  0.8260133306321384
boucle adversarial debut-- num batch  0
boucle adversarial fin
boucle adversarial debut-- num batch  1
boucle adversarial fin
boucle adversarial debut-- num batch  2
boucle adversarial fin
boucle adversarial debut-- num batch  3
boucle adversarial fin
boucle adversarial debut-- num batch  4
boucle adversarial fin
boucle adversarial debut-- num batch  5
boucle adversarial fin
boucle adversarial debut-- num batch  6
boucle adversarial fin
boucle adversarial debut-- num batch  7
boucle adversarial fin
boucle adversarial debut-- num batch  8
boucle adversarial fin
boucle adversarial debut-- num batch  9
boucle adversarial fin
boucle adversarial debut-- num batch  10
boucle adversarial fin
boucle adversarial debut-- num batch  11
boucle adversarial fin
boucle adversarial debut-- num batch  12
boucle adversarial fin
boucle adversarial debut-- num batch  13
boucle adversarial fin
boucle adversarial debut-- num batch  14
boucle adversarial fin
boucle adversarial debut-- num batch  15
boucle adversarial fin
boucle adversarial debut-- num batch  16
boucle adversarial fin
boucle adversarial debut-- num batch  17
boucle adversarial fin
boucle adversarial debut-- num batch  18
boucle adversarial fin
boucle adversarial debut-- num batch  19
boucle adversarial fin
boucle adversarial debut-- num batch  20
boucle adversarial fin
boucle adversarial debut-- num batch  21
boucle adversarial fin
boucle adversarial debut-- num batch  22
boucle adversarial fin
boucle adversarial debut-- num batch  23
boucle adversarial fin
boucle adversarial debut-- num batch  24
boucle adversarial fin
boucle adversarial debut-- num batch  25
boucle adversarial fin
boucle adversarial debut-- num batch  26
boucle adversarial fin
boucle adversarial debut-- num batch  27
boucle adversarial fin
boucle adversarial debut-- num batch  28
boucle adversarial fin
boucle adversarial debut-- num batch  29
boucle adversarial fin
boucle adversarial debut-- num batch  30
boucle adversarial fin
boucle adversarial debut-- num batch  31
boucle adversarial fin
boucle adversarial debut-- num batch  32
boucle adversarial fin
boucle adversarial debut-- num batch  33
boucle adversarial fin
boucle adversarial debut-- num batch  34
boucle adversarial fin
boucle adversarial debut-- num batch  35
boucle adversarial fin
boucle adversarial debut-- num batch  36
boucle adversarial fin
boucle adversarial debut-- num batch  37
boucle adversarial fin
boucle adversarial debut-- num batch  38
boucle adversarial fin
boucle adversarial debut-- num batch  39
boucle adversarial fin
boucle adversarial debut-- num batch  40
boucle adversarial fin
boucle adversarial debut-- num batch  41
boucle adversarial fin
boucle adversarial debut-- num batch  42
boucle adversarial fin
boucle adversarial debut-- num batch  43
boucle adversarial fin
boucle adversarial debut-- num batch  44
boucle adversarial fin
boucle adversarial debut-- num batch  45
boucle adversarial fin
boucle adversarial debut-- num batch  46
boucle adversarial fin
boucle adversarial debut-- num batch  47
boucle adversarial fin
boucle adversarial debut-- num batch  48
boucle adversarial fin
boucle adversarial debut-- num batch  49
boucle adversarial fin
boucle adversarial debut-- num batch  50
boucle adversarial fin
boucle adversarial debut-- num batch  51
boucle adversarial fin
boucle adversarial debut-- num batch  52
boucle adversarial fin
boucle adversarial debut-- num batch  53
boucle adversarial fin
boucle adversarial debut-- num batch  54
boucle adversarial fin
boucle adversarial debut-- num batch  55
boucle adversarial fin
boucle adversarial debut-- num batch  56
boucle adversarial fin
boucle adversarial debut-- num batch  57
boucle adversarial fin
boucle adversarial debut-- num batch  58
boucle adversarial fin
boucle adversarial debut-- num batch  59
boucle adversarial fin
boucle adversarial debut-- num batch  60
boucle adversarial fin
boucle adversarial debut-- num batch  61
boucle adversarial fin
boucle adversarial debut-- num batch  62
boucle adversarial fin
boucle adversarial debut-- num batch  63
boucle adversarial fin
boucle adversarial debut-- num batch  64
boucle adversarial fin
boucle adversarial debut-- num batch  65
boucle adversarial fin
boucle adversarial debut-- num batch  66
boucle adversarial fin
boucle adversarial debut-- num batch  67
boucle adversarial fin
boucle adversarial debut-- num batch  68
boucle adversarial fin
boucle adversarial debut-- num batch  69
boucle adversarial fin
boucle adversarial debut-- num batch  70
boucle adversarial fin
boucle adversarial debut-- num batch  71
boucle adversarial fin
boucle adversarial debut-- num batch  72
boucle adversarial fin
boucle adversarial debut-- num batch  73
boucle adversarial fin
boucle adversarial debut-- num batch  74
boucle adversarial fin
boucle adversarial debut-- num batch  75
boucle adversarial fin
boucle adversarial debut-- num batch  76
boucle adversarial fin
boucle adversarial debut-- num batch  77
boucle adversarial fin
boucle adversarial debut-- num batch  78
boucle adversarial fin
boucle adversarial debut-- num batch  79
boucle adversarial fin
boucle adversarial debut-- num batch  80
boucle adversarial fin
boucle adversarial debut-- num batch  81
boucle adversarial fin
boucle adversarial debut-- num batch  82
boucle adversarial fin
boucle adversarial debut-- num batch  83
boucle adversarial fin
boucle adversarial debut-- num batch  84
boucle adversarial fin
boucle adversarial debut-- num batch  85
boucle adversarial fin
boucle adversarial debut-- num batch  86
boucle adversarial fin
boucle adversarial debut-- num batch  87
boucle adversarial fin
boucle adversarial debut-- num batch  88
boucle adversarial fin
boucle adversarial debut-- num batch  89
boucle adversarial fin
boucle adversarial debut-- num batch  90
boucle adversarial fin
boucle adversarial debut-- num batch  91
boucle adversarial fin
boucle adversarial debut-- num batch  92
boucle adversarial fin
boucle adversarial debut-- num batch  93
boucle adversarial fin
boucle adversarial debut-- num batch  94
boucle adversarial fin
boucle adversarial debut-- num batch  95
boucle adversarial fin
boucle adversarial debut-- num batch  96
boucle adversarial fin
boucle adversarial debut-- num batch  97
boucle adversarial fin
boucle adversarial debut-- num batch  98
boucle adversarial fin
boucle adversarial debut-- num batch  99
boucle adversarial fin
boucle adversarial debut-- num batch  100
boucle adversarial fin
boucle adversarial debut-- num batch  101
boucle adversarial fin
boucle adversarial debut-- num batch  102

boucle adversarial fin
boucle adversarial debut-- num batch  103
boucle adversarial fin
boucle adversarial debut-- num batch  104
boucle adversarial fin
boucle adversarial debut-- num batch  105
boucle adversarial fin
boucle adversarial debut-- num batch  106
boucle adversarial fin
boucle adversarial debut-- num batch  107
boucle adversarial fin
boucle adversarial debut-- num batch  108
boucle adversarial fin
boucle adversarial debut-- num batch  109
boucle adversarial fin
boucle adversarial debut-- num batch  110
boucle adversarial fin
boucle adversarial debut-- num batch  111
boucle adversarial fin
boucle adversarial debut-- num batch  112
boucle adversarial fin
boucle adversarial debut-- num batch  113
boucle adversarial fin
boucle adversarial debut-- num batch  114
boucle adversarial fin
boucle adversarial debut-- num batch  115
boucle adversarial fin
boucle adversarial debut-- num batch  116
boucle adversarial fin
boucle adversarial debut-- num batch  117
boucle adversarial fin
boucle adversarial debut-- num batch  118
boucle adversarial fin
boucle adversarial debut-- num batch  119
boucle adversarial fin
boucle adversarial debut-- num batch  120
boucle adversarial fin
boucle adversarial debut-- num batch  121
boucle adversarial fin
boucle adversarial debut-- num batch  122
boucle adversarial fin
boucle adversarial debut-- num batch  123
boucle adversarial fin
boucle adversarial debut-- num batch  124
boucle adversarial fin
boucle adversarial debut-- num batch  125
boucle adversarial fin
boucle adversarial debut-- num batch  126
boucle adversarial fin
boucle adversarial debut-- num batch  127
boucle adversarial fin
boucle adversarial debut-- num batch  128
boucle adversarial fin
boucle adversarial debut-- num batch  129
boucle adversarial fin
boucle adversarial debut-- num batch  130
boucle adversarial fin
boucle adversarial debut-- num batch  131
boucle adversarial fin
boucle adversarial debut-- num batch  132
boucle adversarial fin
boucle adversarial debut-- num batch  133
boucle adversarial fin
boucle adversarial debut-- num batch  134
boucle adversarial fin
boucle adversarial debut-- num batch  135
boucle adversarial fin
boucle adversarial debut-- num batch  136
boucle adversarial fin
boucle adversarial debut-- num batch  137
boucle adversarial fin
boucle adversarial debut-- num batch  138
boucle adversarial fin
boucle adversarial debut-- num batch  139
boucle adversarial fin
boucle adversarial debut-- num batch  140
boucle adversarial fin
boucle adversarial debut-- num batch  141
boucle adversarial fin
boucle adversarial debut-- num batch  142
boucle adversarial fin
boucle adversarial debut-- num batch  143
boucle adversarial fin
boucle adversarial debut-- num batch  144
boucle adversarial fin
boucle adversarial debut-- num batch  145
boucle adversarial fin
boucle adversarial debut-- num batch  146
boucle adversarial fin
boucle adversarial debut-- num batch  147
boucle adversarial fin
boucle adversarial debut-- num batch  148
boucle adversarial fin
boucle adversarial debut-- num batch  149
boucle adversarial fin
boucle adversarial debut-- num batch  150
boucle adversarial fin
boucle adversarial debut-- num batch  151
boucle adversarial fin
boucle adversarial debut-- num batch  152
boucle adversarial fin
boucle adversarial debut-- num batch  153
boucle adversarial fin
boucle adversarial debut-- num batch  154
boucle adversarial fin
boucle adversarial debut-- num batch  155
boucle adversarial fin
boucle adversarial debut-- num batch  156
boucle adversarial fin
boucle adversarial debut-- num batch  157
boucle adversarial fin
boucle adversarial debut-- num batch  158
boucle adversarial fin
boucle adversarial debut-- num batch  159
boucle adversarial fin
boucle adversarial debut-- num batch  160
boucle adversarial fin
boucle adversarial debut-- num batch  161
boucle adversarial fin
boucle adversarial debut-- num batch  162
boucle adversarial fin
boucle adversarial debut-- num batch  163
boucle adversarial fin
boucle adversarial debut-- num batch  164
boucle adversarial fin
boucle adversarial debut-- num batch  165
boucle adversarial fin
boucle adversarial debut-- num batch  166
boucle adversarial fin
boucle adversarial debut-- num batch  167
boucle adversarial fin
boucle adversarial debut-- num batch  168
boucle adversarial fin
boucle adversarial debut-- num batch  169
boucle adversarial fin
boucle adversarial debut-- num batch  170
boucle adversarial fin
boucle adversarial debut-- num batch  171
boucle adversarial fin
boucle adversarial debut-- num batch  172
boucle adversarial fin
boucle adversarial debut-- num batch  173
boucle adversarial fin
boucle adversarial debut-- num batch  174
boucle adversarial fin
boucle adversarial debut-- num batch  175
boucle adversarial fin
boucle adversarial debut-- num batch  176
boucle adversarial fin
boucle adversarial debut-- num batch  177
boucle adversarial fin
boucle adversarial debut-- num batch  178
boucle adversarial fin
boucle adversarial debut-- num batch  179
boucle adversarial fin
boucle adversarial debut-- num batch  180
boucle adversarial fin
boucle adversarial debut-- num batch  181
boucle adversarial fin
boucle adversarial debut-- num batch  182
boucle adversarial fin
boucle adversarial debut-- num batch  183
boucle adversarial fin
boucle adversarial debut-- num batch  184
boucle adversarial fin
boucle adversarial debut-- num batch  185
boucle adversarial fin
boucle adversarial debut-- num batch  186
boucle adversarial fin
boucle adversarial debut-- num batch  187
boucle adversarial fin
boucle adversarial debut-- num batch  188
boucle adversarial fin
boucle adversarial debut-- num batch  189
boucle adversarial fin
boucle adversarial debut-- num batch  190
boucle adversarial fin
boucle adversarial debut-- num batch  191
boucle adversarial fin
boucle adversarial debut-- num batch  192
boucle adversarial fin
boucle adversarial debut-- num batch  193
boucle adversarial fin
boucle adversarial debut-- num batch  194
boucle adversarial fin
boucle adversarial debut-- num batch  195
boucle adversarial fin
boucle adversarial debut-- num batch  196
boucle adversarial fin
boucle adversarial debut-- num batch  197
boucle adversarial fin
boucle adversarial debut-- num batch  198
boucle adversarial fin
boucle adversarial debut-- num batch  199
boucle adversarial fin
boucle adversarial debut-- num batch  200
boucle adversarial fin
boucle adversarial debut-- num batch  201
boucle adversarial fin
boucle adversarial debut-- num batch  202
boucle adversarial fin
boucle adversarial debut-- num batch  203
boucle adversarial fin
boucle adversarial debut-- num batch  204
boucle adversarial fin
boucle adversarial debut-- num batch  205
boucle adversarial fin
boucle adversarial debut-- num batch  206
boucle adversarial fin
boucle adversarial debut-- num batch  207
boucle adversarial fin
boucle adversarial debut-- num batch  208
boucle adversarial fin
boucle adversarial debut-- num batch  209
boucle adversarial fin
boucle adversarial debut-- num batch  210
boucle adversarial fin
boucle adversarial debut-- num batch  211
boucle adversarial fin
boucle adversarial debut-- num batch  212
boucle adversarial fin
boucle adversarial debut-- num batch  213
boucle adversarial fin
boucle adversarial debut-- num batch  214
boucle adversarial fin
boucle adversarial debut-- num batch  215
boucle adversarial fin
boucle adversarial debut-- num batch  216
boucle adversarial fin
boucle adversarial debut-- num batch  217
boucle adversarial fin
boucle adversarial debut-- num batch  218
boucle adversarial fin
boucle adversarial debut-- num batch  219
boucle adversarial fin
boucle adversarial debut-- num batch  220
boucle adversarial fin
boucle adversarial debut-- num batch  221
boucle adversarial fin
boucle adversarial debut-- num batch  222
boucle adversarial fin
boucle adversarial debut-- num batch  223
boucle adversarial fin
boucle adversarial debut-- num batch  224
boucle adversarial fin
boucle adversarial debut-- num batch  225
boucle adversarial fin
boucle adversarial debut-- num batch  226
boucle adversarial fin
boucle adversarial debut-- num batch  227
boucle adversarial fin
boucle adversarial debut-- num batch  228
boucle adversarial fin

boucle adversarial debut-- num batch  229
boucle adversarial fin
boucle adversarial debut-- num batch  230
boucle adversarial fin
boucle adversarial debut-- num batch  231
boucle adversarial fin
boucle adversarial debut-- num batch  232
boucle adversarial fin
boucle adversarial debut-- num batch  233
boucle adversarial fin
boucle adversarial debut-- num batch  234
boucle adversarial fin
boucle adversarial debut-- num batch  235
boucle adversarial fin
boucle adversarial debut-- num batch  236
boucle adversarial fin
boucle adversarial debut-- num batch  237
boucle adversarial fin
boucle adversarial debut-- num batch  238
boucle adversarial fin
boucle adversarial debut-- num batch  239
boucle adversarial fin
boucle adversarial debut-- num batch  240
boucle adversarial fin
boucle adversarial debut-- num batch  241
boucle adversarial fin
boucle adversarial debut-- num batch  242
boucle adversarial fin
boucle adversarial debut-- num batch  243
boucle adversarial fin
boucle adversarial debut-- num batch  244
boucle adversarial fin
boucle adversarial debut-- num batch  245
boucle adversarial fin
boucle adversarial debut-- num batch  246
boucle adversarial fin
boucle adversarial debut-- num batch  247
boucle adversarial fin
boucle adversarial debut-- num batch  248
boucle adversarial fin
boucle adversarial debut-- num batch  249
boucle adversarial fin
boucle adversarial debut-- num batch  250
boucle adversarial fin
boucle adversarial debut-- num batch  251
boucle adversarial fin
boucle adversarial debut-- num batch  252
boucle adversarial fin
boucle adversarial debut-- num batch  253
boucle adversarial fin
boucle adversarial debut-- num batch  254
boucle adversarial fin
boucle adversarial debut-- num batch  255
boucle adversarial fin
boucle adversarial debut-- num batch  256
boucle adversarial fin
boucle adversarial debut-- num batch  257
boucle adversarial fin
boucle adversarial debut-- num batch  258
boucle adversarial fin
boucle adversarial debut-- num batch  259
boucle adversarial fin
boucle adversarial debut-- num batch  260
boucle adversarial fin
boucle adversarial debut-- num batch  261
boucle adversarial fin
boucle adversarial debut-- num batch  262
boucle adversarial fin
boucle adversarial debut-- num batch  263
boucle adversarial fin
boucle adversarial debut-- num batch  264
boucle adversarial fin
boucle adversarial debut-- num batch  265
boucle adversarial fin
boucle adversarial debut-- num batch  266
boucle adversarial fin
boucle adversarial debut-- num batch  267
boucle adversarial fin
boucle adversarial debut-- num batch  268
boucle adversarial fin
boucle adversarial debut-- num batch  269
boucle adversarial fin
boucle adversarial debut-- num batch  270
boucle adversarial fin
boucle adversarial debut-- num batch  271
boucle adversarial fin
boucle adversarial debut-- num batch  272
boucle adversarial fin
boucle adversarial debut-- num batch  273
boucle adversarial fin
boucle adversarial debut-- num batch  274
boucle adversarial fin
boucle adversarial debut-- num batch  275
boucle adversarial fin
boucle adversarial debut-- num batch  276
boucle adversarial fin
boucle adversarial debut-- num batch  277
boucle adversarial fin
boucle adversarial debut-- num batch  278
boucle adversarial fin
boucle adversarial debut-- num batch  279
boucle adversarial fin
boucle adversarial debut-- num batch  280
boucle adversarial fin
boucle adversarial debut-- num batch  281
boucle adversarial fin
boucle adversarial debut-- num batch  282
boucle adversarial fin
boucle adversarial debut-- num batch  283
boucle adversarial fin
boucle adversarial debut-- num batch  284
boucle adversarial fin
boucle adversarial debut-- num batch  285
boucle adversarial fin
boucle adversarial debut-- num batch  286
boucle adversarial fin
boucle adversarial debut-- num batch  287
boucle adversarial fin
boucle adversarial debut-- num batch  288
boucle adversarial fin
boucle adversarial debut-- num batch  289
boucle adversarial fin
boucle adversarial debut-- num batch  290
boucle adversarial fin
boucle adversarial debut-- num batch  291
boucle adversarial fin
boucle adversarial debut-- num batch  292
boucle adversarial fin
boucle adversarial debut-- num batch  293
boucle adversarial fin
boucle adversarial debut-- num batch  294
boucle adversarial fin
boucle adversarial debut-- num batch  295
boucle adversarial fin
boucle adversarial debut-- num batch  296
boucle adversarial fin
boucle adversarial debut-- num batch  297
boucle adversarial fin
boucle adversarial debut-- num batch  298
boucle adversarial fin
boucle adversarial debut-- num batch  299
boucle adversarial fin
boucle adversarial debut-- num batch  300
boucle adversarial fin
boucle adversarial debut-- num batch  301
boucle adversarial fin
boucle adversarial debut-- num batch  302
boucle adversarial fin
boucle adversarial debut-- num batch  303
boucle adversarial fin
boucle adversarial debut-- num batch  304
boucle adversarial fin
boucle adversarial debut-- num batch  305
boucle adversarial fin
boucle adversarial debut-- num batch  306
boucle adversarial fin
boucle adversarial debut-- num batch  307
boucle adversarial fin
boucle adversarial debut-- num batch  308
boucle adversarial fin
boucle adversarial debut-- num batch  309
boucle adversarial fin
boucle adversarial debut-- num batch  310
boucle adversarial fin
boucle adversarial debut-- num batch  311
boucle adversarial fin
boucle adversarial debut-- num batch  312
boucle adversarial fin
boucle adversarial debut-- num batch  313
boucle adversarial fin
boucle adversarial debut-- num batch  314
boucle adversarial fin
boucle adversarial debut-- num batch  315
boucle adversarial fin
boucle adversarial debut-- num batch  316
boucle adversarial fin
boucle adversarial debut-- num batch  317
boucle adversarial fin
boucle adversarial debut-- num batch  318
boucle adversarial fin
boucle adversarial debut-- num batch  319
boucle adversarial fin
boucle adversarial debut-- num batch  320
boucle adversarial fin
boucle adversarial debut-- num batch  321
boucle adversarial fin
boucle adversarial debut-- num batch  322
boucle adversarial fin
boucle adversarial debut-- num batch  323
boucle adversarial fin
boucle adversarial debut-- num batch  324
boucle adversarial fin
boucle adversarial debut-- num batch  325
boucle adversarial fin
boucle adversarial debut-- num batch  326
boucle adversarial fin
boucle adversarial debut-- num batch  327
boucle adversarial fin
boucle adversarial debut-- num batch  328
boucle adversarial fin
boucle adversarial debut-- num batch  329
boucle adversarial fin
boucle adversarial debut-- num batch  330
boucle adversarial fin
boucle adversarial debut-- num batch  331
boucle adversarial fin
boucle adversarial debut-- num batch  332
boucle adversarial fin
boucle adversarial debut-- num batch  333
boucle adversarial fin
boucle adversarial debut-- num batch  334
boucle adversarial fin
boucle adversarial debut-- num batch  335
boucle adversarial fin
boucle adversarial debut-- num batch  336
boucle adversarial fin
boucle adversarial debut-- num batch  337
boucle adversarial fin
boucle adversarial debut-- num batch  338
boucle adversarial fin
boucle adversarial debut-- num batch  339
boucle adversarial fin
boucle adversarial debut-- num batch  340
boucle adversarial fin
boucle adversarial debut-- num batch  341
boucle adversarial fin
boucle adversarial debut-- num batch  342
boucle adversarial fin
boucle adversarial debut-- num batch  343
boucle adversarial fin
boucle adversarial debut-- num batch  344
boucle adversarial fin
boucle adversarial debut-- num batch  345
boucle adversarial fin
boucle adversarial debut-- num batch  346
boucle adversarial fin
boucle adversarial debut-- num batch  347
boucle adversarial fin
boucle adversarial debut-- num batch  348
boucle adversarial fin
boucle adversarial debut-- num batch  349
boucle adversarial fin
boucle adversarial debut-- num batch  350
boucle adversarial fin
boucle adversarial debut-- num batch  351
boucle adversarial fin
boucle adversarial debut-- num batch  352
boucle adversarial fin
boucle adversarial debut-- num batch  353
boucle adversarial fin
boucle adversarial debut-- num batch  354
boucle adversarial fin
boucle adversarial debut-- num batch  355

boucle adversarial fin
boucle adversarial debut-- num batch  356
boucle adversarial fin
boucle adversarial debut-- num batch  357
boucle adversarial fin
boucle adversarial debut-- num batch  358
boucle adversarial fin
boucle adversarial debut-- num batch  359
boucle adversarial fin
boucle adversarial debut-- num batch  360
boucle adversarial fin
boucle adversarial debut-- num batch  361
boucle adversarial fin
boucle adversarial debut-- num batch  362
boucle adversarial fin
boucle adversarial debut-- num batch  363
boucle adversarial fin
boucle adversarial debut-- num batch  364
boucle adversarial fin
boucle adversarial debut-- num batch  365
boucle adversarial fin
boucle adversarial debut-- num batch  366
boucle adversarial fin
boucle adversarial debut-- num batch  367
boucle adversarial fin
boucle adversarial debut-- num batch  368
boucle adversarial fin
boucle adversarial debut-- num batch  369
boucle adversarial fin
boucle adversarial debut-- num batch  370
boucle adversarial fin
boucle adversarial debut-- num batch  371
boucle adversarial fin
boucle adversarial debut-- num batch  372
boucle adversarial fin
boucle adversarial debut-- num batch  373
boucle adversarial fin
boucle adversarial debut-- num batch  374
boucle adversarial fin
boucle adversarial debut-- num batch  375
boucle adversarial fin
boucle adversarial debut-- num batch  376
boucle adversarial fin
boucle adversarial debut-- num batch  377
boucle adversarial fin
boucle adversarial debut-- num batch  378
boucle adversarial fin
boucle adversarial debut-- num batch  379
boucle adversarial fin
boucle adversarial debut-- num batch  380
boucle adversarial fin
boucle adversarial debut-- num batch  381
boucle adversarial fin
boucle adversarial debut-- num batch  382
boucle adversarial fin
boucle adversarial debut-- num batch  383
boucle adversarial fin
boucle adversarial debut-- num batch  384
boucle adversarial fin
boucle adversarial debut-- num batch  385
boucle adversarial fin
boucle adversarial debut-- num batch  386
boucle adversarial fin
boucle adversarial debut-- num batch  387
boucle adversarial fin
boucle adversarial debut-- num batch  388
boucle adversarial fin
boucle adversarial debut-- num batch  389
boucle adversarial fin
boucle adversarial debut-- num batch  390
boucle adversarial fin
boucle adversarial debut-- num batch  391
boucle adversarial fin
boucle adversarial debut-- num batch  392
boucle adversarial fin
boucle adversarial debut-- num batch  393
boucle adversarial fin
boucle adversarial debut-- num batch  394
boucle adversarial fin
boucle adversarial debut-- num batch  395
boucle adversarial fin
boucle adversarial debut-- num batch  396
boucle adversarial fin
boucle adversarial debut-- num batch  397
boucle adversarial fin
boucle adversarial debut-- num batch  398
boucle adversarial fin
boucle adversarial debut-- num batch  399
boucle adversarial fin
boucle adversarial debut-- num batch  400
boucle adversarial fin
boucle adversarial debut-- num batch  401
boucle adversarial fin
boucle adversarial debut-- num batch  402
boucle adversarial fin
boucle adversarial debut-- num batch  403
boucle adversarial fin
boucle adversarial debut-- num batch  404
boucle adversarial fin
boucle adversarial debut-- num batch  405
boucle adversarial fin
boucle adversarial debut-- num batch  406
boucle adversarial fin
boucle adversarial debut-- num batch  407
boucle adversarial fin
boucle adversarial debut-- num batch  408
boucle adversarial fin
boucle adversarial debut-- num batch  409
boucle adversarial fin
boucle adversarial debut-- num batch  410
boucle adversarial fin
boucle adversarial debut-- num batch  411
boucle adversarial fin
boucle adversarial debut-- num batch  412
boucle adversarial fin
boucle adversarial debut-- num batch  413
boucle adversarial fin
boucle adversarial debut-- num batch  414
boucle adversarial fin
boucle adversarial debut-- num batch  415
boucle adversarial fin
boucle adversarial debut-- num batch  416
boucle adversarial fin
boucle adversarial debut-- num batch  417
boucle adversarial fin
boucle adversarial debut-- num batch  418
boucle adversarial fin
boucle adversarial debut-- num batch  419
boucle adversarial fin
boucle adversarial debut-- num batch  420
boucle adversarial fin
boucle adversarial debut-- num batch  421
boucle adversarial fin
boucle adversarial debut-- num batch  422
boucle adversarial fin
boucle adversarial debut-- num batch  423
boucle adversarial fin
boucle adversarial debut-- num batch  424
boucle adversarial fin
boucle adversarial debut-- num batch  425
boucle adversarial fin
boucle adversarial debut-- num batch  426
boucle adversarial fin
boucle adversarial debut-- num batch  427
boucle adversarial fin
boucle adversarial debut-- num batch  428
boucle adversarial fin
boucle adversarial debut-- num batch  429
boucle adversarial fin
boucle adversarial debut-- num batch  430
boucle adversarial fin
boucle adversarial debut-- num batch  431
boucle adversarial fin
boucle adversarial debut-- num batch  432
boucle adversarial fin
boucle adversarial debut-- num batch  433
boucle adversarial fin
boucle adversarial debut-- num batch  434
boucle adversarial fin
boucle adversarial debut-- num batch  435
boucle adversarial fin
boucle adversarial debut-- num batch  436
boucle adversarial fin
boucle adversarial debut-- num batch  437
boucle adversarial fin
boucle adversarial debut-- num batch  438
boucle adversarial fin
boucle adversarial debut-- num batch  439
boucle adversarial fin
boucle adversarial debut-- num batch  440
boucle adversarial fin
boucle adversarial debut-- num batch  441
boucle adversarial fin
boucle adversarial debut-- num batch  442
boucle adversarial fin
boucle adversarial debut-- num batch  443
boucle adversarial fin
boucle adversarial debut-- num batch  444
boucle adversarial fin
boucle adversarial debut-- num batch  445
boucle adversarial fin
boucle adversarial debut-- num batch  446
boucle adversarial fin
boucle adversarial debut-- num batch  447
boucle adversarial fin
boucle adversarial debut-- num batch  448
boucle adversarial fin
boucle adversarial debut-- num batch  449
boucle adversarial fin
boucle adversarial debut-- num batch  450
boucle adversarial fin
boucle adversarial debut-- num batch  451
boucle adversarial fin
boucle adversarial debut-- num batch  452
boucle adversarial fin
boucle adversarial debut-- num batch  453
boucle adversarial fin
boucle adversarial debut-- num batch  454
boucle adversarial fin
boucle adversarial debut-- num batch  455
boucle adversarial fin
boucle adversarial debut-- num batch  456
boucle adversarial fin
boucle adversarial debut-- num batch  457
boucle adversarial fin
boucle adversarial debut-- num batch  458
boucle adversarial fin
boucle adversarial debut-- num batch  459
boucle adversarial fin
boucle adversarial debut-- num batch  460
boucle adversarial fin
boucle adversarial debut-- num batch  461
boucle adversarial fin
boucle adversarial debut-- num batch  462
boucle adversarial fin
boucle adversarial debut-- num batch  463
boucle adversarial fin
boucle adversarial debut-- num batch  464
boucle adversarial fin
boucle adversarial debut-- num batch  465
boucle adversarial fin
boucle adversarial debut-- num batch  466
boucle adversarial fin
boucle adversarial debut-- num batch  467
boucle adversarial fin
boucle adversarial debut-- num batch  468
boucle adversarial fin
boucle adversarial debut-- num batch  469
boucle adversarial fin
boucle adversarial debut-- num batch  470
boucle adversarial fin
boucle adversarial debut-- num batch  471
boucle adversarial fin
boucle adversarial debut-- num batch  472
boucle adversarial fin
boucle adversarial debut-- num batch  473
boucle adversarial fin
boucle adversarial debut-- num batch  474
boucle adversarial fin
boucle adversarial debut-- num batch  475
boucle adversarial fin
boucle adversarial debut-- num batch  476
boucle adversarial fin
boucle adversarial debut-- num batch  477
boucle adversarial fin
boucle adversarial debut-- num batch  478
boucle adversarial fin
boucle adversarial debut-- num batch  479
boucle adversarial fin
boucle adversarial debut-- num batch  480
boucle adversarial fin
boucle adversarial debut-- num batch  481
boucle adversarial fin
boucle adversarial debut-- num batch  482

boucle adversarial fin
boucle adversarial debut-- num batch  483
boucle adversarial fin
boucle adversarial debut-- num batch  484
boucle adversarial fin
boucle adversarial debut-- num batch  485
boucle adversarial fin
boucle adversarial debut-- num batch  486
boucle adversarial fin
boucle adversarial debut-- num batch  487
boucle adversarial fin
boucle adversarial debut-- num batch  488
boucle adversarial fin
boucle adversarial debut-- num batch  489
boucle adversarial fin
boucle adversarial debut-- num batch  490
boucle adversarial fin
boucle adversarial debut-- num batch  491
boucle adversarial fin
boucle adversarial debut-- num batch  492
boucle adversarial fin
boucle adversarial debut-- num batch  493
boucle adversarial fin
boucle adversarial debut-- num batch  494
boucle adversarial fin
boucle adversarial debut-- num batch  495
boucle adversarial fin
boucle adversarial debut-- num batch  496
boucle adversarial fin
boucle adversarial debut-- num batch  497
boucle adversarial fin
boucle adversarial debut-- num batch  498
boucle adversarial fin
boucle adversarial debut-- num batch  499
boucle adversarial fin
boucle adversarial debut-- num batch  500
boucle adversarial fin
boucle adversarial debut-- num batch  501
boucle adversarial fin
boucle adversarial debut-- num batch  502
boucle adversarial fin
boucle adversarial debut-- num batch  503
boucle adversarial fin
boucle adversarial debut-- num batch  504
boucle adversarial fin
boucle adversarial debut-- num batch  505
boucle adversarial fin
boucle adversarial debut-- num batch  506
boucle adversarial fin
boucle adversarial debut-- num batch  507
boucle adversarial fin
boucle adversarial debut-- num batch  508
boucle adversarial fin
boucle adversarial debut-- num batch  509
boucle adversarial fin
boucle adversarial debut-- num batch  510
boucle adversarial fin
boucle adversarial debut-- num batch  511
boucle adversarial fin
boucle adversarial debut-- num batch  512
boucle adversarial fin
boucle adversarial debut-- num batch  513
boucle adversarial fin
boucle adversarial debut-- num batch  514
boucle adversarial fin
boucle adversarial debut-- num batch  515
boucle adversarial fin
boucle adversarial debut-- num batch  516
boucle adversarial fin
boucle adversarial debut-- num batch  517
boucle adversarial fin
boucle adversarial debut-- num batch  518
boucle adversarial fin
boucle adversarial debut-- num batch  519
boucle adversarial fin
boucle adversarial debut-- num batch  520
boucle adversarial fin
boucle adversarial debut-- num batch  521
boucle adversarial fin
boucle adversarial debut-- num batch  522
boucle adversarial fin
boucle adversarial debut-- num batch  523
boucle adversarial fin
boucle adversarial debut-- num batch  524
boucle adversarial fin
boucle adversarial debut-- num batch  525
boucle adversarial fin
boucle adversarial debut-- num batch  526
boucle adversarial fin
boucle adversarial debut-- num batch  527
boucle adversarial fin
boucle adversarial debut-- num batch  528
boucle adversarial fin
boucle adversarial debut-- num batch  529
boucle adversarial fin
boucle adversarial debut-- num batch  530
boucle adversarial fin
boucle adversarial debut-- num batch  531
boucle adversarial fin
boucle adversarial debut-- num batch  532
boucle adversarial fin
boucle adversarial debut-- num batch  533
boucle adversarial fin
boucle adversarial debut-- num batch  534
boucle adversarial fin
boucle adversarial debut-- num batch  535
boucle adversarial fin
boucle adversarial debut-- num batch  536
boucle adversarial fin
boucle adversarial debut-- num batch  537
boucle adversarial fin
boucle adversarial debut-- num batch  538
boucle adversarial fin
boucle adversarial debut-- num batch  539
boucle adversarial fin
boucle adversarial debut-- num batch  540
boucle adversarial fin
boucle adversarial debut-- num batch  541
boucle adversarial fin
boucle adversarial debut-- num batch  542
boucle adversarial fin
boucle adversarial debut-- num batch  543
boucle adversarial fin
boucle adversarial debut-- num batch  544
boucle adversarial fin
boucle adversarial debut-- num batch  545
boucle adversarial fin
boucle adversarial debut-- num batch  546
boucle adversarial fin
boucle adversarial debut-- num batch  547
boucle adversarial fin
boucle adversarial debut-- num batch  548
boucle adversarial fin
boucle adversarial debut-- num batch  549
boucle adversarial fin
boucle adversarial debut-- num batch  550
boucle adversarial fin
boucle adversarial debut-- num batch  551
boucle adversarial fin
boucle adversarial debut-- num batch  552
boucle adversarial fin
boucle adversarial debut-- num batch  553
boucle adversarial fin
boucle adversarial debut-- num batch  554
boucle adversarial fin
boucle adversarial debut-- num batch  555
boucle adversarial fin
boucle adversarial debut-- num batch  556
boucle adversarial fin
boucle adversarial debut-- num batch  557
boucle adversarial fin
boucle adversarial debut-- num batch  558
boucle adversarial fin
boucle adversarial debut-- num batch  559
boucle adversarial fin
boucle adversarial debut-- num batch  560
boucle adversarial fin
boucle adversarial debut-- num batch  561
boucle adversarial fin
boucle adversarial debut-- num batch  562
boucle adversarial fin
boucle adversarial debut-- num batch  563
boucle adversarial fin
boucle adversarial debut-- num batch  564
boucle adversarial fin
boucle adversarial debut-- num batch  565
boucle adversarial fin
boucle adversarial debut-- num batch  566
boucle adversarial fin
boucle adversarial debut-- num batch  567
boucle adversarial fin
boucle adversarial debut-- num batch  568
boucle adversarial fin
boucle adversarial debut-- num batch  569
boucle adversarial fin
boucle adversarial debut-- num batch  570
boucle adversarial fin
boucle adversarial debut-- num batch  571
boucle adversarial fin
boucle adversarial debut-- num batch  572
boucle adversarial fin
boucle adversarial debut-- num batch  573
boucle adversarial fin
boucle adversarial debut-- num batch  574
boucle adversarial fin
boucle adversarial debut-- num batch  575
boucle adversarial fin
boucle adversarial debut-- num batch  576
boucle adversarial fin
boucle adversarial debut-- num batch  577
boucle adversarial fin
boucle adversarial debut-- num batch  578
boucle adversarial fin
boucle adversarial debut-- num batch  579
boucle adversarial fin
boucle adversarial debut-- num batch  580
boucle adversarial fin
boucle adversarial debut-- num batch  581
boucle adversarial fin
boucle adversarial debut-- num batch  582
boucle adversarial fin
boucle adversarial debut-- num batch  583
boucle adversarial fin
boucle adversarial debut-- num batch  584
boucle adversarial fin
boucle adversarial debut-- num batch  585
boucle adversarial fin
boucle adversarial debut-- num batch  586
boucle adversarial fin
boucle adversarial debut-- num batch  587
boucle adversarial fin
boucle adversarial debut-- num batch  588
boucle adversarial fin
boucle adversarial debut-- num batch  589
boucle adversarial fin
boucle adversarial debut-- num batch  590
boucle adversarial fin
boucle adversarial debut-- num batch  591
boucle adversarial fin
boucle adversarial debut-- num batch  592
boucle adversarial fin
boucle adversarial debut-- num batch  593
boucle adversarial fin
boucle adversarial debut-- num batch  594
boucle adversarial fin
boucle adversarial debut-- num batch  595
boucle adversarial fin
boucle adversarial debut-- num batch  596
boucle adversarial fin
boucle adversarial debut-- num batch  597
boucle adversarial fin
boucle adversarial debut-- num batch  598
boucle adversarial fin
boucle adversarial debut-- num batch  599
boucle adversarial fin
boucle adversarial debut-- num batch  600
boucle adversarial fin
boucle adversarial debut-- num batch  601
boucle adversarial fin
boucle adversarial debut-- num batch  602
boucle adversarial fin
boucle adversarial debut-- num batch  603
boucle adversarial fin
boucle adversarial debut-- num batch  604
boucle adversarial fin
boucle adversarial debut-- num batch  605
boucle adversarial fin
boucle adversarial debut-- num batch  606
boucle adversarial fin
boucle adversarial debut-- num batch  607
boucle adversarial fin
boucle adversarial debut-- num batch  608
boucle adversarial fin
boucle adversarial debut-- num batch  609

boucle adversarial fin
boucle adversarial debut-- num batch  610
boucle adversarial fin
boucle adversarial debut-- num batch  611
boucle adversarial fin
boucle adversarial debut-- num batch  612
boucle adversarial fin
boucle adversarial debut-- num batch  613
boucle adversarial fin
boucle adversarial debut-- num batch  614
boucle adversarial fin
boucle adversarial debut-- num batch  615
boucle adversarial fin
boucle adversarial debut-- num batch  616
boucle adversarial fin
boucle adversarial debut-- num batch  617
boucle adversarial fin
boucle adversarial debut-- num batch  618
boucle adversarial fin
boucle adversarial debut-- num batch  619
boucle adversarial fin
boucle adversarial debut-- num batch  620
boucle adversarial fin
boucle adversarial debut-- num batch  621
boucle adversarial fin
boucle adversarial debut-- num batch  622
boucle adversarial fin
boucle adversarial debut-- num batch  623
boucle adversarial fin
boucle adversarial debut-- num batch  624
boucle adversarial fin
boucle adversarial debut-- num batch  625
boucle adversarial fin
boucle adversarial debut-- num batch  626
boucle adversarial fin
boucle adversarial debut-- num batch  627
boucle adversarial fin
boucle adversarial debut-- num batch  628
boucle adversarial fin
boucle adversarial debut-- num batch  629
boucle adversarial fin
boucle adversarial debut-- num batch  630
boucle adversarial fin
boucle adversarial debut-- num batch  631
boucle adversarial fin
boucle adversarial debut-- num batch  632
boucle adversarial fin
boucle adversarial debut-- num batch  633
boucle adversarial fin
boucle adversarial debut-- num batch  634
boucle adversarial fin
boucle adversarial debut-- num batch  635
boucle adversarial fin
boucle adversarial debut-- num batch  636
boucle adversarial fin
boucle adversarial debut-- num batch  637
boucle adversarial fin
boucle adversarial debut-- num batch  638
boucle adversarial fin
boucle adversarial debut-- num batch  639
boucle adversarial fin
boucle adversarial debut-- num batch  640
boucle adversarial fin
boucle adversarial debut-- num batch  641
boucle adversarial fin
boucle adversarial debut-- num batch  642
boucle adversarial fin
boucle adversarial debut-- num batch  643
boucle adversarial fin
boucle adversarial debut-- num batch  644
boucle adversarial fin
boucle adversarial debut-- num batch  645
boucle adversarial fin
boucle adversarial debut-- num batch  646
boucle adversarial fin
boucle adversarial debut-- num batch  647
boucle adversarial fin
boucle adversarial debut-- num batch  648
boucle adversarial fin
boucle adversarial debut-- num batch  649
boucle adversarial fin
boucle adversarial debut-- num batch  650
boucle adversarial fin
boucle adversarial debut-- num batch  651
boucle adversarial fin
boucle adversarial debut-- num batch  652
boucle adversarial fin
boucle adversarial debut-- num batch  653
boucle adversarial fin
boucle adversarial debut-- num batch  654
boucle adversarial fin
boucle adversarial debut-- num batch  655
boucle adversarial fin
boucle adversarial debut-- num batch  656
boucle adversarial fin
boucle adversarial debut-- num batch  657
boucle adversarial fin
boucle adversarial debut-- num batch  658
boucle adversarial fin
boucle adversarial debut-- num batch  659
boucle adversarial fin
boucle adversarial debut-- num batch  660
boucle adversarial fin
boucle adversarial debut-- num batch  661
boucle adversarial fin
boucle adversarial debut-- num batch  662
boucle adversarial fin
boucle adversarial debut-- num batch  663
boucle adversarial fin
boucle adversarial debut-- num batch  664
boucle adversarial fin
boucle adversarial debut-- num batch  665
boucle adversarial fin
boucle adversarial debut-- num batch  666
boucle adversarial fin
boucle adversarial debut-- num batch  667
boucle adversarial fin
boucle adversarial debut-- num batch  668
boucle adversarial fin
boucle adversarial debut-- num batch  669
boucle adversarial fin
boucle adversarial debut-- num batch  670
boucle adversarial fin
boucle adversarial debut-- num batch  671
boucle adversarial fin
boucle adversarial debut-- num batch  672
boucle adversarial fin
boucle adversarial debut-- num batch  673
boucle adversarial fin
boucle adversarial debut-- num batch  674
boucle adversarial fin
boucle adversarial debut-- num batch  675
boucle adversarial fin
boucle adversarial debut-- num batch  676
boucle adversarial fin
boucle adversarial debut-- num batch  677
boucle adversarial fin
boucle adversarial debut-- num batch  678
boucle adversarial fin
boucle adversarial debut-- num batch  679
boucle adversarial fin
boucle adversarial debut-- num batch  680
boucle adversarial fin
boucle adversarial debut-- num batch  681
boucle adversarial fin
boucle adversarial debut-- num batch  682
boucle adversarial fin
boucle adversarial debut-- num batch  683
boucle adversarial fin
boucle adversarial debut-- num batch  684
boucle adversarial fin
boucle adversarial debut-- num batch  685
boucle adversarial fin
boucle adversarial debut-- num batch  686
boucle adversarial fin
boucle adversarial debut-- num batch  687
boucle adversarial fin
boucle adversarial debut-- num batch  688
boucle adversarial fin
boucle adversarial debut-- num batch  689
boucle adversarial fin
boucle adversarial debut-- num batch  690
boucle adversarial fin
boucle adversarial debut-- num batch  691
boucle adversarial fin
boucle adversarial debut-- num batch  692
boucle adversarial fin
boucle adversarial debut-- num batch  693
boucle adversarial fin
boucle adversarial debut-- num batch  694
boucle adversarial fin
boucle adversarial debut-- num batch  695
boucle adversarial fin
boucle adversarial debut-- num batch  696
boucle adversarial fin
boucle adversarial debut-- num batch  697
boucle adversarial fin
boucle adversarial debut-- num batch  698
boucle adversarial fin
boucle adversarial debut-- num batch  699
boucle adversarial fin
boucle adversarial debut-- num batch  700
boucle adversarial fin
boucle adversarial debut-- num batch  701
boucle adversarial fin
boucle adversarial debut-- num batch  702
boucle adversarial fin
boucle adversarial debut-- num batch  703
boucle adversarial fin
boucle adversarial debut-- num batch  704
boucle adversarial fin
boucle adversarial debut-- num batch  705
boucle adversarial fin
boucle adversarial debut-- num batch  706
boucle adversarial fin
boucle adversarial debut-- num batch  707
boucle adversarial fin
boucle adversarial debut-- num batch  708
boucle adversarial fin
boucle adversarial debut-- num batch  709
boucle adversarial fin
boucle adversarial debut-- num batch  710
boucle adversarial fin
boucle adversarial debut-- num batch  711
boucle adversarial fin
boucle adversarial debut-- num batch  712
boucle adversarial fin
boucle adversarial debut-- num batch  713
boucle adversarial fin
boucle adversarial debut-- num batch  714
boucle adversarial fin
boucle adversarial debut-- num batch  715
boucle adversarial fin
boucle adversarial debut-- num batch  716
boucle adversarial fin
boucle adversarial debut-- num batch  717
boucle adversarial fin
boucle adversarial debut-- num batch  718
boucle adversarial fin
boucle adversarial debut-- num batch  719
boucle adversarial fin
boucle adversarial debut-- num batch  720
boucle adversarial fin
boucle adversarial debut-- num batch  721
boucle adversarial fin
boucle adversarial debut-- num batch  722
boucle adversarial fin
boucle adversarial debut-- num batch  723
boucle adversarial fin
boucle adversarial debut-- num batch  724
boucle adversarial fin
boucle adversarial debut-- num batch  725
boucle adversarial fin
boucle adversarial debut-- num batch  726
boucle adversarial fin
boucle adversarial debut-- num batch  727
boucle adversarial fin
boucle adversarial debut-- num batch  728
boucle adversarial fin
boucle adversarial debut-- num batch  729
boucle adversarial fin
boucle adversarial debut-- num batch  730
boucle adversarial fin
boucle adversarial debut-- num batch  731
boucle adversarial fin
boucle adversarial debut-- num batch  732
boucle adversarial fin
boucle adversarial debut-- num batch  733
boucle adversarial fin
boucle adversarial debut-- num batch  734
boucle adversarial fin
boucle adversarial debut-- num batch  735
boucle adversarial fin
boucle adversarial debut-- num batch  736

boucle adversarial fin
boucle adversarial debut-- num batch  737
boucle adversarial fin
boucle adversarial debut-- num batch  738
boucle adversarial fin
boucle adversarial debut-- num batch  739
boucle adversarial fin
boucle adversarial debut-- num batch  740
boucle adversarial fin
boucle adversarial debut-- num batch  741
boucle adversarial fin
boucle adversarial debut-- num batch  742
boucle adversarial fin
boucle adversarial debut-- num batch  743
boucle adversarial fin
boucle adversarial debut-- num batch  744
boucle adversarial fin
boucle adversarial debut-- num batch  745
boucle adversarial fin
boucle adversarial debut-- num batch  746
boucle adversarial fin
boucle adversarial debut-- num batch  747
boucle adversarial fin
boucle adversarial debut-- num batch  748
boucle adversarial fin
boucle adversarial debut-- num batch  749
boucle adversarial fin
boucle adversarial debut-- num batch  750
boucle adversarial fin
boucle adversarial debut-- num batch  751
boucle adversarial fin
boucle adversarial debut-- num batch  752
boucle adversarial fin
boucle adversarial debut-- num batch  753
boucle adversarial fin
boucle adversarial debut-- num batch  754
boucle adversarial fin
boucle adversarial debut-- num batch  755
boucle adversarial fin
boucle adversarial debut-- num batch  756
boucle adversarial fin
boucle adversarial debut-- num batch  757
boucle adversarial fin
boucle adversarial debut-- num batch  758
boucle adversarial fin
boucle adversarial debut-- num batch  759
boucle adversarial fin
boucle adversarial debut-- num batch  760
boucle adversarial fin
boucle adversarial debut-- num batch  761
boucle adversarial fin
boucle adversarial debut-- num batch  762
boucle adversarial fin
boucle adversarial debut-- num batch  763
boucle adversarial fin
boucle adversarial debut-- num batch  764
boucle adversarial fin
boucle adversarial debut-- num batch  765
boucle adversarial fin
boucle adversarial debut-- num batch  766
boucle adversarial fin
boucle adversarial debut-- num batch  767
boucle adversarial fin
boucle adversarial debut-- num batch  768
boucle adversarial fin
boucle adversarial debut-- num batch  769
boucle adversarial fin
boucle adversarial debut-- num batch  770
boucle adversarial fin
boucle adversarial debut-- num batch  771
boucle adversarial fin
boucle adversarial debut-- num batch  772
boucle adversarial fin
boucle adversarial debut-- num batch  773
boucle adversarial fin
boucle adversarial debut-- num batch  774
boucle adversarial fin
boucle adversarial debut-- num batch  775
boucle adversarial fin
boucle adversarial debut-- num batch  776
boucle adversarial fin
boucle adversarial debut-- num batch  777
boucle adversarial fin
boucle adversarial debut-- num batch  778
boucle adversarial fin
boucle adversarial debut-- num batch  779
boucle adversarial fin
boucle adversarial debut-- num batch  780
boucle adversarial fin
boucle adversarial debut-- num batch  781
boucle adversarial fin
boucle adversarial debut-- num batch  782
boucle adversarial fin
boucle adversarial debut-- num batch  783
boucle adversarial fin
boucle adversarial debut-- num batch  784
boucle adversarial fin
boucle adversarial debut-- num batch  785
boucle adversarial fin
boucle adversarial debut-- num batch  786
boucle adversarial fin
boucle adversarial debut-- num batch  787
boucle adversarial fin
boucle adversarial debut-- num batch  788
boucle adversarial fin
boucle adversarial debut-- num batch  789
boucle adversarial fin
boucle adversarial debut-- num batch  790
boucle adversarial fin
boucle adversarial debut-- num batch  791
boucle adversarial fin
boucle adversarial debut-- num batch  792
boucle adversarial fin
boucle adversarial debut-- num batch  793
boucle adversarial fin
boucle adversarial debut-- num batch  794
boucle adversarial fin
boucle adversarial debut-- num batch  795
boucle adversarial fin
boucle adversarial debut-- num batch  796
boucle adversarial fin
boucle adversarial debut-- num batch  797
boucle adversarial fin
boucle adversarial debut-- num batch  798
boucle adversarial fin
boucle adversarial debut-- num batch  799
boucle adversarial fin
boucle adversarial debut-- num batch  800
boucle adversarial fin
boucle adversarial debut-- num batch  801
boucle adversarial fin
boucle adversarial debut-- num batch  802
boucle adversarial fin
boucle adversarial debut-- num batch  803
boucle adversarial fin
boucle adversarial debut-- num batch  804
boucle adversarial fin
boucle adversarial debut-- num batch  805
boucle adversarial fin
boucle adversarial debut-- num batch  806
boucle adversarial fin
boucle adversarial debut-- num batch  807
boucle adversarial fin
boucle adversarial debut-- num batch  808
boucle adversarial fin
boucle adversarial debut-- num batch  809
boucle adversarial fin
boucle adversarial debut-- num batch  810
boucle adversarial fin
boucle adversarial debut-- num batch  811
boucle adversarial fin
boucle adversarial debut-- num batch  812
boucle adversarial fin
boucle adversarial debut-- num batch  813
boucle adversarial fin
boucle adversarial debut-- num batch  814
boucle adversarial fin
boucle adversarial debut-- num batch  815
boucle adversarial fin
boucle adversarial debut-- num batch  816
boucle adversarial fin
boucle adversarial debut-- num batch  817
boucle adversarial fin
boucle adversarial debut-- num batch  818
boucle adversarial fin
boucle adversarial debut-- num batch  819
boucle adversarial fin
boucle adversarial debut-- num batch  820
boucle adversarial fin
boucle adversarial debut-- num batch  821
boucle adversarial fin
boucle adversarial debut-- num batch  822
boucle adversarial fin
boucle adversarial debut-- num batch  823
boucle adversarial fin
boucle adversarial debut-- num batch  824
boucle adversarial fin
boucle adversarial debut-- num batch  825
boucle adversarial fin
boucle adversarial debut-- num batch  826
boucle adversarial fin
boucle adversarial debut-- num batch  827
boucle adversarial fin
boucle adversarial debut-- num batch  828
boucle adversarial fin
boucle adversarial debut-- num batch  829
boucle adversarial fin
boucle adversarial debut-- num batch  830
boucle adversarial fin
boucle adversarial debut-- num batch  831
boucle adversarial fin
boucle adversarial debut-- num batch  832
boucle adversarial fin
boucle adversarial debut-- num batch  833
boucle adversarial fin
boucle adversarial debut-- num batch  834
boucle adversarial fin
boucle adversarial debut-- num batch  835
boucle adversarial fin
boucle adversarial debut-- num batch  836
boucle adversarial fin
boucle adversarial debut-- num batch  837
boucle adversarial fin
boucle adversarial debut-- num batch  838
boucle adversarial fin
boucle adversarial debut-- num batch  839
boucle adversarial fin
boucle adversarial debut-- num batch  840
boucle adversarial fin
boucle adversarial debut-- num batch  841
boucle adversarial fin
boucle adversarial debut-- num batch  842
boucle adversarial fin
boucle adversarial debut-- num batch  843
boucle adversarial fin
boucle adversarial debut-- num batch  844
boucle adversarial fin
boucle adversarial debut-- num batch  845
boucle adversarial fin
boucle adversarial debut-- num batch  846
boucle adversarial fin
boucle adversarial debut-- num batch  847
boucle adversarial fin
boucle adversarial debut-- num batch  848
boucle adversarial fin
boucle adversarial debut-- num batch  849
boucle adversarial fin
boucle adversarial debut-- num batch  850
boucle adversarial fin
boucle adversarial debut-- num batch  851
boucle adversarial fin
boucle adversarial debut-- num batch  852
boucle adversarial fin
boucle adversarial debut-- num batch  853
boucle adversarial fin
boucle adversarial debut-- num batch  854
boucle adversarial fin
boucle adversarial debut-- num batch  855
boucle adversarial fin
boucle adversarial debut-- num batch  856
boucle adversarial fin
boucle adversarial debut-- num batch  857
boucle adversarial fin
boucle adversarial debut-- num batch  858
boucle adversarial fin
boucle adversarial debut-- num batch  859
boucle adversarial fin
boucle adversarial debut-- num batch  860
boucle adversarial fin
boucle adversarial debut-- num batch  861
boucle adversarial fin
boucle adversarial debut-- num batch  862
boucle adversarial fin
boucle adversarial debut-- num batch  863

boucle adversarial fin
boucle adversarial debut-- num batch  864
boucle adversarial fin
boucle adversarial debut-- num batch  865
boucle adversarial fin
boucle adversarial debut-- num batch  866
boucle adversarial fin
boucle adversarial debut-- num batch  867
boucle adversarial fin
boucle adversarial debut-- num batch  868
boucle adversarial fin
boucle adversarial debut-- num batch  869
boucle adversarial fin
boucle adversarial debut-- num batch  870
boucle adversarial fin
boucle adversarial debut-- num batch  871
boucle adversarial fin
boucle adversarial debut-- num batch  872
boucle adversarial fin
boucle adversarial debut-- num batch  873
boucle adversarial fin
boucle adversarial debut-- num batch  874
boucle adversarial fin
boucle adversarial debut-- num batch  875
boucle adversarial fin
boucle adversarial debut-- num batch  876
boucle adversarial fin
boucle adversarial debut-- num batch  877
boucle adversarial fin
boucle adversarial debut-- num batch  878
boucle adversarial fin
boucle adversarial debut-- num batch  879
boucle adversarial fin
boucle adversarial debut-- num batch  880
boucle adversarial fin
boucle adversarial debut-- num batch  881
boucle adversarial fin
boucle adversarial debut-- num batch  882
boucle adversarial fin
boucle adversarial debut-- num batch  883
boucle adversarial fin
boucle adversarial debut-- num batch  884
boucle adversarial fin
boucle adversarial debut-- num batch  885
boucle adversarial fin
boucle adversarial debut-- num batch  886
boucle adversarial fin
boucle adversarial debut-- num batch  887
boucle adversarial fin
boucle adversarial debut-- num batch  888
boucle adversarial fin
boucle adversarial debut-- num batch  889
boucle adversarial fin
boucle adversarial debut-- num batch  890
boucle adversarial fin
boucle adversarial debut-- num batch  891
boucle adversarial fin
boucle adversarial debut-- num batch  892
boucle adversarial fin
boucle adversarial debut-- num batch  893
boucle adversarial fin
boucle adversarial debut-- num batch  894
boucle adversarial fin
boucle adversarial debut-- num batch  895
boucle adversarial fin
boucle adversarial debut-- num batch  896
boucle adversarial fin
boucle adversarial debut-- num batch  897
boucle adversarial fin
boucle adversarial debut-- num batch  898
boucle adversarial fin
boucle adversarial debut-- num batch  899
boucle adversarial fin
boucle adversarial debut-- num batch  900
boucle adversarial fin
boucle adversarial debut-- num batch  901
boucle adversarial fin
boucle adversarial debut-- num batch  902
boucle adversarial fin
boucle adversarial debut-- num batch  903
boucle adversarial fin
boucle adversarial debut-- num batch  904
boucle adversarial fin
boucle adversarial debut-- num batch  905
boucle adversarial fin
boucle adversarial debut-- num batch  906
boucle adversarial fin
boucle adversarial debut-- num batch  907
boucle adversarial fin
boucle adversarial debut-- num batch  908
boucle adversarial fin
boucle adversarial debut-- num batch  909
boucle adversarial fin
boucle adversarial debut-- num batch  910
boucle adversarial fin
boucle adversarial debut-- num batch  911
boucle adversarial fin
boucle adversarial debut-- num batch  912
boucle adversarial fin
boucle adversarial debut-- num batch  913
boucle adversarial fin
boucle adversarial debut-- num batch  914
boucle adversarial fin
boucle adversarial debut-- num batch  915
boucle adversarial fin
boucle adversarial debut-- num batch  916
boucle adversarial fin
boucle adversarial debut-- num batch  917
boucle adversarial fin
boucle adversarial debut-- num batch  918
boucle adversarial fin
boucle adversarial debut-- num batch  919
boucle adversarial fin
boucle adversarial debut-- num batch  920
boucle adversarial fin
boucle adversarial debut-- num batch  921
boucle adversarial fin
boucle adversarial debut-- num batch  922
boucle adversarial fin
boucle adversarial debut-- num batch  923
boucle adversarial fin
boucle adversarial debut-- num batch  924
boucle adversarial fin
boucle adversarial debut-- num batch  925
boucle adversarial fin
boucle adversarial debut-- num batch  926
boucle adversarial fin
boucle adversarial debut-- num batch  927
boucle adversarial fin
boucle adversarial debut-- num batch  928
boucle adversarial fin
boucle adversarial debut-- num batch  929
boucle adversarial fin
boucle adversarial debut-- num batch  930
boucle adversarial fin
boucle adversarial debut-- num batch  931
boucle adversarial fin
boucle adversarial debut-- num batch  932
boucle adversarial fin
boucle adversarial debut-- num batch  933
boucle adversarial fin
boucle adversarial debut-- num batch  934
boucle adversarial fin
boucle adversarial debut-- num batch  935
boucle adversarial fin
boucle adversarial debut-- num batch  936
boucle adversarial fin
boucle adversarial debut-- num batch  937
boucle adversarial fin
boucle adversarial debut-- num batch  938
boucle adversarial fin
boucle adversarial debut-- num batch  939
boucle adversarial fin
boucle adversarial debut-- num batch  940
boucle adversarial fin
boucle adversarial debut-- num batch  941
boucle adversarial fin
boucle adversarial debut-- num batch  942
boucle adversarial fin
boucle adversarial debut-- num batch  943
boucle adversarial fin
boucle adversarial debut-- num batch  944
boucle adversarial fin
boucle adversarial debut-- num batch  945
boucle adversarial fin
boucle adversarial debut-- num batch  946
boucle adversarial fin
boucle adversarial debut-- num batch  947
boucle adversarial fin
boucle adversarial debut-- num batch  948
boucle adversarial fin
boucle adversarial debut-- num batch  949
boucle adversarial fin
boucle adversarial debut-- num batch  950
boucle adversarial fin
boucle adversarial debut-- num batch  951
boucle adversarial fin
boucle adversarial debut-- num batch  952
boucle adversarial fin
boucle adversarial debut-- num batch  953
boucle adversarial fin
boucle adversarial debut-- num batch  954
boucle adversarial fin
boucle adversarial debut-- num batch  955
boucle adversarial fin
boucle adversarial debut-- num batch  956
boucle adversarial fin
boucle adversarial debut-- num batch  957
boucle adversarial fin
boucle adversarial debut-- num batch  958
boucle adversarial fin
boucle adversarial debut-- num batch  959
boucle adversarial fin
boucle adversarial debut-- num batch  960
boucle adversarial fin
boucle adversarial debut-- num batch  961
boucle adversarial fin
boucle adversarial debut-- num batch  962
boucle adversarial fin
boucle adversarial debut-- num batch  963
boucle adversarial fin
boucle adversarial debut-- num batch  964
boucle adversarial fin
boucle adversarial debut-- num batch  965
boucle adversarial fin
boucle adversarial debut-- num batch  966
boucle adversarial fin
boucle adversarial debut-- num batch  967
boucle adversarial fin
boucle adversarial debut-- num batch  968
boucle adversarial fin
boucle adversarial debut-- num batch  969
boucle adversarial fin
boucle adversarial debut-- num batch  970
boucle adversarial fin
boucle adversarial debut-- num batch  971
boucle adversarial fin
boucle adversarial debut-- num batch  972
boucle adversarial fin
boucle adversarial debut-- num batch  973
boucle adversarial fin
boucle adversarial debut-- num batch  974
boucle adversarial fin
boucle adversarial debut-- num batch  975
boucle adversarial fin
boucle adversarial debut-- num batch  976
boucle adversarial fin
boucle adversarial debut-- num batch  977
boucle adversarial fin
boucle adversarial debut-- num batch  978
boucle adversarial fin
boucle adversarial debut-- num batch  979
boucle adversarial fin
boucle adversarial debut-- num batch  980
boucle adversarial fin
boucle adversarial debut-- num batch  981
boucle adversarial fin
boucle adversarial debut-- num batch  982
boucle adversarial fin
boucle adversarial debut-- num batch  983
boucle adversarial fin
boucle adversarial debut-- num batch  984
boucle adversarial fin
boucle adversarial debut-- num batch  985
boucle adversarial fin
boucle adversarial debut-- num batch  986
boucle adversarial fin
boucle adversarial debut-- num batch  987
boucle adversarial fin
boucle adversarial debut-- num batch  988
boucle adversarial fin
boucle adversarial debut-- num batch  989
boucle adversarial fin
boucle adversarial debut-- num batch  990

boucle adversarial fin
boucle adversarial debut-- num batch  991
boucle adversarial fin
boucle adversarial debut-- num batch  992
boucle adversarial fin
boucle adversarial debut-- num batch  993
boucle adversarial fin
boucle adversarial debut-- num batch  994
boucle adversarial fin
boucle adversarial debut-- num batch  995
boucle adversarial fin
boucle adversarial debut-- num batch  996
boucle adversarial fin
boucle adversarial debut-- num batch  997
boucle adversarial fin
boucle adversarial debut-- num batch  998
boucle adversarial fin
boucle adversarial debut-- num batch  999
boucle adversarial fin
boucle adversarial debut-- num batch  1000
boucle adversarial fin
boucle adversarial debut-- num batch  1001
boucle adversarial fin
boucle adversarial debut-- num batch  1002
boucle adversarial fin
boucle adversarial debut-- num batch  1003
boucle adversarial fin
boucle adversarial debut-- num batch  1004
boucle adversarial fin
boucle adversarial debut-- num batch  1005
boucle adversarial fin
boucle adversarial debut-- num batch  1006
boucle adversarial fin
boucle adversarial debut-- num batch  1007
boucle adversarial fin
boucle adversarial debut-- num batch  1008
boucle adversarial fin
boucle adversarial debut-- num batch  1009
boucle adversarial fin
boucle adversarial debut-- num batch  1010
boucle adversarial fin
boucle adversarial debut-- num batch  1011
boucle adversarial fin
boucle adversarial debut-- num batch  1012
boucle adversarial fin
boucle adversarial debut-- num batch  1013
boucle adversarial fin
boucle adversarial debut-- num batch  1014
boucle adversarial fin
boucle adversarial debut-- num batch  1015
boucle adversarial fin
boucle adversarial debut-- num batch  1016
boucle adversarial fin
boucle adversarial debut-- num batch  1017
boucle adversarial fin
boucle adversarial debut-- num batch  1018
boucle adversarial fin
boucle adversarial debut-- num batch  1019
boucle adversarial fin
boucle adversarial debut-- num batch  1020
boucle adversarial fin
boucle adversarial debut-- num batch  1021
boucle adversarial fin
boucle adversarial debut-- num batch  1022
boucle adversarial fin
boucle adversarial debut-- num batch  1023
boucle adversarial fin
boucle adversarial debut-- num batch  1024
boucle adversarial fin
boucle adversarial debut-- num batch  1025
boucle adversarial fin
boucle adversarial debut-- num batch  1026
boucle adversarial fin
boucle adversarial debut-- num batch  1027
boucle adversarial fin
boucle adversarial debut-- num batch  1028
boucle adversarial fin
boucle adversarial debut-- num batch  1029
boucle adversarial fin
boucle adversarial debut-- num batch  1030
boucle adversarial fin
boucle adversarial debut-- num batch  1031
boucle adversarial fin
boucle adversarial debut-- num batch  1032
boucle adversarial fin
boucle adversarial debut-- num batch  1033
boucle adversarial fin
boucle adversarial debut-- num batch  1034
boucle adversarial fin
boucle adversarial debut-- num batch  1035
boucle adversarial fin
boucle adversarial debut-- num batch  1036
boucle adversarial fin
boucle adversarial debut-- num batch  1037
boucle adversarial fin
boucle adversarial debut-- num batch  1038
boucle adversarial fin
boucle adversarial debut-- num batch  1039
boucle adversarial fin
boucle adversarial debut-- num batch  1040
boucle adversarial fin
boucle adversarial debut-- num batch  1041
boucle adversarial fin
boucle adversarial debut-- num batch  1042
boucle adversarial fin
boucle adversarial debut-- num batch  1043
boucle adversarial fin
boucle adversarial debut-- num batch  1044
boucle adversarial fin
boucle adversarial debut-- num batch  1045
boucle adversarial fin
boucle adversarial debut-- num batch  1046
boucle adversarial fin
boucle adversarial debut-- num batch  1047
boucle adversarial fin
boucle adversarial debut-- num batch  1048
boucle adversarial fin
boucle adversarial debut-- num batch  1049
boucle adversarial fin
boucle adversarial debut-- num batch  1050
boucle adversarial fin
boucle adversarial debut-- num batch  1051
boucle adversarial fin
boucle adversarial debut-- num batch  1052
boucle adversarial fin
boucle adversarial debut-- num batch  1053
boucle adversarial fin
boucle adversarial debut-- num batch  1054
boucle adversarial fin
boucle adversarial debut-- num batch  1055
boucle adversarial fin
boucle adversarial debut-- num batch  1056
boucle adversarial fin
boucle adversarial debut-- num batch  1057
boucle adversarial fin
boucle adversarial debut-- num batch  1058
boucle adversarial fin
boucle adversarial debut-- num batch  1059
boucle adversarial fin
boucle adversarial debut-- num batch  1060
boucle adversarial fin
boucle adversarial debut-- num batch  1061
boucle adversarial fin
boucle adversarial debut-- num batch  1062
boucle adversarial fin
boucle adversarial debut-- num batch  1063
boucle adversarial fin
boucle adversarial debut-- num batch  1064
boucle adversarial fin
boucle adversarial debut-- num batch  1065
boucle adversarial fin
boucle adversarial debut-- num batch  1066
boucle adversarial fin
boucle adversarial debut-- num batch  1067
boucle adversarial fin
boucle adversarial debut-- num batch  1068
boucle adversarial fin
boucle adversarial debut-- num batch  1069
boucle adversarial fin
boucle adversarial debut-- num batch  1070
boucle adversarial fin
boucle adversarial debut-- num batch  1071
boucle adversarial fin
boucle adversarial debut-- num batch  1072
boucle adversarial fin
boucle adversarial debut-- num batch  1073
boucle adversarial fin
boucle adversarial debut-- num batch  1074
boucle adversarial fin
boucle adversarial debut-- num batch  1075
boucle adversarial fin
boucle adversarial debut-- num batch  1076
boucle adversarial fin
boucle adversarial debut-- num batch  1077
boucle adversarial fin
boucle adversarial debut-- num batch  1078
boucle adversarial fin
boucle adversarial debut-- num batch  1079
boucle adversarial fin
boucle adversarial debut-- num batch  1080
boucle adversarial fin
boucle adversarial debut-- num batch  1081
boucle adversarial fin
boucle adversarial debut-- num batch  1082
boucle adversarial fin
boucle adversarial debut-- num batch  1083
boucle adversarial fin
boucle adversarial debut-- num batch  1084
boucle adversarial fin
boucle adversarial debut-- num batch  1085
boucle adversarial fin
boucle adversarial debut-- num batch  1086
boucle adversarial fin
boucle adversarial debut-- num batch  1087
boucle adversarial fin
boucle adversarial debut-- num batch  1088
boucle adversarial fin
boucle adversarial debut-- num batch  1089
boucle adversarial fin
boucle adversarial debut-- num batch  1090
boucle adversarial fin
boucle adversarial debut-- num batch  1091
boucle adversarial fin
boucle adversarial debut-- num batch  1092
boucle adversarial fin
boucle adversarial debut-- num batch  1093
boucle adversarial fin
boucle adversarial debut-- num batch  1094
boucle adversarial fin
boucle adversarial debut-- num batch  1095
boucle adversarial fin
boucle adversarial debut-- num batch  1096
boucle adversarial fin
boucle adversarial debut-- num batch  1097
boucle adversarial fin
boucle adversarial debut-- num batch  1098
boucle adversarial fin
boucle adversarial debut-- num batch  1099
boucle adversarial fin
boucle adversarial debut-- num batch  1100
boucle adversarial fin
boucle adversarial debut-- num batch  1101
boucle adversarial fin
boucle adversarial debut-- num batch  1102
boucle adversarial fin
boucle adversarial debut-- num batch  1103
boucle adversarial fin
boucle adversarial debut-- num batch  1104
boucle adversarial fin
boucle adversarial debut-- num batch  1105
boucle adversarial fin
boucle adversarial debut-- num batch  1106
boucle adversarial fin
boucle adversarial debut-- num batch  1107
boucle adversarial fin
boucle adversarial debut-- num batch  1108
boucle adversarial fin
boucle adversarial debut-- num batch  1109
boucle adversarial fin
boucle adversarial debut-- num batch  1110
boucle adversarial fin
boucle adversarial debut-- num batch  1111
boucle adversarial fin
boucle adversarial debut-- num batch  1112
boucle adversarial fin
boucle adversarial debut-- num batch  1113
boucle adversarial fin
boucle adversarial debut-- num batch  1114
boucle adversarial fin
boucle adversarial debut-- num batch  1115

boucle adversarial fin
boucle adversarial debut-- num batch  1116
boucle adversarial fin
boucle adversarial debut-- num batch  1117
boucle adversarial fin
boucle adversarial debut-- num batch  1118
boucle adversarial fin
boucle adversarial debut-- num batch  1119
boucle adversarial fin
boucle adversarial debut-- num batch  1120
boucle adversarial fin
boucle adversarial debut-- num batch  1121
boucle adversarial fin
boucle adversarial debut-- num batch  1122
boucle adversarial fin
boucle adversarial debut-- num batch  1123
boucle adversarial fin
boucle adversarial debut-- num batch  1124
boucle adversarial fin
boucle adversarial debut-- num batch  1125
boucle adversarial fin
boucle adversarial debut-- num batch  1126
boucle adversarial fin
boucle adversarial debut-- num batch  1127
boucle adversarial fin
boucle adversarial debut-- num batch  1128
boucle adversarial fin
boucle adversarial debut-- num batch  1129
boucle adversarial fin
boucle adversarial debut-- num batch  1130
boucle adversarial fin
boucle adversarial debut-- num batch  1131
boucle adversarial fin
boucle adversarial debut-- num batch  1132
boucle adversarial fin
boucle adversarial debut-- num batch  1133
boucle adversarial fin
boucle adversarial debut-- num batch  1134
boucle adversarial fin
boucle adversarial debut-- num batch  1135
boucle adversarial fin
boucle adversarial debut-- num batch  1136
boucle adversarial fin
boucle adversarial debut-- num batch  1137
boucle adversarial fin
boucle adversarial debut-- num batch  1138
boucle adversarial fin
boucle adversarial debut-- num batch  1139
boucle adversarial fin
boucle adversarial debut-- num batch  1140
boucle adversarial fin
boucle adversarial debut-- num batch  1141
boucle adversarial fin
boucle adversarial debut-- num batch  1142
boucle adversarial fin
boucle adversarial debut-- num batch  1143
boucle adversarial fin
boucle adversarial debut-- num batch  1144
boucle adversarial fin
boucle adversarial debut-- num batch  1145
boucle adversarial fin
boucle adversarial debut-- num batch  1146
boucle adversarial fin
boucle adversarial debut-- num batch  1147
boucle adversarial fin
boucle adversarial debut-- num batch  1148
boucle adversarial fin
boucle adversarial debut-- num batch  1149
boucle adversarial fin
boucle adversarial debut-- num batch  1150
boucle adversarial fin
boucle adversarial debut-- num batch  1151
boucle adversarial fin
boucle adversarial debut-- num batch  1152
boucle adversarial fin
boucle adversarial debut-- num batch  1153
boucle adversarial fin
boucle adversarial debut-- num batch  1154
boucle adversarial fin
boucle adversarial debut-- num batch  1155
boucle adversarial fin
boucle adversarial debut-- num batch  1156
boucle adversarial fin
boucle adversarial debut-- num batch  1157
boucle adversarial fin
boucle adversarial debut-- num batch  1158
boucle adversarial fin
boucle adversarial debut-- num batch  1159
boucle adversarial fin
boucle adversarial debut-- num batch  1160
boucle adversarial fin
boucle adversarial debut-- num batch  1161
boucle adversarial fin
boucle adversarial debut-- num batch  1162
boucle adversarial fin
boucle adversarial debut-- num batch  1163
boucle adversarial fin
boucle adversarial debut-- num batch  1164
boucle adversarial fin
boucle adversarial debut-- num batch  1165
boucle adversarial fin
boucle adversarial debut-- num batch  1166
boucle adversarial fin
boucle adversarial debut-- num batch  1167
boucle adversarial fin
boucle adversarial debut-- num batch  1168
boucle adversarial fin
boucle adversarial debut-- num batch  1169
boucle adversarial fin
boucle adversarial debut-- num batch  1170
boucle adversarial fin
boucle adversarial debut-- num batch  1171
boucle adversarial fin
boucle adversarial debut-- num batch  1172
boucle adversarial fin
boucle adversarial debut-- num batch  1173
boucle adversarial fin
boucle adversarial debut-- num batch  1174
boucle adversarial fin
boucle adversarial debut-- num batch  1175
boucle adversarial fin
boucle adversarial debut-- num batch  1176
boucle adversarial fin
boucle adversarial debut-- num batch  1177
boucle adversarial fin
boucle adversarial debut-- num batch  1178
boucle adversarial fin
boucle adversarial debut-- num batch  1179
boucle adversarial fin
boucle adversarial debut-- num batch  1180
boucle adversarial fin
boucle adversarial debut-- num batch  1181
boucle adversarial fin
boucle adversarial debut-- num batch  1182
boucle adversarial fin
boucle adversarial debut-- num batch  1183
boucle adversarial fin
boucle adversarial debut-- num batch  1184
boucle adversarial fin
boucle adversarial debut-- num batch  1185
boucle adversarial fin
boucle adversarial debut-- num batch  1186
boucle adversarial fin
boucle adversarial debut-- num batch  1187
boucle adversarial fin
boucle adversarial debut-- num batch  1188
boucle adversarial fin
boucle adversarial debut-- num batch  1189
boucle adversarial fin
boucle adversarial debut-- num batch  1190
boucle adversarial fin
boucle adversarial debut-- num batch  1191
boucle adversarial fin
boucle adversarial debut-- num batch  1192
boucle adversarial fin
boucle adversarial debut-- num batch  1193
boucle adversarial fin
boucle adversarial debut-- num batch  1194
boucle adversarial fin
boucle adversarial debut-- num batch  1195
boucle adversarial fin
boucle adversarial debut-- num batch  1196
boucle adversarial fin
boucle adversarial debut-- num batch  1197
boucle adversarial fin
boucle adversarial debut-- num batch  1198
boucle adversarial fin
boucle adversarial debut-- num batch  1199
boucle adversarial fin
boucle adversarial debut-- num batch  1200
boucle adversarial fin
boucle adversarial debut-- num batch  1201
boucle adversarial fin
boucle adversarial debut-- num batch  1202
boucle adversarial fin
boucle adversarial debut-- num batch  1203
boucle adversarial fin
boucle adversarial debut-- num batch  1204
boucle adversarial fin
boucle adversarial debut-- num batch  1205
boucle adversarial fin
boucle adversarial debut-- num batch  1206
boucle adversarial fin
boucle adversarial debut-- num batch  1207
boucle adversarial fin
boucle adversarial debut-- num batch  1208
boucle adversarial fin
boucle adversarial debut-- num batch  1209
boucle adversarial fin
boucle adversarial debut-- num batch  1210
boucle adversarial fin
boucle adversarial debut-- num batch  1211
boucle adversarial fin
boucle adversarial debut-- num batch  1212
boucle adversarial fin
boucle adversarial debut-- num batch  1213
boucle adversarial fin
boucle adversarial debut-- num batch  1214
boucle adversarial fin
boucle adversarial debut-- num batch  1215
boucle adversarial fin
boucle adversarial debut-- num batch  1216
boucle adversarial fin
boucle adversarial debut-- num batch  1217
boucle adversarial fin
boucle adversarial debut-- num batch  1218
boucle adversarial fin
boucle adversarial debut-- num batch  1219
boucle adversarial fin
boucle adversarial debut-- num batch  1220
boucle adversarial fin
boucle adversarial debut-- num batch  1221
boucle adversarial fin
boucle adversarial debut-- num batch  1222
boucle adversarial fin
boucle adversarial debut-- num batch  1223
boucle adversarial fin
boucle adversarial debut-- num batch  1224
boucle adversarial fin
boucle adversarial debut-- num batch  1225
boucle adversarial fin
boucle adversarial debut-- num batch  1226
boucle adversarial fin
boucle adversarial debut-- num batch  1227
boucle adversarial fin
boucle adversarial debut-- num batch  1228
boucle adversarial fin
boucle adversarial debut-- num batch  1229
boucle adversarial fin
boucle adversarial debut-- num batch  1230
boucle adversarial fin
boucle adversarial debut-- num batch  1231
boucle adversarial fin
boucle adversarial debut-- num batch  1232
boucle adversarial fin
boucle adversarial debut-- num batch  1233
boucle adversarial fin
boucle adversarial debut-- num batch  1234
boucle adversarial fin
boucle adversarial debut-- num batch  1235
boucle adversarial fin
boucle adversarial debut-- num batch  1236
boucle adversarial fin
boucle adversarial debut-- num batch  1237
boucle adversarial fin
boucle adversarial debut-- num batch  1238
boucle adversarial fin
boucle adversarial debut-- num batch  1239
boucle adversarial fin

boucle adversarial debut-- num batch  1240
boucle adversarial fin
boucle adversarial debut-- num batch  1241
boucle adversarial fin
boucle adversarial debut-- num batch  1242
boucle adversarial fin
boucle adversarial debut-- num batch  1243
boucle adversarial fin
boucle adversarial debut-- num batch  1244
boucle adversarial fin
boucle adversarial debut-- num batch  1245
boucle adversarial fin
boucle adversarial debut-- num batch  1246
boucle adversarial fin
boucle adversarial debut-- num batch  1247
boucle adversarial fin
boucle adversarial debut-- num batch  1248
boucle adversarial fin
boucle adversarial debut-- num batch  1249
boucle adversarial fin
boucle adversarial debut-- num batch  1250
boucle adversarial fin
boucle adversarial debut-- num batch  1251
boucle adversarial fin
boucle adversarial debut-- num batch  1252
boucle adversarial fin
boucle adversarial debut-- num batch  1253
boucle adversarial fin
boucle adversarial debut-- num batch  1254
boucle adversarial fin
boucle adversarial debut-- num batch  1255
boucle adversarial fin
boucle adversarial debut-- num batch  1256
boucle adversarial fin
boucle adversarial debut-- num batch  1257
boucle adversarial fin
boucle adversarial debut-- num batch  1258
boucle adversarial fin
boucle adversarial debut-- num batch  1259
boucle adversarial fin
boucle adversarial debut-- num batch  1260
boucle adversarial fin
boucle adversarial debut-- num batch  1261
boucle adversarial fin
boucle adversarial debut-- num batch  1262
boucle adversarial fin
boucle adversarial debut-- num batch  1263
boucle adversarial fin
boucle adversarial debut-- num batch  1264
boucle adversarial fin
boucle adversarial debut-- num batch  1265
boucle adversarial fin
boucle adversarial debut-- num batch  1266
boucle adversarial fin
boucle adversarial debut-- num batch  1267
boucle adversarial fin
boucle adversarial debut-- num batch  1268
boucle adversarial fin
boucle adversarial debut-- num batch  1269
boucle adversarial fin
boucle adversarial debut-- num batch  1270
boucle adversarial fin
boucle adversarial debut-- num batch  1271
boucle adversarial fin
boucle adversarial debut-- num batch  1272
boucle adversarial fin
boucle adversarial debut-- num batch  1273
boucle adversarial fin
boucle adversarial debut-- num batch  1274
boucle adversarial fin
boucle adversarial debut-- num batch  1275
boucle adversarial fin
boucle adversarial debut-- num batch  1276
boucle adversarial fin
boucle adversarial debut-- num batch  1277
boucle adversarial fin
boucle adversarial debut-- num batch  1278
boucle adversarial fin
boucle adversarial debut-- num batch  1279
boucle adversarial fin
boucle adversarial debut-- num batch  1280
boucle adversarial fin
boucle adversarial debut-- num batch  1281
boucle adversarial fin
boucle adversarial debut-- num batch  1282
boucle adversarial fin
boucle adversarial debut-- num batch  1283
boucle adversarial fin
boucle adversarial debut-- num batch  1284
boucle adversarial fin
boucle adversarial debut-- num batch  1285
boucle adversarial fin
boucle adversarial debut-- num batch  1286
boucle adversarial fin
boucle adversarial debut-- num batch  1287
boucle adversarial fin
boucle adversarial debut-- num batch  1288
boucle adversarial fin
boucle adversarial debut-- num batch  1289
boucle adversarial fin
boucle adversarial debut-- num batch  1290
boucle adversarial fin
boucle adversarial debut-- num batch  1291
boucle adversarial fin
boucle adversarial debut-- num batch  1292
boucle adversarial fin
boucle adversarial debut-- num batch  1293
boucle adversarial fin
boucle adversarial debut-- num batch  1294
boucle adversarial fin
boucle adversarial debut-- num batch  1295
boucle adversarial fin
boucle adversarial debut-- num batch  1296
boucle adversarial fin
boucle adversarial debut-- num batch  1297
boucle adversarial fin
boucle adversarial debut-- num batch  1298
boucle adversarial fin
boucle adversarial debut-- num batch  1299
boucle adversarial fin
boucle adversarial debut-- num batch  1300
boucle adversarial fin
boucle adversarial debut-- num batch  1301
boucle adversarial fin
boucle adversarial debut-- num batch  1302
boucle adversarial fin
boucle adversarial debut-- num batch  1303
boucle adversarial fin
boucle adversarial debut-- num batch  1304
boucle adversarial fin
boucle adversarial debut-- num batch  1305
boucle adversarial fin
boucle adversarial debut-- num batch  1306
boucle adversarial fin
boucle adversarial debut-- num batch  1307
boucle adversarial fin
boucle adversarial debut-- num batch  1308
boucle adversarial fin
boucle adversarial debut-- num batch  1309
boucle adversarial fin
boucle adversarial debut-- num batch  1310
boucle adversarial fin
boucle adversarial debut-- num batch  1311
boucle adversarial fin
boucle adversarial debut-- num batch  1312
boucle adversarial fin
boucle adversarial debut-- num batch  1313
boucle adversarial fin
boucle adversarial debut-- num batch  1314
boucle adversarial fin
boucle adversarial debut-- num batch  1315
boucle adversarial fin
boucle adversarial debut-- num batch  1316
boucle adversarial fin
boucle adversarial debut-- num batch  1317
boucle adversarial fin
boucle adversarial debut-- num batch  1318
boucle adversarial fin
boucle adversarial debut-- num batch  1319
boucle adversarial fin
boucle adversarial debut-- num batch  1320
boucle adversarial fin
boucle adversarial debut-- num batch  1321
boucle adversarial fin
boucle adversarial debut-- num batch  1322
boucle adversarial fin
boucle adversarial debut-- num batch  1323
boucle adversarial fin
boucle adversarial debut-- num batch  1324
boucle adversarial fin
boucle adversarial debut-- num batch  1325
boucle adversarial fin
boucle adversarial debut-- num batch  1326
boucle adversarial fin
boucle adversarial debut-- num batch  1327
boucle adversarial fin
boucle adversarial debut-- num batch  1328
boucle adversarial fin
boucle adversarial debut-- num batch  1329
boucle adversarial fin
boucle adversarial debut-- num batch  1330
boucle adversarial fin
boucle adversarial debut-- num batch  1331
boucle adversarial fin
boucle adversarial debut-- num batch  1332
boucle adversarial fin
boucle adversarial debut-- num batch  1333
boucle adversarial fin
boucle adversarial debut-- num batch  1334
boucle adversarial fin
boucle adversarial debut-- num batch  1335
boucle adversarial fin
boucle adversarial debut-- num batch  1336
boucle adversarial fin
boucle adversarial debut-- num batch  1337
boucle adversarial fin
boucle adversarial debut-- num batch  1338
boucle adversarial fin
boucle adversarial debut-- num batch  1339
boucle adversarial fin
boucle adversarial debut-- num batch  1340
boucle adversarial fin
boucle adversarial debut-- num batch  1341
boucle adversarial fin
boucle adversarial debut-- num batch  1342
boucle adversarial fin
boucle adversarial debut-- num batch  1343
boucle adversarial fin
boucle adversarial debut-- num batch  1344
boucle adversarial fin
boucle adversarial debut-- num batch  1345
boucle adversarial fin
boucle adversarial debut-- num batch  1346
boucle adversarial fin
boucle adversarial debut-- num batch  1347
boucle adversarial fin
boucle adversarial debut-- num batch  1348
boucle adversarial fin
boucle adversarial debut-- num batch  1349
boucle adversarial fin
boucle adversarial debut-- num batch  1350
boucle adversarial fin
boucle adversarial debut-- num batch  1351
boucle adversarial fin
boucle adversarial debut-- num batch  1352
boucle adversarial fin
boucle adversarial debut-- num batch  1353
boucle adversarial fin
boucle adversarial debut-- num batch  1354
boucle adversarial fin
boucle adversarial debut-- num batch  1355
boucle adversarial fin
boucle adversarial debut-- num batch  1356
boucle adversarial fin
boucle adversarial debut-- num batch  1357
boucle adversarial fin
boucle adversarial debut-- num batch  1358
boucle adversarial fin
boucle adversarial debut-- num batch  1359
boucle adversarial fin
boucle adversarial debut-- num batch  1360
boucle adversarial fin
boucle adversarial debut-- num batch  1361
boucle adversarial fin
boucle adversarial debut-- num batch  1362
boucle adversarial fin
boucle adversarial debut-- num batch  1363
boucle adversarial fin
boucle adversarial debut-- num batch  1364

boucle adversarial fin
boucle adversarial debut-- num batch  1365
boucle adversarial fin
boucle adversarial debut-- num batch  1366
boucle adversarial fin
boucle adversarial debut-- num batch  1367
boucle adversarial fin
boucle adversarial debut-- num batch  1368
boucle adversarial fin
boucle adversarial debut-- num batch  1369
boucle adversarial fin
boucle adversarial debut-- num batch  1370
boucle adversarial fin
boucle adversarial debut-- num batch  1371
boucle adversarial fin
boucle adversarial debut-- num batch  1372
boucle adversarial fin
boucle adversarial debut-- num batch  1373
boucle adversarial fin
boucle adversarial debut-- num batch  1374
boucle adversarial fin
boucle adversarial debut-- num batch  1375
boucle adversarial fin
boucle adversarial debut-- num batch  1376
boucle adversarial fin
boucle adversarial debut-- num batch  1377
boucle adversarial fin
boucle adversarial debut-- num batch  1378
boucle adversarial fin
boucle adversarial debut-- num batch  1379
boucle adversarial fin
boucle adversarial debut-- num batch  1380
boucle adversarial fin
boucle adversarial debut-- num batch  1381
boucle adversarial fin
boucle adversarial debut-- num batch  1382
boucle adversarial fin
boucle adversarial debut-- num batch  1383
boucle adversarial fin
boucle adversarial debut-- num batch  1384
boucle adversarial fin
boucle adversarial debut-- num batch  1385
boucle adversarial fin
boucle adversarial debut-- num batch  1386
boucle adversarial fin
boucle adversarial debut-- num batch  1387
boucle adversarial fin
boucle adversarial debut-- num batch  1388
boucle adversarial fin
boucle adversarial debut-- num batch  1389
boucle adversarial fin
boucle adversarial debut-- num batch  1390
boucle adversarial fin
boucle adversarial debut-- num batch  1391
boucle adversarial fin
boucle adversarial debut-- num batch  1392
boucle adversarial fin
boucle adversarial debut-- num batch  1393
boucle adversarial fin
boucle adversarial debut-- num batch  1394
boucle adversarial fin
boucle adversarial debut-- num batch  1395
boucle adversarial fin
boucle adversarial debut-- num batch  1396
boucle adversarial fin
boucle adversarial debut-- num batch  1397
boucle adversarial fin
boucle adversarial debut-- num batch  1398
boucle adversarial fin
boucle adversarial debut-- num batch  1399
boucle adversarial fin
boucle adversarial debut-- num batch  1400
boucle adversarial fin
boucle adversarial debut-- num batch  1401
boucle adversarial fin
boucle adversarial debut-- num batch  1402
boucle adversarial fin
boucle adversarial debut-- num batch  1403
boucle adversarial fin
boucle adversarial debut-- num batch  1404
boucle adversarial fin
boucle adversarial debut-- num batch  1405
boucle adversarial fin
boucle adversarial debut-- num batch  1406
boucle adversarial fin
boucle adversarial debut-- num batch  1407
boucle adversarial fin
boucle adversarial debut-- num batch  1408
boucle adversarial fin
boucle adversarial debut-- num batch  1409
boucle adversarial fin
boucle adversarial debut-- num batch  1410
boucle adversarial fin
boucle adversarial debut-- num batch  1411
boucle adversarial fin
boucle adversarial debut-- num batch  1412
boucle adversarial fin
boucle adversarial debut-- num batch  1413
boucle adversarial fin
boucle adversarial debut-- num batch  1414
boucle adversarial fin
boucle adversarial debut-- num batch  1415
boucle adversarial fin
boucle adversarial debut-- num batch  1416
boucle adversarial fin
boucle adversarial debut-- num batch  1417
boucle adversarial fin
boucle adversarial debut-- num batch  1418
boucle adversarial fin
boucle adversarial debut-- num batch  1419
boucle adversarial fin
boucle adversarial debut-- num batch  1420
boucle adversarial fin
boucle adversarial debut-- num batch  1421
boucle adversarial fin
boucle adversarial debut-- num batch  1422
boucle adversarial fin
boucle adversarial debut-- num batch  1423
boucle adversarial fin
boucle adversarial debut-- num batch  1424
boucle adversarial fin
boucle adversarial debut-- num batch  1425
boucle adversarial fin
boucle adversarial debut-- num batch  1426
boucle adversarial fin
boucle adversarial debut-- num batch  1427
boucle adversarial fin
boucle adversarial debut-- num batch  1428
boucle adversarial fin
boucle adversarial debut-- num batch  1429
boucle adversarial fin
boucle adversarial debut-- num batch  1430
boucle adversarial fin
boucle adversarial debut-- num batch  1431
boucle adversarial fin
boucle adversarial debut-- num batch  1432
boucle adversarial fin
boucle adversarial debut-- num batch  1433
boucle adversarial fin
boucle adversarial debut-- num batch  1434
boucle adversarial fin
boucle adversarial debut-- num batch  1435
boucle adversarial fin
boucle adversarial debut-- num batch  1436
boucle adversarial fin
boucle adversarial debut-- num batch  1437
boucle adversarial fin
boucle adversarial debut-- num batch  1438
boucle adversarial fin
boucle adversarial debut-- num batch  1439
boucle adversarial fin
boucle adversarial debut-- num batch  1440
boucle adversarial fin
boucle adversarial debut-- num batch  1441
boucle adversarial fin
boucle adversarial debut-- num batch  1442
boucle adversarial fin
boucle adversarial debut-- num batch  1443
boucle adversarial fin
boucle adversarial debut-- num batch  1444
boucle adversarial fin
boucle adversarial debut-- num batch  1445
boucle adversarial fin
boucle adversarial debut-- num batch  1446
boucle adversarial fin
boucle adversarial debut-- num batch  1447
boucle adversarial fin
boucle adversarial debut-- num batch  1448
boucle adversarial fin
boucle adversarial debut-- num batch  1449
boucle adversarial fin
boucle adversarial debut-- num batch  1450
boucle adversarial fin
boucle adversarial debut-- num batch  1451
boucle adversarial fin
boucle adversarial debut-- num batch  1452
boucle adversarial fin
boucle adversarial debut-- num batch  1453
boucle adversarial fin
boucle adversarial debut-- num batch  1454
boucle adversarial fin
boucle adversarial debut-- num batch  1455
boucle adversarial fin
boucle adversarial debut-- num batch  1456
boucle adversarial fin
boucle adversarial debut-- num batch  1457
boucle adversarial fin
boucle adversarial debut-- num batch  1458
boucle adversarial fin
boucle adversarial debut-- num batch  1459
boucle adversarial fin
boucle adversarial debut-- num batch  1460
boucle adversarial fin
boucle adversarial debut-- num batch  1461
boucle adversarial fin
boucle adversarial debut-- num batch  1462
boucle adversarial fin
boucle adversarial debut-- num batch  1463
boucle adversarial fin
boucle adversarial debut-- num batch  1464
boucle adversarial fin
boucle adversarial debut-- num batch  1465
boucle adversarial fin
boucle adversarial debut-- num batch  1466
boucle adversarial fin
boucle adversarial debut-- num batch  1467
boucle adversarial fin
boucle adversarial debut-- num batch  1468
boucle adversarial fin
boucle adversarial debut-- num batch  1469
boucle adversarial fin
boucle adversarial debut-- num batch  1470
boucle adversarial fin
boucle adversarial debut-- num batch  1471
boucle adversarial fin
boucle adversarial debut-- num batch  1472
boucle adversarial fin
boucle adversarial debut-- num batch  1473
boucle adversarial fin
boucle adversarial debut-- num batch  1474
boucle adversarial fin
boucle adversarial debut-- num batch  1475
boucle adversarial fin
boucle adversarial debut-- num batch  1476
boucle adversarial fin
boucle adversarial debut-- num batch  1477
boucle adversarial fin
boucle adversarial debut-- num batch  1478
boucle adversarial fin
boucle adversarial debut-- num batch  1479
boucle adversarial fin
boucle adversarial debut-- num batch  1480
boucle adversarial fin
boucle adversarial debut-- num batch  1481
boucle adversarial fin
boucle adversarial debut-- num batch  1482
boucle adversarial fin
boucle adversarial debut-- num batch  1483
boucle adversarial fin
boucle adversarial debut-- num batch  1484
boucle adversarial fin
boucle adversarial debut-- num batch  1485
boucle adversarial fin
boucle adversarial debut-- num batch  1486
boucle adversarial fin
boucle adversarial debut-- num batch  1487
boucle adversarial fin
boucle adversarial debut-- num batch  1488
boucle adversarial fin

boucle adversarial debut-- num batch  1489
boucle adversarial fin
boucle adversarial debut-- num batch  1490
boucle adversarial fin
boucle adversarial debut-- num batch  1491
boucle adversarial fin
boucle adversarial debut-- num batch  1492
boucle adversarial fin
boucle adversarial debut-- num batch  1493
boucle adversarial fin
boucle adversarial debut-- num batch  1494
boucle adversarial fin
boucle adversarial debut-- num batch  1495
boucle adversarial fin
boucle adversarial debut-- num batch  1496
boucle adversarial fin
boucle adversarial debut-- num batch  1497
boucle adversarial fin
boucle adversarial debut-- num batch  1498
boucle adversarial fin
boucle adversarial debut-- num batch  1499
boucle adversarial fin
boucle adversarial debut-- num batch  1500
boucle adversarial fin
boucle adversarial debut-- num batch  1501
boucle adversarial fin
boucle adversarial debut-- num batch  1502
boucle adversarial fin
boucle adversarial debut-- num batch  1503
boucle adversarial fin
boucle adversarial debut-- num batch  1504
boucle adversarial fin
boucle adversarial debut-- num batch  1505
boucle adversarial fin
boucle adversarial debut-- num batch  1506
boucle adversarial fin
boucle adversarial debut-- num batch  1507
boucle adversarial fin
boucle adversarial debut-- num batch  1508
boucle adversarial fin
boucle adversarial debut-- num batch  1509
boucle adversarial fin
boucle adversarial debut-- num batch  1510
boucle adversarial fin
boucle adversarial debut-- num batch  1511
boucle adversarial fin
boucle adversarial debut-- num batch  1512
boucle adversarial fin
boucle adversarial debut-- num batch  1513
boucle adversarial fin
boucle adversarial debut-- num batch  1514
boucle adversarial fin
boucle adversarial debut-- num batch  1515
boucle adversarial fin
boucle adversarial debut-- num batch  1516
boucle adversarial fin
boucle adversarial debut-- num batch  1517
boucle adversarial fin
boucle adversarial debut-- num batch  1518
boucle adversarial fin
boucle adversarial debut-- num batch  1519
boucle adversarial fin
boucle adversarial debut-- num batch  1520
boucle adversarial fin
boucle adversarial debut-- num batch  1521
boucle adversarial fin
boucle adversarial debut-- num batch  1522
boucle adversarial fin
boucle adversarial debut-- num batch  1523
boucle adversarial fin
boucle adversarial debut-- num batch  1524
boucle adversarial fin
boucle adversarial debut-- num batch  1525
boucle adversarial fin
boucle adversarial debut-- num batch  1526
boucle adversarial fin
boucle adversarial debut-- num batch  1527
boucle adversarial fin
boucle adversarial debut-- num batch  1528
boucle adversarial fin
boucle adversarial debut-- num batch  1529
boucle adversarial fin
boucle adversarial debut-- num batch  1530
boucle adversarial fin
boucle adversarial debut-- num batch  1531
boucle adversarial fin
boucle adversarial debut-- num batch  1532
boucle adversarial fin
boucle adversarial debut-- num batch  1533
boucle adversarial fin
boucle adversarial debut-- num batch  1534
boucle adversarial fin
boucle adversarial debut-- num batch  1535
boucle adversarial fin
boucle adversarial debut-- num batch  1536
boucle adversarial fin
boucle adversarial debut-- num batch  1537
boucle adversarial fin
boucle adversarial debut-- num batch  1538
boucle adversarial fin
boucle adversarial debut-- num batch  1539
boucle adversarial fin
boucle adversarial debut-- num batch  1540
boucle adversarial fin
boucle adversarial debut-- num batch  1541
boucle adversarial fin
boucle adversarial debut-- num batch  1542
boucle adversarial fin
boucle adversarial debut-- num batch  1543
boucle adversarial fin
boucle adversarial debut-- num batch  1544
boucle adversarial fin
boucle adversarial debut-- num batch  1545
boucle adversarial fin
boucle adversarial debut-- num batch  1546
boucle adversarial fin
boucle adversarial debut-- num batch  1547
boucle adversarial fin
boucle adversarial debut-- num batch  1548
boucle adversarial fin
boucle adversarial debut-- num batch  1549
boucle adversarial fin
boucle adversarial debut-- num batch  1550
boucle adversarial fin
boucle adversarial debut-- num batch  1551
boucle adversarial fin
boucle adversarial debut-- num batch  1552
boucle adversarial fin
boucle adversarial debut-- num batch  1553
boucle adversarial fin
boucle adversarial debut-- num batch  1554
boucle adversarial fin
boucle adversarial debut-- num batch  1555
boucle adversarial fin
boucle adversarial debut-- num batch  1556
boucle adversarial fin
boucle adversarial debut-- num batch  1557
boucle adversarial fin
boucle adversarial debut-- num batch  1558
boucle adversarial fin
boucle adversarial debut-- num batch  1559
boucle adversarial fin
boucle adversarial debut-- num batch  1560
boucle adversarial fin
boucle adversarial debut-- num batch  1561
boucle adversarial fin
boucle adversarial debut-- num batch  1562
boucle adversarial fin
boucle adversarial debut-- num batch  1563
boucle adversarial fin
boucle adversarial debut-- num batch  1564
boucle adversarial fin
boucle adversarial debut-- num batch  1565
boucle adversarial fin
boucle adversarial debut-- num batch  1566
boucle adversarial fin
boucle adversarial debut-- num batch  1567
boucle adversarial fin
boucle adversarial debut-- num batch  1568
boucle adversarial fin
boucle adversarial debut-- num batch  1569
boucle adversarial fin
boucle adversarial debut-- num batch  1570
boucle adversarial fin
boucle adversarial debut-- num batch  1571
boucle adversarial fin
boucle adversarial debut-- num batch  1572
boucle adversarial fin
boucle adversarial debut-- num batch  1573
boucle adversarial fin
boucle adversarial debut-- num batch  1574
boucle adversarial fin
boucle adversarial debut-- num batch  1575
boucle adversarial fin
boucle adversarial debut-- num batch  1576
boucle adversarial fin
boucle adversarial debut-- num batch  1577
boucle adversarial fin
boucle adversarial debut-- num batch  1578
boucle adversarial fin
boucle adversarial debut-- num batch  1579
boucle adversarial fin
boucle adversarial debut-- num batch  1580
boucle adversarial fin
boucle adversarial debut-- num batch  1581
boucle adversarial fin
boucle adversarial debut-- num batch  1582
boucle adversarial fin
boucle adversarial debut-- num batch  1583
boucle adversarial fin
boucle adversarial debut-- num batch  1584
boucle adversarial fin
boucle adversarial debut-- num batch  1585
boucle adversarial fin
boucle adversarial debut-- num batch  1586
boucle adversarial fin
boucle adversarial debut-- num batch  1587
boucle adversarial fin
boucle adversarial debut-- num batch  1588
boucle adversarial fin
boucle adversarial debut-- num batch  1589
boucle adversarial fin
boucle adversarial debut-- num batch  1590
boucle adversarial fin
boucle adversarial debut-- num batch  1591
boucle adversarial fin
boucle adversarial debut-- num batch  1592
boucle adversarial fin
boucle adversarial debut-- num batch  1593
boucle adversarial fin
boucle adversarial debut-- num batch  1594
boucle adversarial fin
boucle adversarial debut-- num batch  1595
boucle adversarial fin
boucle adversarial debut-- num batch  1596
boucle adversarial fin
boucle adversarial debut-- num batch  1597
boucle adversarial fin
boucle adversarial debut-- num batch  1598
boucle adversarial fin
boucle adversarial debut-- num batch  1599
boucle adversarial fin
boucle adversarial debut-- num batch  1600
boucle adversarial fin
boucle adversarial debut-- num batch  1601
boucle adversarial fin
boucle adversarial debut-- num batch  1602
boucle adversarial fin
boucle adversarial debut-- num batch  1603
boucle adversarial fin
boucle adversarial debut-- num batch  1604
boucle adversarial fin
boucle adversarial debut-- num batch  1605
boucle adversarial fin
boucle adversarial debut-- num batch  1606
boucle adversarial fin
boucle adversarial debut-- num batch  1607
boucle adversarial fin
boucle adversarial debut-- num batch  1608
boucle adversarial fin
boucle adversarial debut-- num batch  1609
boucle adversarial fin
boucle adversarial debut-- num batch  1610
boucle adversarial fin
boucle adversarial debut-- num batch  1611
boucle adversarial fin
boucle adversarial debut-- num batch  1612
boucle adversarial fin
boucle adversarial debut-- num batch  1613

boucle adversarial fin
boucle adversarial debut-- num batch  1614
boucle adversarial fin
boucle adversarial debut-- num batch  1615
boucle adversarial fin
boucle adversarial debut-- num batch  1616
boucle adversarial fin
boucle adversarial debut-- num batch  1617
boucle adversarial fin
boucle adversarial debut-- num batch  1618
boucle adversarial fin
boucle adversarial debut-- num batch  1619
boucle adversarial fin
boucle adversarial debut-- num batch  1620
boucle adversarial fin
boucle adversarial debut-- num batch  1621
boucle adversarial fin
boucle adversarial debut-- num batch  1622
boucle adversarial fin
boucle adversarial debut-- num batch  1623
boucle adversarial fin
boucle adversarial debut-- num batch  1624
boucle adversarial fin
boucle adversarial debut-- num batch  1625
boucle adversarial fin
boucle adversarial debut-- num batch  1626
boucle adversarial fin
boucle adversarial debut-- num batch  1627
boucle adversarial fin
boucle adversarial debut-- num batch  1628
boucle adversarial fin
boucle adversarial debut-- num batch  1629
boucle adversarial fin
boucle adversarial debut-- num batch  1630
boucle adversarial fin
boucle adversarial debut-- num batch  1631
boucle adversarial fin
boucle adversarial debut-- num batch  1632
boucle adversarial fin
boucle adversarial debut-- num batch  1633
boucle adversarial fin
boucle adversarial debut-- num batch  1634
boucle adversarial fin
boucle adversarial debut-- num batch  1635
boucle adversarial fin
boucle adversarial debut-- num batch  1636
boucle adversarial fin
boucle adversarial debut-- num batch  1637
boucle adversarial fin
boucle adversarial debut-- num batch  1638
boucle adversarial fin
boucle adversarial debut-- num batch  1639
boucle adversarial fin
boucle adversarial debut-- num batch  1640
boucle adversarial fin
boucle adversarial debut-- num batch  1641
boucle adversarial fin
boucle adversarial debut-- num batch  1642
boucle adversarial fin
boucle adversarial debut-- num batch  1643
boucle adversarial fin
boucle adversarial debut-- num batch  1644
boucle adversarial fin
boucle adversarial debut-- num batch  1645
boucle adversarial fin
boucle adversarial debut-- num batch  1646
boucle adversarial fin
boucle adversarial debut-- num batch  1647
boucle adversarial fin
boucle adversarial debut-- num batch  1648
boucle adversarial fin
boucle adversarial debut-- num batch  1649
boucle adversarial fin
boucle adversarial debut-- num batch  1650
boucle adversarial fin
boucle adversarial debut-- num batch  1651
boucle adversarial fin
boucle adversarial debut-- num batch  1652
boucle adversarial fin
boucle adversarial debut-- num batch  1653
boucle adversarial fin
boucle adversarial debut-- num batch  1654
boucle adversarial fin
boucle adversarial debut-- num batch  1655
boucle adversarial fin
boucle adversarial debut-- num batch  1656
boucle adversarial fin
boucle adversarial debut-- num batch  1657
boucle adversarial fin
boucle adversarial debut-- num batch  1658
boucle adversarial fin
boucle adversarial debut-- num batch  1659
boucle adversarial fin
boucle adversarial debut-- num batch  1660
boucle adversarial fin
boucle adversarial debut-- num batch  1661
boucle adversarial fin
boucle adversarial debut-- num batch  1662
boucle adversarial fin
boucle adversarial debut-- num batch  1663
boucle adversarial fin
boucle adversarial debut-- num batch  1664
boucle adversarial fin
boucle adversarial debut-- num batch  1665
boucle adversarial fin
boucle adversarial debut-- num batch  1666
boucle adversarial fin
boucle adversarial debut-- num batch  1667
boucle adversarial fin
boucle adversarial debut-- num batch  1668
boucle adversarial fin
boucle adversarial debut-- num batch  1669
boucle adversarial fin
boucle adversarial debut-- num batch  1670
boucle adversarial fin
boucle adversarial debut-- num batch  1671
boucle adversarial fin
boucle adversarial debut-- num batch  1672
boucle adversarial fin
boucle adversarial debut-- num batch  1673
boucle adversarial fin
boucle adversarial debut-- num batch  1674
boucle adversarial fin
boucle adversarial debut-- num batch  1675
boucle adversarial fin
boucle adversarial debut-- num batch  1676
boucle adversarial fin
boucle adversarial debut-- num batch  1677
boucle adversarial fin
boucle adversarial debut-- num batch  1678
boucle adversarial fin
boucle adversarial debut-- num batch  1679
boucle adversarial fin
boucle adversarial debut-- num batch  1680
boucle adversarial fin
boucle adversarial debut-- num batch  1681
boucle adversarial fin
boucle adversarial debut-- num batch  1682
boucle adversarial fin
boucle adversarial debut-- num batch  1683
boucle adversarial fin
boucle adversarial debut-- num batch  1684
boucle adversarial fin
boucle adversarial debut-- num batch  1685
boucle adversarial fin
boucle adversarial debut-- num batch  1686
boucle adversarial fin
boucle adversarial debut-- num batch  1687
boucle adversarial fin
boucle adversarial debut-- num batch  1688
boucle adversarial fin
boucle adversarial debut-- num batch  1689
boucle adversarial fin
boucle adversarial debut-- num batch  1690
boucle adversarial fin
boucle adversarial debut-- num batch  1691
boucle adversarial fin
boucle adversarial debut-- num batch  1692
boucle adversarial fin
boucle adversarial debut-- num batch  1693
boucle adversarial fin
boucle adversarial debut-- num batch  1694
boucle adversarial fin
boucle adversarial debut-- num batch  1695
boucle adversarial fin
boucle adversarial debut-- num batch  1696
boucle adversarial fin
boucle adversarial debut-- num batch  1697
boucle adversarial fin
boucle adversarial debut-- num batch  1698
boucle adversarial fin
boucle adversarial debut-- num batch  1699
boucle adversarial fin
boucle adversarial debut-- num batch  1700
boucle adversarial fin
boucle adversarial debut-- num batch  1701
boucle adversarial fin
boucle adversarial debut-- num batch  1702
boucle adversarial fin
boucle adversarial debut-- num batch  1703
boucle adversarial fin
boucle adversarial debut-- num batch  1704
boucle adversarial fin
boucle adversarial debut-- num batch  1705
boucle adversarial fin
boucle adversarial debut-- num batch  1706
boucle adversarial fin
boucle adversarial debut-- num batch  1707
boucle adversarial fin
boucle adversarial debut-- num batch  1708
boucle adversarial fin
boucle adversarial debut-- num batch  1709
boucle adversarial fin
boucle adversarial debut-- num batch  1710
boucle adversarial fin
boucle adversarial debut-- num batch  1711
boucle adversarial fin
boucle adversarial debut-- num batch  1712
boucle adversarial fin
boucle adversarial debut-- num batch  1713
boucle adversarial fin
boucle adversarial debut-- num batch  1714
boucle adversarial fin
boucle adversarial debut-- num batch  1715
boucle adversarial fin
boucle adversarial debut-- num batch  1716
boucle adversarial fin
boucle adversarial debut-- num batch  1717
boucle adversarial fin
boucle adversarial debut-- num batch  1718
boucle adversarial fin
boucle adversarial debut-- num batch  1719
boucle adversarial fin
boucle adversarial debut-- num batch  1720
boucle adversarial fin
boucle adversarial debut-- num batch  1721
boucle adversarial fin
boucle adversarial debut-- num batch  1722
boucle adversarial fin
boucle adversarial debut-- num batch  1723
boucle adversarial fin
boucle adversarial debut-- num batch  1724
boucle adversarial fin
boucle adversarial debut-- num batch  1725
boucle adversarial fin
boucle adversarial debut-- num batch  1726
boucle adversarial fin
boucle adversarial debut-- num batch  1727
boucle adversarial fin
boucle adversarial debut-- num batch  1728
boucle adversarial fin
boucle adversarial debut-- num batch  1729
boucle adversarial fin
boucle adversarial debut-- num batch  1730
boucle adversarial fin
boucle adversarial debut-- num batch  1731
boucle adversarial fin
boucle adversarial debut-- num batch  1732
boucle adversarial fin
boucle adversarial debut-- num batch  1733
boucle adversarial fin
boucle adversarial debut-- num batch  1734
boucle adversarial fin
boucle adversarial debut-- num batch  1735
boucle adversarial fin
boucle adversarial debut-- num batch  1736
boucle adversarial fin
boucle adversarial debut-- num batch  1737
boucle adversarial fin
boucle adversarial debut-- num batch  1738

boucle adversarial fin
boucle adversarial debut-- num batch  1739
boucle adversarial fin
boucle adversarial debut-- num batch  1740
boucle adversarial fin
boucle adversarial debut-- num batch  1741
boucle adversarial fin
boucle adversarial debut-- num batch  1742
boucle adversarial fin
boucle adversarial debut-- num batch  1743
boucle adversarial fin
boucle adversarial debut-- num batch  1744
boucle adversarial fin
boucle adversarial debut-- num batch  1745
boucle adversarial fin
boucle adversarial debut-- num batch  1746
boucle adversarial fin
boucle adversarial debut-- num batch  1747
boucle adversarial fin
boucle adversarial debut-- num batch  1748
boucle adversarial fin
boucle adversarial debut-- num batch  1749
boucle adversarial fin
boucle adversarial debut-- num batch  1750
boucle adversarial fin
boucle adversarial debut-- num batch  1751
boucle adversarial fin
boucle adversarial debut-- num batch  1752
boucle adversarial fin
boucle adversarial debut-- num batch  1753
boucle adversarial fin
boucle adversarial debut-- num batch  1754
boucle adversarial fin
boucle adversarial debut-- num batch  1755
boucle adversarial fin
boucle adversarial debut-- num batch  1756
boucle adversarial fin
boucle adversarial debut-- num batch  1757
boucle adversarial fin
boucle adversarial debut-- num batch  1758
boucle adversarial fin
boucle adversarial debut-- num batch  1759
boucle adversarial fin
boucle adversarial debut-- num batch  1760
boucle adversarial fin
boucle adversarial debut-- num batch  1761
boucle adversarial fin
boucle adversarial debut-- num batch  1762
boucle adversarial fin
boucle adversarial debut-- num batch  1763
boucle adversarial fin
boucle adversarial debut-- num batch  1764
boucle adversarial fin
boucle adversarial debut-- num batch  1765
boucle adversarial fin
boucle adversarial debut-- num batch  1766
boucle adversarial fin
boucle adversarial debut-- num batch  1767
boucle adversarial fin
boucle adversarial debut-- num batch  1768
boucle adversarial fin
boucle adversarial debut-- num batch  1769
boucle adversarial fin
boucle adversarial debut-- num batch  1770
boucle adversarial fin
boucle adversarial debut-- num batch  1771
boucle adversarial fin
boucle adversarial debut-- num batch  1772
boucle adversarial fin
boucle adversarial debut-- num batch  1773
boucle adversarial fin
boucle adversarial debut-- num batch  1774
boucle adversarial fin
boucle adversarial debut-- num batch  1775
boucle adversarial fin
boucle adversarial debut-- num batch  1776
boucle adversarial fin
boucle adversarial debut-- num batch  1777
boucle adversarial fin
boucle adversarial debut-- num batch  1778
boucle adversarial fin
boucle adversarial debut-- num batch  1779
boucle adversarial fin
boucle adversarial debut-- num batch  1780
boucle adversarial fin
boucle adversarial debut-- num batch  1781
boucle adversarial fin
boucle adversarial debut-- num batch  1782
boucle adversarial fin
boucle adversarial debut-- num batch  1783
boucle adversarial fin
boucle adversarial debut-- num batch  1784
boucle adversarial fin
boucle adversarial debut-- num batch  1785
boucle adversarial fin
boucle adversarial debut-- num batch  1786
boucle adversarial fin
boucle adversarial debut-- num batch  1787
boucle adversarial fin
boucle adversarial debut-- num batch  1788
boucle adversarial fin
boucle adversarial debut-- num batch  1789
boucle adversarial fin
boucle adversarial debut-- num batch  1790
boucle adversarial fin
boucle adversarial debut-- num batch  1791
boucle adversarial fin
boucle adversarial debut-- num batch  1792
boucle adversarial fin
boucle adversarial debut-- num batch  1793
boucle adversarial fin
boucle adversarial debut-- num batch  1794
boucle adversarial fin
boucle adversarial debut-- num batch  1795
boucle adversarial fin
boucle adversarial debut-- num batch  1796
boucle adversarial fin
boucle adversarial debut-- num batch  1797
boucle adversarial fin
boucle adversarial debut-- num batch  1798
boucle adversarial fin
boucle adversarial debut-- num batch  1799
boucle adversarial fin
boucle adversarial debut-- num batch  1800
boucle adversarial fin
boucle adversarial debut-- num batch  1801
boucle adversarial fin
boucle adversarial debut-- num batch  1802
boucle adversarial fin
boucle adversarial debut-- num batch  1803
boucle adversarial fin
boucle adversarial debut-- num batch  1804
boucle adversarial fin
boucle adversarial debut-- num batch  1805
boucle adversarial fin
boucle adversarial debut-- num batch  1806
boucle adversarial fin
boucle adversarial debut-- num batch  1807
boucle adversarial fin
boucle adversarial debut-- num batch  1808
boucle adversarial fin
boucle adversarial debut-- num batch  1809
boucle adversarial fin
boucle adversarial debut-- num batch  1810
boucle adversarial fin
boucle adversarial debut-- num batch  1811
boucle adversarial fin
boucle adversarial debut-- num batch  1812
boucle adversarial fin
boucle adversarial debut-- num batch  1813
boucle adversarial fin
boucle adversarial debut-- num batch  1814
boucle adversarial fin
boucle adversarial debut-- num batch  1815
boucle adversarial fin
boucle adversarial debut-- num batch  1816
boucle adversarial fin
boucle adversarial debut-- num batch  1817
boucle adversarial fin
boucle adversarial debut-- num batch  1818
boucle adversarial fin
boucle adversarial debut-- num batch  1819
boucle adversarial fin
boucle adversarial debut-- num batch  1820
boucle adversarial fin
boucle adversarial debut-- num batch  1821
boucle adversarial fin
boucle adversarial debut-- num batch  1822
boucle adversarial fin
boucle adversarial debut-- num batch  1823
boucle adversarial fin
boucle adversarial debut-- num batch  1824
boucle adversarial fin
boucle adversarial debut-- num batch  1825
boucle adversarial fin
boucle adversarial debut-- num batch  1826
boucle adversarial fin
boucle adversarial debut-- num batch  1827
boucle adversarial fin
boucle adversarial debut-- num batch  1828
boucle adversarial fin
boucle adversarial debut-- num batch  1829
boucle adversarial fin
boucle adversarial debut-- num batch  1830
boucle adversarial fin
boucle adversarial debut-- num batch  1831
boucle adversarial fin
boucle adversarial debut-- num batch  1832
boucle adversarial fin
boucle adversarial debut-- num batch  1833
boucle adversarial fin
boucle adversarial debut-- num batch  1834
boucle adversarial fin
boucle adversarial debut-- num batch  1835
boucle adversarial fin
boucle adversarial debut-- num batch  1836
boucle adversarial fin
boucle adversarial debut-- num batch  1837
boucle adversarial fin
boucle adversarial debut-- num batch  1838
boucle adversarial fin
boucle adversarial debut-- num batch  1839
boucle adversarial fin
boucle adversarial debut-- num batch  1840
boucle adversarial fin
boucle adversarial debut-- num batch  1841
boucle adversarial fin
boucle adversarial debut-- num batch  1842
boucle adversarial fin
boucle adversarial debut-- num batch  1843
boucle adversarial fin
boucle adversarial debut-- num batch  1844
boucle adversarial fin
boucle adversarial debut-- num batch  1845
boucle adversarial fin
boucle adversarial debut-- num batch  1846
boucle adversarial fin
boucle adversarial debut-- num batch  1847
boucle adversarial fin
boucle adversarial debut-- num batch  1848
boucle adversarial fin
boucle adversarial debut-- num batch  1849
boucle adversarial fin
boucle adversarial debut-- num batch  1850
boucle adversarial fin
boucle adversarial debut-- num batch  1851
boucle adversarial fin
boucle adversarial debut-- num batch  1852
boucle adversarial fin
boucle adversarial debut-- num batch  1853
boucle adversarial fin
boucle adversarial debut-- num batch  1854
boucle adversarial fin
boucle adversarial debut-- num batch  1855
boucle adversarial fin
boucle adversarial debut-- num batch  1856
boucle adversarial fin
boucle adversarial debut-- num batch  1857
boucle adversarial fin
boucle adversarial debut-- num batch  1858
boucle adversarial fin
boucle adversarial debut-- num batch  1859
boucle adversarial fin
boucle adversarial debut-- num batch  1860
boucle adversarial fin
boucle adversarial debut-- num batch  1861
boucle adversarial fin
boucle adversarial debut-- num batch  1862
boucle adversarial fin

boucle adversarial debut-- num batch  1863
boucle adversarial fin
boucle adversarial debut-- num batch  1864
boucle adversarial fin
boucle adversarial debut-- num batch  1865
boucle adversarial fin
boucle adversarial debut-- num batch  1866
boucle adversarial fin
boucle adversarial debut-- num batch  1867
boucle adversarial fin
boucle adversarial debut-- num batch  1868
boucle adversarial fin
boucle adversarial debut-- num batch  1869
boucle adversarial fin
boucle adversarial debut-- num batch  1870
boucle adversarial fin
boucle adversarial debut-- num batch  1871
boucle adversarial fin
boucle adversarial debut-- num batch  1872
boucle adversarial fin
boucle adversarial debut-- num batch  1873
boucle adversarial fin
boucle adversarial debut-- num batch  1874
boucle adversarial fin
boucle adversarial debut-- num batch  1875
boucle adversarial fin
boucle adversarial debut-- num batch  1876
boucle adversarial fin
boucle adversarial debut-- num batch  1877
boucle adversarial fin
boucle adversarial debut-- num batch  1878
boucle adversarial fin
boucle adversarial debut-- num batch  1879
boucle adversarial fin
boucle adversarial debut-- num batch  1880
boucle adversarial fin
boucle adversarial debut-- num batch  1881
boucle adversarial fin
boucle adversarial debut-- num batch  1882
boucle adversarial fin
boucle adversarial debut-- num batch  1883
boucle adversarial fin
boucle adversarial debut-- num batch  1884
boucle adversarial fin
boucle adversarial debut-- num batch  1885
boucle adversarial fin
boucle adversarial debut-- num batch  1886
boucle adversarial fin
boucle adversarial debut-- num batch  1887
boucle adversarial fin
boucle adversarial debut-- num batch  1888
boucle adversarial fin
boucle adversarial debut-- num batch  1889
boucle adversarial fin
boucle adversarial debut-- num batch  1890
boucle adversarial fin
boucle adversarial debut-- num batch  1891
boucle adversarial fin
boucle adversarial debut-- num batch  1892
boucle adversarial fin
boucle adversarial debut-- num batch  1893
boucle adversarial fin
boucle adversarial debut-- num batch  1894
boucle adversarial fin
boucle adversarial debut-- num batch  1895
boucle adversarial fin
boucle adversarial debut-- num batch  1896
boucle adversarial fin
boucle adversarial debut-- num batch  1897
boucle adversarial fin
boucle adversarial debut-- num batch  1898
boucle adversarial fin
boucle adversarial debut-- num batch  1899
boucle adversarial fin
boucle adversarial debut-- num batch  1900
boucle adversarial fin
boucle adversarial debut-- num batch  1901
boucle adversarial fin
boucle adversarial debut-- num batch  1902
boucle adversarial fin
boucle adversarial debut-- num batch  1903
boucle adversarial fin
boucle adversarial debut-- num batch  1904
boucle adversarial fin
boucle adversarial debut-- num batch  1905
boucle adversarial fin
boucle adversarial debut-- num batch  1906
boucle adversarial fin
boucle adversarial debut-- num batch  1907
boucle adversarial fin
boucle adversarial debut-- num batch  1908
boucle adversarial fin
boucle adversarial debut-- num batch  1909
boucle adversarial fin
boucle adversarial debut-- num batch  1910
boucle adversarial fin
boucle adversarial debut-- num batch  1911
boucle adversarial fin
boucle adversarial debut-- num batch  1912
boucle adversarial fin
boucle adversarial debut-- num batch  1913
boucle adversarial fin
boucle adversarial debut-- num batch  1914
boucle adversarial fin
boucle adversarial debut-- num batch  1915
boucle adversarial fin
boucle adversarial debut-- num batch  1916
boucle adversarial fin
boucle adversarial debut-- num batch  1917
boucle adversarial fin
boucle adversarial debut-- num batch  1918
boucle adversarial fin
boucle adversarial debut-- num batch  1919
boucle adversarial fin
boucle adversarial debut-- num batch  1920
boucle adversarial fin
boucle adversarial debut-- num batch  1921
boucle adversarial fin
boucle adversarial debut-- num batch  1922
boucle adversarial fin
boucle adversarial debut-- num batch  1923
boucle adversarial fin
boucle adversarial debut-- num batch  1924
boucle adversarial fin
boucle adversarial debut-- num batch  1925
boucle adversarial fin
boucle adversarial debut-- num batch  1926
boucle adversarial fin
boucle adversarial debut-- num batch  1927
boucle adversarial fin
boucle adversarial debut-- num batch  1928
boucle adversarial fin
boucle adversarial debut-- num batch  1929
boucle adversarial fin
boucle adversarial debut-- num batch  1930
boucle adversarial fin
boucle adversarial debut-- num batch  1931
boucle adversarial fin
boucle adversarial debut-- num batch  1932
boucle adversarial fin
boucle adversarial debut-- num batch  1933
boucle adversarial fin
boucle adversarial debut-- num batch  1934
boucle adversarial fin
boucle adversarial debut-- num batch  1935
boucle adversarial fin
boucle adversarial debut-- num batch  1936
boucle adversarial fin
boucle adversarial debut-- num batch  1937
boucle adversarial fin
boucle adversarial debut-- num batch  1938
boucle adversarial fin
boucle adversarial debut-- num batch  1939
boucle adversarial fin
boucle adversarial debut-- num batch  1940
boucle adversarial fin
boucle adversarial debut-- num batch  1941
boucle adversarial fin
boucle adversarial debut-- num batch  1942
boucle adversarial fin
boucle adversarial debut-- num batch  1943
boucle adversarial fin
boucle adversarial debut-- num batch  1944
boucle adversarial fin
boucle adversarial debut-- num batch  1945
boucle adversarial fin
boucle adversarial debut-- num batch  1946
boucle adversarial fin
boucle adversarial debut-- num batch  1947
boucle adversarial fin
boucle adversarial debut-- num batch  1948
boucle adversarial fin
boucle adversarial debut-- num batch  1949
boucle adversarial fin
boucle adversarial debut-- num batch  1950
boucle adversarial fin
boucle adversarial debut-- num batch  1951
boucle adversarial fin
boucle adversarial debut-- num batch  1952
boucle adversarial fin
boucle adversarial debut-- num batch  1953
boucle adversarial fin
boucle adversarial debut-- num batch  1954
boucle adversarial fin
boucle adversarial debut-- num batch  1955
boucle adversarial fin
boucle adversarial debut-- num batch  1956
boucle adversarial fin
boucle adversarial debut-- num batch  1957
boucle adversarial fin
boucle adversarial debut-- num batch  1958
boucle adversarial fin
boucle adversarial debut-- num batch  1959
boucle adversarial fin
boucle adversarial debut-- num batch  1960
boucle adversarial fin
boucle adversarial debut-- num batch  1961
boucle adversarial fin
boucle adversarial debut-- num batch  1962
boucle adversarial fin
boucle adversarial debut-- num batch  1963
boucle adversarial fin
boucle adversarial debut-- num batch  1964
boucle adversarial fin
boucle adversarial debut-- num batch  1965
boucle adversarial fin
boucle adversarial debut-- num batch  1966
boucle adversarial fin
boucle adversarial debut-- num batch  1967
boucle adversarial fin
boucle adversarial debut-- num batch  1968
boucle adversarial fin
boucle adversarial debut-- num batch  1969
boucle adversarial fin
boucle adversarial debut-- num batch  1970
boucle adversarial fin
boucle adversarial debut-- num batch  1971
boucle adversarial fin
boucle adversarial debut-- num batch  1972
boucle adversarial fin
boucle adversarial debut-- num batch  1973
boucle adversarial fin
boucle adversarial debut-- num batch  1974
boucle adversarial fin
boucle adversarial debut-- num batch  1975
boucle adversarial fin
boucle adversarial debut-- num batch  1976
boucle adversarial fin
boucle adversarial debut-- num batch  1977
boucle adversarial fin
boucle adversarial debut-- num batch  1978
boucle adversarial fin
boucle adversarial debut-- num batch  1979
boucle adversarial fin
boucle adversarial debut-- num batch  1980
boucle adversarial fin
boucle adversarial debut-- num batch  1981
boucle adversarial fin
boucle adversarial debut-- num batch  1982
boucle adversarial fin
boucle adversarial debut-- num batch  1983
boucle adversarial fin
boucle adversarial debut-- num batch  1984
boucle adversarial fin
boucle adversarial debut-- num batch  1985
boucle adversarial fin
boucle adversarial debut-- num batch  1986
boucle adversarial fin
boucle adversarial debut-- num batch  1987

boucle adversarial fin
boucle adversarial debut-- num batch  1988
boucle adversarial fin
boucle adversarial debut-- num batch  1989
boucle adversarial fin
boucle adversarial debut-- num batch  1990
boucle adversarial fin
boucle adversarial debut-- num batch  1991
boucle adversarial fin
boucle adversarial debut-- num batch  1992
boucle adversarial fin
boucle adversarial debut-- num batch  1993
boucle adversarial fin
boucle adversarial debut-- num batch  1994
boucle adversarial fin
boucle adversarial debut-- num batch  1995
boucle adversarial fin
boucle adversarial debut-- num batch  1996
boucle adversarial fin
boucle adversarial debut-- num batch  1997
boucle adversarial fin
boucle adversarial debut-- num batch  1998
boucle adversarial fin
boucle adversarial debut-- num batch  1999
boucle adversarial fin
boucle adversarial debut-- num batch  2000
boucle adversarial fin
boucle adversarial debut-- num batch  2001
boucle adversarial fin
boucle adversarial debut-- num batch  2002
boucle adversarial fin
boucle adversarial debut-- num batch  2003
boucle adversarial fin
boucle adversarial debut-- num batch  2004
boucle adversarial fin
boucle adversarial debut-- num batch  2005
boucle adversarial fin
boucle adversarial debut-- num batch  2006
boucle adversarial fin
boucle adversarial debut-- num batch  2007
boucle adversarial fin
boucle adversarial debut-- num batch  2008
boucle adversarial fin
boucle adversarial debut-- num batch  2009
boucle adversarial fin
boucle adversarial debut-- num batch  2010
boucle adversarial fin
boucle adversarial debut-- num batch  2011
boucle adversarial fin
boucle adversarial debut-- num batch  2012
boucle adversarial fin
boucle adversarial debut-- num batch  2013
boucle adversarial fin
boucle adversarial debut-- num batch  2014
boucle adversarial fin
boucle adversarial debut-- num batch  2015
boucle adversarial fin
boucle adversarial debut-- num batch  2016
boucle adversarial fin
boucle adversarial debut-- num batch  2017
boucle adversarial fin
boucle adversarial debut-- num batch  2018
boucle adversarial fin
boucle adversarial debut-- num batch  2019
boucle adversarial fin
boucle adversarial debut-- num batch  2020
boucle adversarial fin
boucle adversarial debut-- num batch  2021
boucle adversarial fin
boucle adversarial debut-- num batch  2022
boucle adversarial fin
boucle adversarial debut-- num batch  2023
boucle adversarial fin
boucle adversarial debut-- num batch  2024
boucle adversarial fin
boucle adversarial debut-- num batch  2025
boucle adversarial fin
boucle adversarial debut-- num batch  2026
boucle adversarial fin
boucle adversarial debut-- num batch  2027
boucle adversarial fin
boucle adversarial debut-- num batch  2028
boucle adversarial fin
boucle adversarial debut-- num batch  2029
boucle adversarial fin
boucle adversarial debut-- num batch  2030
boucle adversarial fin
boucle adversarial debut-- num batch  2031
boucle adversarial fin
boucle adversarial debut-- num batch  2032
boucle adversarial fin
boucle adversarial debut-- num batch  2033
boucle adversarial fin
boucle adversarial debut-- num batch  2034
boucle adversarial fin
boucle adversarial debut-- num batch  2035
boucle adversarial fin
boucle adversarial debut-- num batch  2036
boucle adversarial fin
boucle adversarial debut-- num batch  2037
boucle adversarial fin
boucle adversarial debut-- num batch  2038
boucle adversarial fin
boucle adversarial debut-- num batch  2039
boucle adversarial fin
boucle adversarial debut-- num batch  2040
boucle adversarial fin
boucle adversarial debut-- num batch  2041
boucle adversarial fin
boucle adversarial debut-- num batch  2042
boucle adversarial fin
boucle adversarial debut-- num batch  2043
boucle adversarial fin
boucle adversarial debut-- num batch  2044
boucle adversarial fin
boucle adversarial debut-- num batch  2045
boucle adversarial fin
boucle adversarial debut-- num batch  2046
boucle adversarial fin
boucle adversarial debut-- num batch  2047
boucle adversarial fin
boucle adversarial debut-- num batch  2048
boucle adversarial fin
boucle adversarial debut-- num batch  2049
boucle adversarial fin
boucle adversarial debut-- num batch  2050
boucle adversarial fin
boucle adversarial debut-- num batch  2051
boucle adversarial fin
boucle adversarial debut-- num batch  2052
boucle adversarial fin
boucle adversarial debut-- num batch  2053
boucle adversarial fin
boucle adversarial debut-- num batch  2054
boucle adversarial fin
boucle adversarial debut-- num batch  2055
boucle adversarial fin
boucle adversarial debut-- num batch  2056
boucle adversarial fin
boucle adversarial debut-- num batch  2057
boucle adversarial fin
boucle adversarial debut-- num batch  2058
boucle adversarial fin
boucle adversarial debut-- num batch  2059
boucle adversarial fin
boucle adversarial debut-- num batch  2060
boucle adversarial fin
boucle adversarial debut-- num batch  2061
boucle adversarial fin
boucle adversarial debut-- num batch  2062
boucle adversarial fin
boucle adversarial debut-- num batch  2063
boucle adversarial fin
boucle adversarial debut-- num batch  2064
boucle adversarial fin
boucle adversarial debut-- num batch  2065
boucle adversarial fin
boucle adversarial debut-- num batch  2066
boucle adversarial fin
boucle adversarial debut-- num batch  2067
boucle adversarial fin
boucle adversarial debut-- num batch  2068
boucle adversarial fin
boucle adversarial debut-- num batch  2069
boucle adversarial fin
boucle adversarial debut-- num batch  2070
boucle adversarial fin
boucle adversarial debut-- num batch  2071
boucle adversarial fin
boucle adversarial debut-- num batch  2072
boucle adversarial fin
boucle adversarial debut-- num batch  2073
boucle adversarial fin
boucle adversarial debut-- num batch  2074
boucle adversarial fin
boucle adversarial debut-- num batch  2075
boucle adversarial fin
boucle adversarial debut-- num batch  2076
boucle adversarial fin
boucle adversarial debut-- num batch  2077
boucle adversarial fin
boucle adversarial debut-- num batch  2078
boucle adversarial fin
boucle adversarial debut-- num batch  2079
boucle adversarial fin
boucle adversarial debut-- num batch  2080
boucle adversarial fin
boucle adversarial debut-- num batch  2081
boucle adversarial fin
boucle adversarial debut-- num batch  2082
boucle adversarial fin
boucle adversarial debut-- num batch  2083
boucle adversarial fin
boucle adversarial debut-- num batch  2084
boucle adversarial fin
boucle adversarial debut-- num batch  2085
boucle adversarial fin
boucle adversarial debut-- num batch  2086
boucle adversarial fin
boucle adversarial debut-- num batch  2087
boucle adversarial fin
boucle adversarial debut-- num batch  2088
boucle adversarial fin
boucle adversarial debut-- num batch  2089
boucle adversarial fin
boucle adversarial debut-- num batch  2090
boucle adversarial fin
boucle adversarial debut-- num batch  2091
boucle adversarial fin
boucle adversarial debut-- num batch  2092
boucle adversarial fin
boucle adversarial debut-- num batch  2093
boucle adversarial fin
boucle adversarial debut-- num batch  2094
boucle adversarial fin
boucle adversarial debut-- num batch  2095
boucle adversarial fin
boucle adversarial debut-- num batch  2096
boucle adversarial fin
boucle adversarial debut-- num batch  2097
boucle adversarial fin
boucle adversarial debut-- num batch  2098
boucle adversarial fin
boucle adversarial debut-- num batch  2099
boucle adversarial fin
boucle adversarial debut-- num batch  2100
boucle adversarial fin
boucle adversarial debut-- num batch  2101
boucle adversarial fin
boucle adversarial debut-- num batch  2102
boucle adversarial fin
boucle adversarial debut-- num batch  2103
boucle adversarial fin
boucle adversarial debut-- num batch  2104
boucle adversarial fin
boucle adversarial debut-- num batch  2105
boucle adversarial fin
boucle adversarial debut-- num batch  2106
boucle adversarial fin
boucle adversarial debut-- num batch  2107
boucle adversarial fin
boucle adversarial debut-- num batch  2108
boucle adversarial fin
boucle adversarial debut-- num batch  2109
boucle adversarial fin
boucle adversarial debut-- num batch  2110
boucle adversarial fin
boucle adversarial debut-- num batch  2111
boucle adversarial fin
boucle adversarial debut-- num batch  2112

boucle adversarial fin
boucle adversarial debut-- num batch  2113
boucle adversarial fin
boucle adversarial debut-- num batch  2114
boucle adversarial fin
boucle adversarial debut-- num batch  2115
boucle adversarial fin
boucle adversarial debut-- num batch  2116
boucle adversarial fin
boucle adversarial debut-- num batch  2117
boucle adversarial fin
boucle adversarial debut-- num batch  2118
boucle adversarial fin
boucle adversarial debut-- num batch  2119
boucle adversarial fin
boucle adversarial debut-- num batch  2120
boucle adversarial fin
boucle adversarial debut-- num batch  2121
boucle adversarial fin
boucle adversarial debut-- num batch  2122
boucle adversarial fin
boucle adversarial debut-- num batch  2123
boucle adversarial fin
boucle adversarial debut-- num batch  2124
boucle adversarial fin
boucle adversarial debut-- num batch  2125
boucle adversarial fin
boucle adversarial debut-- num batch  2126
boucle adversarial fin
boucle adversarial debut-- num batch  2127
boucle adversarial fin
boucle adversarial debut-- num batch  2128
boucle adversarial fin
boucle adversarial debut-- num batch  2129
boucle adversarial fin
boucle adversarial debut-- num batch  2130
boucle adversarial fin
boucle adversarial debut-- num batch  2131
boucle adversarial fin
boucle adversarial debut-- num batch  2132
boucle adversarial fin
boucle adversarial debut-- num batch  2133
boucle adversarial fin
boucle adversarial debut-- num batch  2134
boucle adversarial fin
boucle adversarial debut-- num batch  2135
boucle adversarial fin
boucle adversarial debut-- num batch  2136
boucle adversarial fin
boucle adversarial debut-- num batch  2137
boucle adversarial fin
boucle adversarial debut-- num batch  2138
boucle adversarial fin
boucle adversarial debut-- num batch  2139
boucle adversarial fin
boucle adversarial debut-- num batch  2140
boucle adversarial fin
boucle adversarial debut-- num batch  2141
boucle adversarial fin
boucle adversarial debut-- num batch  2142
boucle adversarial fin
boucle adversarial debut-- num batch  2143
boucle adversarial fin
boucle adversarial debut-- num batch  2144
boucle adversarial fin
boucle adversarial debut-- num batch  2145
boucle adversarial fin
boucle adversarial debut-- num batch  2146
boucle adversarial fin
boucle adversarial debut-- num batch  2147
boucle adversarial fin
boucle adversarial debut-- num batch  2148
boucle adversarial fin
boucle adversarial debut-- num batch  2149
boucle adversarial fin
boucle adversarial debut-- num batch  2150
boucle adversarial fin
boucle adversarial debut-- num batch  2151
boucle adversarial fin
boucle adversarial debut-- num batch  2152
boucle adversarial fin
boucle adversarial debut-- num batch  2153
boucle adversarial fin
boucle adversarial debut-- num batch  2154
boucle adversarial fin
boucle adversarial debut-- num batch  2155
boucle adversarial fin
boucle adversarial debut-- num batch  2156
boucle adversarial fin
boucle adversarial debut-- num batch  2157
boucle adversarial fin
boucle adversarial debut-- num batch  2158
boucle adversarial fin
boucle adversarial debut-- num batch  2159
boucle adversarial fin
boucle adversarial debut-- num batch  2160
boucle adversarial fin
boucle adversarial debut-- num batch  2162
boucle adversarial fin
boucle adversarial debut-- num batch  2163
boucle adversarial fin
boucle adversarial debut-- num batch  2164
boucle adversarial fin
boucle adversarial debut-- num batch  2165
boucle adversarial fin
boucle adversarial debut-- num batch  2166
boucle adversarial fin
boucle adversarial debut-- num batch  2167
boucle adversarial fin
boucle adversarial debut-- num batch  2168
boucle adversarial fin
boucle adversarial debut-- num batch  2169
boucle adversarial fin
boucle adversarial debut-- num batch  2170
boucle adversarial fin
boucle adversarial debut-- num batch  2171
boucle adversarial fin
boucle adversarial debut-- num batch  2172
boucle adversarial fin
boucle adversarial debut-- num batch  2173
boucle adversarial fin
boucle adversarial debut-- num batch  2174
boucle adversarial fin
boucle adversarial debut-- num batch  2175
boucle adversarial fin
boucle adversarial debut-- num batch  2176
boucle adversarial fin
boucle adversarial debut-- num batch  2177
boucle adversarial fin
boucle adversarial debut-- num batch  2178
boucle adversarial fin
boucle adversarial debut-- num batch  2179
boucle adversarial fin
boucle adversarial debut-- num batch  2180
boucle adversarial fin
boucle adversarial debut-- num batch  2181
boucle adversarial fin
boucle adversarial debut-- num batch  2182
boucle adversarial fin
boucle adversarial debut-- num batch  2183
boucle adversarial fin
boucle adversarial debut-- num batch  2184
boucle adversarial fin
boucle adversarial debut-- num batch  2185
boucle adversarial fin
boucle adversarial debut-- num batch  2186
boucle adversarial fin
boucle adversarial debut-- num batch  2187
boucle adversarial fin
boucle adversarial debut-- num batch  2188
boucle adversarial fin
boucle adversarial debut-- num batch  2189
boucle adversarial fin
boucle adversarial debut-- num batch  2190
boucle adversarial fin
boucle adversarial debut-- num batch  2191
boucle adversarial fin
boucle adversarial debut-- num batch  2192
boucle adversarial fin
boucle adversarial debut-- num batch  2193
boucle adversarial fin
boucle adversarial debut-- num batch  2194
boucle adversarial fin
boucle adversarial debut-- num batch  2195
boucle adversarial fin
boucle adversarial debut-- num batch  2196
boucle adversarial fin
boucle adversarial debut-- num batch  2197
boucle adversarial fin
boucle adversarial debut-- num batch  2198
boucle adversarial fin
boucle adversarial debut-- num batch  2199
boucle adversarial fin
boucle adversarial debut-- num batch  2200
boucle adversarial fin
boucle adversarial debut-- num batch  2201
boucle adversarial fin
boucle adversarial debut-- num batch  2202
boucle adversarial fin
boucle adversarial debut-- num batch  2203
boucle adversarial fin
boucle adversarial debut-- num batch  2204
boucle adversarial fin
boucle adversarial debut-- num batch  2205
boucle adversarial fin
boucle adversarial debut-- num batch  2206
boucle adversarial fin
boucle adversarial debut-- num batch  2207
boucle adversarial fin
boucle adversarial debut-- num batch  2208
boucle adversarial fin
boucle adversarial debut-- num batch  2209
boucle adversarial fin
boucle adversarial debut-- num batch  2210
boucle adversarial fin
boucle adversarial debut-- num batch  2211
boucle adversarial fin
boucle adversarial debut-- num batch  2212
boucle adversarial fin
boucle adversarial debut-- num batch  2213
boucle adversarial fin
boucle adversarial debut-- num batch  2214
boucle adversarial fin
boucle adversarial debut-- num batch  2215
boucle adversarial fin
boucle adversarial debut-- num batch  2216
boucle adversarial fin
boucle adversarial debut-- num batch  2217
boucle adversarial fin
boucle adversarial debut-- num batch  2218
boucle adversarial fin
boucle adversarial debut-- num batch  2219
boucle adversarial fin
boucle adversarial debut-- num batch  2220
boucle adversarial fin
boucle adversarial debut-- num batch  2221
boucle adversarial fin
boucle adversarial debut-- num batch  2222
boucle adversarial fin
boucle adversarial debut-- num batch  2223
boucle adversarial fin
boucle adversarial debut-- num batch  2224
boucle adversarial fin
boucle adversarial debut-- num batch  2225
boucle adversarial fin
boucle adversarial debut-- num batch  2226
boucle adversarial fin
boucle adversarial debut-- num batch  2227
boucle adversarial fin
boucle adversarial debut-- num batch  2228
boucle adversarial fin
boucle adversarial debut-- num batch  2229
boucle adversarial fin
boucle adversarial debut-- num batch  2230
boucle adversarial fin
boucle adversarial debut-- num batch  2231
boucle adversarial fin
boucle adversarial debut-- num batch  2232
boucle adversarial fin
boucle adversarial debut-- num batch  2233
boucle adversarial fin
boucle adversarial debut-- num batch  2234
boucle adversarial fin
boucle adversarial debut-- num batch  2235
boucle adversarial fin
boucle adversarial debut-- num batch  2236
boucle adversarial fin
boucle adversarial debut-- num batch  2237
boucle adversarial fin
boucle adversarial debut-- num batch  2238

boucle adversarial fin
boucle adversarial debut-- num batch  2239
boucle adversarial fin
boucle adversarial debut-- num batch  2240
boucle adversarial fin
boucle adversarial debut-- num batch  2241
boucle adversarial fin
boucle adversarial debut-- num batch  2242
boucle adversarial fin
boucle adversarial debut-- num batch  2243
boucle adversarial fin
boucle adversarial debut-- num batch  2244
boucle adversarial fin
boucle adversarial debut-- num batch  2245
boucle adversarial fin
boucle adversarial debut-- num batch  2246
boucle adversarial fin
boucle adversarial debut-- num batch  2247
boucle adversarial fin
boucle adversarial debut-- num batch  2248
boucle adversarial fin
boucle adversarial debut-- num batch  2249
boucle adversarial fin
boucle adversarial debut-- num batch  2250
boucle adversarial fin
boucle adversarial debut-- num batch  2251
boucle adversarial fin
boucle adversarial debut-- num batch  2252
boucle adversarial fin
boucle adversarial debut-- num batch  2253
boucle adversarial fin
boucle adversarial debut-- num batch  2254
boucle adversarial fin
boucle adversarial debut-- num batch  2255
boucle adversarial fin
boucle adversarial debut-- num batch  2256
boucle adversarial fin
boucle adversarial debut-- num batch  2257
boucle adversarial fin
boucle adversarial debut-- num batch  2258
boucle adversarial fin
boucle adversarial debut-- num batch  2259
boucle adversarial fin
boucle adversarial debut-- num batch  2260
boucle adversarial fin
boucle adversarial debut-- num batch  2261
boucle adversarial fin
boucle adversarial debut-- num batch  2262
boucle adversarial fin
boucle adversarial debut-- num batch  2263
boucle adversarial fin
boucle adversarial debut-- num batch  2264
boucle adversarial fin
boucle adversarial debut-- num batch  2265
boucle adversarial fin
boucle adversarial debut-- num batch  2266
boucle adversarial fin
boucle adversarial debut-- num batch  2267
boucle adversarial fin
boucle adversarial debut-- num batch  2268
boucle adversarial fin
boucle adversarial debut-- num batch  2269
boucle adversarial fin
boucle adversarial debut-- num batch  2270
boucle adversarial fin
boucle adversarial debut-- num batch  2271
boucle adversarial fin
boucle adversarial debut-- num batch  2272
boucle adversarial fin
boucle adversarial debut-- num batch  2273
boucle adversarial fin
boucle adversarial debut-- num batch  2274
boucle adversarial fin
boucle adversarial debut-- num batch  2275
boucle adversarial fin
boucle adversarial debut-- num batch  2276
boucle adversarial fin
boucle adversarial debut-- num batch  2277
boucle adversarial fin
boucle adversarial debut-- num batch  2278
boucle adversarial fin
boucle adversarial debut-- num batch  2279
boucle adversarial fin
boucle adversarial debut-- num batch  2280
boucle adversarial fin
boucle adversarial debut-- num batch  2281
boucle adversarial fin
boucle adversarial debut-- num batch  2282
boucle adversarial fin
boucle adversarial debut-- num batch  2283
boucle adversarial fin
boucle adversarial debut-- num batch  2284
boucle adversarial fin
boucle adversarial debut-- num batch  2285
boucle adversarial fin
boucle adversarial debut-- num batch  2286
boucle adversarial fin
boucle adversarial debut-- num batch  2287
boucle adversarial fin
boucle adversarial debut-- num batch  2288
boucle adversarial fin
boucle adversarial debut-- num batch  2289
boucle adversarial fin
boucle adversarial debut-- num batch  2290
boucle adversarial fin
boucle adversarial debut-- num batch  2291
boucle adversarial fin
boucle adversarial debut-- num batch  2292
boucle adversarial fin
boucle adversarial debut-- num batch  2293
boucle adversarial fin
boucle adversarial debut-- num batch  2294
boucle adversarial fin
boucle adversarial debut-- num batch  2295
boucle adversarial fin
boucle adversarial debut-- num batch  2296
boucle adversarial fin
boucle adversarial debut-- num batch  2297
boucle adversarial fin
boucle adversarial debut-- num batch  2298
boucle adversarial fin
boucle adversarial debut-- num batch  2299
boucle adversarial fin
boucle adversarial debut-- num batch  2300
boucle adversarial fin
boucle adversarial debut-- num batch  2301
boucle adversarial fin
boucle adversarial debut-- num batch  2302
boucle adversarial fin
boucle adversarial debut-- num batch  2303
boucle adversarial fin
boucle adversarial debut-- num batch  2304
boucle adversarial fin
boucle adversarial debut-- num batch  2305
boucle adversarial fin
boucle adversarial debut-- num batch  2306
boucle adversarial fin
boucle adversarial debut-- num batch  2307
boucle adversarial fin
boucle adversarial debut-- num batch  2308
boucle adversarial fin
boucle adversarial debut-- num batch  2309
boucle adversarial fin
boucle adversarial debut-- num batch  2310
boucle adversarial fin
boucle adversarial debut-- num batch  2311
boucle adversarial fin
boucle adversarial debut-- num batch  2312
boucle adversarial fin
boucle adversarial debut-- num batch  2313
boucle adversarial fin
boucle adversarial debut-- num batch  2314
boucle adversarial fin
boucle adversarial debut-- num batch  2315
boucle adversarial fin
boucle adversarial debut-- num batch  2316
boucle adversarial fin
boucle adversarial debut-- num batch  2317
boucle adversarial fin
boucle adversarial debut-- num batch  2318
boucle adversarial fin
boucle adversarial debut-- num batch  2319
boucle adversarial fin
boucle adversarial debut-- num batch  2320
boucle adversarial fin
boucle adversarial debut-- num batch  2321
boucle adversarial fin
boucle adversarial debut-- num batch  2322
boucle adversarial fin
boucle adversarial debut-- num batch  2323
boucle adversarial fin
boucle adversarial debut-- num batch  2324
boucle adversarial fin
boucle adversarial debut-- num batch  2325
boucle adversarial fin
boucle adversarial debut-- num batch  2326
boucle adversarial fin
boucle adversarial debut-- num batch  2327
boucle adversarial fin
boucle adversarial debut-- num batch  2328
boucle adversarial fin
boucle adversarial debut-- num batch  2329
boucle adversarial fin
boucle adversarial debut-- num batch  2330
boucle adversarial fin
boucle adversarial debut-- num batch  2331
boucle adversarial fin
boucle adversarial debut-- num batch  2332
boucle adversarial fin
boucle adversarial debut-- num batch  2333
boucle adversarial fin
boucle adversarial debut-- num batch  2334
boucle adversarial fin
boucle adversarial debut-- num batch  2335
boucle adversarial fin
boucle adversarial debut-- num batch  2336
boucle adversarial fin
boucle adversarial debut-- num batch  2337
boucle adversarial fin
boucle adversarial debut-- num batch  2338
boucle adversarial fin
boucle adversarial debut-- num batch  2339
boucle adversarial fin
boucle adversarial debut-- num batch  2340
boucle adversarial fin
boucle adversarial debut-- num batch  2341
boucle adversarial fin
boucle adversarial debut-- num batch  2342
boucle adversarial fin
boucle adversarial debut-- num batch  2343
boucle adversarial fin
boucle adversarial debut-- num batch  2344
boucle adversarial fin
boucle adversarial debut-- num batch  2345
boucle adversarial fin
boucle adversarial debut-- num batch  2346
boucle adversarial fin
boucle adversarial debut-- num batch  2347
boucle adversarial fin
boucle adversarial debut-- num batch  2348
boucle adversarial fin
boucle adversarial debut-- num batch  2349
boucle adversarial fin
boucle adversarial debut-- num batch  2350
boucle adversarial fin
boucle adversarial debut-- num batch  2351
boucle adversarial fin
boucle adversarial debut-- num batch  2352
boucle adversarial fin
boucle adversarial debut-- num batch  2353
boucle adversarial fin
boucle adversarial debut-- num batch  2354
boucle adversarial fin
boucle adversarial debut-- num batch  2355
boucle adversarial fin
boucle adversarial debut-- num batch  2356
boucle adversarial fin
boucle adversarial debut-- num batch  2357
boucle adversarial fin
boucle adversarial debut-- num batch  2358
boucle adversarial fin
boucle adversarial debut-- num batch  2359
boucle adversarial fin
boucle adversarial debut-- num batch  2360
boucle adversarial fin
boucle adversarial debut-- num batch  2361
boucle adversarial fin
boucle adversarial debut-- num batch  2362
boucle adversarial fin

boucle adversarial debut-- num batch  2363
boucle adversarial fin
boucle adversarial debut-- num batch  2364
boucle adversarial fin
boucle adversarial debut-- num batch  2365
boucle adversarial fin
boucle adversarial debut-- num batch  2366
boucle adversarial fin
boucle adversarial debut-- num batch  2367
boucle adversarial fin
boucle adversarial debut-- num batch  2368
boucle adversarial fin
boucle adversarial debut-- num batch  2369
boucle adversarial fin
boucle adversarial debut-- num batch  2370
boucle adversarial fin
boucle adversarial debut-- num batch  2371
boucle adversarial fin
boucle adversarial debut-- num batch  2372
boucle adversarial fin
boucle adversarial debut-- num batch  2373
boucle adversarial fin
boucle adversarial debut-- num batch  2374
boucle adversarial fin
boucle adversarial debut-- num batch  2375
boucle adversarial fin
boucle adversarial debut-- num batch  2376
boucle adversarial fin
boucle adversarial debut-- num batch  2377
boucle adversarial fin
boucle adversarial debut-- num batch  2378
boucle adversarial fin
boucle adversarial debut-- num batch  2379
boucle adversarial fin
boucle adversarial debut-- num batch  2380
boucle adversarial fin
boucle adversarial debut-- num batch  2381
boucle adversarial fin
boucle adversarial debut-- num batch  2382
boucle adversarial fin
boucle adversarial debut-- num batch  2383
boucle adversarial fin
boucle adversarial debut-- num batch  2384
boucle adversarial fin
boucle adversarial debut-- num batch  2385
boucle adversarial fin
boucle adversarial debut-- num batch  2386
boucle adversarial fin
boucle adversarial debut-- num batch  2387
boucle adversarial fin
boucle adversarial debut-- num batch  2388
boucle adversarial fin
boucle adversarial debut-- num batch  2389
boucle adversarial fin
boucle adversarial debut-- num batch  2390
boucle adversarial fin
boucle adversarial debut-- num batch  2391
boucle adversarial fin
boucle adversarial debut-- num batch  2392
boucle adversarial fin
boucle adversarial debut-- num batch  2393
boucle adversarial fin
boucle adversarial debut-- num batch  2394
boucle adversarial fin
boucle adversarial debut-- num batch  2395
boucle adversarial fin
boucle adversarial debut-- num batch  2396
boucle adversarial fin
boucle adversarial debut-- num batch  2397
boucle adversarial fin
boucle adversarial debut-- num batch  2398
boucle adversarial fin
boucle adversarial debut-- num batch  2399
boucle adversarial fin
boucle adversarial debut-- num batch  2400
boucle adversarial fin
boucle adversarial debut-- num batch  2401
boucle adversarial fin
boucle adversarial debut-- num batch  2402
boucle adversarial fin
boucle adversarial debut-- num batch  2403
boucle adversarial fin
boucle adversarial debut-- num batch  2404
boucle adversarial fin
boucle adversarial debut-- num batch  2405
boucle adversarial fin
boucle adversarial debut-- num batch  2406
boucle adversarial fin
boucle adversarial debut-- num batch  2407
boucle adversarial fin
boucle adversarial debut-- num batch  2408
boucle adversarial fin
boucle adversarial debut-- num batch  2409
boucle adversarial fin
boucle adversarial debut-- num batch  2410
boucle adversarial fin
boucle adversarial debut-- num batch  2411
boucle adversarial fin
boucle adversarial debut-- num batch  2412
boucle adversarial fin
boucle adversarial debut-- num batch  2413
boucle adversarial fin
boucle adversarial debut-- num batch  2414
boucle adversarial fin
boucle adversarial debut-- num batch  2415
boucle adversarial fin
boucle adversarial debut-- num batch  2416
boucle adversarial fin
boucle adversarial debut-- num batch  2417
boucle adversarial fin
boucle adversarial debut-- num batch  2418
boucle adversarial fin
boucle adversarial debut-- num batch  2419
boucle adversarial fin
boucle adversarial debut-- num batch  2420
boucle adversarial fin
boucle adversarial debut-- num batch  2421
boucle adversarial fin
boucle adversarial debut-- num batch  2422
boucle adversarial fin
boucle adversarial debut-- num batch  2423
boucle adversarial fin
boucle adversarial debut-- num batch  2424
boucle adversarial fin
boucle adversarial debut-- num batch  2425
boucle adversarial fin
boucle adversarial debut-- num batch  2426
boucle adversarial fin
boucle adversarial debut-- num batch  2427
boucle adversarial fin
boucle adversarial debut-- num batch  2428
boucle adversarial fin
boucle adversarial debut-- num batch  2429
boucle adversarial fin
boucle adversarial debut-- num batch  2430
boucle adversarial fin
boucle adversarial debut-- num batch  2431
boucle adversarial fin
boucle adversarial debut-- num batch  2432
boucle adversarial fin
boucle adversarial debut-- num batch  2433
boucle adversarial fin
boucle adversarial debut-- num batch  2434
boucle adversarial fin
boucle adversarial debut-- num batch  2435
boucle adversarial fin
boucle adversarial debut-- num batch  2436
boucle adversarial fin
boucle adversarial debut-- num batch  2437
boucle adversarial fin
boucle adversarial debut-- num batch  2438
boucle adversarial fin
boucle adversarial debut-- num batch  2439
boucle adversarial fin
boucle adversarial debut-- num batch  2440
boucle adversarial fin
boucle adversarial debut-- num batch  2441
boucle adversarial fin
boucle adversarial debut-- num batch  2442
boucle adversarial fin
boucle adversarial debut-- num batch  2443
boucle adversarial fin
boucle adversarial debut-- num batch  2444
boucle adversarial fin
boucle adversarial debut-- num batch  2445
boucle adversarial fin
boucle adversarial debut-- num batch  2446
boucle adversarial fin
boucle adversarial debut-- num batch  2447
boucle adversarial fin
boucle adversarial debut-- num batch  2448
boucle adversarial fin
boucle adversarial debut-- num batch  2449
boucle adversarial fin
boucle adversarial debut-- num batch  2450
boucle adversarial fin
boucle adversarial debut-- num batch  2451
boucle adversarial fin
boucle adversarial debut-- num batch  2452
boucle adversarial fin
boucle adversarial debut-- num batch  2453
boucle adversarial fin
boucle adversarial debut-- num batch  2454
boucle adversarial fin
boucle adversarial debut-- num batch  2455
boucle adversarial fin
boucle adversarial debut-- num batch  2456
boucle adversarial fin
boucle adversarial debut-- num batch  2457
boucle adversarial fin
boucle adversarial debut-- num batch  2458
boucle adversarial fin
boucle adversarial debut-- num batch  2459
boucle adversarial fin
boucle adversarial debut-- num batch  2460
boucle adversarial fin
boucle adversarial debut-- num batch  2461
boucle adversarial fin
boucle adversarial debut-- num batch  2462
boucle adversarial fin
boucle adversarial debut-- num batch  2463
boucle adversarial fin
boucle adversarial debut-- num batch  2464
boucle adversarial fin
boucle adversarial debut-- num batch  2465
boucle adversarial fin
boucle adversarial debut-- num batch  2466
boucle adversarial fin
boucle adversarial debut-- num batch  2467
boucle adversarial fin
boucle adversarial debut-- num batch  2468
boucle adversarial fin
boucle adversarial debut-- num batch  2469
boucle adversarial fin
boucle adversarial debut-- num batch  2470
boucle adversarial fin
boucle adversarial debut-- num batch  2471
boucle adversarial fin
boucle adversarial debut-- num batch  2472
boucle adversarial fin
boucle adversarial debut-- num batch  2473
boucle adversarial fin
boucle adversarial debut-- num batch  2474
boucle adversarial fin
boucle adversarial debut-- num batch  2475
boucle adversarial fin
boucle adversarial debut-- num batch  2476
boucle adversarial fin
boucle adversarial debut-- num batch  2477
boucle adversarial fin
boucle adversarial debut-- num batch  2478
boucle adversarial fin
boucle adversarial debut-- num batch  2479
boucle adversarial fin
boucle adversarial debut-- num batch  2480
boucle adversarial fin
boucle adversarial debut-- num batch  2481
boucle adversarial fin
boucle adversarial debut-- num batch  2482
boucle adversarial fin
boucle adversarial debut-- num batch  2483
boucle adversarial fin
boucle adversarial debut-- num batch  2484
boucle adversarial fin
boucle adversarial debut-- num batch  2485
boucle adversarial fin
boucle adversarial debut-- num batch  2486
boucle adversarial fin
boucle adversarial debut-- num batch  2487

boucle adversarial fin
boucle adversarial debut-- num batch  2488
boucle adversarial fin
boucle adversarial debut-- num batch  2489
boucle adversarial fin
boucle adversarial debut-- num batch  2490
boucle adversarial fin
boucle adversarial debut-- num batch  2491
boucle adversarial fin
boucle adversarial debut-- num batch  2492
boucle adversarial fin
boucle adversarial debut-- num batch  2493
boucle adversarial fin
boucle adversarial debut-- num batch  2494
boucle adversarial fin
boucle adversarial debut-- num batch  2495
boucle adversarial fin
boucle adversarial debut-- num batch  2496
boucle adversarial fin
boucle adversarial debut-- num batch  2497
boucle adversarial fin
boucle adversarial debut-- num batch  2498
boucle adversarial fin
boucle adversarial debut-- num batch  2499
boucle adversarial fin
boucle adversarial debut-- num batch  2500
boucle adversarial fin
boucle adversarial debut-- num batch  2501
boucle adversarial fin
boucle adversarial debut-- num batch  2502
boucle adversarial fin
boucle adversarial debut-- num batch  2503
boucle adversarial fin
boucle adversarial debut-- num batch  2504
boucle adversarial fin
boucle adversarial debut-- num batch  2505
boucle adversarial fin
boucle adversarial debut-- num batch  2506
boucle adversarial fin
boucle adversarial debut-- num batch  2507
boucle adversarial fin
boucle adversarial debut-- num batch  2508
boucle adversarial fin
boucle adversarial debut-- num batch  2509
boucle adversarial fin
boucle adversarial debut-- num batch  2510
boucle adversarial fin
boucle adversarial debut-- num batch  2511
boucle adversarial fin
boucle adversarial debut-- num batch  2512
boucle adversarial fin
boucle adversarial debut-- num batch  2513
boucle adversarial fin
boucle adversarial debut-- num batch  2514
boucle adversarial fin
boucle adversarial debut-- num batch  2515
boucle adversarial fin
boucle adversarial debut-- num batch  2516
boucle adversarial fin
boucle adversarial debut-- num batch  2517
boucle adversarial fin
boucle adversarial debut-- num batch  2518
boucle adversarial fin
boucle adversarial debut-- num batch  2519
boucle adversarial fin
boucle adversarial debut-- num batch  2520
boucle adversarial fin
boucle adversarial debut-- num batch  2521
boucle adversarial fin
boucle adversarial debut-- num batch  2522
boucle adversarial fin
boucle adversarial debut-- num batch  2523
boucle adversarial fin
boucle adversarial debut-- num batch  2524
boucle adversarial fin
boucle adversarial debut-- num batch  2525
boucle adversarial fin
boucle adversarial debut-- num batch  2526
boucle adversarial fin
boucle adversarial debut-- num batch  2527
boucle adversarial fin
boucle adversarial debut-- num batch  2528
boucle adversarial fin
boucle adversarial debut-- num batch  2529
boucle adversarial fin
boucle adversarial debut-- num batch  2530
boucle adversarial fin
boucle adversarial debut-- num batch  2531
boucle adversarial fin
boucle adversarial debut-- num batch  2532
boucle adversarial fin
boucle adversarial debut-- num batch  2533
boucle adversarial fin
boucle adversarial debut-- num batch  2534
boucle adversarial fin
boucle adversarial debut-- num batch  2535
boucle adversarial fin
boucle adversarial debut-- num batch  2536
boucle adversarial fin
boucle adversarial debut-- num batch  2537
boucle adversarial fin
boucle adversarial debut-- num batch  2538
boucle adversarial fin
boucle adversarial debut-- num batch  2539
boucle adversarial fin
boucle adversarial debut-- num batch  2540
boucle adversarial fin
boucle adversarial debut-- num batch  2541
boucle adversarial fin
boucle adversarial debut-- num batch  2542
boucle adversarial fin
boucle adversarial debut-- num batch  2543
boucle adversarial fin
boucle adversarial debut-- num batch  2544
boucle adversarial fin
boucle adversarial debut-- num batch  2545
boucle adversarial fin
boucle adversarial debut-- num batch  2546
boucle adversarial fin
boucle adversarial debut-- num batch  2547
boucle adversarial fin
boucle adversarial debut-- num batch  2548
boucle adversarial fin
boucle adversarial debut-- num batch  2549
boucle adversarial fin
boucle adversarial debut-- num batch  2550
boucle adversarial fin
boucle adversarial debut-- num batch  2551
boucle adversarial fin
boucle adversarial debut-- num batch  2552
boucle adversarial fin
boucle adversarial debut-- num batch  2553
boucle adversarial fin
boucle adversarial debut-- num batch  2554
boucle adversarial fin
boucle adversarial debut-- num batch  2555
boucle adversarial fin
boucle adversarial debut-- num batch  2556
boucle adversarial fin
boucle adversarial debut-- num batch  2557
boucle adversarial fin
boucle adversarial debut-- num batch  2558
boucle adversarial fin
boucle adversarial debut-- num batch  2559
boucle adversarial fin
boucle adversarial debut-- num batch  2560
boucle adversarial fin
boucle adversarial debut-- num batch  2561
boucle adversarial fin
boucle adversarial debut-- num batch  2562
boucle adversarial fin
boucle adversarial debut-- num batch  2563
boucle adversarial fin
boucle adversarial debut-- num batch  2564
boucle adversarial fin
boucle adversarial debut-- num batch  2565
boucle adversarial fin
boucle adversarial debut-- num batch  2566
boucle adversarial fin
boucle adversarial debut-- num batch  2567
boucle adversarial fin
boucle adversarial debut-- num batch  2568
boucle adversarial fin
boucle adversarial debut-- num batch  2569
boucle adversarial fin
boucle adversarial debut-- num batch  2570
boucle adversarial fin
boucle adversarial debut-- num batch  2571
boucle adversarial fin
boucle adversarial debut-- num batch  2572
boucle adversarial fin
boucle adversarial debut-- num batch  2573
boucle adversarial fin
boucle adversarial debut-- num batch  2574
boucle adversarial fin
boucle adversarial debut-- num batch  2575
boucle adversarial fin
boucle adversarial debut-- num batch  2576
boucle adversarial fin
boucle adversarial debut-- num batch  2577
boucle adversarial fin
boucle adversarial debut-- num batch  2578
boucle adversarial fin
boucle adversarial debut-- num batch  2579
boucle adversarial fin
boucle adversarial debut-- num batch  2580
boucle adversarial fin
boucle adversarial debut-- num batch  2581
boucle adversarial fin
boucle adversarial debut-- num batch  2582
boucle adversarial fin
boucle adversarial debut-- num batch  2583
boucle adversarial fin
boucle adversarial debut-- num batch  2584
boucle adversarial fin
boucle adversarial debut-- num batch  2585
boucle adversarial fin
boucle adversarial debut-- num batch  2586
boucle adversarial fin
boucle adversarial debut-- num batch  2587
boucle adversarial fin
boucle adversarial debut-- num batch  2588
boucle adversarial fin
boucle adversarial debut-- num batch  2589
boucle adversarial fin
boucle adversarial debut-- num batch  2590
boucle adversarial fin
boucle adversarial debut-- num batch  2591
boucle adversarial fin
boucle adversarial debut-- num batch  2592
boucle adversarial fin
boucle adversarial debut-- num batch  2593
boucle adversarial fin
boucle adversarial debut-- num batch  2594
boucle adversarial fin
boucle adversarial debut-- num batch  2595
boucle adversarial fin
boucle adversarial debut-- num batch  2596
boucle adversarial fin
boucle adversarial debut-- num batch  2597
boucle adversarial fin
boucle adversarial debut-- num batch  2598
boucle adversarial fin
boucle adversarial debut-- num batch  2599
boucle adversarial fin
boucle adversarial debut-- num batch  2600
boucle adversarial fin
boucle adversarial debut-- num batch  2601
boucle adversarial fin
boucle adversarial debut-- num batch  2602
boucle adversarial fin
boucle adversarial debut-- num batch  2603
boucle adversarial fin
boucle adversarial debut-- num batch  2604
boucle adversarial fin
boucle adversarial debut-- num batch  2605
boucle adversarial fin
boucle adversarial debut-- num batch  2606
boucle adversarial fin
boucle adversarial debut-- num batch  2607
boucle adversarial fin
boucle adversarial debut-- num batch  2608
boucle adversarial fin
boucle adversarial debut-- num batch  2609
boucle adversarial fin
boucle adversarial debut-- num batch  2610
boucle adversarial fin
boucle adversarial debut-- num batch  2611
boucle adversarial fin
boucle adversarial debut-- num batch  2612

boucle adversarial fin
boucle adversarial debut-- num batch  2613
boucle adversarial fin
boucle adversarial debut-- num batch  2614
boucle adversarial fin
boucle adversarial debut-- num batch  2615
boucle adversarial fin
boucle adversarial debut-- num batch  2616
boucle adversarial fin
boucle adversarial debut-- num batch  2617
boucle adversarial fin
boucle adversarial debut-- num batch  2618
boucle adversarial fin
boucle adversarial debut-- num batch  2619
boucle adversarial fin
boucle adversarial debut-- num batch  2620
boucle adversarial fin
boucle adversarial debut-- num batch  2621
boucle adversarial fin
boucle adversarial debut-- num batch  2622
boucle adversarial fin
boucle adversarial debut-- num batch  2623
boucle adversarial fin
boucle adversarial debut-- num batch  2624
boucle adversarial fin
boucle adversarial debut-- num batch  2625
boucle adversarial fin
boucle adversarial debut-- num batch  2626
boucle adversarial fin
boucle adversarial debut-- num batch  2627
boucle adversarial fin
boucle adversarial debut-- num batch  2628
boucle adversarial fin
boucle adversarial debut-- num batch  2629
boucle adversarial fin
boucle adversarial debut-- num batch  2630
boucle adversarial fin
boucle adversarial debut-- num batch  2631
boucle adversarial fin
boucle adversarial debut-- num batch  2632
boucle adversarial fin
boucle adversarial debut-- num batch  2633
boucle adversarial fin
boucle adversarial debut-- num batch  2634
boucle adversarial fin
boucle adversarial debut-- num batch  2635
boucle adversarial fin
boucle adversarial debut-- num batch  2636
boucle adversarial fin
boucle adversarial debut-- num batch  2637
boucle adversarial fin
boucle adversarial debut-- num batch  2638
boucle adversarial fin
boucle adversarial debut-- num batch  2639
boucle adversarial fin
boucle adversarial debut-- num batch  2640
boucle adversarial fin
boucle adversarial debut-- num batch  2641
boucle adversarial fin
boucle adversarial debut-- num batch  2642
boucle adversarial fin
boucle adversarial debut-- num batch  2643
boucle adversarial fin
boucle adversarial debut-- num batch  2644
boucle adversarial fin
boucle adversarial debut-- num batch  2645
boucle adversarial fin
boucle adversarial debut-- num batch  2646
boucle adversarial fin
boucle adversarial debut-- num batch  2647
boucle adversarial fin
boucle adversarial debut-- num batch  2648
boucle adversarial fin
boucle adversarial debut-- num batch  2649
boucle adversarial fin
boucle adversarial debut-- num batch  2650
boucle adversarial fin
boucle adversarial debut-- num batch  2651
boucle adversarial fin
boucle adversarial debut-- num batch  2652
boucle adversarial fin
boucle adversarial debut-- num batch  2653
boucle adversarial fin
boucle adversarial debut-- num batch  2654
boucle adversarial fin
boucle adversarial debut-- num batch  2655
boucle adversarial fin
boucle adversarial debut-- num batch  2656
boucle adversarial fin
boucle adversarial debut-- num batch  2657
boucle adversarial fin
boucle adversarial debut-- num batch  2658
boucle adversarial fin
boucle adversarial debut-- num batch  2659
boucle adversarial fin
boucle adversarial debut-- num batch  2660
boucle adversarial fin
boucle adversarial debut-- num batch  2661
boucle adversarial fin
boucle adversarial debut-- num batch  2662
boucle adversarial fin
boucle adversarial debut-- num batch  2663
boucle adversarial fin
boucle adversarial debut-- num batch  2664
boucle adversarial fin
boucle adversarial debut-- num batch  2665
boucle adversarial fin
boucle adversarial debut-- num batch  2666
boucle adversarial fin
boucle adversarial debut-- num batch  2667
boucle adversarial fin
boucle adversarial debut-- num batch  2668
boucle adversarial fin
boucle adversarial debut-- num batch  2669
boucle adversarial fin
boucle adversarial debut-- num batch  2670
boucle adversarial fin
boucle adversarial debut-- num batch  2671
boucle adversarial fin
boucle adversarial debut-- num batch  2672
boucle adversarial fin
boucle adversarial debut-- num batch  2673
boucle adversarial fin
boucle adversarial debut-- num batch  2674
boucle adversarial fin
boucle adversarial debut-- num batch  2675
boucle adversarial fin
boucle adversarial debut-- num batch  2676
boucle adversarial fin
boucle adversarial debut-- num batch  2677
boucle adversarial fin
boucle adversarial debut-- num batch  2678
boucle adversarial fin
boucle adversarial debut-- num batch  2679
boucle adversarial fin
boucle adversarial debut-- num batch  2680
boucle adversarial fin
boucle adversarial debut-- num batch  2681
boucle adversarial fin
boucle adversarial debut-- num batch  2682
boucle adversarial fin
boucle adversarial debut-- num batch  2683
boucle adversarial fin
boucle adversarial debut-- num batch  2684
boucle adversarial fin
boucle adversarial debut-- num batch  2685
boucle adversarial fin
boucle adversarial debut-- num batch  2686
boucle adversarial fin
boucle adversarial debut-- num batch  2687
boucle adversarial fin
boucle adversarial debut-- num batch  2688
boucle adversarial fin
boucle adversarial debut-- num batch  2689
boucle adversarial fin
boucle adversarial debut-- num batch  2690
boucle adversarial fin
boucle adversarial debut-- num batch  2691
boucle adversarial fin
boucle adversarial debut-- num batch  2692
boucle adversarial fin
boucle adversarial debut-- num batch  2693
boucle adversarial fin
boucle adversarial debut-- num batch  2694
boucle adversarial fin
boucle adversarial debut-- num batch  2695
boucle adversarial fin
boucle adversarial debut-- num batch  2696
boucle adversarial fin
boucle adversarial debut-- num batch  2697
boucle adversarial fin
boucle adversarial debut-- num batch  2698
boucle adversarial fin
boucle adversarial debut-- num batch  2699
boucle adversarial fin
boucle adversarial debut-- num batch  2700
boucle adversarial fin
boucle adversarial debut-- num batch  2701
boucle adversarial fin
boucle adversarial debut-- num batch  2702
boucle adversarial fin
boucle adversarial debut-- num batch  2703
boucle adversarial fin
boucle adversarial debut-- num batch  2704
boucle adversarial fin
boucle adversarial debut-- num batch  2705
boucle adversarial fin
boucle adversarial debut-- num batch  2706
boucle adversarial fin
boucle adversarial debut-- num batch  2707
boucle adversarial fin
boucle adversarial debut-- num batch  2708
boucle adversarial fin
boucle adversarial debut-- num batch  2709
boucle adversarial fin
boucle adversarial debut-- num batch  2710
boucle adversarial fin
boucle adversarial debut-- num batch  2711
boucle adversarial fin
boucle adversarial debut-- num batch  2712
boucle adversarial fin
boucle adversarial debut-- num batch  2713
boucle adversarial fin
boucle adversarial debut-- num batch  2714
boucle adversarial fin
boucle adversarial debut-- num batch  2715
boucle adversarial fin
boucle adversarial debut-- num batch  2716
boucle adversarial fin
boucle adversarial debut-- num batch  2717
boucle adversarial fin
boucle adversarial debut-- num batch  2718
boucle adversarial fin
boucle adversarial debut-- num batch  2719
boucle adversarial fin
boucle adversarial debut-- num batch  2720
boucle adversarial fin
boucle adversarial debut-- num batch  2721
boucle adversarial fin
boucle adversarial debut-- num batch  2722
boucle adversarial fin
boucle adversarial debut-- num batch  2723
boucle adversarial fin
boucle adversarial debut-- num batch  2724
boucle adversarial fin
boucle adversarial debut-- num batch  2725
boucle adversarial fin
boucle adversarial debut-- num batch  2726
boucle adversarial fin
boucle adversarial debut-- num batch  2727
boucle adversarial fin
boucle adversarial debut-- num batch  2728
boucle adversarial fin
boucle adversarial debut-- num batch  2729
boucle adversarial fin
boucle adversarial debut-- num batch  2730
boucle adversarial fin
boucle adversarial debut-- num batch  2731
boucle adversarial fin
boucle adversarial debut-- num batch  2732
boucle adversarial fin
boucle adversarial debut-- num batch  2733
boucle adversarial fin
boucle adversarial debut-- num batch  2734
boucle adversarial fin
boucle adversarial debut-- num batch  2735
boucle adversarial fin
boucle adversarial debut-- num batch  2736
boucle adversarial fin
boucle adversarial debut-- num batch  2737

boucle adversarial fin
boucle adversarial debut-- num batch  2738
boucle adversarial fin
boucle adversarial debut-- num batch  2739
boucle adversarial fin
boucle adversarial debut-- num batch  2740
boucle adversarial fin
boucle adversarial debut-- num batch  2741
boucle adversarial fin
boucle adversarial debut-- num batch  2742
boucle adversarial fin
boucle adversarial debut-- num batch  2743
boucle adversarial fin
boucle adversarial debut-- num batch  2744
boucle adversarial fin
boucle adversarial debut-- num batch  2745
boucle adversarial fin
boucle adversarial debut-- num batch  2746
boucle adversarial fin
boucle adversarial debut-- num batch  2747
boucle adversarial fin
boucle adversarial debut-- num batch  2748
boucle adversarial fin
boucle adversarial debut-- num batch  2749
boucle adversarial fin
boucle adversarial debut-- num batch  2750
boucle adversarial fin
boucle adversarial debut-- num batch  2751
boucle adversarial fin
boucle adversarial debut-- num batch  2752
boucle adversarial fin
boucle adversarial debut-- num batch  2753
boucle adversarial fin
boucle adversarial debut-- num batch  2754
boucle adversarial fin
boucle adversarial debut-- num batch  2755
boucle adversarial fin
boucle adversarial debut-- num batch  2756
boucle adversarial fin
boucle adversarial debut-- num batch  2757
boucle adversarial fin
boucle adversarial debut-- num batch  2758
boucle adversarial fin
boucle adversarial debut-- num batch  2759
boucle adversarial fin
boucle adversarial debut-- num batch  2760
boucle adversarial fin
boucle adversarial debut-- num batch  2761
boucle adversarial fin
boucle adversarial debut-- num batch  2762
boucle adversarial fin
boucle adversarial debut-- num batch  2763
boucle adversarial fin
boucle adversarial debut-- num batch  2764
boucle adversarial fin
boucle adversarial debut-- num batch  2765
boucle adversarial fin
boucle adversarial debut-- num batch  2766
boucle adversarial fin
boucle adversarial debut-- num batch  2767
boucle adversarial fin
boucle adversarial debut-- num batch  2768
boucle adversarial fin
boucle adversarial debut-- num batch  2769
boucle adversarial fin
boucle adversarial debut-- num batch  2770
boucle adversarial fin
boucle adversarial debut-- num batch  2771
boucle adversarial fin
boucle adversarial debut-- num batch  2772
boucle adversarial fin
boucle adversarial debut-- num batch  2773
boucle adversarial fin
boucle adversarial debut-- num batch  2774
boucle adversarial fin
boucle adversarial debut-- num batch  2775
boucle adversarial fin
boucle adversarial debut-- num batch  2776
boucle adversarial fin
boucle adversarial debut-- num batch  2777
boucle adversarial fin
boucle adversarial debut-- num batch  2778
boucle adversarial fin
boucle adversarial debut-- num batch  2779
boucle adversarial fin
boucle adversarial debut-- num batch  2780
boucle adversarial fin
boucle adversarial debut-- num batch  2781
boucle adversarial fin
boucle adversarial debut-- num batch  2782
boucle adversarial fin
boucle adversarial debut-- num batch  2783
boucle adversarial fin
boucle adversarial debut-- num batch  2784
boucle adversarial fin
boucle adversarial debut-- num batch  2785
boucle adversarial fin
boucle adversarial debut-- num batch  2786
boucle adversarial fin
boucle adversarial debut-- num batch  2787
boucle adversarial fin
boucle adversarial debut-- num batch  2788
boucle adversarial fin
boucle adversarial debut-- num batch  2789
boucle adversarial fin
boucle adversarial debut-- num batch  2790
boucle adversarial fin
boucle adversarial debut-- num batch  2791
boucle adversarial fin
boucle adversarial debut-- num batch  2792
boucle adversarial fin
boucle adversarial debut-- num batch  2793
boucle adversarial fin
boucle adversarial debut-- num batch  2794
boucle adversarial fin
boucle adversarial debut-- num batch  2795
boucle adversarial fin
boucle adversarial debut-- num batch  2796
boucle adversarial fin
boucle adversarial debut-- num batch  2797
boucle adversarial fin
boucle adversarial debut-- num batch  2798
boucle adversarial fin
boucle adversarial debut-- num batch  2799
boucle adversarial fin
boucle adversarial debut-- num batch  2800
boucle adversarial fin
boucle adversarial debut-- num batch  2801
boucle adversarial fin
boucle adversarial debut-- num batch  2802
boucle adversarial fin
boucle adversarial debut-- num batch  2803
boucle adversarial fin
boucle adversarial debut-- num batch  2804
boucle adversarial fin
boucle adversarial debut-- num batch  2805
boucle adversarial fin
boucle adversarial debut-- num batch  2806
boucle adversarial fin
boucle adversarial debut-- num batch  2807
boucle adversarial fin
boucle adversarial debut-- num batch  2808
boucle adversarial fin
boucle adversarial debut-- num batch  2809
boucle adversarial fin
boucle adversarial debut-- num batch  2810
boucle adversarial fin
boucle adversarial debut-- num batch  2811
boucle adversarial fin
boucle adversarial debut-- num batch  2812
boucle adversarial fin
boucle adversarial debut-- num batch  2813
boucle adversarial fin
boucle adversarial debut-- num batch  2814
boucle adversarial fin
boucle adversarial debut-- num batch  2815
boucle adversarial fin
boucle adversarial debut-- num batch  2816
boucle adversarial fin
boucle adversarial debut-- num batch  2817
boucle adversarial fin
boucle adversarial debut-- num batch  2818
boucle adversarial fin
boucle adversarial debut-- num batch  2819
boucle adversarial fin
boucle adversarial debut-- num batch  2820
boucle adversarial fin
boucle adversarial debut-- num batch  2821
boucle adversarial fin
boucle adversarial debut-- num batch  2822
boucle adversarial fin
boucle adversarial debut-- num batch  2823
boucle adversarial fin
boucle adversarial debut-- num batch  2824
boucle adversarial fin
boucle adversarial debut-- num batch  2825
boucle adversarial fin
boucle adversarial debut-- num batch  2826
boucle adversarial fin
boucle adversarial debut-- num batch  2827
boucle adversarial fin
boucle adversarial debut-- num batch  2828
boucle adversarial fin
boucle adversarial debut-- num batch  2829
boucle adversarial fin
boucle adversarial debut-- num batch  2830
boucle adversarial fin
boucle adversarial debut-- num batch  2831
boucle adversarial fin
boucle adversarial debut-- num batch  2832
boucle adversarial fin
boucle adversarial debut-- num batch  2833
boucle adversarial fin
boucle adversarial debut-- num batch  2834
boucle adversarial fin
boucle adversarial debut-- num batch  2835
boucle adversarial fin
boucle adversarial debut-- num batch  2836
boucle adversarial fin
boucle adversarial debut-- num batch  2837
boucle adversarial fin
boucle adversarial debut-- num batch  2838
boucle adversarial fin
boucle adversarial debut-- num batch  2839
boucle adversarial fin
boucle adversarial debut-- num batch  2840
boucle adversarial fin
boucle adversarial debut-- num batch  2841
boucle adversarial fin
boucle adversarial debut-- num batch  2842
boucle adversarial fin
boucle adversarial debut-- num batch  2843
boucle adversarial fin
boucle adversarial debut-- num batch  2844
boucle adversarial fin
boucle adversarial debut-- num batch  2845
boucle adversarial fin
boucle adversarial debut-- num batch  2846
boucle adversarial fin
boucle adversarial debut-- num batch  2847
boucle adversarial fin
boucle adversarial debut-- num batch  2848
boucle adversarial fin
boucle adversarial debut-- num batch  2849
boucle adversarial fin
boucle adversarial debut-- num batch  2850
boucle adversarial fin
boucle adversarial debut-- num batch  2851
boucle adversarial fin
boucle adversarial debut-- num batch  2852
boucle adversarial fin
boucle adversarial debut-- num batch  2853
boucle adversarial fin
boucle adversarial debut-- num batch  2854
boucle adversarial fin
boucle adversarial debut-- num batch  2855
boucle adversarial fin
boucle adversarial debut-- num batch  2856
boucle adversarial fin
boucle adversarial debut-- num batch  2857
boucle adversarial fin
boucle adversarial debut-- num batch  2858
boucle adversarial fin
boucle adversarial debut-- num batch  2859
boucle adversarial fin
boucle adversarial debut-- num batch  2860
boucle adversarial fin
boucle adversarial debut-- num batch  2861
boucle adversarial fin
boucle adversarial debut-- num batch  2862

boucle adversarial fin
boucle adversarial debut-- num batch  2863
boucle adversarial fin
boucle adversarial debut-- num batch  2864
boucle adversarial fin
boucle adversarial debut-- num batch  2865
boucle adversarial fin
boucle adversarial debut-- num batch  2866
boucle adversarial fin
boucle adversarial debut-- num batch  2867
boucle adversarial fin
boucle adversarial debut-- num batch  2868
boucle adversarial fin
boucle adversarial debut-- num batch  2869
boucle adversarial fin
boucle adversarial debut-- num batch  2870
boucle adversarial fin
boucle adversarial debut-- num batch  2871
boucle adversarial fin
boucle adversarial debut-- num batch  2872
boucle adversarial fin
boucle adversarial debut-- num batch  2873
boucle adversarial fin
boucle adversarial debut-- num batch  2874
boucle adversarial fin
boucle adversarial debut-- num batch  2875
boucle adversarial fin
boucle adversarial debut-- num batch  2876
boucle adversarial fin
boucle adversarial debut-- num batch  2877
boucle adversarial fin
boucle adversarial debut-- num batch  2878
boucle adversarial fin
boucle adversarial debut-- num batch  2879
boucle adversarial fin
boucle adversarial debut-- num batch  2880
boucle adversarial fin
boucle adversarial debut-- num batch  2881
boucle adversarial fin
boucle adversarial debut-- num batch  2882
boucle adversarial fin
boucle adversarial debut-- num batch  2883
boucle adversarial fin
boucle adversarial debut-- num batch  2884
boucle adversarial fin
boucle adversarial debut-- num batch  2885
boucle adversarial fin
boucle adversarial debut-- num batch  2886
boucle adversarial fin
boucle adversarial debut-- num batch  2887
boucle adversarial fin
boucle adversarial debut-- num batch  2888
boucle adversarial fin
boucle adversarial debut-- num batch  2889
boucle adversarial fin
boucle adversarial debut-- num batch  2890
boucle adversarial fin
boucle adversarial debut-- num batch  2891
boucle adversarial fin
boucle adversarial debut-- num batch  2892
boucle adversarial fin
boucle adversarial debut-- num batch  2893
boucle adversarial fin
boucle adversarial debut-- num batch  2894
boucle adversarial fin
boucle adversarial debut-- num batch  2895
boucle adversarial fin
boucle adversarial debut-- num batch  2896
boucle adversarial fin
boucle adversarial debut-- num batch  2897
boucle adversarial fin
boucle adversarial debut-- num batch  2898
boucle adversarial fin
boucle adversarial debut-- num batch  2899
boucle adversarial fin
boucle adversarial debut-- num batch  2900
boucle adversarial fin
boucle adversarial debut-- num batch  2901
boucle adversarial fin
boucle adversarial debut-- num batch  2902
boucle adversarial fin
boucle adversarial debut-- num batch  2903
boucle adversarial fin
boucle adversarial debut-- num batch  2904
boucle adversarial fin
boucle adversarial debut-- num batch  2905
boucle adversarial fin
boucle adversarial debut-- num batch  2906
boucle adversarial fin
boucle adversarial debut-- num batch  2907
boucle adversarial fin
boucle adversarial debut-- num batch  2908
boucle adversarial fin
boucle adversarial debut-- num batch  2909
boucle adversarial fin
boucle adversarial debut-- num batch  2910
boucle adversarial fin
boucle adversarial debut-- num batch  2911
boucle adversarial fin
boucle adversarial debut-- num batch  2912
boucle adversarial fin
boucle adversarial debut-- num batch  2913
boucle adversarial fin
boucle adversarial debut-- num batch  2914
boucle adversarial fin
boucle adversarial debut-- num batch  2915
boucle adversarial fin
boucle adversarial debut-- num batch  2916
boucle adversarial fin
boucle adversarial debut-- num batch  2917
boucle adversarial fin
boucle adversarial debut-- num batch  2918
boucle adversarial fin
boucle adversarial debut-- num batch  2919
boucle adversarial fin
boucle adversarial debut-- num batch  2920
boucle adversarial fin
boucle adversarial debut-- num batch  2921
boucle adversarial fin
boucle adversarial debut-- num batch  2922
boucle adversarial fin
boucle adversarial debut-- num batch  2923
boucle adversarial fin
boucle adversarial debut-- num batch  2924
boucle adversarial fin
boucle adversarial debut-- num batch  2925
boucle adversarial fin
boucle adversarial debut-- num batch  2926
boucle adversarial fin
boucle adversarial debut-- num batch  2927
boucle adversarial fin
boucle adversarial debut-- num batch  2928
boucle adversarial fin
boucle adversarial debut-- num batch  2929
boucle adversarial fin
boucle adversarial debut-- num batch  2930
boucle adversarial fin
boucle adversarial debut-- num batch  2931
boucle adversarial fin
boucle adversarial debut-- num batch  2932
boucle adversarial fin
boucle adversarial debut-- num batch  2933
boucle adversarial fin
boucle adversarial debut-- num batch  2934
boucle adversarial fin
boucle adversarial debut-- num batch  2935
boucle adversarial fin
boucle adversarial debut-- num batch  2936
boucle adversarial fin
boucle adversarial debut-- num batch  2937
boucle adversarial fin
boucle adversarial debut-- num batch  2938
boucle adversarial fin
boucle adversarial debut-- num batch  2939
boucle adversarial fin
boucle adversarial debut-- num batch  2940
boucle adversarial fin
boucle adversarial debut-- num batch  2941
boucle adversarial fin
boucle adversarial debut-- num batch  2942
boucle adversarial fin
boucle adversarial debut-- num batch  2943
boucle adversarial fin
boucle adversarial debut-- num batch  2944
boucle adversarial fin
boucle adversarial debut-- num batch  2945
boucle adversarial fin
boucle adversarial debut-- num batch  2946
boucle adversarial fin
boucle adversarial debut-- num batch  2947
boucle adversarial fin
boucle adversarial debut-- num batch  2948
boucle adversarial fin
boucle adversarial debut-- num batch  2949
boucle adversarial fin
boucle adversarial debut-- num batch  2950
boucle adversarial fin
boucle adversarial debut-- num batch  2951
boucle adversarial fin
boucle adversarial debut-- num batch  2952
boucle adversarial fin
boucle adversarial debut-- num batch  2953
boucle adversarial fin
boucle adversarial debut-- num batch  2954
boucle adversarial fin
boucle adversarial debut-- num batch  2955
boucle adversarial fin
boucle adversarial debut-- num batch  2956
boucle adversarial fin
boucle adversarial debut-- num batch  2957
boucle adversarial fin
boucle adversarial debut-- num batch  2958
boucle adversarial fin
boucle adversarial debut-- num batch  2959
boucle adversarial fin
boucle adversarial debut-- num batch  2960
boucle adversarial fin
boucle adversarial debut-- num batch  2961
boucle adversarial fin
boucle adversarial debut-- num batch  2962
boucle adversarial fin
boucle adversarial debut-- num batch  2963
boucle adversarial fin
boucle adversarial debut-- num batch  2964
boucle adversarial fin
boucle adversarial debut-- num batch  2965
boucle adversarial fin
boucle adversarial debut-- num batch  2966
boucle adversarial fin
boucle adversarial debut-- num batch  2967
boucle adversarial fin
boucle adversarial debut-- num batch  2968
boucle adversarial fin
boucle adversarial debut-- num batch  2969
boucle adversarial fin
boucle adversarial debut-- num batch  2970
boucle adversarial fin
boucle adversarial debut-- num batch  2971
boucle adversarial fin
boucle adversarial debut-- num batch  2972
boucle adversarial fin
boucle adversarial debut-- num batch  2973
boucle adversarial fin
boucle adversarial debut-- num batch  2974
boucle adversarial fin
boucle adversarial debut-- num batch  2975
boucle adversarial fin
boucle adversarial debut-- num batch  2976
boucle adversarial fin
boucle adversarial debut-- num batch  2977
boucle adversarial fin
boucle adversarial debut-- num batch  2978
boucle adversarial fin
boucle adversarial debut-- num batch  2979
boucle adversarial fin
boucle adversarial debut-- num batch  2980
boucle adversarial fin
boucle adversarial debut-- num batch  2981
boucle adversarial fin
boucle adversarial debut-- num batch  2982
boucle adversarial fin
boucle adversarial debut-- num batch  2983
boucle adversarial fin
boucle adversarial debut-- num batch  2984
boucle adversarial fin
boucle adversarial debut-- num batch  2985
boucle adversarial fin
boucle adversarial debut-- num batch  2986
boucle adversarial fin
boucle adversarial debut-- num batch  2987

boucle adversarial fin
boucle adversarial debut-- num batch  2988
boucle adversarial fin
boucle adversarial debut-- num batch  2989
boucle adversarial fin
boucle adversarial debut-- num batch  2990
boucle adversarial fin
boucle adversarial debut-- num batch  2991
boucle adversarial fin
boucle adversarial debut-- num batch  2992
boucle adversarial fin
boucle adversarial debut-- num batch  2993
boucle adversarial fin
boucle adversarial debut-- num batch  2994
boucle adversarial fin
boucle adversarial debut-- num batch  2995
boucle adversarial fin
boucle adversarial debut-- num batch  2996
boucle adversarial fin
boucle adversarial debut-- num batch  2997
boucle adversarial fin
boucle adversarial debut-- num batch  2998
boucle adversarial fin
boucle adversarial debut-- num batch  2999
boucle adversarial fin
boucle adversarial debut-- num batch  3000
boucle adversarial fin
boucle adversarial debut-- num batch  3001
boucle adversarial fin
boucle adversarial debut-- num batch  3002
boucle adversarial fin
boucle adversarial debut-- num batch  3003
boucle adversarial fin
boucle adversarial debut-- num batch  3004
boucle adversarial fin
boucle adversarial debut-- num batch  3005
boucle adversarial fin
boucle adversarial debut-- num batch  3006
boucle adversarial fin
boucle adversarial debut-- num batch  3007
boucle adversarial fin
boucle adversarial debut-- num batch  3008
boucle adversarial fin
boucle adversarial debut-- num batch  3009
boucle adversarial fin
boucle adversarial debut-- num batch  3010
boucle adversarial fin
boucle adversarial debut-- num batch  3011
boucle adversarial fin
boucle adversarial debut-- num batch  3012
boucle adversarial fin
boucle adversarial debut-- num batch  3013
boucle adversarial fin
boucle adversarial debut-- num batch  3014
boucle adversarial fin
boucle adversarial debut-- num batch  3015
boucle adversarial fin
boucle adversarial debut-- num batch  3016
boucle adversarial fin
boucle adversarial debut-- num batch  3017
boucle adversarial fin
boucle adversarial debut-- num batch  3018
boucle adversarial fin
boucle adversarial debut-- num batch  3019
boucle adversarial fin
boucle adversarial debut-- num batch  3020
boucle adversarial fin
boucle adversarial debut-- num batch  3021
boucle adversarial fin
boucle adversarial debut-- num batch  3022
boucle adversarial fin
boucle adversarial debut-- num batch  3023
boucle adversarial fin
boucle adversarial debut-- num batch  3024
boucle adversarial fin
boucle adversarial debut-- num batch  3025
boucle adversarial fin
boucle adversarial debut-- num batch  3026
boucle adversarial fin
boucle adversarial debut-- num batch  3027
boucle adversarial fin
boucle adversarial debut-- num batch  3028
boucle adversarial fin
boucle adversarial debut-- num batch  3029
boucle adversarial fin
boucle adversarial debut-- num batch  3030
boucle adversarial fin
boucle adversarial debut-- num batch  3031
boucle adversarial fin
boucle adversarial debut-- num batch  3032
boucle adversarial fin
boucle adversarial debut-- num batch  3033
boucle adversarial fin
boucle adversarial debut-- num batch  3034
boucle adversarial fin
boucle adversarial debut-- num batch  3035
boucle adversarial fin
boucle adversarial debut-- num batch  3036
boucle adversarial fin
boucle adversarial debut-- num batch  3037
boucle adversarial fin
boucle adversarial debut-- num batch  3038
boucle adversarial fin
boucle adversarial debut-- num batch  3039
boucle adversarial fin
boucle adversarial debut-- num batch  3040
boucle adversarial fin
boucle adversarial debut-- num batch  3041
boucle adversarial fin
boucle adversarial debut-- num batch  3042
boucle adversarial fin
boucle adversarial debut-- num batch  3043
boucle adversarial fin
boucle adversarial debut-- num batch  3044
boucle adversarial fin
boucle adversarial debut-- num batch  3045
boucle adversarial fin
boucle adversarial debut-- num batch  3046
boucle adversarial fin
boucle adversarial debut-- num batch  3047
boucle adversarial fin
boucle adversarial debut-- num batch  3048
boucle adversarial fin
boucle adversarial debut-- num batch  3049
boucle adversarial fin
boucle adversarial debut-- num batch  3050
boucle adversarial fin
boucle adversarial debut-- num batch  3051
boucle adversarial fin
boucle adversarial debut-- num batch  3052
boucle adversarial fin
boucle adversarial debut-- num batch  3053
boucle adversarial fin
boucle adversarial debut-- num batch  3054
boucle adversarial fin
boucle adversarial debut-- num batch  3055
boucle adversarial fin
boucle adversarial debut-- num batch  3056
boucle adversarial fin
boucle adversarial debut-- num batch  3057
boucle adversarial fin
boucle adversarial debut-- num batch  3058
boucle adversarial fin
boucle adversarial debut-- num batch  3059
boucle adversarial fin
boucle adversarial debut-- num batch  3060
boucle adversarial fin
boucle adversarial debut-- num batch  3061
boucle adversarial fin
boucle adversarial debut-- num batch  3062
boucle adversarial fin
boucle adversarial debut-- num batch  3063
boucle adversarial fin
boucle adversarial debut-- num batch  3064
boucle adversarial fin
boucle adversarial debut-- num batch  3065
boucle adversarial fin
boucle adversarial debut-- num batch  3066
boucle adversarial fin
boucle adversarial debut-- num batch  3067
boucle adversarial fin
boucle adversarial debut-- num batch  3068
boucle adversarial fin
boucle adversarial debut-- num batch  3069
boucle adversarial fin
boucle adversarial debut-- num batch  3070
boucle adversarial fin
boucle adversarial debut-- num batch  3071
boucle adversarial fin
boucle adversarial debut-- num batch  3072
boucle adversarial fin
boucle adversarial debut-- num batch  3073
boucle adversarial fin
boucle adversarial debut-- num batch  3074
boucle adversarial fin
boucle adversarial debut-- num batch  3075
boucle adversarial fin
boucle adversarial debut-- num batch  3076
boucle adversarial fin
boucle adversarial debut-- num batch  3077
boucle adversarial fin
boucle adversarial debut-- num batch  3078
boucle adversarial fin
boucle adversarial debut-- num batch  3079
boucle adversarial fin
boucle adversarial debut-- num batch  3080
boucle adversarial fin
boucle adversarial debut-- num batch  3081
boucle adversarial fin
boucle adversarial debut-- num batch  3082
boucle adversarial fin
boucle adversarial debut-- num batch  3083
boucle adversarial fin
boucle adversarial debut-- num batch  3084
boucle adversarial fin
boucle adversarial debut-- num batch  3085
boucle adversarial fin
boucle adversarial debut-- num batch  3086
boucle adversarial fin
boucle adversarial debut-- num batch  3087
boucle adversarial fin
boucle adversarial debut-- num batch  3088
boucle adversarial fin
boucle adversarial debut-- num batch  3089
boucle adversarial fin
boucle adversarial debut-- num batch  3090
boucle adversarial fin
boucle adversarial debut-- num batch  3091
boucle adversarial fin
boucle adversarial debut-- num batch  3092
boucle adversarial fin
boucle adversarial debut-- num batch  3093
boucle adversarial fin
boucle adversarial debut-- num batch  3094
boucle adversarial fin
boucle adversarial debut-- num batch  3095
boucle adversarial fin
boucle adversarial debut-- num batch  3096
boucle adversarial fin
boucle adversarial debut-- num batch  3097
boucle adversarial fin
boucle adversarial debut-- num batch  3098
boucle adversarial fin
boucle adversarial debut-- num batch  3099
boucle adversarial fin
boucle adversarial debut-- num batch  3100
boucle adversarial fin
boucle adversarial debut-- num batch  3101
boucle adversarial fin
boucle adversarial debut-- num batch  3102
boucle adversarial fin
boucle adversarial debut-- num batch  3103
boucle adversarial fin
boucle adversarial debut-- num batch  3104
boucle adversarial fin
boucle adversarial debut-- num batch  3105
boucle adversarial fin
boucle adversarial debut-- num batch  3106
boucle adversarial fin
boucle adversarial debut-- num batch  3107
boucle adversarial fin
boucle adversarial debut-- num batch  3108
boucle adversarial fin
boucle adversarial debut-- num batch  3109
boucle adversarial fin
boucle adversarial debut-- num batch  3110
boucle adversarial fin
boucle adversarial debut-- num batch  3111
boucle adversarial fin

boucle adversarial debut-- num batch  3112
boucle adversarial fin
boucle adversarial debut-- num batch  3113
boucle adversarial fin
boucle adversarial debut-- num batch  3114
boucle adversarial fin
boucle adversarial debut-- num batch  3115
boucle adversarial fin
boucle adversarial debut-- num batch  3116
boucle adversarial fin
boucle adversarial debut-- num batch  3117
boucle adversarial fin
boucle adversarial debut-- num batch  3118
boucle adversarial fin
boucle adversarial debut-- num batch  3119
boucle adversarial fin
boucle adversarial debut-- num batch  3120
boucle adversarial fin
boucle adversarial debut-- num batch  3121
boucle adversarial fin
boucle adversarial debut-- num batch  3122
boucle adversarial fin
boucle adversarial debut-- num batch  3123
boucle adversarial fin
boucle adversarial debut-- num batch  3124
boucle adversarial fin
boucle adversarial debut-- num batch  3125
boucle adversarial fin
boucle adversarial debut-- num batch  3126
boucle adversarial fin
boucle adversarial debut-- num batch  3127
boucle adversarial fin
boucle adversarial debut-- num batch  3128
boucle adversarial fin
boucle adversarial debut-- num batch  3129
boucle adversarial fin
boucle adversarial debut-- num batch  3130
boucle adversarial fin
boucle adversarial debut-- num batch  3131
boucle adversarial fin
boucle adversarial debut-- num batch  3132
boucle adversarial fin
boucle adversarial debut-- num batch  3133
boucle adversarial fin
boucle adversarial debut-- num batch  3134
boucle adversarial fin
boucle adversarial debut-- num batch  3135
boucle adversarial fin
boucle adversarial debut-- num batch  3136
boucle adversarial fin
boucle adversarial debut-- num batch  3137
boucle adversarial fin
boucle adversarial debut-- num batch  3138
boucle adversarial fin
boucle adversarial debut-- num batch  3139
boucle adversarial fin
boucle adversarial debut-- num batch  3140
boucle adversarial fin
boucle adversarial debut-- num batch  3141
boucle adversarial fin
boucle adversarial debut-- num batch  3142
boucle adversarial fin
boucle adversarial debut-- num batch  3143
boucle adversarial fin
boucle adversarial debut-- num batch  3144
boucle adversarial fin
boucle adversarial debut-- num batch  3145
boucle adversarial fin
boucle adversarial debut-- num batch  3146
boucle adversarial fin
boucle adversarial debut-- num batch  3147
boucle adversarial fin
boucle adversarial debut-- num batch  3148
boucle adversarial fin
boucle adversarial debut-- num batch  3149
boucle adversarial fin
boucle adversarial debut-- num batch  3150
boucle adversarial fin
boucle adversarial debut-- num batch  3151
boucle adversarial fin
boucle adversarial debut-- num batch  3152
boucle adversarial fin
boucle adversarial debut-- num batch  3153
boucle adversarial fin
boucle adversarial debut-- num batch  3154
boucle adversarial fin
boucle adversarial debut-- num batch  3155
boucle adversarial fin
boucle adversarial debut-- num batch  3156
boucle adversarial fin
boucle adversarial debut-- num batch  3157
boucle adversarial fin
boucle adversarial debut-- num batch  3158
boucle adversarial fin
boucle adversarial debut-- num batch  3159
boucle adversarial fin
boucle adversarial debut-- num batch  3160
boucle adversarial fin
boucle adversarial debut-- num batch  3161
boucle adversarial fin
boucle adversarial debut-- num batch  3162
boucle adversarial fin
boucle adversarial debut-- num batch  3163
boucle adversarial fin
boucle adversarial debut-- num batch  3164
boucle adversarial fin
boucle adversarial debut-- num batch  3165
boucle adversarial fin
boucle adversarial debut-- num batch  3166
boucle adversarial fin
boucle adversarial debut-- num batch  3167
boucle adversarial fin
boucle adversarial debut-- num batch  3168
boucle adversarial fin
boucle adversarial debut-- num batch  3169
boucle adversarial fin
boucle adversarial debut-- num batch  3170
boucle adversarial fin
boucle adversarial debut-- num batch  3171
boucle adversarial fin
boucle adversarial debut-- num batch  3172
boucle adversarial fin
boucle adversarial debut-- num batch  3173
boucle adversarial fin
boucle adversarial debut-- num batch  3174
boucle adversarial fin
boucle adversarial debut-- num batch  3175
boucle adversarial fin
boucle adversarial debut-- num batch  3176
boucle adversarial fin
boucle adversarial debut-- num batch  3177
boucle adversarial fin
boucle adversarial debut-- num batch  3178
boucle adversarial fin
boucle adversarial debut-- num batch  3179
boucle adversarial fin
boucle adversarial debut-- num batch  3180
boucle adversarial fin
boucle adversarial debut-- num batch  3181
boucle adversarial fin
boucle adversarial debut-- num batch  3182
boucle adversarial fin
boucle adversarial debut-- num batch  3183
boucle adversarial fin
boucle adversarial debut-- num batch  3184
boucle adversarial fin
boucle adversarial debut-- num batch  3185
boucle adversarial fin
boucle adversarial debut-- num batch  3186
boucle adversarial fin
boucle adversarial debut-- num batch  3187
boucle adversarial fin
boucle adversarial debut-- num batch  3188
boucle adversarial fin
boucle adversarial debut-- num batch  3189
boucle adversarial fin
boucle adversarial debut-- num batch  3190
boucle adversarial fin
boucle adversarial debut-- num batch  3191
boucle adversarial fin
boucle adversarial debut-- num batch  3192
boucle adversarial fin
boucle adversarial debut-- num batch  3193
boucle adversarial fin
boucle adversarial debut-- num batch  3194
boucle adversarial fin
boucle adversarial debut-- num batch  3195
boucle adversarial fin
boucle adversarial debut-- num batch  3196
boucle adversarial fin
boucle adversarial debut-- num batch  3197
boucle adversarial fin
boucle adversarial debut-- num batch  3198
boucle adversarial fin
boucle adversarial debut-- num batch  3199
boucle adversarial fin
boucle adversarial debut-- num batch  3200
boucle adversarial fin
boucle adversarial debut-- num batch  3201
boucle adversarial fin
boucle adversarial debut-- num batch  3202
boucle adversarial fin
boucle adversarial debut-- num batch  3203
boucle adversarial fin
boucle adversarial debut-- num batch  3204
boucle adversarial fin
boucle adversarial debut-- num batch  3205
boucle adversarial fin
boucle adversarial debut-- num batch  3206
boucle adversarial fin
boucle adversarial debut-- num batch  3207
boucle adversarial fin
boucle adversarial debut-- num batch  3208
boucle adversarial fin
boucle adversarial debut-- num batch  3209
boucle adversarial fin
boucle adversarial debut-- num batch  3210
boucle adversarial fin
boucle adversarial debut-- num batch  3211
boucle adversarial fin
boucle adversarial debut-- num batch  3212
boucle adversarial fin
boucle adversarial debut-- num batch  3213
boucle adversarial fin
boucle adversarial debut-- num batch  3214
boucle adversarial fin
boucle adversarial debut-- num batch  3215
boucle adversarial fin
boucle adversarial debut-- num batch  3216
boucle adversarial fin
boucle adversarial debut-- num batch  3217
boucle adversarial fin
boucle adversarial debut-- num batch  3218
boucle adversarial fin
boucle adversarial debut-- num batch  3219
boucle adversarial fin
boucle adversarial debut-- num batch  3220
boucle adversarial fin
boucle adversarial debut-- num batch  3221
boucle adversarial fin
boucle adversarial debut-- num batch  3222
boucle adversarial fin
boucle adversarial debut-- num batch  3223
boucle adversarial fin
boucle adversarial debut-- num batch  3224
boucle adversarial fin
boucle adversarial debut-- num batch  3225
boucle adversarial fin
boucle adversarial debut-- num batch  3226
boucle adversarial fin
boucle adversarial debut-- num batch  3227
boucle adversarial fin
boucle adversarial debut-- num batch  3228
boucle adversarial fin
boucle adversarial debut-- num batch  3229
boucle adversarial fin
boucle adversarial debut-- num batch  3230
boucle adversarial fin
boucle adversarial debut-- num batch  3231
boucle adversarial fin
boucle adversarial debut-- num batch  3232
boucle adversarial fin
boucle adversarial debut-- num batch  3233
boucle adversarial fin
boucle adversarial debut-- num batch  3234
boucle adversarial fin
boucle adversarial debut-- num batch  3235
boucle adversarial fin
boucle adversarial debut-- num batch  3236

boucle adversarial fin
boucle adversarial debut-- num batch  3237
boucle adversarial fin
boucle adversarial debut-- num batch  3238
boucle adversarial fin
boucle adversarial debut-- num batch  3239
boucle adversarial fin
boucle adversarial debut-- num batch  3240
boucle adversarial fin
boucle adversarial debut-- num batch  3241
boucle adversarial fin
boucle adversarial debut-- num batch  3242
boucle adversarial fin
boucle adversarial debut-- num batch  3243
boucle adversarial fin
boucle adversarial debut-- num batch  3244
boucle adversarial fin
boucle adversarial debut-- num batch  3245
boucle adversarial fin
boucle adversarial debut-- num batch  3246
boucle adversarial fin
boucle adversarial debut-- num batch  3247
boucle adversarial fin
boucle adversarial debut-- num batch  3248
boucle adversarial fin
boucle adversarial debut-- num batch  3249
boucle adversarial fin
boucle adversarial debut-- num batch  3250
boucle adversarial fin
boucle adversarial debut-- num batch  3251
boucle adversarial fin
boucle adversarial debut-- num batch  3252
boucle adversarial fin
boucle adversarial debut-- num batch  3253
boucle adversarial fin
boucle adversarial debut-- num batch  3254
boucle adversarial fin
boucle adversarial debut-- num batch  3255
boucle adversarial fin
boucle adversarial debut-- num batch  3256
boucle adversarial fin
boucle adversarial debut-- num batch  3257
boucle adversarial fin
boucle adversarial debut-- num batch  3258
boucle adversarial fin
boucle adversarial debut-- num batch  3259
boucle adversarial fin
boucle adversarial debut-- num batch  3260
boucle adversarial fin
boucle adversarial debut-- num batch  3261
boucle adversarial fin
boucle adversarial debut-- num batch  3262
boucle adversarial fin
boucle adversarial debut-- num batch  3263
boucle adversarial fin
boucle adversarial debut-- num batch  3264
boucle adversarial fin
boucle adversarial debut-- num batch  3265
boucle adversarial fin
boucle adversarial debut-- num batch  3266
boucle adversarial fin
boucle adversarial debut-- num batch  3267
boucle adversarial fin
boucle adversarial debut-- num batch  3268
boucle adversarial fin
boucle adversarial debut-- num batch  3269
boucle adversarial fin
boucle adversarial debut-- num batch  3270
boucle adversarial fin
boucle adversarial debut-- num batch  3271
boucle adversarial fin
boucle adversarial debut-- num batch  3272
boucle adversarial fin
boucle adversarial debut-- num batch  3273
boucle adversarial fin
boucle adversarial debut-- num batch  3274
boucle adversarial fin
boucle adversarial debut-- num batch  3275
boucle adversarial fin
boucle adversarial debut-- num batch  3276
boucle adversarial fin
boucle adversarial debut-- num batch  3277
boucle adversarial fin
boucle adversarial debut-- num batch  3278
boucle adversarial fin
boucle adversarial debut-- num batch  3279
boucle adversarial fin
boucle adversarial debut-- num batch  3280
boucle adversarial fin
boucle adversarial debut-- num batch  3281
boucle adversarial fin
boucle adversarial debut-- num batch  3282
boucle adversarial fin
boucle adversarial debut-- num batch  3283
boucle adversarial fin
boucle adversarial debut-- num batch  3284
boucle adversarial fin
boucle adversarial debut-- num batch  3285
boucle adversarial fin
boucle adversarial debut-- num batch  3286
boucle adversarial fin
boucle adversarial debut-- num batch  3287
boucle adversarial fin
boucle adversarial debut-- num batch  3288
boucle adversarial fin
boucle adversarial debut-- num batch  3289
boucle adversarial fin
boucle adversarial debut-- num batch  3290
boucle adversarial fin
boucle adversarial debut-- num batch  3291
boucle adversarial fin
boucle adversarial debut-- num batch  3292
boucle adversarial fin
boucle adversarial debut-- num batch  3293
boucle adversarial fin
boucle adversarial debut-- num batch  3294
boucle adversarial fin
boucle adversarial debut-- num batch  3295
boucle adversarial fin
boucle adversarial debut-- num batch  3296
boucle adversarial fin
boucle adversarial debut-- num batch  3297
boucle adversarial fin
boucle adversarial debut-- num batch  3298
boucle adversarial fin
boucle adversarial debut-- num batch  3299
boucle adversarial fin
boucle adversarial debut-- num batch  3300
boucle adversarial fin
boucle adversarial debut-- num batch  3301
boucle adversarial fin
boucle adversarial debut-- num batch  3302
boucle adversarial fin
boucle adversarial debut-- num batch  3303
boucle adversarial fin
boucle adversarial debut-- num batch  3304
boucle adversarial fin
boucle adversarial debut-- num batch  3305
boucle adversarial fin
boucle adversarial debut-- num batch  3306
boucle adversarial fin
boucle adversarial debut-- num batch  3307
boucle adversarial fin
boucle adversarial debut-- num batch  3308
boucle adversarial fin
boucle adversarial debut-- num batch  3309
boucle adversarial fin
boucle adversarial debut-- num batch  3310
boucle adversarial fin
boucle adversarial debut-- num batch  3311
boucle adversarial fin
boucle adversarial debut-- num batch  3312
boucle adversarial fin
boucle adversarial debut-- num batch  3313
boucle adversarial fin
boucle adversarial debut-- num batch  3314
boucle adversarial fin
boucle adversarial debut-- num batch  3315
boucle adversarial fin
boucle adversarial debut-- num batch  3316
boucle adversarial fin
boucle adversarial debut-- num batch  3317
boucle adversarial fin
boucle adversarial debut-- num batch  3318
boucle adversarial fin
boucle adversarial debut-- num batch  3319
boucle adversarial fin
boucle adversarial debut-- num batch  3320
boucle adversarial fin
boucle adversarial debut-- num batch  3321
boucle adversarial fin
boucle adversarial debut-- num batch  3322
boucle adversarial fin
boucle adversarial debut-- num batch  3323
boucle adversarial fin
boucle adversarial debut-- num batch  3324
boucle adversarial fin
boucle adversarial debut-- num batch  3325
boucle adversarial fin
boucle adversarial debut-- num batch  3326
boucle adversarial fin
boucle adversarial debut-- num batch  3327
boucle adversarial fin
boucle adversarial debut-- num batch  3328
boucle adversarial fin
boucle adversarial debut-- num batch  3329
boucle adversarial fin
boucle adversarial debut-- num batch  3330
boucle adversarial fin
boucle adversarial debut-- num batch  3331
boucle adversarial fin
boucle adversarial debut-- num batch  3332
boucle adversarial fin
boucle adversarial debut-- num batch  3333
boucle adversarial fin
boucle adversarial debut-- num batch  3334
boucle adversarial fin
boucle adversarial debut-- num batch  3335
boucle adversarial fin
boucle adversarial debut-- num batch  3336
boucle adversarial fin
boucle adversarial debut-- num batch  3337
boucle adversarial fin
boucle adversarial debut-- num batch  3338
boucle adversarial fin
boucle adversarial debut-- num batch  3339
boucle adversarial fin
boucle adversarial debut-- num batch  3340
boucle adversarial fin
boucle adversarial debut-- num batch  3341
boucle adversarial fin
boucle adversarial debut-- num batch  3342
boucle adversarial fin
boucle adversarial debut-- num batch  3343
boucle adversarial fin
boucle adversarial debut-- num batch  3344
boucle adversarial fin
boucle adversarial debut-- num batch  3345
boucle adversarial fin
boucle adversarial debut-- num batch  3346
boucle adversarial fin
boucle adversarial debut-- num batch  3347
boucle adversarial fin
boucle adversarial debut-- num batch  3348
boucle adversarial fin
boucle adversarial debut-- num batch  3349
boucle adversarial fin
boucle adversarial debut-- num batch  3350
boucle adversarial fin
boucle adversarial debut-- num batch  3351
boucle adversarial fin
boucle adversarial debut-- num batch  3352
boucle adversarial fin
boucle adversarial debut-- num batch  3353
boucle adversarial fin
boucle adversarial debut-- num batch  3354
boucle adversarial fin
boucle adversarial debut-- num batch  3355
boucle adversarial fin
boucle adversarial debut-- num batch  3356
boucle adversarial fin
boucle adversarial debut-- num batch  3357
boucle adversarial fin
boucle adversarial debut-- num batch  3358
boucle adversarial fin
boucle adversarial debut-- num batch  3359
boucle adversarial fin
boucle adversarial debut-- num batch  3360
boucle adversarial fin
boucle adversarial debut-- num batch  3361

boucle adversarial fin
boucle adversarial debut-- num batch  3362
boucle adversarial fin
boucle adversarial debut-- num batch  3363
boucle adversarial fin
boucle adversarial debut-- num batch  3364
boucle adversarial fin
boucle adversarial debut-- num batch  3365
boucle adversarial fin
boucle adversarial debut-- num batch  3366
boucle adversarial fin
boucle adversarial debut-- num batch  3367
boucle adversarial fin
boucle adversarial debut-- num batch  3368
boucle adversarial fin
boucle adversarial debut-- num batch  3369
boucle adversarial fin
boucle adversarial debut-- num batch  3370
boucle adversarial fin
boucle adversarial debut-- num batch  3371
boucle adversarial fin
boucle adversarial debut-- num batch  3372
boucle adversarial fin
boucle adversarial debut-- num batch  3373
boucle adversarial fin
boucle adversarial debut-- num batch  3374
boucle adversarial fin
boucle adversarial debut-- num batch  3375
boucle adversarial fin
boucle adversarial debut-- num batch  3376
boucle adversarial fin
boucle adversarial debut-- num batch  3377
boucle adversarial fin
boucle adversarial debut-- num batch  3378
boucle adversarial fin
boucle adversarial debut-- num batch  3379
boucle adversarial fin
boucle adversarial debut-- num batch  3380
boucle adversarial fin
boucle adversarial debut-- num batch  3381
boucle adversarial fin
boucle adversarial debut-- num batch  3382
boucle adversarial fin
boucle adversarial debut-- num batch  3383
boucle adversarial fin
boucle adversarial debut-- num batch  3384
boucle adversarial fin
boucle adversarial debut-- num batch  3385
boucle adversarial fin
boucle adversarial debut-- num batch  3386
boucle adversarial fin
boucle adversarial debut-- num batch  3387
boucle adversarial fin
boucle adversarial debut-- num batch  3388
boucle adversarial fin
boucle adversarial debut-- num batch  3389
boucle adversarial fin
boucle adversarial debut-- num batch  3390
boucle adversarial fin
boucle adversarial debut-- num batch  3391
boucle adversarial fin
boucle adversarial debut-- num batch  3392
boucle adversarial fin
boucle adversarial debut-- num batch  3393
boucle adversarial fin
boucle adversarial debut-- num batch  3394
boucle adversarial fin
boucle adversarial debut-- num batch  3395
boucle adversarial fin
boucle adversarial debut-- num batch  3396
boucle adversarial fin
boucle adversarial debut-- num batch  3397
boucle adversarial fin
boucle adversarial debut-- num batch  3398
boucle adversarial fin
boucle adversarial debut-- num batch  3399
boucle adversarial fin
boucle adversarial debut-- num batch  3400
boucle adversarial fin
boucle adversarial debut-- num batch  3401
boucle adversarial fin
boucle adversarial debut-- num batch  3402
boucle adversarial fin
boucle adversarial debut-- num batch  3403
boucle adversarial fin
boucle adversarial debut-- num batch  3404
boucle adversarial fin
boucle adversarial debut-- num batch  3405
boucle adversarial fin
boucle adversarial debut-- num batch  3406
boucle adversarial fin
boucle adversarial debut-- num batch  3407
boucle adversarial fin
boucle adversarial debut-- num batch  3408
boucle adversarial fin
boucle adversarial debut-- num batch  3409
boucle adversarial fin
boucle adversarial debut-- num batch  3410
boucle adversarial fin
boucle adversarial debut-- num batch  3411
boucle adversarial fin
boucle adversarial debut-- num batch  3412
boucle adversarial fin
boucle adversarial debut-- num batch  3413
boucle adversarial fin
boucle adversarial debut-- num batch  3414
boucle adversarial fin
boucle adversarial debut-- num batch  3415
boucle adversarial fin
boucle adversarial debut-- num batch  3416
boucle adversarial fin
boucle adversarial debut-- num batch  3417
boucle adversarial fin
boucle adversarial debut-- num batch  3418
boucle adversarial fin
boucle adversarial debut-- num batch  3419
boucle adversarial fin
boucle adversarial debut-- num batch  3420
boucle adversarial fin
boucle adversarial debut-- num batch  3421
boucle adversarial fin
boucle adversarial debut-- num batch  3422
boucle adversarial fin
boucle adversarial debut-- num batch  3423
boucle adversarial fin
boucle adversarial debut-- num batch  3424
boucle adversarial fin
boucle adversarial debut-- num batch  3425
boucle adversarial fin
boucle adversarial debut-- num batch  3426
boucle adversarial fin
boucle adversarial debut-- num batch  3427
boucle adversarial fin
boucle adversarial debut-- num batch  3428
boucle adversarial fin
boucle adversarial debut-- num batch  3429
boucle adversarial fin
boucle adversarial debut-- num batch  3430
boucle adversarial fin
boucle adversarial debut-- num batch  3431
boucle adversarial fin
boucle adversarial debut-- num batch  3432
boucle adversarial fin
boucle adversarial debut-- num batch  3433
boucle adversarial fin
boucle adversarial debut-- num batch  3434
boucle adversarial fin
boucle adversarial debut-- num batch  3435
boucle adversarial fin
boucle adversarial debut-- num batch  3436
boucle adversarial fin
boucle adversarial debut-- num batch  3437
boucle adversarial fin
boucle adversarial debut-- num batch  3438
boucle adversarial fin
boucle adversarial debut-- num batch  3439
boucle adversarial fin
boucle adversarial debut-- num batch  3440
boucle adversarial fin
boucle adversarial debut-- num batch  3441
boucle adversarial fin
boucle adversarial debut-- num batch  3442
boucle adversarial fin
boucle adversarial debut-- num batch  3443
boucle adversarial fin
boucle adversarial debut-- num batch  3444
boucle adversarial fin
boucle adversarial debut-- num batch  3445
boucle adversarial fin
boucle adversarial debut-- num batch  3446
boucle adversarial fin
boucle adversarial debut-- num batch  3447
boucle adversarial fin
boucle adversarial debut-- num batch  3448
boucle adversarial fin
boucle adversarial debut-- num batch  3449
boucle adversarial fin
boucle adversarial debut-- num batch  3450
boucle adversarial fin
boucle adversarial debut-- num batch  3451
boucle adversarial fin
boucle adversarial debut-- num batch  3452
boucle adversarial fin
boucle adversarial debut-- num batch  3453
boucle adversarial fin
boucle adversarial debut-- num batch  3454
boucle adversarial fin
boucle adversarial debut-- num batch  3455
boucle adversarial fin
boucle adversarial debut-- num batch  3456
boucle adversarial fin
boucle adversarial debut-- num batch  3457
boucle adversarial fin
boucle adversarial debut-- num batch  3458
boucle adversarial fin
boucle adversarial debut-- num batch  3459
boucle adversarial fin
boucle adversarial debut-- num batch  3460
boucle adversarial fin
boucle adversarial debut-- num batch  3461
boucle adversarial fin
boucle adversarial debut-- num batch  3462
boucle adversarial fin
boucle adversarial debut-- num batch  3463
boucle adversarial fin
boucle adversarial debut-- num batch  3464
boucle adversarial fin
boucle adversarial debut-- num batch  3465
boucle adversarial fin
boucle adversarial debut-- num batch  3466
boucle adversarial fin
boucle adversarial debut-- num batch  3467
boucle adversarial fin
boucle adversarial debut-- num batch  3468
boucle adversarial fin
boucle adversarial debut-- num batch  3469
boucle adversarial fin
boucle adversarial debut-- num batch  3470
boucle adversarial fin
boucle adversarial debut-- num batch  3471
boucle adversarial fin
boucle adversarial debut-- num batch  3472
boucle adversarial fin
boucle adversarial debut-- num batch  3473
boucle adversarial fin
boucle adversarial debut-- num batch  3474
boucle adversarial fin
boucle adversarial debut-- num batch  3475
boucle adversarial fin
boucle adversarial debut-- num batch  3476
boucle adversarial fin
boucle adversarial debut-- num batch  3477
boucle adversarial fin
boucle adversarial debut-- num batch  3478
boucle adversarial fin
boucle adversarial debut-- num batch  3479
boucle adversarial fin
boucle adversarial debut-- num batch  3480
boucle adversarial fin
boucle adversarial debut-- num batch  3481
boucle adversarial fin
boucle adversarial debut-- num batch  3482
boucle adversarial fin
boucle adversarial debut-- num batch  3483
boucle adversarial fin
boucle adversarial debut-- num batch  3484
boucle adversarial fin
boucle adversarial debut-- num batch  3485
boucle adversarial fin
boucle adversarial debut-- num batch  3486

boucle adversarial fin
boucle adversarial debut-- num batch  3487
boucle adversarial fin
boucle adversarial debut-- num batch  3488
boucle adversarial fin
boucle adversarial debut-- num batch  3489
boucle adversarial fin
boucle adversarial debut-- num batch  3490
boucle adversarial fin
boucle adversarial debut-- num batch  3491
boucle adversarial fin
boucle adversarial debut-- num batch  3492
boucle adversarial fin
boucle adversarial debut-- num batch  3493
boucle adversarial fin
boucle adversarial debut-- num batch  3494
boucle adversarial fin
boucle adversarial debut-- num batch  3495
boucle adversarial fin
boucle adversarial debut-- num batch  3496
boucle adversarial fin
boucle adversarial debut-- num batch  3497
boucle adversarial fin
boucle adversarial debut-- num batch  3498
boucle adversarial fin
boucle adversarial debut-- num batch  3499
boucle adversarial fin
boucle adversarial debut-- num batch  3500
boucle adversarial fin
boucle adversarial debut-- num batch  3501
boucle adversarial fin
boucle adversarial debut-- num batch  3502
boucle adversarial fin
boucle adversarial debut-- num batch  3503
boucle adversarial fin
boucle adversarial debut-- num batch  3504
boucle adversarial fin
boucle adversarial debut-- num batch  3505
boucle adversarial fin
boucle adversarial debut-- num batch  3506
boucle adversarial fin
boucle adversarial debut-- num batch  3507
boucle adversarial fin
boucle adversarial debut-- num batch  3508
boucle adversarial fin
boucle adversarial debut-- num batch  3509
boucle adversarial fin
boucle adversarial debut-- num batch  3510
boucle adversarial fin
boucle adversarial debut-- num batch  3511
boucle adversarial fin
boucle adversarial debut-- num batch  3512
boucle adversarial fin
boucle adversarial debut-- num batch  3513
boucle adversarial fin
boucle adversarial debut-- num batch  3514
boucle adversarial fin
boucle adversarial debut-- num batch  3515
boucle adversarial fin
boucle adversarial debut-- num batch  3516
boucle adversarial fin
boucle adversarial debut-- num batch  3517
boucle adversarial fin
boucle adversarial debut-- num batch  3518
boucle adversarial fin
boucle adversarial debut-- num batch  3519
boucle adversarial fin
boucle adversarial debut-- num batch  3520
boucle adversarial fin
boucle adversarial debut-- num batch  3521
boucle adversarial fin
boucle adversarial debut-- num batch  3522
boucle adversarial fin
boucle adversarial debut-- num batch  3523
boucle adversarial fin
boucle adversarial debut-- num batch  3524
boucle adversarial fin
boucle adversarial debut-- num batch  3525
boucle adversarial fin
boucle adversarial debut-- num batch  3526
boucle adversarial fin
boucle adversarial debut-- num batch  3527
boucle adversarial fin
boucle adversarial debut-- num batch  3528
boucle adversarial fin
boucle adversarial debut-- num batch  3529
boucle adversarial fin
boucle adversarial debut-- num batch  3530
boucle adversarial fin
boucle adversarial debut-- num batch  3531
boucle adversarial fin
boucle adversarial debut-- num batch  3532
boucle adversarial fin
boucle adversarial debut-- num batch  3533
boucle adversarial fin
boucle adversarial debut-- num batch  3534
boucle adversarial fin
boucle adversarial debut-- num batch  3535
boucle adversarial fin
boucle adversarial debut-- num batch  3536
boucle adversarial fin
boucle adversarial debut-- num batch  3537
boucle adversarial fin
boucle adversarial debut-- num batch  3538
boucle adversarial fin
boucle adversarial debut-- num batch  3539
boucle adversarial fin
boucle adversarial debut-- num batch  3540
boucle adversarial fin
boucle adversarial debut-- num batch  3541
boucle adversarial fin
boucle adversarial debut-- num batch  3542
boucle adversarial fin
boucle adversarial debut-- num batch  3543
boucle adversarial fin
boucle adversarial debut-- num batch  3544
boucle adversarial fin
boucle adversarial debut-- num batch  3545
boucle adversarial fin
boucle adversarial debut-- num batch  3546
boucle adversarial fin
boucle adversarial debut-- num batch  3547
boucle adversarial fin
boucle adversarial debut-- num batch  3548
boucle adversarial fin
boucle adversarial debut-- num batch  3549
boucle adversarial fin
boucle adversarial debut-- num batch  3550
boucle adversarial fin
boucle adversarial debut-- num batch  3551
boucle adversarial fin
boucle adversarial debut-- num batch  3552
boucle adversarial fin
boucle adversarial debut-- num batch  3553
boucle adversarial fin
boucle adversarial debut-- num batch  3554
boucle adversarial fin
boucle adversarial debut-- num batch  3555
boucle adversarial fin
boucle adversarial debut-- num batch  3556
boucle adversarial fin
boucle adversarial debut-- num batch  3557
boucle adversarial fin
boucle adversarial debut-- num batch  3558
boucle adversarial fin
boucle adversarial debut-- num batch  3559
boucle adversarial fin
boucle adversarial debut-- num batch  3560
boucle adversarial fin
boucle adversarial debut-- num batch  3561
boucle adversarial fin
boucle adversarial debut-- num batch  3562
boucle adversarial fin
boucle adversarial debut-- num batch  3563
boucle adversarial fin
boucle adversarial debut-- num batch  3564
boucle adversarial fin
boucle adversarial debut-- num batch  3565
boucle adversarial fin
boucle adversarial debut-- num batch  3566
boucle adversarial fin
boucle adversarial debut-- num batch  3567
boucle adversarial fin
boucle adversarial debut-- num batch  3568
boucle adversarial fin
boucle adversarial debut-- num batch  3569
boucle adversarial fin
boucle adversarial debut-- num batch  3570
boucle adversarial fin
boucle adversarial debut-- num batch  3571
boucle adversarial fin
boucle adversarial debut-- num batch  3572
boucle adversarial fin
boucle adversarial debut-- num batch  3573
boucle adversarial fin
boucle adversarial debut-- num batch  3574
boucle adversarial fin
boucle adversarial debut-- num batch  3575
boucle adversarial fin
boucle adversarial debut-- num batch  3576
boucle adversarial fin
boucle adversarial debut-- num batch  3577
boucle adversarial fin
boucle adversarial debut-- num batch  3578
boucle adversarial fin
boucle adversarial debut-- num batch  3579
boucle adversarial fin
boucle adversarial debut-- num batch  3580
boucle adversarial fin
boucle adversarial debut-- num batch  3581
boucle adversarial fin
boucle adversarial debut-- num batch  3582
boucle adversarial fin
boucle adversarial debut-- num batch  3583
boucle adversarial fin
boucle adversarial debut-- num batch  3584
boucle adversarial fin
boucle adversarial debut-- num batch  3585
boucle adversarial fin
boucle adversarial debut-- num batch  3586
boucle adversarial fin
boucle adversarial debut-- num batch  3587
boucle adversarial fin
boucle adversarial debut-- num batch  3588
boucle adversarial fin
boucle adversarial debut-- num batch  3589
boucle adversarial fin
boucle adversarial debut-- num batch  3590
boucle adversarial fin
boucle adversarial debut-- num batch  3591
boucle adversarial fin
boucle adversarial debut-- num batch  3592
boucle adversarial fin
boucle adversarial debut-- num batch  3593
boucle adversarial fin
boucle adversarial debut-- num batch  3594
boucle adversarial fin
boucle adversarial debut-- num batch  3595
boucle adversarial fin
boucle adversarial debut-- num batch  3596
boucle adversarial fin
boucle adversarial debut-- num batch  3597
boucle adversarial fin
boucle adversarial debut-- num batch  3598
boucle adversarial fin
boucle adversarial debut-- num batch  3599
boucle adversarial fin
boucle adversarial debut-- num batch  3600
boucle adversarial fin
boucle adversarial debut-- num batch  3601
boucle adversarial fin
boucle adversarial debut-- num batch  3602
boucle adversarial fin
boucle adversarial debut-- num batch  3603
boucle adversarial fin
boucle adversarial debut-- num batch  3604
boucle adversarial fin
boucle adversarial debut-- num batch  3605
boucle adversarial fin
boucle adversarial debut-- num batch  3606
boucle adversarial fin
boucle adversarial debut-- num batch  3607
boucle adversarial fin
boucle adversarial debut-- num batch  3608
boucle adversarial fin
boucle adversarial debut-- num batch  3609
boucle adversarial fin
boucle adversarial debut-- num batch  3610
boucle adversarial fin
boucle adversarial debut-- num batch  3611

boucle adversarial fin
boucle adversarial debut-- num batch  3612
boucle adversarial fin
boucle adversarial debut-- num batch  3613
boucle adversarial fin
boucle adversarial debut-- num batch  3614
boucle adversarial fin
boucle adversarial debut-- num batch  3615
boucle adversarial fin
boucle adversarial debut-- num batch  3616
boucle adversarial fin
boucle adversarial debut-- num batch  3617
boucle adversarial fin
boucle adversarial debut-- num batch  3618
boucle adversarial fin
boucle adversarial debut-- num batch  3619
boucle adversarial fin
boucle adversarial debut-- num batch  3620
boucle adversarial fin
boucle adversarial debut-- num batch  3621
boucle adversarial fin
boucle adversarial debut-- num batch  3622
boucle adversarial fin
boucle adversarial debut-- num batch  3623
boucle adversarial fin
boucle adversarial debut-- num batch  3624
boucle adversarial fin
boucle adversarial debut-- num batch  3625
boucle adversarial fin
boucle adversarial debut-- num batch  3626
boucle adversarial fin
boucle adversarial debut-- num batch  3627
boucle adversarial fin
boucle adversarial debut-- num batch  3628
boucle adversarial fin
boucle adversarial debut-- num batch  3629
boucle adversarial fin
boucle adversarial debut-- num batch  3630
boucle adversarial fin
boucle adversarial debut-- num batch  3631
boucle adversarial fin
boucle adversarial debut-- num batch  3632
boucle adversarial fin
boucle adversarial debut-- num batch  3633
boucle adversarial fin
boucle adversarial debut-- num batch  3634
boucle adversarial fin
boucle adversarial debut-- num batch  3635
boucle adversarial fin
boucle adversarial debut-- num batch  3636
boucle adversarial fin
boucle adversarial debut-- num batch  3637
boucle adversarial fin
boucle adversarial debut-- num batch  3638
boucle adversarial fin
boucle adversarial debut-- num batch  3639
boucle adversarial fin
boucle adversarial debut-- num batch  3640
boucle adversarial fin
boucle adversarial debut-- num batch  3641
boucle adversarial fin
boucle adversarial debut-- num batch  3642
boucle adversarial fin
boucle adversarial debut-- num batch  3643
boucle adversarial fin
boucle adversarial debut-- num batch  3644
boucle adversarial fin
boucle adversarial debut-- num batch  3645
boucle adversarial fin
boucle adversarial debut-- num batch  3646
boucle adversarial fin
boucle adversarial debut-- num batch  3647
boucle adversarial fin
boucle adversarial debut-- num batch  3648
boucle adversarial fin
boucle adversarial debut-- num batch  3649
boucle adversarial fin
boucle adversarial debut-- num batch  3650
boucle adversarial fin
boucle adversarial debut-- num batch  3651
boucle adversarial fin
boucle adversarial debut-- num batch  3652
boucle adversarial fin
boucle adversarial debut-- num batch  3653
boucle adversarial fin
boucle adversarial debut-- num batch  3654
boucle adversarial fin
boucle adversarial debut-- num batch  3655
boucle adversarial fin
boucle adversarial debut-- num batch  3656
boucle adversarial fin
boucle adversarial debut-- num batch  3657
boucle adversarial fin
boucle adversarial debut-- num batch  3658
boucle adversarial fin
boucle adversarial debut-- num batch  3659
boucle adversarial fin
boucle adversarial debut-- num batch  3660
boucle adversarial fin
boucle adversarial debut-- num batch  3661
boucle adversarial fin
boucle adversarial debut-- num batch  3662
boucle adversarial fin
boucle adversarial debut-- num batch  3663
boucle adversarial fin
boucle adversarial debut-- num batch  3664
boucle adversarial fin
boucle adversarial debut-- num batch  3665
boucle adversarial fin
boucle adversarial debut-- num batch  3666
boucle adversarial fin
boucle adversarial debut-- num batch  3667
boucle adversarial fin
boucle adversarial debut-- num batch  3668
boucle adversarial fin
boucle adversarial debut-- num batch  3669
boucle adversarial fin
boucle adversarial debut-- num batch  3670
boucle adversarial fin
boucle adversarial debut-- num batch  3671
boucle adversarial fin
boucle adversarial debut-- num batch  3672
boucle adversarial fin
boucle adversarial debut-- num batch  3673
boucle adversarial fin
boucle adversarial debut-- num batch  3674
boucle adversarial fin
boucle adversarial debut-- num batch  3675
boucle adversarial fin
boucle adversarial debut-- num batch  3676
boucle adversarial fin
boucle adversarial debut-- num batch  3677
boucle adversarial fin
boucle adversarial debut-- num batch  3678
boucle adversarial fin
boucle adversarial debut-- num batch  3679
boucle adversarial fin
boucle adversarial debut-- num batch  3680
boucle adversarial fin
boucle adversarial debut-- num batch  3681
boucle adversarial fin
boucle adversarial debut-- num batch  3682
boucle adversarial fin
boucle adversarial debut-- num batch  3683
boucle adversarial fin
boucle adversarial debut-- num batch  3684
boucle adversarial fin
boucle adversarial debut-- num batch  3685
boucle adversarial fin
boucle adversarial debut-- num batch  3686
boucle adversarial fin
boucle adversarial debut-- num batch  3687
boucle adversarial fin
boucle adversarial debut-- num batch  3688
boucle adversarial fin
boucle adversarial debut-- num batch  3689
boucle adversarial fin
boucle adversarial debut-- num batch  3690
boucle adversarial fin
boucle adversarial debut-- num batch  3691
boucle adversarial fin
boucle adversarial debut-- num batch  3692
boucle adversarial fin
boucle adversarial debut-- num batch  3693
boucle adversarial fin
boucle adversarial debut-- num batch  3694
boucle adversarial fin
boucle adversarial debut-- num batch  3695
boucle adversarial fin
boucle adversarial debut-- num batch  3696
boucle adversarial fin
boucle adversarial debut-- num batch  3697
boucle adversarial fin
boucle adversarial debut-- num batch  3698
boucle adversarial fin
boucle adversarial debut-- num batch  3699
boucle adversarial fin
boucle adversarial debut-- num batch  3700
boucle adversarial fin
boucle adversarial debut-- num batch  3701
boucle adversarial fin
boucle adversarial debut-- num batch  3702
boucle adversarial fin
boucle adversarial debut-- num batch  3703
boucle adversarial fin
boucle adversarial debut-- num batch  3704
boucle adversarial fin
boucle adversarial debut-- num batch  3705
boucle adversarial fin
boucle adversarial debut-- num batch  3706
boucle adversarial fin
boucle adversarial debut-- num batch  3707
boucle adversarial fin
boucle adversarial debut-- num batch  3708
boucle adversarial fin
boucle adversarial debut-- num batch  3709
boucle adversarial fin
boucle adversarial debut-- num batch  3710
boucle adversarial fin
boucle adversarial debut-- num batch  3711
boucle adversarial fin
boucle adversarial debut-- num batch  3712
boucle adversarial fin
boucle adversarial debut-- num batch  3713
boucle adversarial fin
boucle adversarial debut-- num batch  3714
boucle adversarial fin
boucle adversarial debut-- num batch  3715
boucle adversarial fin
boucle adversarial debut-- num batch  3716
boucle adversarial fin
boucle adversarial debut-- num batch  3717
boucle adversarial fin
boucle adversarial debut-- num batch  3718
boucle adversarial fin
boucle adversarial debut-- num batch  3719
boucle adversarial fin
boucle adversarial debut-- num batch  3720
boucle adversarial fin
boucle adversarial debut-- num batch  3721
boucle adversarial fin
boucle adversarial debut-- num batch  3722
boucle adversarial fin
boucle adversarial debut-- num batch  3723
boucle adversarial fin
boucle adversarial debut-- num batch  3724
boucle adversarial fin
boucle adversarial debut-- num batch  3725
boucle adversarial fin
boucle adversarial debut-- num batch  3726
boucle adversarial fin
boucle adversarial debut-- num batch  3727
boucle adversarial fin
boucle adversarial debut-- num batch  3728
boucle adversarial fin
boucle adversarial debut-- num batch  3729
boucle adversarial fin
boucle adversarial debut-- num batch  3730
boucle adversarial fin
boucle adversarial debut-- num batch  3731
boucle adversarial fin
boucle adversarial debut-- num batch  3732
boucle adversarial fin
boucle adversarial debut-- num batch  3733
boucle adversarial fin
boucle adversarial debut-- num batch  3734
boucle adversarial fin
boucle adversarial debut-- num batch  3735
boucle adversarial fin
boucle adversarial debut-- num batch  3736

boucle adversarial fin
boucle adversarial debut-- num batch  3737
boucle adversarial fin
boucle adversarial debut-- num batch  3738
boucle adversarial fin
boucle adversarial debut-- num batch  3739
boucle adversarial fin
boucle adversarial debut-- num batch  3740
boucle adversarial fin
boucle adversarial debut-- num batch  3741
boucle adversarial fin
boucle adversarial debut-- num batch  3742
boucle adversarial fin
boucle adversarial debut-- num batch  3743
boucle adversarial fin
boucle adversarial debut-- num batch  3744
boucle adversarial fin
boucle adversarial debut-- num batch  3745
boucle adversarial fin
boucle adversarial debut-- num batch  3746
boucle adversarial fin
boucle adversarial debut-- num batch  3747
boucle adversarial fin
boucle adversarial debut-- num batch  3748
boucle adversarial fin
boucle adversarial debut-- num batch  3749
boucle adversarial fin
boucle adversarial debut-- num batch  3750
boucle adversarial fin
boucle adversarial debut-- num batch  3751
boucle adversarial fin
boucle adversarial debut-- num batch  3752
boucle adversarial fin
boucle adversarial debut-- num batch  3753
boucle adversarial fin
boucle adversarial debut-- num batch  3754
boucle adversarial fin
boucle adversarial debut-- num batch  3755
boucle adversarial fin
boucle adversarial debut-- num batch  3756
boucle adversarial fin
boucle adversarial debut-- num batch  3757
boucle adversarial fin
boucle adversarial debut-- num batch  3758
boucle adversarial fin
boucle adversarial debut-- num batch  3759
boucle adversarial fin
boucle adversarial debut-- num batch  3760
boucle adversarial fin
boucle adversarial debut-- num batch  3761
boucle adversarial fin
boucle adversarial debut-- num batch  3762
boucle adversarial fin
boucle adversarial debut-- num batch  3763
boucle adversarial fin
boucle adversarial debut-- num batch  3764
boucle adversarial fin
boucle adversarial debut-- num batch  3765
boucle adversarial fin
boucle adversarial debut-- num batch  3766
boucle adversarial fin
boucle adversarial debut-- num batch  3767
boucle adversarial fin
boucle adversarial debut-- num batch  3768
boucle adversarial fin
boucle adversarial debut-- num batch  3769
boucle adversarial fin
boucle adversarial debut-- num batch  3770
boucle adversarial fin
boucle adversarial debut-- num batch  3771
boucle adversarial fin
boucle adversarial debut-- num batch  3772
boucle adversarial fin
boucle adversarial debut-- num batch  3773
boucle adversarial fin
boucle adversarial debut-- num batch  3774
boucle adversarial fin
boucle adversarial debut-- num batch  3775
boucle adversarial fin
boucle adversarial debut-- num batch  3776
boucle adversarial fin
boucle adversarial debut-- num batch  3777
boucle adversarial fin
boucle adversarial debut-- num batch  3778
boucle adversarial fin
boucle adversarial debut-- num batch  3779
boucle adversarial fin
boucle adversarial debut-- num batch  3780
boucle adversarial fin
boucle adversarial debut-- num batch  3781
boucle adversarial fin
boucle adversarial debut-- num batch  3782
boucle adversarial fin
boucle adversarial debut-- num batch  3783
boucle adversarial fin
boucle adversarial debut-- num batch  3784
boucle adversarial fin
boucle adversarial debut-- num batch  3785
boucle adversarial fin
boucle adversarial debut-- num batch  3786
boucle adversarial fin
boucle adversarial debut-- num batch  3787
boucle adversarial fin
boucle adversarial debut-- num batch  3788
boucle adversarial fin
boucle adversarial debut-- num batch  3789
boucle adversarial fin
boucle adversarial debut-- num batch  3790
boucle adversarial fin
boucle adversarial debut-- num batch  3791
boucle adversarial fin
boucle adversarial debut-- num batch  3792
boucle adversarial fin
boucle adversarial debut-- num batch  3793
boucle adversarial fin
boucle adversarial debut-- num batch  3794
boucle adversarial fin
boucle adversarial debut-- num batch  3795
boucle adversarial fin
boucle adversarial debut-- num batch  3796
boucle adversarial fin
boucle adversarial debut-- num batch  3797
boucle adversarial fin
boucle adversarial debut-- num batch  3798
boucle adversarial fin
boucle adversarial debut-- num batch  3799
boucle adversarial fin
boucle adversarial debut-- num batch  3800
boucle adversarial fin
boucle adversarial debut-- num batch  3801
boucle adversarial fin
boucle adversarial debut-- num batch  3802
boucle adversarial fin
boucle adversarial debut-- num batch  3803
boucle adversarial fin
boucle adversarial debut-- num batch  3804
boucle adversarial fin
boucle adversarial debut-- num batch  3805
boucle adversarial fin
boucle adversarial debut-- num batch  3806
boucle adversarial fin
boucle adversarial debut-- num batch  3807
boucle adversarial fin
boucle adversarial debut-- num batch  3808
boucle adversarial fin
boucle adversarial debut-- num batch  3809
boucle adversarial fin
boucle adversarial debut-- num batch  3810
boucle adversarial fin
boucle adversarial debut-- num batch  3811
boucle adversarial fin
boucle adversarial debut-- num batch  3812
boucle adversarial fin
boucle adversarial debut-- num batch  3813
boucle adversarial fin
boucle adversarial debut-- num batch  3814
boucle adversarial fin
boucle adversarial debut-- num batch  3815
boucle adversarial fin
boucle adversarial debut-- num batch  3816
boucle adversarial fin
boucle adversarial debut-- num batch  3817
boucle adversarial fin
boucle adversarial debut-- num batch  3818
boucle adversarial fin
boucle adversarial debut-- num batch  3819
boucle adversarial fin
boucle adversarial debut-- num batch  3820
boucle adversarial fin
boucle adversarial debut-- num batch  3821
boucle adversarial fin
boucle adversarial debut-- num batch  3822
boucle adversarial fin
boucle adversarial debut-- num batch  3823
boucle adversarial fin
boucle adversarial debut-- num batch  3824
boucle adversarial fin
boucle adversarial debut-- num batch  3825
boucle adversarial fin
boucle adversarial debut-- num batch  3826
boucle adversarial fin
boucle adversarial debut-- num batch  3827
boucle adversarial fin
boucle adversarial debut-- num batch  3828
boucle adversarial fin
boucle adversarial debut-- num batch  3829
boucle adversarial fin
boucle adversarial debut-- num batch  3830
boucle adversarial fin
boucle adversarial debut-- num batch  3831
boucle adversarial fin
boucle adversarial debut-- num batch  3832
boucle adversarial fin
boucle adversarial debut-- num batch  3833
boucle adversarial fin
boucle adversarial debut-- num batch  3834
boucle adversarial fin
boucle adversarial debut-- num batch  3835
boucle adversarial fin
boucle adversarial debut-- num batch  3836
boucle adversarial fin
boucle adversarial debut-- num batch  3837
boucle adversarial fin
boucle adversarial debut-- num batch  3838
boucle adversarial fin
boucle adversarial debut-- num batch  3839
boucle adversarial fin
boucle adversarial debut-- num batch  3840
boucle adversarial fin
boucle adversarial debut-- num batch  3841
boucle adversarial fin
boucle adversarial debut-- num batch  3842
boucle adversarial fin
boucle adversarial debut-- num batch  3843
boucle adversarial fin
boucle adversarial debut-- num batch  3844
boucle adversarial fin
boucle adversarial debut-- num batch  3845
boucle adversarial fin
boucle adversarial debut-- num batch  3846
boucle adversarial fin
boucle adversarial debut-- num batch  3847
boucle adversarial fin
boucle adversarial debut-- num batch  3848
boucle adversarial fin
boucle adversarial debut-- num batch  3849
boucle adversarial fin
boucle adversarial debut-- num batch  3850
boucle adversarial fin
boucle adversarial debut-- num batch  3851
boucle adversarial fin
boucle adversarial debut-- num batch  3852
boucle adversarial fin
boucle adversarial debut-- num batch  3853
boucle adversarial fin
boucle adversarial debut-- num batch  3854
boucle adversarial fin
boucle adversarial debut-- num batch  3855
boucle adversarial fin
boucle adversarial debut-- num batch  3856
boucle adversarial fin
boucle adversarial debut-- num batch  3857
boucle adversarial fin
boucle adversarial debut-- num batch  3858
boucle adversarial fin
boucle adversarial debut-- num batch  3859
boucle adversarial fin
boucle adversarial debut-- num batch  3860
boucle adversarial fin
boucle adversarial debut-- num batch  3861

boucle adversarial fin
boucle adversarial debut-- num batch  3862
boucle adversarial fin
boucle adversarial debut-- num batch  3863
boucle adversarial fin
boucle adversarial debut-- num batch  3864
boucle adversarial fin
boucle adversarial debut-- num batch  3865
boucle adversarial fin
boucle adversarial debut-- num batch  3866
boucle adversarial fin
boucle adversarial debut-- num batch  3867
boucle adversarial fin
boucle adversarial debut-- num batch  3868
boucle adversarial fin
boucle adversarial debut-- num batch  3869
boucle adversarial fin
boucle adversarial debut-- num batch  3870
boucle adversarial fin
boucle adversarial debut-- num batch  3871
boucle adversarial fin
boucle adversarial debut-- num batch  3872
boucle adversarial fin
boucle adversarial debut-- num batch  3873
boucle adversarial fin
boucle adversarial debut-- num batch  3874
boucle adversarial fin
boucle adversarial debut-- num batch  3875
boucle adversarial fin
boucle adversarial debut-- num batch  3876
boucle adversarial fin
boucle adversarial debut-- num batch  3877
boucle adversarial fin
boucle adversarial debut-- num batch  3878
boucle adversarial fin
boucle adversarial debut-- num batch  3879
boucle adversarial fin
boucle adversarial debut-- num batch  3880
boucle adversarial fin
boucle adversarial debut-- num batch  3881
boucle adversarial fin
boucle adversarial debut-- num batch  3882
boucle adversarial fin
boucle adversarial debut-- num batch  3883
boucle adversarial fin
boucle adversarial debut-- num batch  3884
boucle adversarial fin
boucle adversarial debut-- num batch  3885
boucle adversarial fin
boucle adversarial debut-- num batch  3886
boucle adversarial fin
boucle adversarial debut-- num batch  3887
boucle adversarial fin
boucle adversarial debut-- num batch  3888
boucle adversarial fin
boucle adversarial debut-- num batch  3889
boucle adversarial fin
boucle adversarial debut-- num batch  3890
boucle adversarial fin
boucle adversarial debut-- num batch  3891
boucle adversarial fin
boucle adversarial debut-- num batch  3892
boucle adversarial fin
boucle adversarial debut-- num batch  3893
boucle adversarial fin
boucle adversarial debut-- num batch  3894
boucle adversarial fin
boucle adversarial debut-- num batch  3895
boucle adversarial fin
boucle adversarial debut-- num batch  3896
boucle adversarial fin
boucle adversarial debut-- num batch  3897
boucle adversarial fin
boucle adversarial debut-- num batch  3898
boucle adversarial fin
boucle adversarial debut-- num batch  3899
boucle adversarial fin
boucle adversarial debut-- num batch  3900
boucle adversarial fin
boucle adversarial debut-- num batch  3901
boucle adversarial fin
boucle adversarial debut-- num batch  3902
boucle adversarial fin
boucle adversarial debut-- num batch  3903
boucle adversarial fin
boucle adversarial debut-- num batch  3904
boucle adversarial fin
boucle adversarial debut-- num batch  3905
boucle adversarial fin
boucle adversarial debut-- num batch  3906
boucle adversarial fin
boucle adversarial debut-- num batch  3907
boucle adversarial fin
boucle adversarial debut-- num batch  3908
boucle adversarial fin
boucle adversarial debut-- num batch  3909
boucle adversarial fin
boucle adversarial debut-- num batch  3910
boucle adversarial fin
boucle adversarial debut-- num batch  3911
boucle adversarial fin
boucle adversarial debut-- num batch  3912
boucle adversarial fin
boucle adversarial debut-- num batch  3913
boucle adversarial fin
boucle adversarial debut-- num batch  3914
boucle adversarial fin
boucle adversarial debut-- num batch  3915
boucle adversarial fin
boucle adversarial debut-- num batch  3916
boucle adversarial fin
boucle adversarial debut-- num batch  3917
boucle adversarial fin
Training // Epoch 2 //  Total r_cost = 2799917.24231  Total s_cost = 1360.08607  Total s_mean = -0.02180  Total s_std = 3913.73248  Total a_cost = 632.33772 Training time : 74160992 ms negative Sampling time : 174950 ms negative samples : 4011610
precision_1	[0.2250000],	||	 precision_5	[0.1903642],	||	 precision_10	[0.1738079],	||	 precision_15	[0.1609603]
recall_1   	[0.0079383],	||	 recall_5   	[0.0339846],	||	 recall_10   	[0.0616546],	||	 recall_15   	[0.0856548]
f_measure_1	[0.0153355],	||	 f_measure_5	[0.0576732],	||	 f_measure_10	[0.0910214],	||	 f_measure_15	[0.1118100]
ndcg_1     	[0.2250000],	||	 ndcg_5     	[0.1972000],	||	 ndcg_10     	[0.1873616],	||	 ndcg_15     	[0.1825655]
Metrics for user type	 M
precision_1	[0.2641422],	||	 precision_5	[0.2106673],	||	 precision_10	[0.1901178],	||	 precision_15	[0.1753406]
recall_1	[0.0093639],	||	 recall_5	[0.0367411],	||	 recall_10	[0.0648360],	||	 recall_15	[0.0896665]
ndcg_1	[0.2641422],	||	 ndcg_5	[0.2213983],	||	 ndcg_10	[0.2074611],	||	 ndcg_15	[0.2006979]
AUC per user type	[0.8342900]
Metrics for user type	 F
precision_1	[0.1258046],	||	 precision_5	[0.1389116],	||	 precision_10	[0.1324751],	||	 precision_15	[0.1245173]
recall_1	[0.0043255],	||	 recall_5	[0.0269990],	||	 recall_10	[0.0535923],	||	 recall_15	[0.0754882]
ndcg_1	[0.1258046],	||	 ndcg_5	[0.1358762],	||	 ndcg_10	[0.1364246],	||	 ndcg_15	[0.1366137]
AUC per user type	[0.8017667]
AUC global is:  0.825087671250574
precision_1	[0.2250000],	||	 precision_5	[0.1903642],	||	 precision_10	[0.1738079],	||	 precision_15	[0.1609603]
recall_1   	[0.0079383],	||	 recall_5   	[0.0339846],	||	 recall_10   	[0.0616546],	||	 recall_15   	[0.0856548]
f_measure_1	[0.0153355],	||	 f_measure_5	[0.0576732],	||	 f_measure_10	[0.0910214],	||	 f_measure_15	[0.1118100]
ndcg_1     	[0.2250000],	||	 ndcg_5     	[0.1972000],	||	 ndcg_10     	[0.1873616],	||	 ndcg_15     	[0.1825655]

In [30]:
# [precision, recall, f_score, NDCG] = utility.test_model_all(Recom, test_df, train_df)

# utility.test_model_per_user_type(Recom, test_df, train_df, user_type_list, key_type)
# auc = utility.auc_per_user(Recom, test_df, train_df)
# print("AUC global is: ", auc)

precision_1	[0.2250000],	||	 precision_5	[0.1903642],	||	 precision_10	[0.1738079],	||	 precision_15	[0.1609603]
recall_1   	[0.0079383],	||	 recall_5   	[0.0339846],	||	 recall_10   	[0.0616546],	||	 recall_15   	[0.0856548]
f_measure_1	[0.0153355],	||	 f_measure_5	[0.0576732],	||	 f_measure_10	[0.0910214],	||	 f_measure_15	[0.1118100]
ndcg_1     	[0.2250000],	||	 ndcg_5     	[0.1972000],	||	 ndcg_10     	[0.1873616],	||	 ndcg_15     	[0.1825655]
Metrics for user type	 M
precision_1	[0.2641422],	||	 precision_5	[0.2106673],	||	 precision_10	[0.1901178],	||	 precision_15	[0.1753406]
recall_1	[0.0093639],	||	 recall_5	[0.0367411],	||	 recall_10	[0.0648360],	||	 recall_15	[0.0896665]
ndcg_1	[0.2641422],	||	 ndcg_5	[0.2213983],	||	 ndcg_10	[0.2074611],	||	 ndcg_15	[0.2006979]
AUC per user type	[0.8342900]
Metrics for user type	 F
precision_1	[0.1258046],	||	 precision_5	[0.1389116],	||	 precision_10	[0.1324751],	||	 precision_15	[0.1245173]
recall_1	[0.0043255],	||	 recall_5	[0.0269990],	||	 recall_10	[0.0535923],	||	 recall_15	[0.0754882]
ndcg_1	[0.1258046],	||	 ndcg_5	[0.1358762],	||	 ndcg_10	[0.1364246],	||	 ndcg_15	[0.1366137]
AUC per user type	[0.8017667]
AUC global is:  0.825087671250574

In [31]:
import matplotlib.pyplot as plt
import pandas as pd
from colour import Color

def savepdf_barplot_color_gradient(ymin = 0.5, ymax = 0.7, whis = 5, start_color='pink',end_color='blue',num_color=5, title='',axis_x = None, xlabel = '', axis_y1 = None, ylabel ='', plot_file = ''):
    
    fig = plt.figure()
    gs = fig.add_gridspec(1, 2, hspace=0, wspace=0)
    (ax1, ax2) = gs.subplots(sharex='col', sharey='row')
    
    red = Color(start_color)
    colors = list(red.range_to(Color(end_color), num_color))
    colors = [color.rgb for color in colors]
    
    X_axis = np.arange(len(axis_x))
    ax1.bar(X_axis, axis_y1, color=colors)
    ax1.hlines(y=axis_y1[0], xmin = 0, xmax = len(axis_x)-1, colors='black', linestyles='--', lw=1)
    
    plt.sca(ax1)
    plt.xticks(X_axis, axis_x, rotation =50)
    #plt.xlabel(xlabel)
    #fig.suptitle(title)
    plt.ylabel(ylabel, fontsize=18)
    plt.rcParams.update({'font.size': 13}) 
    plt.grid()
    
    plt.sca(ax2)
    ax2.boxplot(axis_y1, whis = whis)
    ax1.set_ylim(ymin, ymax)
    
    plt.tight_layout()
    plt.savefig(plot_file)

def savepdf_barplot_color_gradient2(start_color='pink',end_color='blue',num_color=20, title='',axis_x = None, xlabel = '', axis_y1 = None, ylabel ='', plot_file = ''):
    
    red = Color(start_color)
    colors = list(red.range_to(Color(end_color), num_color))
    colors = [color.rgb for color in colors]
    
    X_axis = np.arange(len(axis_x))
    plt.bar(X_axis, axis_y1, color=colors)
    
    
    plt.xticks(X_axis, axis_x, rotation =70)
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    plt.title(title)
    plt.grid()
    
   # plt.tight_layout()
    plt.savefig(plot_file)