In [34]:
import json
import numpy as np
import pandas as pd
import pickle5 as pickle
import copy

In [35]:
#pip show pickle5

In [36]:
rdf_all = pd.read_csv('./modcloth/df_modcloth.csv', sep=",")
rdf_all['user_id'] = rdf_all['user_id'].astype('category').cat.codes
rdf_all.head(100)

,item_id,user_id,rating,timestamp,size,fit,user_attr,model_attr,category,brand,year,split
0,7443,309,4,2010-01-21 08:00:00+00:00,NaN,NaN,Small,Small,Dresses,NaN,2012,0
1,7443,13009,3,2010-01-27 08:00:00+00:00,NaN,NaN,NaN,Small,Dresses,NaN,2012,0
2,7443,5534,4,2010-01-29 08:00:00+00:00,NaN,NaN,Small,Small,Dresses,NaN,2012,0
3,7443,1716,4,2010-02-13 08:00:00+00:00,NaN,NaN,NaN,Small,Dresses,NaN,2012,0
4,7443,42071,4,2010-02-18 08:00:00+00:00,NaN,NaN,Small,Small,Dresses,NaN,2012,0
...,...,...,...,...,...,...,...,...,...,...,...,...
95,7443,384,4,2010-11-06 07:00:00+00:00,NaN,Slightly small,Small,Small,Dresses,NaN,2012,0
96,7443,10111,3,2010-11-06 07:00:00+00:00,NaN,Slightly small,NaN,Small,Dresses,NaN,2012,0
97,7443,26577,4,2010-11-06 07:00:00+00:00,NaN,Just right,Large,Small,Dresses,NaN,2012,0
98,11960,42721,3,2010-11-06 07:00:00+00:00,NaN,Just right,NaN,Small&Large,Outerwear,NaN,2010,2
99,11960,543,5,2010-11-06 07:00:00+00:00,NaN,Just right,NaN,Small&Large,Outerwear,NaN,2010,0

In [37]:
rdf_all = rdf_all.dropna(subset=['user_attr'])
rdf_all.reset_index(drop=True, inplace=True)
rdf_all.head()

,item_id,user_id,rating,timestamp,size,fit,user_attr,model_attr,category,brand,year,split
0,7443,309,4,2010-01-21 08:00:00+00:00,NaN,NaN,Small,Small,Dresses,NaN,2012,0
1,7443,5534,4,2010-01-29 08:00:00+00:00,NaN,NaN,Small,Small,Dresses,NaN,2012,0
2,7443,42071,4,2010-02-18 08:00:00+00:00,NaN,NaN,Small,Small,Dresses,NaN,2012,0
3,7443,3485,2,2010-02-26 08:00:00+00:00,NaN,NaN,Small,Small,Dresses,NaN,2012,0
4,7443,1964,4,2010-04-06 07:00:00+00:00,NaN,NaN,Small,Small,Dresses,NaN,2012,0

In [38]:
rdf = rdf_all[["user_id","item_id", "rating"]]

rdf.head()

   user_id  item_id  rating
0      309     7443       4
1     5534     7443       4
2    42071     7443       4
3     3485     7443       2
4     1964     7443       4

In [39]:
user_df = rdf_all[["user_id", "user_attr"]]

user_df.shape

(91526, 2)

In [40]:
user_df.head()

   user_id user_attr
0      309     Small
1     5534     Small
2    42071     Small
3     3485     Small
4     1964     Small

In [41]:
user_type_dict = dict()
for u in range(len(user_df)):
    type_str = user_df.at[u, "user_attr"]
    
    #type_list = type_str.split('|')
    type_list = type_str
    user_type_dict[user_df.at[u, 'user_id']] = [type_list]

In [42]:
print(user_type_dict)

{309: ['Small'], 5534: ['Small'], 42071: ['Small'], 3485: ['Small'], 1964: ['Small'], 6862: ['Large'], 380: ['Small'], 10927: ['Small'], 27219: ['Small'], 36776: ['Small'], 3897: ['Small'], 4774: ['Small'], 6488: ['Small'], 4617: ['Small'], 6330: ['Small'], 13885: ['Small'], 4985: ['Small'], 2759: ['Small'], 1672: ['Small'], 2058: ['Small'], 6692: ['Small'], 857: ['Small'], 3415: ['Small'], 3520: ['Small'], 5891: ['Small'], 1250: ['Small'], 3089: ['Small'], 5022: ['Small'], 1176: ['Small'], 5129: ['Small'], 2465: ['Small'], 5924: ['Small'], 6316: ['Small'], 339: ['Small'], 5568: ['Small'], 5168: ['Small'], 124: ['Small'], 6509: ['Small'], 6546: ['Small'], 697: ['Small'], 852: ['Small'], 3578: ['Small'], 6476: ['Small'], 41159: ['Small'], 6185: ['Small'], 1479: ['Small'], 6720: ['Small'], 1958: ['Large'], 246: ['Large'], 384: ['Small'], 26577: ['Large'], 38400: ['Small'], 928: ['Small'], 8073: ['Small'], 320: ['Small'], 4770: ['Small'], 4171: ['Small'], 1222: ['Small'], 5456: ['Small'], 218: ['Small'], 40670: ['Small'], 6128: ['Small'], 2951: ['Small'], 1787: ['Small'], 4740: ['Small'], 1187: ['Small'], 4167: ['Small'], 2478: ['Small'], 3414: ['Small'], 1308: ['Small'], 4857: ['Small'], 13930: ['Small'], 13709: ['Small'], 18192: ['Small'], 6674: ['Small'], 27153: ['Small'], 22477: ['Small'], 37023: ['Small'], 3417: ['Small'], 3017: ['Small'], 4926: ['Small'], 1274: ['Small'], 4119: ['Small'], 18175: ['Small'], 40184: ['Small'], 44109: ['Small'], 25346: ['Small'], 5607: ['Small'], 12396: ['Small'], 24146: ['Small'], 18393: ['Small'], 1543: ['Small'], 35128: ['Small'], 3042: ['Small'], 42799: ['Small'], 3641: ['Small'], 1978: ['Small'], 11742: ['Large'], 11089: ['Small'], 18199: ['Small'], 2998: ['Small'], 41524: ['Small'], 27955: ['Small'], 5949: ['Small'], 972: ['Small'], 19779: ['Small'], 32876: ['Small'], 22346: ['Small'], 2366: ['Small'], 6160: ['Small'], 6574: ['Large'], 6221: ['Small'], 38568: ['Small'], 1198: ['Small'], 3794: ['Small'], 1200: ['Small'], 2626: ['Small'], 3341: ['Small'], 1395: ['Large'], 5592: ['Small'], 965: ['Small'], 34674: ['Small'], 6635: ['Small'], 2932: ['Small'], 35131: ['Small'], 8581: ['Small'], 3200: ['Large'], 19870: ['Small'], 5403: ['Small'], 12211: ['Small'], 9401: ['Small'], 44244: ['Small'], 22491: ['Small'], 14253: ['Small'], 4377: ['Small'], 2739: ['Small'], 34591: ['Small'], 9346: ['Small'], 2428: ['Small'], 6288: ['Large'], 6473: ['Small'], 43848: ['Small'], 36379: ['Small'], 194: ['Small'], 26095: ['Small'], 36543: ['Large'], 23258: ['Small'], 848: ['Small'], 9523: ['Small'], 2398: ['Small'], 6448: ['Small'], 39705: ['Small'], 3477: ['Small'], 4633: ['Small'], 5283: ['Small'], 2314: ['Small'], 44769: ['Small'], 8221: ['Small'], 11221: ['Small'], 6397: ['Small'], 4906: ['Small'], 5357: ['Small'], 40931: ['Small'], 2273: ['Small'], 24817: ['Small'], 5050: ['Small'], 25645: ['Small'], 1352: ['Small'], 2198: ['Small'], 35478: ['Small'], 6648: ['Small'], 6311: ['Small'], 3933: ['Small'], 1451: ['Small'], 2168: ['Small'], 28093: ['Small'], 5539: ['Small'], 695: ['Small'], 31307: ['Small'], 4842: ['Small'], 122: ['Small'], 2173: ['Large'], 12952: ['Small'], 1433: ['Small'], 3345: ['Small'], 2566: ['Small'], 1130: ['Small'], 43477: ['Small'], 3308: ['Small'], 2841: ['Large'], 8669: ['Small'], 953: ['Small'], 487: ['Small'], 597: ['Small'], 25130: ['Small'], 3594: ['Small'], 3247: ['Small'], 512: ['Small'], 20553: ['Small'], 21086: ['Small'], 6019: ['Small'], 4494: ['Small'], 4756: ['Small'], 4012: ['Large'], 5738: ['Large'], 4584: ['Small'], 36683: ['Small'], 3602: ['Small'], 4311: ['Large'], 1039: ['Small'], 6882: ['Small'], 4766: ['Small'], 2906: ['Small'], 19327: ['Small'], 1944: ['Small'], 3494: ['Small'], 2747: ['Small'], 370: ['Small'], 44299: ['Small'], 21798: ['Small'], 5680: ['Small'], 5016: ['Small'], 17472: ['Large'], 1722: ['Small'], 3942: ['Small'], 39795: ['Small'], 528: ['Small'], 29280: ['Small'], 3068: ['Small'], 479: ['Small'], 5778: ['Small'], 3835: ['Small'], 36585: ['Small'], 36843: ['Small'], 36560: ['Large'], 7597: ['Small'], 3029: ['Small'], 1400: ['Small'], 9686: ['Small'], 11475: ['Small'], 24661: ['Small'], 20489: ['Small'], 5356: ['Small'], 14146: ['Small'], 7263: ['Small'], 1270: ['Small'], 5682: ['Small'], 1792: ['Small'], 28751: ['Small'], 24510: ['Small'], 2208: ['Small'], 7875: ['Small'], 4281: ['Small'], 2968: ['Small'], 4205: ['Small'], 3424: ['Large'], 3854: ['Small'], 5372: ['Small'], 995: ['Small'], 35191: ['Small'], 2792: ['Small'], 2551: ['Small'], 11707: ['Small'], 5187: ['Small'], 1382: ['Small'], 3814: ['Small'], 5459: ['Large'], 13272: ['Small'], 3009: ['Small'], 17440: ['Small'], 1220: ['Small'], 2278: ['Small'], 4348: ['Small'], 6679: ['Small'], 2644: ['Small'], 11256: ['Small'], 1542: ['Small'], 19653: ['Small'], 2157: ['Small'], 23238: ['Small'], 9177: ['Small'], 957: ['Small'], 30138: ['Small'], 23051: ['Small'], 13665: ['Small'], 2895: ['Small'], 5736: ['Small'], 4040: ['Small'], 3127: ['Small'], 11100: ['Small'], 5799: ['Small'], 4886: ['Small'], 6085: ['Small'], 3102: ['Small'], 20473: ['Small'], 1514: ['Small'], 2066: ['Small'], 40389: ['Large'], 15563: ['Small'], 3091: ['Small'], 4015: ['Small'], 17996: ['Small'], 4268: ['Large'], 4892: ['Small'], 6263: ['Large'], 2504: ['Small'], 6202: ['Small'], 34387: ['Small'], 4330: ['Small'], 4109: ['Small'], 980: ['Small'], 26002: ['Small'], 37242: ['Small'], 6223: ['Small'], 40615: ['Small'], 31137: ['Small'], 5254: ['Small'], 25404: ['Large'], 1692: ['Small'], 6012: ['Small'], 32138: ['Small'], 3934: ['Small'], 2677: ['Small'], 2999: ['Large'], 6503: ['Small'], 39422: ['Small'], 7580: ['Small'], 890: ['Small'], 1413: ['Small'], 33704: ['Small'], 4181: ['Small'], 14506: ['Small'], 6538: ['Small'], 4043: ['Small'], 25726: ['Small'], 31418: ['Small'], 16150: ['Small'], 10185: ['Small'], 2568: ['Small'], 25426: ['Small'], 6721: ['Small'], 3255: ['Small'], 42463: ['Small'], 4189: ['Small'], 39550: ['Large'], 40145: ['Small'], 5014: ['Small'], 17698: ['Small'], 3329: ['Small'], 2756: ['Small'], 11637: ['Small'], 4714: ['Small'], 11568: ['Small'], 16409: ['Small'], 6676: ['Small'], 1172: ['Small'], 1058: ['Small'], 37000: ['Small'], 4384: ['Small'], 3593: ['Small'], 552: ['Small'], 5444: ['Small'], 29485: ['Small'], 9178: ['Small'], 5056: ['Small'], 1218: ['Small'], 9733: ['Small'], 3031: ['Small'], 24567: ['Small'], 2704: ['Large'], 34844: ['Small'], 6068: ['Small'], 29847: ['Small'], 37137: ['Large'], 24790: ['Small'], 4351: ['Small'], 38228: ['Small'], 2531: ['Small'], 2859: ['Small'], 22893: ['Small'], 3844: ['Small'], 12432: ['Small'], 11628: ['Large'], 13041: ['Small'], 3965: ['Small'], 16898: ['Small'], 159: ['Small'], 3895: ['Small'], 8148: ['Small'], 13681: ['Small'], 38750: ['Small'], 3348: ['Small'], 5979: ['Small'], 21141: ['Large'], 37192: ['Small'], 5852: ['Small'], 5159: ['Small'], 4523: ['Small'], 3785: ['Small'], 30933: ['Small'], 4475: ['Small'], 1215: ['Small'], 22680: ['Small'], 20191: ['Small'], 2277: ['Small'], 4176: ['Small'], 5714: ['Small'], 6645: ['Small'], 35181: ['Small'], 4122: ['Small'], 5775: ['Small'], 4586: ['Small'], 24747: ['Large'], 4996: ['Small'], 314: ['Small'], 5189: ['Small'], 38044: ['Small'], 40509: ['Small'], 26326: ['Small'], 10994: ['Small'], 3915: ['Small'], 3560: ['Small'], 3215: ['Small'], 28542: ['Small'], 4313: ['Small'], 4932: ['Small'], 1269: ['Small'], 7498: ['Small'], 4393: ['Small'], 24560: ['Small'], 1730: ['Small'], 20729: ['Small'], 6242: ['Small'], 34610: ['Small'], 41840: ['Small'], 1827: ['Small'], 2469: ['Small'], 5093: ['Small'], 15463: ['Small'], 2674: ['Small'], 14259: ['Small'], 13821: ['Small'], 3241: ['Small'], 2430: ['Small'], 6683: ['Small'], 2654: ['Small'], 32297: ['Small'], 2699: ['Small'], 43570: ['Small'], 5422: ['Small'], 6786: ['Small'], 44288: ['Small'], 12754: ['Small'], 1534: ['Small'], 28226: ['Small'], 1316: ['Small'], 9531: ['Small'], 39165: ['Small'], 3355: ['Small'], 25564: ['Small'], 5451: ['Small'], 3327: ['Small'], 15181: ['Small'], 39409: ['Small'], 1675: ['Small'], 4998: ['Small'], 1973: ['Small'], 1583: ['Small'], 3407: ['Small'], 23168: ['Small'], 41158: ['Small'], 30361: ['Small'], 3086: ['Small'], 6433: ['Small'], 29043: ['Small'], 14734: ['Small'], 4318: ['Small'], 4308: ['Small'], 4309: ['Small'], 5140: ['Small'], 1226: ['Small'], 29826: ['Small'], 6219: ['Small'], 19326: ['Small'], 21860: ['Small'], 21271: ['Small'], 6482: ['Small'], 1561: ['Small'], 12578: ['Small'], 614: ['Small'], 729: ['Small'], 15339: ['Small'], 14704: ['Small'], 1470: ['Small'], 23442: ['Small'], 11616: ['Small'], 35851: ['Small'], 1254: ['Small'], 1674: ['Small'], 28446: ['Small'], 30728: ['Small'], 1207: ['Small'], 37443: ['Small'], 4909: ['Large'], 41821: ['Small'], 4554: ['Small'], 4247: ['Small'], 4689: ['Small'], 8929: ['Small'], 3006: ['Small'], 5612: ['Small'], 2977: ['Small'], 28695: ['Large'], 10585: ['Small'], 3377: ['Small'], 33255: ['Small'], 42503: ['Small'], 1024: ['Small'], 33933: ['Small'], 43309: ['Small'], 6624: ['Small'], 17305: ['Small'], 19472: ['Small'], 16168: ['Small'], 2766: ['Small'], 17924: ['Small'], 14569: ['Small'], 21935: ['Small'], 40650: ['Large'], 42710: ['Small'], 4257: ['Small'], 5416: ['Small'], 10986: ['Large'], 4133: ['Small'], 12554: ['Large'], 31772: ['Small'], 3905: ['Small'], 30026: ['Small'], 7509: ['Small'], 13859: ['Small'], 348: ['Small'], 43608: ['Large'], 9242: ['Small'], 5303: ['Small'], 3597: ['Large'], 7974: ['Small'], 2885: ['Small'], 3440: ['Small'], 6367: ['Small'], 6090: ['Small'], 6275: ['Small'], 18997: ['Small'], 1959: ['Small'], 15447: ['Small'], 6858: ['Small'], 7882: ['Small'], 2084: ['Small'], 2350: ['Small'], 2186: ['Small'], 2829: ['Small'], 16640: ['Small'], 315: ['Small'], 30368: ['Small'], 23759: ['Small'], 6309: ['Small'], 1676: ['Small'], 41029: ['Small'], 21578: ['Small'], 4462: ['Small'], 3081: ['Small'], 5096: ['Small'], 1707: ['Small'], 39159: ['Small'], 1799: ['Small'], 774: ['Small'], 26615: ['Small'], 23220: ['Small'], 5686: ['Small'], 6342: ['Small'], 13604: ['Small'], 2611: ['Large'], 2729: ['Small'], 14830: ['Large'], 44685: ['Small'], 3084: ['Small'], 4908: ['Small'], 4255: ['Small'], 26811: ['Small'], 39786: ['Small'], 11466: ['Small'], 22047: ['Small'], 3313: ['Large'], 23538: ['Small'], 2892: ['Small'], 5703: ['Small'], 2507: ['Small'], 21077: ['Small'], 11197: ['Small'], 1821: ['Small'], 39259: ['Small'], 198: ['Small'], 4628: ['Small'], 6761: ['Small'], 9698: ['Small'], 29523: ['Small'], 27133: ['Small'], 23879: ['Small'], 26566: ['Small'], 41250: ['Small'], 3213: ['Small'], 39915: ['Small'], 4032: ['Large'], 6410: ['Small'], 16619: ['Small'], 1386: ['Small'], 1929: ['Small'], 27472: ['Small'], 39610: ['Small'], 6368: ['Small'], 4220: ['Small'], 25402: ['Small'], 1582: ['Large'], 25133: ['Large'], 6044: ['Small'], 38194: ['Small'], 44543: ['Small'], 6974: ['Small'], 27500: ['Small'], 2921: ['Small'], 1244: ['Small'], 43322: ['Small'], 17990: ['Small'], 8032: ['Small'], 34886: ['Small'], 29171: ['Small'], 5286: ['Small'], 27956: ['Small'], 15051: ['Small'], 25208: ['Small'], 43146: ['Small'], 36340: ['Small'], 32643: ['Small'], 7270: ['Small'], 40932: ['Small'], 43785: ['Small'], 5322: ['Small'], 187: ['Small'], 2414: ['Small'], 351: ['Small'], 4718: ['Small'], 27065: ['Small'], 16775: ['Small'], 3120: ['Small'], 41155: ['Small'], 1037: ['Small'], 39494: ['Small'], 22320: ['Small'], 427: ['Small'], 42985: ['Small'], 11424: ['Small'], 24196: ['Large'], 2122: ['Small'], 5485: ['Small'], 616: ['Small'], 1227: ['Small'], 4375: ['Small'], 20207: ['Small'], 36966: ['Small'], 37433: ['Small'], 20906: ['Large'], 27888: ['Small'], 345: ['Small'], 6084: ['Small'], 22410: ['Small'], 1443: ['Small'], 18623: ['Small'], 8632: ['Small'], 5146: ['Small'], 15795: ['Small'], 28187: ['Small'], 16842: ['Small'], 645: ['Small'], 27864: ['Small'], 34928: ['Small'], 34724: ['Small'], 25995: ['Small'], 2808: ['Small'], 26575: ['Small'], 3322: ['Small'], 39916: ['Small'], 396: ['Small'], 3436: ['Small'], 3333: ['Small'], 3839: ['Small'], 26701: ['Small'], 3028: ['Small'], 366: ['Small'], 3174: ['Small'], 29803: ['Small'], 2346: ['Small'], 800: ['Small'], 6812: ['Small'], 38151: ['Small'], 6231: ['Small'], 14493: ['Small'], 27226: ['Small'], 31925: ['Small'], 20148: ['Small'], 31010: ['Small'], 6523: ['Small'], 4891: ['Small'], 3053: ['Small'], 24159: ['Small'], 10547: ['Small'], 3760: ['Small'], 283: ['Small'], 25732: ['Small'], 24741: ['Small'], 37397: ['Large'], 2280: ['Small'], 6477: ['Small'], 25415: ['Small'], 20228: ['Small'], 5460: ['Small'], 15762: ['Small'], 8754: ['Small'], 17618: ['Small'], 3591: ['Small'], 43114: ['Small'], 39600: ['Small'], 17216: ['Small'], 14379: ['Small'], 12706: ['Small'], 16164: ['Small'], 2970: ['Small'], 5199: ['Small'], 43425: ['Small'], 37816: ['Small'], 34938: ['Small'], 34056: ['Small'], 3725: ['Small'], 40484: ['Small'], 36545: ['Small'], 8889: ['Small'], 2477: ['Small'], 480: ['Small'], 28526: ['Small'], 24707: ['Small'], 11270: ['Small'], 12480: ['Small'], 656: ['Small'], 10542: ['Small'], 4094: ['Small'], 3259: ['Small'], 2910: ['Small'], 3406: ['Small'], 1681: ['Small'], 34624: ['Small'], 5423: ['Small'], 11253: ['Small'], 6431: ['Small'], 22348: ['Small'], 17058: ['Large'], 22478: ['Small'], 42983: ['Small'], 547: ['Small'], 33372: ['Small'], 5389: ['Small'], 17681: ['Small'], 10795: ['Small'], 29121: ['Small'], 1245: ['Small'], 17875: ['Small'], 6270: ['Small'], 17107: ['Small'], 32328: ['Small'], 6512: ['Small'], 3459: ['Large'], 36924: ['Small'], 29967: ['Small'], 8393: ['Small'], 482: ['Small'], 2868: ['Small'], 4939: ['Small'], 39406: ['Small'], 5614: ['Large'], 31916: ['Small'], 4276: ['Small'], 26483: ['Small'], 34210: ['Small'], 6903: ['Small'], 33486: ['Large'], 37886: ['Small'], 34247: ['Small'], 5919: ['Small'], 33832: ['Small'], 2813: ['Small'], 3254: ['Small'], 3608: ['Small'], 37850: ['Small'], 31028: ['Small'], 4279: ['Small'], 4422: ['Small'], 20093: ['Small'], 1286: ['Large'], 10576: ['Small'], 12062: ['Small'], 3008: ['Small'], 6131: ['Small'], 32265: ['Small'], 42057: ['Small'], 1665: ['Small'], 41574: ['Small'], 4437: ['Small'], 31325: ['Small'], 3320: ['Small'], 28134: ['Small'], 7178: ['Small'], 35839: ['Small'], 1224: ['Small'], 9620: ['Small'], 732: ['Small'], 4683: ['Small'], 9097: ['Small'], 24291: ['Small'], 25122: ['Large'], 17391: ['Small'], 2755: ['Small'], 1015: ['Small'], 1750: ['Small'], 23792: ['Small'], 27832: ['Small'], 6017: ['Small'], 3405: ['Small'], 25210: ['Small'], 6487: ['Large'], 39898: ['Small'], 34536: ['Small'], 4525: ['Small'], 32172: ['Small'], 2607: ['Small'], 5517: ['Small'], 4018: ['Small'], 4182: ['Small'], 18305: ['Small'], 8604: ['Small'], 35336: ['Small'], 12557: ['Small'], 33865: ['Small'], 6726: ['Large'], 1603: ['Small'], 30325: ['Small'], 15416: ['Small'], 4911: ['Small'], 7739: ['Small'], 31841: ['Small'], 1209: ['Small'], 43080: ['Small'], 20443: ['Small'], 35462: ['Small'], 508: ['Small'], 6605: ['Small'], 1484: ['Small'], 3289: ['Small'], 2282: ['Large'], 33550: ['Small'], 13106: ['Small'], 22830: ['Small'], 21570: ['Small'], 25615: ['Small'], 42410: ['Small'], 4075: ['Small'], 21403: ['Large'], 28023: ['Small'], 4515: ['Small'], 3561: ['Small'], 34139: ['Small'], 26831: ['Small'], 3085: ['Small'], 31757: ['Small'], 619: ['Small'], 21234: ['Small'], 20170: ['Small'], 18796: ['Small'], 25949: ['Small'], 1483: ['Small'], 5010: ['Small'], 40659: ['Small'], 42111: ['Small'], 19617: ['Small'], 41342: ['Small'], 3973: ['Small'], 4574: ['Small'], 3522: ['Small'], 2100: ['Small'], 349: ['Small'], 1845: ['Small'], 32746: ['Small'], 13061: ['Small'], 4854: ['Large'], 37369: ['Small'], 200: ['Small'], 27514: ['Small'], 31150: ['Small'], 5956: ['Small'], 976: ['Small'], 29795: ['Small'], 4657: ['Large'], 3540: ['Small'], 1338: ['Small'], 4434: ['Small'], 18793: ['Small'], 11586: ['Small'], 43809: ['Small'], 21447: ['Small'], 29892: ['Small'], 3090: ['Large'], 42525: ['Small'], 24622: ['Small'], 21489: ['Small'], 34112: ['Small'], 24502: ['Small'], 24791: ['Small'], 24379: ['Small'], 36001: ['Small'], 37431: ['Small'], 5591: ['Small'], 4065: ['Small'], 4558: ['Small'], 973: ['Small'], 33139: ['Small'], 4014: ['Small'], 3307: ['Small'], 34808: ['Small'], 36095: ['Small'], 5037: ['Small'], 2987: ['Large'], 14094: ['Small'], 38946: ['Small'], 17243: ['Small'], 24729: ['Large'], 312: ['Large'], 4579: ['Small'], 9018: ['Small'], 498: ['Small'], 24544: ['Small'], 8181: ['Small'], 31647: ['Small'], 22394: ['Small'], 8003: ['Large'], 6835: ['Small'], 15240: ['Small'], 5296: ['Small'], 34974: ['Small'], 5848: ['Small'], 44628: ['Small'], 4101: ['Small'], 9412: ['Small'], 34443: ['Small'], 39594: ['Small'], 13035: ['Small'], 41071: ['Small'], 4023: ['Small'], 16439: ['Small'], 26721: ['Small'], 31693: ['Small'], 12737: ['Small'], 19061: ['Small'], 24568: ['Small'], 3508: ['Small'], 38484: ['Small'], 3909: ['Small'], 4135: ['Small'], 3453: ['Small'], 11550: ['Small'], 40369: ['Large'], 10446: ['Small'], 21697: ['Small'], 35764: ['Small'], 8541: ['Small'], 8715: ['Small'], 10562: ['Small'], 32700: ['Small'], 1553: ['Small'], 29579: ['Small'], 7424: ['Small'], 2124: ['Small'], 38819: ['Small'], 14605: ['Small'], 999: ['Small'], 1537: ['Small'], 25409: ['Small'], 3971: ['Small'], 37787: ['Small'], 17181: ['Small'], 1237: ['Small'], 450: ['Small'], 5696: ['Small'], 35223: ['Small'], 19769: ['Small'], 1965: ['Small'], 3224: ['Small'], 2237: ['Small'], 28056: ['Small'], 1210: ['Small'], 994: ['Small'], 5789: ['Small'], 24642: ['Small'], 875: ['Small'], 23569: ['Large'], 44392: ['Small'], 11242: ['Small'], 11263: ['Small'], 10613: ['Small'], 41215: ['Small'], 356: ['Small'], 3791: ['Small'], 32580: ['Small'], 6817: ['Small'], 395: ['Small'], 33226: ['Small'], 16605: ['Small'], 18490: ['Small'], 19469: ['Small'], 14520: ['Small'], 44516: ['Small'], 14573: ['Small'], 5350: ['Small'], 30338: ['Small'], 1446: ['Small'], 4651: ['Small'], 18548: ['Small'], 22843: ['Small'], 6863: ['Small'], 17621: ['Small'], 17278: ['Small'], 7403: ['Small'], 2347: ['Small'], 2091: ['Small'], 4927: ['Small'], 10309: ['Small'], 2036: ['Small'], 2009: ['Small'], 5960: ['Small'], 38035: ['Small'], 10701: ['Large'], 1609: ['Small'], 3953: ['Small'], 13251: ['Small'], 2370: ['Small'], 6237: ['Small'], 23270: ['Small'], 2834: ['Small'], 39576: ['Small'], 3250: ['Small'], 30393: ['Large'], 341: ['Small'], 6203: ['Small'], 35608: ['Small'], 41897: ['Small'], 382: ['Small'], 3614: ['Large'], 36855: ['Small'], 20900: ['Small'], 6317: ['Large'], 28454: ['Small'], 4508: ['Small'], 1936: ['Large'], 12749: ['Small'], 26942: ['Small'], 22747: ['Small'], 3498: ['Small'], 6564: ['Small'], 3821: ['Small'], 18183: ['Small'], 20764: ['Small'], 43691: ['Small'], 29263: ['Small'], 3321: ['Small'], 34320: ['Small'], 1822: ['Small'], 23658: ['Small'], 3403: ['Large'], 2508: ['Small'], 39608: ['Large'], 2001: ['Small'], 19249: ['Large'], 4413: ['Small'], 822: ['Small'], 40454: ['Small'], 35794: ['Small'], 6255: ['Small'], 27664: ['Small'], 2604: ['Small'], 24304: ['Small'], 1763: ['Small'], 1485: ['Small'], 6690: ['Small'], 16667: ['Small'], 29597: ['Small'], 38813: ['Small'], 21526: ['Small'], 5784: ['Small'], 1208: ['Small'], 39194: ['Small'], 9798: ['Small'], 41707: ['Small'], 4218: ['Small'], 4227: ['Small'], 8932: ['Small'], 34099: ['Small'], 27845: ['Large'], 35701: ['Small'], 10324: ['Small'], 13613: ['Small'], 43735: ['Small'], 23611: ['Small'], 6713: ['Small'], 43724: ['Small'], 632: ['Small'], 2554: ['Small'], 1588: ['Small'], 13563: ['Small'], 24977: ['Small'], 7655: ['Large'], 4703: ['Small'], 2360: ['Small'], 7978: ['Small'], 2473: ['Small'], 44715: ['Small'], 5108: ['Small'], 5540: ['Small'], 15341: ['Small'], 11825: ['Small'], 3783: ['Small'], 5689: ['Small'], 23674: ['Small'], 17437: ['Small'], 12075: ['Small'], 41928: ['Small'], 43717: ['Small'], 6656: ['Small'], 33710: ['Small'], 19540: ['Small'], 34246: ['Small'], 359: ['Small'], 14758: ['Small'], 19306: ['Small'], 5490: ['Small'], 5908: ['Large'], 2534: ['Small

In [43]:
item_set = set(rdf['item_id'].unique())
user_set = set(rdf['user_id'].unique())
print('item num = ' + str(len(item_set)))
print('user num = ' + str(len(user_set)))

item num = 1019
user num = 39536

In [44]:
# count the number for each user type and sort
import operator
type_count = dict()
for l in user_type_dict:
    for g in user_type_dict[l]:
        if not g in type_count:
            type_count[g] = 1
        else:
            type_count[g] += 1

type_count_sorted = sorted(type_count.items(), key=operator.itemgetter(1), reverse=True)
type_count_sorted

[('Small', 30141), ('Large', 9395)]

In [45]:
key_type = ['Small', 'Large']

# get the key_type->user_list dict
key_type_user = dict()
for k in key_type:
    key_type_user[k] = list()
for user in user_type_dict:
    for t in user_type_dict[user]:
        if t in key_type:
            key_type_user[t].append(user)

In [46]:
# collect all the users with key types
key_user_set = set()
for types in key_type_user:
    key_user_set |= set(key_type_user[types])

nonkey_user_set = user_set - key_user_set

In [47]:
# remove the non-key type users in rdf
remove_list = []
for user in nonkey_user_set:
    remove_list += rdf.index[rdf['user_id'] == user].values.tolist()

In [48]:
rdf.drop(remove_list, inplace=True)

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:3997: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [49]:
rdf.reset_index(drop=True, inplace=True)
rating_df = copy.copy(rdf)

In [50]:
rdf = copy.copy(rating_df)

In [51]:
# iteratively remove items and users with less than 2 reviews
rdf.reset_index(drop=True, inplace=True)

rdf['user_freq'] = rdf.groupby('user_id')['user_id'].transform('count')
rdf.drop(rdf.index[rdf['user_freq'] <= 2], inplace=True)
rdf.reset_index(drop=True, inplace=True)
rdf['item_freq'] = rdf.groupby('item_id')['item_id'].transform('count')
rdf.drop(rdf.index[rdf['item_freq'] <= 2], inplace=True)
rdf.reset_index(drop=True, inplace=True)
rdf['user_freq'] = rdf.groupby('user_id')['user_id'].transform('count')
rdf.reset_index(drop=True, inplace=True)
rdf['user_id'].value_counts()

5756     248
411      203
22660    198
3735     195
2907     191
        ...
7823       2
18032      2
23406      2
32011      2
4092       2
Name: user_id, Length: 6339, dtype: int64

In [52]:
item_list = rdf['item_id'].unique()
user_list = rdf['user_id'].unique()
print('item num = ' + str(len(item_list)))
print('user num = ' + str(len(user_list)))

item num = 915
user num = 6339

In [53]:
# get the user and item str id->int id dict
i = 0
user_id_dict = dict()
for u in user_list:
    if not u in user_id_dict:
        user_id_dict[u] = i
        i += 1
j = 0
item_id_dict = dict()
for i in item_list:
    if not i in item_id_dict:
        item_id_dict[i] = j
        j += 1

In [54]:
print('sparsity: ' + str(len(rdf) * 1.0 / (len(user_list) * len(item_list))))

sparsity: 0.008835580244423238

In [55]:
# get the df of train, vali, and test set
rdf.reset_index(inplace=True, drop=True)
train_df = rdf.copy()
vali_df = rdf.copy()
test_df = rdf.copy()

train_ratio = 0.8
vali_ratio = 0.0
test_ratio = 0.2
num_all = len(rdf)
vali_idx = []
test_idx = []

test_vali_idx = []
i = 0
num_user = len(user_list)
for u in user_list:
    u_idx = train_df.index[train_df['user_id'] == u]
    idx_len = len(u_idx)
    test_len = int(idx_len * (test_ratio + vali_ratio))
    if test_len == 0:
        test_len = 1
    tmp = np.random.choice(u_idx, size=test_len, replace=False)
    test_vali_idx += tmp.tolist()
    i += 1
    if i % 5000 == 0:
        print(str(i) + '/' + str(num_user))

# tmp = (np.random.choice(range(num_all), size=(test_len+vali_len), replace=False)).tolist()
test_len = int(len(test_vali_idx) * test_ratio / (test_ratio + vali_ratio))
vali_len = int(len(test_vali_idx) - test_len)
test_idx = (np.random.choice(test_vali_idx, size=test_len, replace=False)).tolist()
vali_idx = (np.random.choice(test_vali_idx, size=vali_len, replace=False)).tolist()

test_set = set(test_idx)
vali_set = set(vali_idx)
train_set = set(range(num_all)) - test_set - vali_set
train_idx = list(train_set)
train_df.drop((test_idx + vali_idx), axis=0, inplace=True)
test_df.drop((train_idx + vali_idx), axis=0, inplace=True)
vali_df.drop((train_idx + test_idx), axis=0, inplace=True)

5000/6339

In [56]:
train_df.shape

(40354, 5)

In [76]:
len(train_df['user_id'].unique())

6339

In [57]:
# get the matrix of train, vali and test set

train_df.reset_index(drop=True, inplace=True)
test_df.reset_index(drop=True, inplace=True)
vali_df.reset_index(drop=True, inplace=True)
rdf.reset_index(drop=True, inplace=True)
train = np.zeros((len(user_list), len(item_list)))
test = np.zeros((len(user_list), len(item_list)))
vali = np.zeros((len(user_list), len(item_list)))
for r in range(len(train_df)):
    train[user_id_dict[train_df.at[r, 'user_id']], item_id_dict[train_df.at[r, 'item_id']]] = 1.0
for r in range(len(test_df)):
    test[user_id_dict[test_df.at[r, 'user_id']], item_id_dict[test_df.at[r, 'item_id']]] = 1.0
for r in range(len(vali_df)):
    vali[user_id_dict[vali_df.at[r, 'user_id']], item_id_dict[vali_df.at[r, 'item_id']]] = 1.0

In [58]:
test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [59]:
# get the user int id-> str id list, and the same for item 
user_list = user_id_dict.keys()
user_idd_list = list()
for u in range(len(user_list)):
    user_idd_list.append('')
for user in user_id_dict:
    user_idd_list[user_id_dict[user]] = user

item_list = item_id_dict.keys()
item_idd_list = list()
for i in range(len(item_list)):
    item_idd_list.append('')
for item in item_id_dict:
    item_idd_list[item_id_dict[item]] = item
    
# get the user int id->types list
user_idd_type_list = list()
for u in range(len(user_idd_list)):
    user_idd_type_list.append(user_type_dict[user_idd_list[u]])

In [60]:
train_df.head()

   user_id  item_id  rating  user_freq  item_freq
0      309     7443       4         66        431
1     5534     7443       4         30        431
2    42071     7443       4         12        431
3     3485     7443       2         71        431
4     1964     7443       4         11        431

In [61]:
train_df.drop('user_freq', axis=1, inplace=True)
train_df.drop('item_freq', axis=1, inplace=True)
vali_df.drop('user_freq', axis=1, inplace=True)
vali_df.drop('item_freq', axis=1, inplace=True)
test_df.drop('user_freq', axis=1, inplace=True)
test_df.drop('item_freq', axis=1, inplace=True)
rdf.drop('user_freq', axis=1, inplace=True)
rdf.drop('item_freq', axis=1, inplace=True)

In [62]:
train_df.head()

   user_id  item_id  rating
0      309     7443       4
1     5534     7443       4
2    42071     7443       4
3     3485     7443       2
4     1964     7443       4

In [63]:
# get df for rdf, train, vali, test with int id for user and item
import copy
rating_df = copy.copy(rdf)
for i in range(len(rdf)):
    rating_df.at[i, 'user_id'] = user_id_dict[rating_df.at[i, 'user_id']]
    rating_df.at[i, 'item_id'] = item_id_dict[rating_df.at[i, 'item_id']]

training_df = copy.copy(train_df)
for i in range(len(training_df)):
    training_df.at[i, 'user_id'] = user_id_dict[training_df.at[i, 'user_id']]
    training_df.at[i, 'item_id'] = item_id_dict[training_df.at[i, 'item_id']]

valiing_df = copy.copy(vali_df)
for i in range(len(valiing_df)):
    valiing_df.at[i, 'user_id'] = user_id_dict[valiing_df.at[i, 'user_id']]
    valiing_df.at[i, 'item_id'] = item_id_dict[valiing_df.at[i, 'item_id']]

testing_df = copy.copy(test_df)
for i in range(len(testing_df)):
    testing_df.at[i, 'user_id'] = user_id_dict[testing_df.at[i, 'user_id']]
    testing_df.at[i, 'item_id'] = item_id_dict[testing_df.at[i, 'item_id']]

In [64]:
# generate the rating list for each key type, get the type->ratings dict
rdf.reset_index(drop=True, inplace=True)
key_type_rating = dict()
for k in key_type:
    key_type_rating[k] = 0.0
for r in range(len(rdf)):
    user = rdf.at[r, 'user_id']
    gl = user_type_dict[user]
    for k in key_type:
        if k in gl:
            key_type_rating[k] += 1.0

# get the user int id->type list
type_user_vector = dict()
for k in key_type:
    type_user_vector[k] = np.zeros((1, len(user_list)))
for u in range(len(user_idd_type_list)):
    type_list = user_idd_type_list[u]
    for t in type_list:
        if t in key_type:
            type_user_vector[t][0,u] = 1.0

In [65]:
with open("user_type_dict_modcloth.pkl", "wb") as f:
    pickle.dump(user_type_dict, f)
with open("type_user_vector_modcloth.pkl", "wb") as f:
    pickle.dump(type_user_vector, f, pickle.HIGHEST_PROTOCOL)
with open("key_type_modcloth.pkl", "wb") as f:
    pickle.dump(key_type, f, pickle.HIGHEST_PROTOCOL)
with open("user_id_dict_modcloth.pkl", "wb") as f:
    pickle.dump(user_id_dict, f, pickle.HIGHEST_PROTOCOL)
with open("item_id_dict_modcloth.pkl", "wb") as f:
    pickle.dump(item_id_dict, f, pickle.HIGHEST_PROTOCOL)
# with open("rdf.pkl", "wb") as f:
#     pickle.dump(rdf, f, pickle.HIGHEST_PROTOCOL)
with open("rating_df_modcloth.pkl", "wb") as f:
    pickle.dump(rating_df, f, pickle.HIGHEST_PROTOCOL)
with open("training_df_modcloth.pkl", "wb") as f:
    pickle.dump(training_df, f, pickle.HIGHEST_PROTOCOL)
with open("valiing_df_modcloth.pkl", "wb") as f:
    pickle.dump(valiing_df, f, pickle.HIGHEST_PROTOCOL)
with open("testing_df_modcloth.pkl", "wb") as f:
    pickle.dump(testing_df, f, pickle.HIGHEST_PROTOCOL)
with open("user_idd_type_list_modcloth.pkl", "wb") as f:
    pickle.dump(user_idd_type_list, f, pickle.HIGHEST_PROTOCOL)
with open("item_idd_list_modcloth.pkl", "wb") as f:
    pickle.dump(item_idd_list, f, pickle.HIGHEST_PROTOCOL)
with open("user_idd_list_modcloth.pkl", "wb") as f:
    pickle.dump(user_idd_list, f, pickle.HIGHEST_PROTOCOL)
with open("key_type_rating_modcloth.pkl", "wb") as f:
    pickle.dump(key_type_rating, f, pickle.HIGHEST_PROTOCOL)
    
with open("train_modcloth.mat", "wb") as f:
    np.save(f, train)
with open("test_modcloth.mat", "wb") as f:
    np.save(f, test)
with open("vali_modcloth.mat", "wb") as f:
    np.save(f, vali)

In [68]:
# count the number for each user type and sort
import pickle5 as pickle
from operator import itemgetter
user_list = rdf['user_id'].unique()
#user_type_dict = pickle.load(open('./user_type_dict.pkl'))

with open('./user_type_dict_modcloth.pkl', 'rb') as f:
    user_type_dict = pickle.load(f,encoding='latin1')

with open('./key_type_modcloth.pkl', 'rb') as f:
    key_type = pickle.load(f,encoding='latin1')

#key_type = pickle.load(open('./key_type.pkl'))

type_count = dict()
for u in user_list:
    gl = user_type_dict[u]
    for g in gl:
        if g in key_type:
            if not g in type_count:
                type_count[g] = 1
            else:
                type_count[g] += 1

# with open("genre_count.pkl", "wb") as f:
#     pickle.dump(genre_count, f, pickle.HIGHEST_PROTOCOL)
                
type_count_sorted = sorted(type_count.items(), key=itemgetter(1), reverse=True)
type_count_sorted

[('Small', 4614), ('Large', 1725)]

In [69]:
with open("type_count_modcloth.pkl", "wb") as f:
    pickle.dump(type_count_sorted, f)

In [70]:
import numpy as np
import pickle5 as pickle
import copy as copy
train = np.load('./train_modcloth.mat')

with open('./user_idd_type_list_modcloth.pkl', 'rb') as f:
    user_idd_type_list = pickle.load(f,encoding='latin1')

user_idd_type_list = np.array(user_idd_type_list)


mask = 1.0 * (train > 0)
item_type_count = list()
for i in range(train.shape[1]):
    temp_type_count = copy.copy(type_count)
    mask_i = mask[:, i]
    gll = user_idd_type_list[mask_i == 1.0]
    for gl in gll:
        for g in gl:
            if g in key_type:
                temp_type_count[g] -= 1
    item_type_count.append(temp_type_count)
# with open("user_genre_count.pkl", "wb") as f:
#     pickle.dump(user_genre_count, f, pickle.HIGHEST_PROTOCOL)

In [71]:
with open("item_type_count_modcloth.pkl", "wb") as f:
    pickle.dump(item_type_count, f)

In [72]:
len(item_type_count)

915

In [73]:
type_count_sorted

[('Small', 4614), ('Large', 1725)]

In [74]:
with open('./key_type_rating_modcloth.pkl', 'rb') as f:
    key_type_rating = pickle.load(f,encoding='latin1')


#key_type_rating = pickle.load(open('./key_genre_rating.pkl'))
type_avg_like = dict()
for k in key_type:
    type_avg_like[k] = key_type_rating[k] * 1.0 / type_count[k]

In [75]:
type_avg_like_sorted = sorted(type_avg_like.items(), key=itemgetter(1), reverse=True)
type_avg_like_sorted

[('Small', 9.178803641092328), ('Large', 5.15768115942029)]